### ISSUE TITLE
Add GENE_SET_CSV to Enums 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1004]
## Need
- Enum describing gene set files for DatasetArtifactFileType

## Approach
- create GENE_SET_CSV in DatasetArtifactFileType 
- migrate db

## DOD
- update unit tests to include testing of new enum types

**Comment by Bento007** [comment]
Will displaying all of the GENE_SET_CSV on the collections page make it crowded? Is it an s3 link that we store in link type?

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
