### ISSUE TITLE
Update front end download modal to include option to download genesets for a dataset

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1006]
See figma -  https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=364%3A0

This option should only be available if there are genesets linked to the dataset

![Screen Shot 2021-03-22 at 23.08.29.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/9d311654-cdb0-4eb1-8bcc-78208464f23f)

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
