### ISSUE TITLE
Validate more gene set information

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1023]
**The most up-to-date requirements are now defined in the [Gene Set File Format](https://github.com/chanzuckerberg/single-cell-curation/pull/34)**

Because gene set names are no longer unique to a collection, the validation code no longer needs to check for collisions among gene set names - this correction is tracked in [Update Gene Sets File Format to reflect simplified design ](https://github.com/chanzuckerberg/single-cell-curation/issues/56).

cellxgene explorer has defined additional requirements for `gene_set_names`. 

cellxgene portal MUST warn and fail when the following illegal ASCII characters or sequences are detected in any **required** field value:

* control characters (decimal 0-31)
* DEL (decimal 127)
* leading spaces (decimal 32) in a field - `     This is an example`
* trailing spaces (decimal 32) in a field - `This is an example     ` 
* multiple spaces (decimal 32) "internal" to a field - `This     is an example`

---

Based on feedback from @pablo-gar for the[ curator perspective](https://github.com/chanzuckerberg/single-cell-curation/pull/34#issuecomment-805355169) and from @bkmartinjr for [cellxgene explorer](https://github.com/chanzuckerberg/single-cell-curation/pull/34/files/c545d308a46ec4c9737426cd16912da32172c9c1#r604538758), the portal will **ELIMINATE** this original requirement:

All `gene_symbol(s)` for a `gene_set_name` MUST be on contiguous rows; otherwise, an out-of-order row is interpreted as a duplicate `gene_set_name`. In this case, validation MUST display a warning and fail the upload. This is illustrated by **~~club.cell~~** in the example:

---
| gene_set_name | gene_set_description | gene_symbol | gene_description |
|---------------|----------------------|-------------|------------------|
| club.cell     | description          | CCKAR       | description      |
| club.cell     |                      | SCGB3A2     | description      |
| club.cell     |                      | CYP2F2      | description      |
| macrophage    | description          | CD68        | description      |
| **~~club.cell~~**     |                      | CD163       | description      |

This has been previously implemented in [Validate geneset information](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/909).

---

**In the update, the out-of-order row should simply be included in the existing `club.cell` gene set.**

**Comment by Bento007** [comment]
@seve please estimate

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
