### ISSUE TITLE
Update POST /dp/v1/collection/{collection_uuid} to copy genesets

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#1054]
## Need
A curator wants to modify the genesets on their published collection in a revision.

## Approach
Copy all of the geneset rows related to a collection and its datasets. The copied genesets should be linked to the data sets base on the data sets original ID, not the temporary ID used for revision.

## Definition of Done
- When viewing a newly generated revision of a collection, the gene sets linked to the collection revision should be the same as the gene sets linked to the published collection.
- The gene sets of the revision must also be mapped to the data sets the published data sets were mapped to.

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
