### ISSUE TITLE
Update POST /dp/v1/collections/{collection_uuid}/publish to link genesets

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#1055]
## Need
The changes made to gene sets during a revision must be visible once the collection is published.

## Approach
Delete all of the gene set on the published collection. Link the revised genesets to the published collection. After the dataset has been copied over, link the genesets to the published datasets based on the dataset original_uuid. Delete the revision gene sets from the private collection.

## Definition of Done
- Added gene sets are linked to the published collection and data sets once published
- Delete gene sets are removed from the published collection and data sets once the published
- Modified gene sets are linked to the published collection and data sets once published.

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
