### ISSUE TITLE
Merge revision feature flag into curator feature flag when feature is released

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1062]
From https://github.com/chanzuckerberg/corpora-data-portal/issues/983#issuecomment-800480654

There was a rationale to define separate feature flags for `cc` (Create Collection) and `auth` in the past. Moving forward, I would recommend that we merge released features to one feature flag such as `curator=true`.  (Or perhaps something slightly harder to guess) Features under development would still have an internal feature flag. When the feature is ready for release to curators, then the internal feature flag would be deprecated and replaced by `curator`.

For example:

1. `?cc=true&auth=true` -> `?curator=true`
2. Gene sets in development -> `?curator=true&gs=true`, make sure this can be enabled from the top level of the frontend.
3. Gene sets released to curators -> `?curator=true` which now includes create collections, auth, gene sets
4. Revision in development -> `?curator=true&revision=true`
5. Revision released to curators -> `?curator=true` which now includes create collections, auth, gene sets, revise collections

## Definition of Done

- [ ] Merge `rc` flag into `curator` flag.
- [ ] Remove `rc` flag.

**Comment by brianraymor** [comment]
This issue was incorrectly closed when addressing [Update feature flags to work on ALL routes](https://github.com/chanzuckerberg/corpora-data-portal/issues/983).

Re-opening.

**Comment by tihuan** [comment]
in prod!
