### ISSUE TITLE
Uploads fail in the staging environment

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1068]
There appears to be an issue with communication between the step function and the batch job
For example this is the output of the batch job in the step function for a recent upload attempt
```
{
  "collection_uuid": "7acfc7d1-9737-4bab-bc6c-20e39e116a56",
  "url": "https://www.dropbox.com/s/1g1kn6se4ai5zf1/7MB.h5ad?dl=1",
  "dataset_uuid": "a22b7097-7b15-4d7d-b4ed-37481ae3b052",
  "error": {
    "Error": "Batch.ClientException",
    "Cause": "JobDefinition arn:aws:batch:us-west-2:699936264352:job-definition/dp-staging-stagestack-upload:92 is not in ACTIVE status (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: d45febe2-f88a-434d-8f30-5c16009f4907; Proxy: null)"
  }
}
```

See
https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:699936264352:execution:dp-staging-stagestack-sfn:a22b7097-7b15-4d7d-b4ed-37481ae3b052_1617724712 for more details

**Comment by maniarathi** [comment]
Close due to being an old issue.
