### ISSUE TITLE
Delete Genesets when Canceling a revision

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#1088]
## Need
When a revision is canceled delete all genesets related to that revision

## Approach
- Verify that associated genesets are deleted when a collection revision is canceled.
- If deletion of csvs (for the revision) in s3 isnt set up -- implement

## Definition of Done
- Demonstrate that the genesets associated with the collections datasets are deleted (from both the geneset table and the csv from s3) when the revision is canceled.

**Comment by maniarathi** [comment]
Closing as gene sets is a deprecated feature from Portal.
