### ISSUE TITLE
Processing Container falls over on 29GB Dataset

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#1120]
## Describe the bug
The dataset failed processing with this error message:
![Screen Shot 2021-04-22 at 10 52 32 AM](https://user-images.githubusercontent.com/1429913/115762979-e0450000-a358-11eb-96bc-8ab9beab36f7.png)

The user are also unable to download the h5ad for ["Survey of human embryonic development" dataset ](https://cellxgene.cziscience.com/collections/c114c20f-1ef4-49a5-9c2e-d965787fb90c/private). 
<img width="527" alt="Screen Shot 2021-04-21 at 12 40 27 PM" src="https://user-images.githubusercontent.com/1429913/115762426-5006bb00-a358-11eb-8231-b8b749e507a4.png">
The cxg file was successfully processed and uploaded to s3. 
The dataset was roughly 29Gb, the largest dataset we've processed to date. The container failed with [error 137](https://stackoverflow.com/questions/46282928/aws-ecs-exit-code-137) which could mean out of memory. In the logs the container did try to upload the h5ad. It looks like the boto3 code failed silently and the container proceeded to update the database as if the h5ad was uploaded. 

```
2021-04-20T21:15:24.986-07:00 INFO:__main__:Uploading to [DatasetArtifactFileType.H5AD] to S3 bucket: [corpora-data-prod].
2021-04-20T21:18:54.027-07:00 INFO:__main__:Updating database with DatasetArtifactFileType.H5AD.
```
From the logs, you can see that 3.5 minutes passed between attempting to upload and updating the database. Boto3 normally spits out log messages when it's uploading, which was not present in the logs.

## Expected behavior
- frontend messages should be present that clearly illustrate why the container failed.
- the processing container should not update the database with an h5ad artifact if the artifact was not uploaded to s3.
- the h5ad file should be uploaded first that way we can rerun the dataset without downloading from dropbox again.

## Environment
- **Container instance ARN** arn:aws:ecs:us-west-2:231426846575:container-instance/dp-prod-20210325000000_Batch_e8c8b587-7c9c-3892-9ab1-b3dc49bed5af/75fcc58ab8d745c693dd915782c38a57
- **Memory** 230000
- **Image** 699936264352.dkr.ecr.us-west-2.amazonaws.com/corpora-upload:sha-360de42a
- **DATASET_ID**	589b68f3-b69c-4e51-88ab-bd6e6e99ae66
- **DEPLOYMENT_STAGE**	prod
- **AWS_DEFAULT_REGION**	us-west-2
- **ARTIFACT_BUCKET**	corpora-data-prod
- **MANAGED_BY_AWS**	STARTED_BY_STEP_FUNCTIONS
- **CELLXGENE_BUCKET**	hosted-cellxgene-prod
- **FRONTEND_URL**	https://cellxgene.cziscience.com
- **ECS task ARN** arn:aws:ecs:us-west-2:231426846575:task/dp-prod-20210325000000_Batch_e8c8b587-7c9c-3892-9ab1-b3dc49bed5af/7d7cdab6ab9b465da31e56322b5110c8
## Additional context
- cxg was processed and uploaded to s3
- dataset was 29GB in size
- container returned 137
- cloudwatch log stream [dp-prod-prodstack-upload/default/7d7cdab6ab9b465da31e56322b5110c8](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fprod$252Fprodstack$252Fupload/log-events/dp-prod-prodstack-upload$252Fdefault$252F7d7cdab6ab9b465da31e56322b5110c8)

**Comment by MDunitz** [comment]
@maniarathi and I discussed creating a backdoor to convert and upload large datasets instead of changing all of the upload infra to fit rare cases. We could create a large instance and let Pablo convert the data and then copy it to s3 and then manually add the dataset links to the database.

**Comment by MDunitz** [comment]
Reduce allowable size in API to match the current container limitations (currently 23GB)
When rejecting due to dataset size show message to user that they should contact us directly.  @hthomas-czi do you have any ux recs?

@MaximilianLombardo 
- [ ] add note about size limits to curation tutorial

**Comment by brianraymor** [comment]
The dropbox chooser has a [sizeLimit filter](https://github.com/chanzuckerberg/corpora-data-portal/blob/44b98b49bd3a38bf19d9f73b9b75e14d2b4e0586/frontend/src/components/DropboxChooser/index.tsx#L32) that the portal uses to block curator selection of uploads that exceed our maximum size. 

`  sizeLimit: UPLOAD_SIZE_LIMIT_BYTES,
`

https://www.dropbox.com/developers/chooser

```
    // Optional. A limit on the size of each file that may be selected, in bytes.
    // If specified, the user will only be able to select files with size
    // less than or equal to this limit.
    // For the purposes of this option, folders have size zero.
    sizeLimit: 1024, // or any positive number
```

**Comment by brianraymor** [comment]
Closing per conversation with @maniarathi
