### ISSUE TITLE
Run processing container unit tests.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#1129]
## Need
We have tests for the processing container, but they take 40min to run using github actions. The 40min is because the processing container cache is not hitting in github actions. This causes the whole container to be rebuilt. 

## Definition of Done
- processing container tests will run on push-test
- All of the unit run in under 15min

**Comment by atolopko-czi** [comment]
Can we close this issue?

**Comment by maniarathi** [comment]
@MDunitz ? Good to close?

**Comment by brianraymor** [comment]
Closing due to lack of response. Re-open if needed.
