### ISSUE TITLE
Remove geneset-collection linkage code

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1134]
## Need
- In order to support the new product direction for genesets we need to remove code related to genesets for collections

## Approach
- delete collection id/visibility from geneset table
- migrate db
- delete collections/colllection_id/genesets POST route and any associated code
- update genesets information in GET collections/collection_id response object to be dataset specific
- remove collection deletion code that references gene sets.
- remove collection visibility check from geneset deletion code
## DOD
- Genesets are no longer linked to collections
- Code no longer in use is deleted
- tests referencing collection genesets are updated or deleted

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
