### ISSUE TITLE
Create DELETE dataset/{dataset_id}/genesets endpoint

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1136]
## Need
An endpoint to delete all genesets for a dataset

## Approach
- If the dataset is linked to a private collection, and the user is the owner of the collection, delete all genesets linked to a given dataset
- Need to also delete the csv from s3

## DOD
- Return a 204 on success
- If the user is not the owner of the collection return a 403
- If the collection is not private return a 405

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
