### ISSUE TITLE
[Frontend] A curator can add genesets to a dataset

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1137]
Figma - https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=178%3A1414

![Screen Shot 2021-04-27 at 09.56.44.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/73ca2df1-6303-4b01-aa19-6fc13297098e)

![Screen Shot 2021-04-27 at 09.58.08.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/d9871649-f4e0-41d7-9cb1-47a6b96d5a27)

**Comment by MDunitz** [comment]
Reuse validation and request formatting code for adding a geneset to a collection but instead send POST request to `dataset/{dataset_id}/genesets

**Comment by MDunitz** [comment]
Note that updates to geneset validation are in ticket 1140

**Comment by MDunitz** [comment]
Also includes removing the "ugly" test button

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
