### ISSUE TITLE
[Frontend] A curator can replace all genesets for a dataset

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1138]
figma - https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=623%3A82

![Screen Shot 2021-04-27 at 09.59.11.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/c7c65bce-3f8c-4fdd-b132-2dfcad8cd92c)

**Comment by MDunitz** [comment]
This should utilize  DELETE `datasets/{dataset_id}/genesets` to remove the genesets and then POST ``datasets/{dataset_id}/genesets` to add the replacement genesets

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
