### ISSUE TITLE
[Frontend] A curator can delete all genesets for a dataset in a private collection

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1139]
figma - https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=623%3A82

![Screen Shot 2021-04-27 at 09.59.11.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/c7862149-0b09-49d8-92bc-9b776071b529)

**Comment by MDunitz** [comment]
Use DELETE `datasets/{dataset_id}/genesets` endpoint

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
