### ISSUE TITLE
On hover display genesets associated with a dataset (count and names)

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1141]
figma - https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=25%3A367

![Screen Shot 2021-04-27 at 10.07.12.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/db5fb3d3-33ac-4e63-9000-905608014421)

This should only be visible to curators/owners of the collection the dataset is associated with

**Comment by MDunitz** [comment]
This should only be visible in private collections and only to the curator/owner

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
