### ISSUE TITLE
The download and explore actions for a dataset should be "obvious"

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1164]
Feedback from @jahilton

> I feel like you've buried the lead. The two actions I can do with this dataset are the least obvious feature on the page

RE:
![Screen Shot 2021-05-04 at 11.10.21 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/fbb39779-3613-4ac3-8eda-65a583dfb601)

UX Design
[Primary Color Action Buttons](https://www.figma.com/file/9EIBLKyI33uIasAMJ1qOcj/Miscellaneous?node-id=1%3A1326)

**Comment by brianraymor** [comment]
@ambrosejcarr riffed:

> My only thought is "what if the buttons were light blue to mimic the hyperlink color and distinguish them from the metadata?"

**Comment by MDunitz** [comment]
@hthomas-czi will upload some designs to address this by the end of sprint 20 (5/28).

**Comment by brianraymor** [comment]
@hthomas-czi and I also discussed that the `explore` glyph lacks the background frame of the original cellxgene design (or reverses the foreground and background colors), which may cause it to appear _unfamiliar_ to consumers.

![Screen Shot 2021-05-25 at 12.07.23 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/0a299ead-bc60-493e-a3c6-c61760f2e4fa)

![Screen Shot 2021-05-25 at 12.07.39 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/1b91fbff-ad5e-4d89-9820-45eb370bf2d0)

**Comment by brianraymor** [comment]
Closing based on the redesign.
