### ISSUE TITLE
Backdoor to facilitate upload of large datasets

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1173]
## Need
A way to upload datasets larger than what the container allows

## Approach
- [ ] Create a script to manually add the dataset links, metadata and assets to the database for the appropriate collection

## Note

Talk to Pablo re: S3 locations
Use `db/tunnel` for db access
Use cxg_admin to execute with new command

[This partially addresses bug: Processing Container falls over on 29GB Dataset](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1120)

**Comment by maniarathi** [comment]
This is addressed by the ongoing Curation APIs work, so closing.
