### ISSUE TITLE
Embed Plausible Analytics on cellxgene.cziscience.com

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/single-cell-data-portal#1210]
@maniarathi Add more details. Plausible has a script that needs to get embedded. 

1. Plausible credentials are available in 1Password vault
1. Must be added to both Explorer and Data Portal
1. For adding script tags in DP FE, Next.js recommends using their `next/script` component 🙆‍♂️  Details [here](https://nextjs.org/docs/basic-features/script) thank you!
1. Wire up Plausible in the app both DP and Explorer
1. DP: Update CSP in Next.js config to include Plausible's URL, otherwise the browser will block Plausible script from sending data to Plausible via Content Security Policy: https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/next.config.js#L21
1. Explorer also has CSP setting
1. Ensure Plausible dashboard gets data as expected
1. IMPORTANT: MAKE SURE THE SCRIPT SENDS DATA TO THE RIGHT ENV (dev, staging, prod, etc.)

[Plausible doc](https://plausible.io/docs/custom-domain/#replace-the-tracking-code-on-your-website-with-the-new-code)

NOTES:

1. https://plausible.io/sites should have two sites, one for prod and one for staging!
1. Prod: https://plausible.io/cellxgene.cziscience.com
1. Staging: https://plausible.io/cellxgene.staging.single-cell.czi.technology

**Comment by tihuan** [comment]
@maniarathi do we have a contract with Plausible already? If so, can I get access please? I'll add details to this ticket after playing with it! Thank you!

**Comment by maniarathi** [comment]
We do! All the details are in the cellxgene 1pass vault. Let me know if you don't have access to it!

**Comment by tihuan** [comment]
I just updated the details of the ticket. Hope it's clear now! Thank you!

**Comment by ambrosejcarr** [comment]
@tihuan we want to replace the google analytics functionality (that was working at one point) so that we can measure the number of users who explore each dataset on cellxgene. 

I _believe_ that means we need plausible on the explorer as well, since not all users who navigate to explorer will be referrals from the data portal.

**Comment by tihuan** [comment]
Yeah I think adding to both makes a lot more sense lol Just updated the description accordingly. Thanks so much, Ambrose!!

**Comment by tihuan** [comment]
Awesomee thanks for confirming, Arathi 🙏 !

**Comment by tihuan** [comment]
Plausible is available in staging DP and Explorer now! PTAL @brianraymor 🙏 Thank you!!
