### ISSUE TITLE
Leading and trailing spaces are not stripped prior to writing to the database

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1221]
Last night, I was prototyping with the DOI values returned by the portal API and noticed that one collection has a DOI with a leading space:

> 'Evolution of cellular diversity in primary motor cortex of human, marmoset monkey, and mouse'
> ' https://doi.org/10.1101/2020.03.31.016972'

I created a [collection in staging](https://cellxgene.staging.single-cell.czi.technology/collections/f59b63d5-a218-41a3-a2c3-f6f14e4d8a87) with leading white spaces in multiple text fields.

The response from the API demonstrates that the leading spaces were not stripped:

```
{
    "contact_email": "  brian@something.com",
    "contact_name": "    contact name with space",
    "description": "    description with space",
    "links": [
       {
            "link_name": "",
            "link_type": "DOI",
            "link_url": "     https://doi.org/withspace"
        }
    ],
    "name": "    collection with space"
}
```
We should not require our API users to add a `string.strip()` for such cases. 

## Definition of Done

The cleaning to strip whitespace should be done on the backend prior to committing the values to the database.

Any current cases in the database should be corrected.

**Comment by tihuan** [comment]
@ebezzi how to check staging version?

**Comment by ebezzi** [comment]
Confirmed this is in staging. I also did some preliminary QA on Brian's collection and it seems to be working as expected.
