### ISSUE TITLE
feat(withdraw): Add withdrawn dataset toast

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#1237]
## Need
When a dataset is tombstoned and user visits a direct link to it they should be redirected from the dataset url via the data adaptor to the collection page with a toast indicating the resource has been removed.

[original user story](https://github.com/chanzuckerberg/single-cell/issues/138)

## Approach

The toasts should reflect this [figma](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=802%3A4920). 

The data adaptor should catch requests to tombstoned datasets and redirect the user to the collection page for the dataset with a query parameter indicating the dataset and its tombstoned status. On the collection page, the withdrawn dataset toast should appear with the query parameter's data. The user will be redirected to the collection page with a query string that will trigger the toast.

## Definition of Done
- Navigating to a tombstoned dataset result in a withdrawn dataset toast.

**Comment by leslieypark** [comment]
@brianraymor @hthomas-czi The Figma link for this is for the "Publishing with Deleted Datasets Confirmation" toast.
I also checked the original user story design links, and they're both for the "Publishing with Deleted Datasets Confirmation".

Is there an update design for the withdrawn dataset toast?

**Comment by brianraymor** [comment]
Confirmed the new link with Harley and updated the figma link in the top-level summary comment.

**Comment by dimple-jethani** [comment]
test

**Comment by leslieypark** [comment]
FE portion is ready for QA

**Comment by leslieypark** [comment]
Please note for QAing:
There is a 5 minute delay between a dataset being deleted via the data portal, and the availability of the redirect in the explorer. This is due to how we're caching the dataset metadata in the explorer.
