### ISSUE TITLE
Deprecate obsolete feature flags

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1239]
All curators are being notified next week to use `?curator=true` for access to released curation features.

Definitions and references to obsolete feature flags should be removed from the codebase for `CREATE_COLLECTION` and `AUTH`. 

```
export enum FEATURES {
  CREATE_COLLECTION = "cc",
  AUTH = "auth",
  GENE_SETS = "gs",
  CURATOR = "curator",
  REVISION = "rc",
}
```

**Comment by tihuan** [comment]
@leslieypark moved this to QA ready since it's merged! Thank you!

**Comment by tihuan** [comment]
@brianraymor PTAL the old flags are gone!
