### ISSUE TITLE
[Bug] Hosted cellxgene unit tests currently running against cellxgene package

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1247]
## Need
The cellxgene unit tests should run in conditions as similar as possible to how they run in production. Currently the hosted unit tests spin up the cellxgene package server instead of the server used in elastic beanstalk

## Approach
update the unit tests to use the wsgi server/create a test server and necessary infrastructure 

## DOD
- unit tests pass when testing in an environment similar to the prod env

**Comment by tihuan** [comment]
In staging now!
