### ISSUE TITLE
mean_genes_per_cell is calculated and then thrown away

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1251]
I’ve been looking into the `mean_genes_per_cell` dependency on `layer_descriptions` which is deprecated in schema v2.0.0. `mean_genes_per_cell` is calculated in [extract_metadata](https://github.com/chanzuckerberg/corpora-data-portal/blob/dc6d1667991a5a44137469fd145bd28681c07e21/backend/corpora/dataset_processing/process.py#L253) and then [thrown away](https://github.com/chanzuckerberg/corpora-data-portal/blob/dc6d1667991a5a44137469fd145bd28681c07e21/backend/corpora/dataset_processing/process.py#L227)?

```
# TODO: Delete this line once mean_genes_per_cell is in the db
metadata.pop(“mean_genes_per_cell”, None)
```

Very Zen.

This will need to be stored in the database and returned by the `GET /dp​/v1​/collections​/{collection_uuid}` portal API.

---

In addition, schema 2.0.0 supports two different values for  [`feature_biotype`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/corpora_schema.md#feature_biotype) - 'gene' or 'spike-in'. The calculation for `mean_genes_per_cell` must only include features that are genes. 

---

Per a July 29 slack conversation with @ambrosejcarr and @seve - the source of the matrix for the calculation:

1. If AnnData.raw.X is defined, then process is done -- this is the raw data.
2. If AnnData.uns['X_normalization']  is set to “none”, then process is done -- AnnData.X is the raw data.
3. Otherwise, there is no raw data because this is an [Accessibility Assay](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/corpora_schema.md#x-matrix-layers) such as ATAC-seq. In this case, default to AnnData.X.

**Comment by MDunitz** [comment]
Set to zero for all datasets with the initial db migration
Ensure the value is stored when uploading a new dataset

**Comment by pablo-gar** [comment]
@MDunitz 

Could you please clarify your comment? What is initial db migration?

**Comment by MDunitz** [comment]
In order to store this information we need to add a field to the dataset table in the db. That will require migrating the db. To avoid errors caused by unexpected null values I'm saying we should set the value to zero initially (since we plan to reingest all the datasets anyways at which point it will be set to the correct value -- assuming we update the code to store the value when uploading a new dataset)

**Comment by brianraymor** [comment]
> assuming we update the code to store the value when uploading a new dataset)

I choose to include this bug in the epic for 2.0.0 to ensure that the code **was** updated prior to revising our entire data corpus.
