### ISSUE TITLE
Upload of dataset failed but CXG was created

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1252]
See the conversation in [single-cell-eng](https://czi-sci.slack.com/archives/C023Q1APASK/p1624654124078400) which includes the link to the private collection and its CXG which I'm not exposing in this issue.

The dataset failed to upload, but both the `download` and `explore` buttons are enabled and should be disabled or not present. There are no dataset downloads available as expected, but clicking on `explore` opens the CXG in explorer - although the CXG should not exist since the upload failed. 

![Screen Shot 2021-06-28 at 2.46.18 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/bb9a834c-bfaa-4a38-9e73-485934c39a08)

**Comment by tihuan** [comment]
@brianraymor @MDunitz Have we figured out what the fix is? Is it updating the upload steps outlined by Trent [here](https://czi-sci.slack.com/archives/C023Q1APASK/p1624928972085700?thread_ts=1624654124.078400&cid=C023Q1APASK)? Would that still be a 1 pointer?

@MDunitz since this is a BE change, we might need your expertise here 😆🙏

Thank you!

**Comment by brianraymor** [comment]
From the earlier conversation, conclusion is **bolded** below. Basically, `extract_metadata` needs to occur before conversions to ensure that validation is successful prior to conversions. At some point, an [additional validation step](https://github.com/chanzuckerberg/corpora-data-portal/blob/dc6d1667991a5a44137469fd145bd28681c07e21/backend/corpora/dataset_processing/process.py#L258) related to the raw matrix for use in calculating `mean_genes` was added in the wrong place (should have been in `cellxgene-schema`) which can result in validation failing "late" in step 3.

> 1. validate h5ad
> 2. generate and upload CXG to cellxgene bucket, and update the database
> 3. extra[ct] metadata from h5ad and update database
> 4. upload h5ad artifact and update database
> 5. generate loom file, upload, and update database
> 6. generate seurat file, upload, and update database.
> 
> **For some reason the dataset failed at step 3. This is why the cxg is available and nothing else. Changing the order of most of these steps is trivial. I personally think Step 2 should go after step 4.**

**Comment by tihuan** [comment]
@MDunitz  will add sample dataset for testing! thank you!

**Comment by brianraymor** [comment]
Fails as expected. (The error message is the older "try again").

**Comment by tihuan** [comment]
Thanks @brianraymor ! Moved to ready for prod 🎉
