### ISSUE TITLE
[Explorer] Delete Desktop code from explorer repo

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1275]
## Need
To remove code specific to the desktop cellxgene application from the explorer repo

## Approach
- [x] Delete backend/server
- [x] Delete backend/test/test_server
- [x] rename setup_hosted.py to setup.py
- [x] rename manifest_hosted to manifest
- [x] move common into czi_hosted
- [x] move test_common into test_czi_hosted
- [x] backend/czi_hosted -> server
- [x] backend/tests/test_czi_hosted -> tests
- [x] Remove make commands for desktop
- [x] update/simplify remaining make commands
- [x] remove desktop references from github actions
- [x] remove compatibility tests
- [ ] remove desktop references from documentation 

## DOD
- no references to czi_hosted in the explorer repo
- no references to desktop in the explorer repo

**Comment by MDunitz** [comment]
Recommend splitting this into multiple prs (suggestion for splitting it up)

- remove the desktop code
- refactor the remaining code
- update the make commands
- update the github actions

**Comment by blrnw3** [comment]
@MDunitz what/where are the compatibility tests?
Also, do we need to keep the `docs` directory in single-cell-explorer?

**Comment by MDunitz** [comment]
Compatibility tests were a github action workflow triggered weekly. I deleted them in an earlier pr.
We dont need to keep the docs directory but we should keep/update any docs that are relevant to the explorer
