### ISSUE TITLE
feat(withdraw): Add withdrawn collection toasts 

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1283]
## Need
When a collection is tombstoned and user visits a direct link to it they should be directed to the collections page with a toast indicating the resource has been removed. We also need to edit the copy on the publish collection dialog that states that collections cannot be deleted

## Approach
The toasts should reflect this [figma](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=803%3A0). 

For a collection, the withdrawn collection toast should appear when a user attempts to visit the collection page of a tombstone collection. GET collection/{collection_id} will return the information need to populate this page. 

**Additional context**
Originally a part of #1237

## Definition of Done
	- Navigating to a tombstoned collection results in a withdrawn collection toast.

**Comment by maesen** [comment]
Note: passed in refinement 8/24 because we don't have the ability to delete a collection yet.
