### ISSUE TITLE
[Spike] Investigate authorization roles in auth0

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1284]
## Need
- Stanford curators need to revise/reupload datasets they dont own

## Approach
A.) 
- DB snapshot
- update owner of all datasets (to be stanford)
- revise dataset
- transfer ownership back based on db snapshot

B.) 
- Create superusers via auth0
- create for superuser status when checking dataset owner

**Comment by tihuan** [comment]
@ebezzi fixed smoke tests!

**Comment by ebezzi** [comment]
The spike has been implemented as part of this ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1368. Moving this to Done.
