### ISSUE TITLE
[Bug] Failed uploads dont trigger a notification to the single-cell-ops channel

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1287]
## Need
- Determine why failed uploads no longer trigger a notification in the single-cell-ops channel. Fix or create a ticket to fix the underlying issue

**Comment by metakuni** [comment]
To do: Check with Madison next week.

**Comment by metakuni** [comment]
The stretch task of only notifying on the last retry will be addressed by #1588, currently in progress.

**Comment by metakuni** [comment]
Closing this story since we do appear to be getting Slack notifications on failed uploads. Will create a new bug story if appropriate.
