### ISSUE TITLE
add new fields to dataset entity

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1296]
New or updated fields as a result of schema 2.0 should be stored in the DB and served to the collection endpoint `/dp/v1/collections/{id}`.

Default Values for Migration:
* `sex`, `cell_type`, `X_normalization`, `X_approximate_distribution`: null
* `is_primary_data`: False
* schema_version: Script should generate values for existing datasets

| Old UML | New UML | 
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/8716829/127538627-cde2410f-5837-4e05-9bde-f8fd8fac0396.png) | ![image](https://user-images.githubusercontent.com/8716829/128054433-1bb45a70-8a94-4800-8d7c-e77402387120.png) |

##### changes marked in blue

Note: Sex is marked as a change, but no change to the DB will be needed. The API will switch from https://github.com/chanzuckerberg/corpora-data-portal/blob/135214e9f423d815645fb3e953dc3a222b7fd252/backend/config/corpora-api.yml#L821-L824
to
```
sex:
  $ref: "#/components/schemas/ontology_element_array"
```

----

A few dataset attributes have been either added, changed, or removed, update our api yml to reflect those changes:
https://github.com/chanzuckerberg/corpora-data-portal/blob/44b98b49bd3a38bf19d9f73b9b75e14d2b4e0586/backend/config/corpora-api.yml#L688-L743

The frontend should also add the fields to the collection entity defined in `src/common/queries/entities.ts`

### Definition of Done
* DB Migration with new and modified DB columns
* A script to generate `schema_version` for existing datasets
* Updated UML published and chanzuckerberg/single-cell references updated
* Updated api yaml
* Update entities.ts (in the frontend)
* Update all the unit tests so the mocked data is on par with the new schema definition

**Comment by seve** [comment]
Removing frontend aspect of this ticket and creating new ticket since a bit more work will be needed

**Comment by seve** [comment]
All new fields can be null while we migrate 1.x.x datasets to 2.0.0 since there will be no immediate UX impact

**Comment by maniarathi** [comment]
I wonder if it might be useful to add the `schema_version` in the database as well to log what schema version the dataset was validated against. It may not be useful in the API now, but could be useful data to have at some point (I'm thinking even as a gut check to verify all the datasets that are public facing are migrated to version 2.0 before we launch).

**Comment by seve** [comment]
Store schema in db and write script to generate the version # for older datasets
