### ISSUE TITLE
Update our usage of `cellxgene-schema` to match 2.0.0 changes

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1297]
During the upload process, we need to now call `cellxgene-schema` with the following arguments to support the application of human-readable labels:
`cellxgene-schema validate --add-labels <OUTPUT FILE>`

Please coordinate with @pablo-gar

### Definition of Done
* Replace our existing `cellxgene-schema` with updated call
* Continue down processing path with the resulting output file
* Clean up output file and original H5ad at the end of processing
~* Fix any broken tests~
~* Handle any possible failure paths resulting from the call~
~* Remove any of our redundant h5ad validation from `H5ADDataFile`~

**Comment by maesen** [comment]
@leslieypark @metakuni @danieljhegeman @blrnw3 Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1297?planning-poker)

**Comment by maesen** [comment]
Since we're running up against our Sept 10th deadline, let's descope these pieces:

- Fix any broken tests
- Handle any possible failure paths resulting from the call
- Remove any of our redundant h5ad validation from H5ADDataFile

**Comment by brianraymor** [comment]
Closing per conversation with @maniarathi
