### ISSUE TITLE
Replace existing `layer_descriptions` field with new schema 2.0.0 `X_normalization`

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1300]
`layer_descriptions` is being depricated and replaced by `X_normalization` [here](https://github.com/chanzuckerberg/single-cell-curation/pull/103)

Change dataset validator to check for presence of `X_normalization` field:
https://github.com/chanzuckerberg/corpora-data-portal/blob/44b98b49bd3a38bf19d9f73b9b75e14d2b4e0586/backend/corpora/common/dataset_validator.py#L134-L146

Change raw layer extraction (See #1251  for the logic needed to identify the appropriate layer)
https://github.com/chanzuckerberg/corpora-data-portal/blob/7139b4f7a123544b7982dde74b8ddf17436f11de/backend/corpora/dataset_processing/process.py#L257-L267

Store `X_normalization` as a dataset column and serve on `GET /dp​/v1​/collections​/{id}` 

Add field to dataset entitity on frontend

### Definition of Done
* Add `@ambrosejcarr` to review raw layer extraction and mean genes per cell calculation

**Comment by leslieypark** [comment]
"Change raw layer extraction" portion of this ticket is done here: https://github.com/chanzuckerberg/corpora-data-portal/pull/1351

**Comment by leslieypark** [comment]
"Change dataset validator" portion of this ticket is done here: https://github.com/chanzuckerberg/single-cell-data-portal/pull/1363
