### ISSUE TITLE
Revising collection information requires a manual refresh

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1305]
I changed the collection name. There was no update until I manually refreshed.

https://images.zenhubusercontent.com/280546849/14d9952e-ad1e-4799-9977-ea670a876d29/screen_recording_2021_07_28_at_2_58_25_pm.mov

`Publish` is also disabled until the refresh.

**Comment by hthomas-czi** [comment]
Looks good to me.
