### ISSUE TITLE
Adding a dataset during a revision requires a manual refresh

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1307]
I added a dataset. The toast informed me that the upload had started. I waited. I waited. Then I finally refreshed:

https://images.zenhubusercontent.com/228681195/56c9c58e-af22-442f-9eff-4ab16697b229/screen_recording_2021_07_28_at_3_15_32_pm.mov

**Comment by hthomas-czi** [comment]
Looks good to me.
