### ISSUE TITLE
Cancelling a revision takes 6-7 seconds?

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1308]
This is more of a _fit and finish_ issue, but I would expect that cancelling a revision would be instantaneous from the perspective of the curator with asynchronous cleanup occurring in the background. Is there a technical reason that this is not possible? 

https://images.zenhubusercontent.com/228681195/4fc11bde-c839-42f1-9908-404b5f1d5654/screen_recording_2021_07_28_at_3_50_13_pm.mov

**Comment by tihuan** [comment]
Added `frontend` since I believe it's FE retrying GET collection 3 times unnecessarily that's causing the slow down!

**Comment by tihuan** [comment]
PR is out!

https://github.com/chanzuckerberg/single-cell-data-portal/pull/1360

**Comment by brianraymor** [comment]
LGTM.

**Comment by tihuan** [comment]
Thanks, Brian! Moved to ready for prod 🎉
