### ISSUE TITLE
Revision status not being enabled when rapidly operating on collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1309]
Edge case:

1. I start a revision.
2. I update a dataset.
3. I cancel the revision during the update.
4. I start a revision on the same collection.
5. I attempt to update the dataset, but the menu item is not present:

![Screen Shot 2021-07-28 at 4.05.19 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/aa4bed72-ff5c-4f02-bd47-9befc20f569e)

I need to refresh the page to for the menu item to appear.

**Comment by hthomas-czi** [comment]
Looks good to me.
