### ISSUE TITLE
update metadata extraction code to extract new attributes

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1314]
We need to extract the new and modified anndata fields to feed to the DB.

* `organism` has now moved from `uns` to `obs` 
   * https://github.com/chanzuckerberg/corpora-data-portal/blob/c9cf328f6f0ff97a1c764a9bd5a0b3655b598fd0/backend/corpora/dataset_processing/process.py#L287
* `is_primary_data`, a new field, needs to be fetched from `obs`
* `cell_type` and `cell_type_ontology_term_id` are new fields in `obs`
* `sex` now has the corresponding `sex_onotology_term_id` field on `obs`
   * https://github.com/chanzuckerberg/corpora-data-portal/blob/c9cf328f6f0ff97a1c764a9bd5a0b3655b598fd0/backend/corpora/dataset_processing/process.py#L291
* `X_normalization` is a new field which will be found on `uns`
* `X_approximate_distribution` is a new field which will be found on `uns`

See related issue #1296 for UML and value types

**Comment by tihuan** [comment]
@ebezzi help verify in staging before QA
