### ISSUE TITLE
Metadata categoricals are inconsistently sorted in the All Collections view

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1329]
In the _All Collections_ view, some metadata categoricals for collections are correctly sorted, but others are **not** such as `Tissue` in Tabula Muris Senis.

![Screen Shot 2021-08-05 at 4.05.13 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/24e49899-e4f4-42a8-b915-e9f9a96c6196)

For the _A Collection_ view, all dataset categoricals appear to be correctly sorted in all cases. 

In addition, sorting must be case-insensitive.

**Comment by tihuan** [comment]
@brianraymor PTAL!

**Comment by brianraymor** [comment]
@tihuan - looks good for all the columns that have categoricals.

**Comment by tihuan** [comment]
Awesome thanks so much for QAing! Moving to ready for prod 🙌
