### ISSUE TITLE
[SPIKE] Cell centric data portal database

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1331]
## Need 
The schema 2.0 changes, the requirements for search and filter, and our general long term strategy are focused on a cell centric model however our current database centers on the datasets

## Investigate
Different options for performantly storing, accessing and searching the cell level information our users are interested in

## Details
- Search and filter is a good example of where this will be needed. If a user searches for lung and asthma, they want cells that come from diseased lung tissue, not cells that are in a dataset that contains cells from a lung and cells from a patient with asthma (which is what we are currently able to return)

**Comment by brianraymor** [comment]
This "reminder" issue is not needed.
