### ISSUE TITLE
Add datadog monitoring/alert to the covid atlas

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1332]
## Need
- A way to monitor the covid atlas to ensure it is available

## Approach
- Add a datadog monitor/alert with a slack notification that triggers when the website is unresponsive

## DOD
- If the covid atlas website is down we are alerted in the ops channel

**Comment by maniarathi** [comment]
Closing due to low priority and "[important ideas come back](https://basecamp.com/shapeup/2.1-chapter-07)."
