### ISSUE TITLE
The API must be updated to support filtering by date ranges

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1340]
### API

`created_at` and `updated_at` must be removed from API GET responses.

#### `GET /dp​/v1​/collections`

`created_at` must be replaced with `published_on`.
`updated_at` must be added for `revised_on`.

```
{'created_at': 1629404918.812605,
 'id': '9c757238-335f-43e8-b292-66159b5f9b20',
 'visibility': 'PUBLIC'}
```

It is also possible to filter collections with Unix epoch date range:

// Return all the collections created in March 2021
payload = {'from_date': '1614556800', 'to_date': '1617148800'}
by_date = requests.get(COLLECTIONS_REQUEST, params=payload)

This API should either be updated to use the new `published_on` and `revised_on` fields or deprecated in favor of a more specific filtering API. 

#### `GET /dp/v1/collections/{collection_uuid}`

1. `created_at` and `updated_at` for the collection must be replaced with `published_on` and `revised_on`.
2. `created_at` and `updated_at` for each dataset in `datasets` must be replaced with `published_on` and `revised_on`.
3. `created_at` and `updated_at` for each asset in `dataset_assets` must not be included. In general, asset timestamps should be the same as the containing `datasets` timestamp so the information is redundant to return or store. 

```
{'access_type': 'READ',
 'contact_email': 'brianraymor@test.com',
 'contact_name': 'Brian Raymor',
 'created_at': 1628821977.884414,
 'data_submission_policy_version': '1.0',
 'datasets': [{'assay': [{'label': "10x 3' v3 sequencing",
     'ontology_term_id': 'EFO:0009922'}],
   'cell_count': 2638,
   'collection_id': '1afb1a31-4306-4b4d-9edf-7e0560cddcd7',
   'collection_visibility': 'PUBLIC',
   'created_at': 1628821996.414398,
   'dataset_assets': [{'created_at': 1628824647.889531,
     'dataset_id': '5d9dd27c-8fbd-4799-976f-24fc42c39faf',
     'filename': 'explorer_cxg',
     'filetype': 'CXG',
     'id': 'b6e189be-7830-4b03-83c0-e0a5d6c39d08',
     's3_uri': 's3://hosted-cellxgene-staging/f5855772-e060-4c30-a3fa-bb5e8fd9ec9a.cxg/',
     'type': 'REMIX',
     'updated_at': 1628824837.300442,
     'user_submitted': True},
      ...
 'description': 'testing revised_at\r\nediting collection details',
 'id': '1afb1a31-4306-4b4d-9edf-7e0560cddcd7',
 'name': 'revised_at',
 'obfuscated_uuid': '',
 'updated_at': 1628824015.49317,
 'visibility': 'PUBLIC'}
```
 ---

If sorting is added to this API:

The publication date is calculated as follows:

1. If the collection includes a published DOI, then the journal publication date is the publication date for both the collection and its datasets.
2. Otherwise, the publication date, in order of priority, is the revised_at or published_at timestamp for the collection or the dataset.

**Comment by maniarathi** [comment]
@brianraymor Can this issue be closed?

**Comment by brianraymor** [comment]
We may want to add to fit and finish for the curation API.
