### ISSUE TITLE
Fix: update collection/collection_id response object

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1343]
## Need
- Remove tombstoned datasets from the collection details endpoint response object

## Approach
 - remove include_tombstones from function call

## DOD
- tombstoned datasets are not returned 
- update unit tests

**Comment by brianraymor** [comment]
@MDunitz - Please see [Need design for tombstoned data](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1389)

**Comment by Bento007** [comment]
Verified as fixed.

Started a revision, removed a dataset, published, and checked for the presents of a tombstoned dataset in the collection response body.
