### ISSUE TITLE
Revision E2E Part 2

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#1349]
Part 1 is [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/1292)

1. This ticket needs to discuss with BE team on possibly mocking upload dataset process in non prod environment, so we can test dataset upload quickly. 
1. Also figure out how to log into Dropbox and select a dataset to upload in E2E. And if not possible due to 2FA and/or bot detection, maybe FE conditionally adds a hidden input field for non prod envs to supply a test dataset URL`https://example.com/test-upload` to signal BE to use the mock upload process?

- Frontend testing through playwright 
    - [ ] Trying to publish it
       - Check that publishing a revision ends the revision state
       - Updates the published collection
    - [ ] Delete an original dataset. Publish. 
       - Visit the original CXG link which must redirect to the collection and pop a toast about the withdrawal. 
    - [ ] Revised Dataset Tags
       - Create a static collection with one of each dataset type ( this is done manually, outside the test suite, and the collection shouldn't be edited past that)
       - Test for tags  

- Notes:
   - We've been kicking the can down the road re: testing dataset uploads.  Perhaps we add some mocking for the dataset upload and processing steps for non-prod environments, and add conditional env tests accordingly
      - ie. on dev + staging: dropbox url of https://example.com/test-upload fires off a mock upload process which completes in a few seconds pointing to a number of static test datasets + assets

**Comment by tihuan** [comment]
I've changed this ticket to a spike (design me!) to investigate both mock dataset upload and Dropbox auth in E2E

**Comment by maesen** [comment]
Note: this testing was originally a part of revisions:
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/36

We are moving it to our cool-down backlog.

**Comment by tihuan** [comment]
Related to https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/971

**Comment by atolopko-czi** [comment]
@tihuan still worthwhile?

**Comment by atolopko-czi** [comment]
@maniarathi @dsadgat Kuni suggested this as possible work for TestCo when they return to Single Cell.

**Comment by metakuni** [comment]
Closing since curators now use the Discover API.
