### ISSUE TITLE
Re-upload staging test dataset to be compliant with schema 2.0.0

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1354]
The dataset 79dfc1fe-cc7a-454a-ba26-4c72f0876436 in staging is currently used for unit tests in corpora-data-portal. While we transition to 2.0.0, this has been manually modified in S3 to be compliant with 2.0.0, but the metadata in the database will be 1.1.0. Once the migration is complete, reupload this dataset so everything is 2.0.0 compliant.

TEAM COMMENTS:
* We have hacked a test dataset to make the unit tests pass.
* You can ping the data wrangling channel to get a better alternative

**Comment by atolopko-czi** [comment]
Clarification needed:
* So engineers manually changed this dataset? I can see the timestamp is updated.
```
❯ aws --profile single-cell-dev s3 ls s3://corpora-data-staging/79dfc1fe-cc7a-454a-ba26-4c72f0876436/
2021-08-24 17:51:13   18218219 local.h5ad
2021-08-17 14:57:29    9977305 local.loom
2021-08-17 14:57:48   25126129 local.rds
```
* Do we just want to reupload this exact file to staging data portal so it can reprocess it fully? Or do we want to obtain the "real" curator-updated version of this file, whenever that may be ready?
* Is the reason this specific UUID matters is that it's referenced in tests [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/16883102bde64272d277bce0288b2c4c4b0f3e14/tests/unit/processing_container/test_process.py#L25-L24)? Couldn't we just upload the file and change the test to whatever new UUID is created?
* What about the other UUID referenced in that test?
* I assume we should also address the TODOs in the [test file](https://github.com/chanzuckerberg/single-cell-data-portal/blob/16883102bde64272d277bce0288b2c4c4b0f3e14/tests/unit/processing_container/test_process.py#L59) and issue a PR?
* These "unit" tests are only ever run on staging env?

**Comment by atolopko-czi** [comment]
Talked with @ebezzi. Bottom line is that the test just needs _some_ h5ad file, which doesn't need to be on staging at all. I think originally the file was taken from S3 to avoid committing this large-ish file to the repo.  But it's really just a test fixture and can be stored anywhere.  Ideally, in the repo so as not to depend upon network for unit test behavior.

**Comment by blrnw3** [comment]
Does the explorer test dataset need to be updated too? https://github.com/chanzuckerberg/single-cell-explorer/tree/main/example-dataset

**Comment by atolopko-czi** [comment]
> Does the explorer test dataset need to be updated too? https://github.com/chanzuckerberg/single-cell-explorer/tree/main/example-dataset

Shouldn't hosted explorer be unaware of h5ad files now? I'm wondering if any and all usages of that file are for code that shouldn't even in the repo anymore. Or, if an h5ad is being used for tests, it should be changesd to use a CXG, assuming the h5ad is being loaded in tests using AnnDataAdapter, rather than a CxgDataAdapter.  The former being unnecessary in hosted explorer now, if I understand correctly.

**Comment by blrnw3** [comment]
You are correct. My mistake, this is covered by this ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1277
Good catch 🦅
