### ISSUE TITLE
Lint cellxgene desktop and hosted explorer

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1355]
## Need
To clean up the code bases and handle all linting issues

## Approach
Run make lint on both repos and commit the changes
ensure that the makefile lint / format config matches the editor (package) definitions in pyproject.toml/setup.cfg so we dont have unnecessary code changes in future prs

## DOD 
running make lint or make fmt creates no changes

**Comment by blrnw3** [comment]
hosted has been linted

**Comment by maniarathi** [comment]
Closing as we decided not to make further linting changes to cellxgene for now.
