### ISSUE TITLE
Implement authorization for curators

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1368]
The website should have this behavior with respect to authorization:

1. Everyone who is signed in should be able to create a collection (you still need the `?curator=true` flag to see the `Create collection` button) (currently implemented)
2. A user should be able to view, edit and create revisions only for collections they own (currently implemented)
3. Curators (i.e. users with `write:permissions` scope) should be able to view, edit and create revisions for all collections (TODO)

The basic authorization infra has already been created as part of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1284

**Comment by ebezzi** [comment]
@brianraymor thanks for the corrections, I edited the description.

**Comment by maesen** [comment]
TEAM COMMENTS:
* Auth0 permissions already set up. `write:permissions` scope will give this curation power.
* Endpoint to get collections should return all collections (public and private) under My Collections for users with this scope. ("Waive" the filter.)
* Scope of this ticket also includes adding test cases. Test user will need this scope.
