### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by leslieypark** [chanzuckerberg/single-cell-data-portal#1371]
There is a flaky test when checking conversion statuses before they are loaded:

https://github.com/chanzuckerberg/single-cell-data-portal/runs/3447166530?check_suite_focus=true

Similar issue was fixed previously here: https://github.com/chanzuckerberg/single-cell-data-portal/pull/1352

**Comment by brianraymor** [comment]
Closing per conversation with @ebezzi
