### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1377]
## Need
Every month we check for available (and compatible) updates for data portal dependencies

## Approach 
See [doc on updating dependencies ](https://github.com/chanzuckerberg/single-cell/blob/main/how-we-work/how-to-upgrade-dependencies.md)

**Comment by metakuni** [comment]
Bumping for [Nov 1 notification in Slack](https://czi-sci.slack.com/archives/C0244PQK934/p1635782439062900):
```
Slackbot  12:00
Reminder: Please create an issue for both corpora-data-portal and cellxgene to update all dependency packages (both npm and pip) at some point during this current sprint.
```

**Comment by tihuan** [comment]
working in staging!

**Comment by tihuan** [comment]
Working in prod!
