### ISSUE TITLE
Need design for tombstoned data

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1389]
See the [thread](https://czi-sci.slack.com/archives/C023Q1APASK/p1631041537114500) in **#single-cell-eng**:

> Specifically, we wanted to check with you on how we should handle tombestoned datasets. The Figma attached to the ticket has an image where the name of the dataset is included in the toast message.
Currently we don’t have an endpoint in the data portal to get a specific dataset’s (incl. tombstoned dataset) information. We can either:
1. Not include the tombstoned dataset’s name in the toast message.
2.  Create an endpoint in the data portal to get information for a specific dataset. E.g., GET dataset/{id}
3. Include tombstoned datasets in the collection detail endpoint. (Not recommended)

For the moment, `1` is the consensus solution.

I'm collecting [input from partners](https://cziscience.slack.com/archives/C01L65J7PLP/p1631057434014200) on their API requirements and preferences related to _tombstoned_ collections and datasets to help inform the design. In general, the partners would like access to this information.

**Comment by brianraymor** [comment]
Per conversation with @maniarathi and @maesen, this will be input into the architectural roadmap and API redesign discussions in Q4. I'm leaving it attached to this related epic as a placeholder until then.

**Comment by brianraymor** [comment]
The toast for withdrawn collections also needs an API to acquire the `collection name` and `contact`. A more generic message was implemented in the interim. See [**curator-experience**](https://czi-sci.slack.com/archives/C02JYPUKTL2/p1636498201007600?thread_ts=1636489469.000800&cid=C02JYPUKTL2)

**Comment by maniarathi** [comment]
@brianraymor This is good to close right?

**Comment by brianraymor** [comment]
@danieljhegeman - this has been addressed in the curation API like:

_If a collection in the list has been deleted, then it is annotated with tombstone set to True._

**Comment by danieljhegeman** [comment]
@brianraymor correct, that is the behavior of the Curation API
