### ISSUE TITLE
Update test_process.py to remove the cellxgene-schema validation mock

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1402]
[This test](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/processing_container/test_process.py) currently mocks the functionality of `cellxgene-schema`. Since this is effectively a functional test (uses real datasets), we shouldn't mock it. Some changes are required though:
- Since the new `cellxgene-schema` also adds labels, we should not download an h5ad file from one of the existing datasets, because that will have labels. We should instead upload an unlabelled h5ad file to Dropbox (or S3, but dropbox will probably make this easier), pass it through `cellxgene-schema` and also verify that the labels have been properly added.

**Comment by atolopko-czi** [comment]
Referenced test has been moved or no longer exists.
