### ISSUE TITLE
h5ad->cxg transform must ensure x_col_shift array of same type as X matrix

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1410]
To conform to the [0.2.0 CXG spec](https://github.com/chanzuckerberg/single-cell-explorer/blob/aa58df7cac5d8a87b26600f236d10b4bae7e8163/dev_docs/cxg.md) the `single-cell-data-portal` repo's `backend.corpora.common.utils.matrix_utils.get_column_shift_encode_for_matrix` must return a col_shift array of the same numpy type as the `matrix` arg. See [original comment](https://github.com/chanzuckerberg/single-cell-explorer/pull/49/files#r706650079).

This should be a fairly minor code change. However, it's not known whether it is evening causing any problems in Explorer. If not, is simply a "bug" in that the generated CXG file is strictly following the spec.

If the shifted matrix values are being reified incorrectly in Explorer (due to type mismatching), then affected CXG files need to be determined and regenerated.

**Comment by maniarathi** [comment]
Marking this as a P0 since if we need to re-generate the CXG, we should do that ASAP to avoid any bugs.
