### ISSUE TITLE
Remove support for the loom format

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1427]
Based on the absence of loom downloads in the download reports, @ambrosejcarr has confirmed that we may deprecate this feature prior to product launch:

* Remove loom as a format for downloads in the UI
* Remove conversion from h5ad to loom during upload
* Remove loom related tests and/or validation
* Remove all references to loom in the code base

**Comment by seve** [comment]
Swapping this ticket to an epic to catch all three parts:
* FE removal
* Backend removal
* Deletion of S3 assets
