### ISSUE TITLE
Add additional datasets to staging env

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#1441]
Please add the schema 2.0.0 version of the following datasets to the staging environment:

- [azimuth](https://cellxgene.cziscience.com/collections/2f75d249-1bec-459b-bf2b-b86221097ced)
- [human heart](https://cellxgene.cziscience.com/collections/b52eb423-5d0d-4645-b217-e1c6d38b2e72)
- [human cell landscape](https://cellxgene.cziscience.com/collections/38833785-fac5-48fd-944a-0f62a4c23ed1)

**Comment by signechambers1** [comment]
fyi @ambrosejcarr @brianraymor @MaximilianLombardo if there are additional datasets that would be helpful to have in staging please add here

**Comment by brianraymor** [comment]
I'm sorry - what is the purpose of this issue? And we would need to add 2.0.0 versions of the datasets?

**Comment by signechambers1** [comment]
@brianraymor its helpful for me to test explorer features on larger datasets in staging so I asked Madison to add a few. I think we do need the 2.0.0 versions (ill edit the description of the issue). I think these are already migrated to 2.0 or on the list to be migrated but please correct me if im wrong, no intention to add extra curation work.

fyi @MDunitz

**Comment by brianraymor** [comment]
I see. I'd wait until 2.0.0 re-curation is complete. It's just started.

**Comment by metakuni** [comment]
#1735 might deprecate this story

**Comment by metakuni** [comment]
Closing this issue since #1735 will address adding these 3 collections to the staging environment.
