### ISSUE TITLE
Add test assertions to test_process integration test

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1449]
As follow-up to #1354, assertions should be added to `tests.unit.processing_container.test_process.TestDatasetProcessing.test_main()`.

**Comment by atolopko-czi** [comment]
Can be moved to Cool Down epic, once created.

**Comment by brianraymor** [comment]
Moved to _cool down_ after reviewing with @atolopko-czi.

**Comment by Bento007** [comment]
Specifically what asserts?

**Comment by atolopko-czi** [comment]
> Specifically what asserts?

A TODO suggests [these](https://github.com/chanzuckerberg/single-cell-data-portal/blob/dcc2cc8fdb70d1018c5c2fd671561bed83302158/tests/unit/processing_container/test_process.py#L106-L109). But you may have a better idea now of what's important to assert for overall pipeline success/health.

**Comment by metakuni** [comment]
@atolopko-czi , can this be closed?

**Comment by atolopko-czi** [comment]
Yup, the referenced test class doesn't even exist anymore.
