### ISSUE TITLE
chore: Cleanup loom artifacts left over from removal

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1455]
## Need
Datasets created pre-loom deprecation have generated converted .loom files.  We should go through and purge these files from S3

**Comment by seve** [comment]
[loom_uri.txt](https://github.com/chanzuckerberg/single-cell-data-portal/files/7254978/loom_uri.txt)

**Comment by blrnw3** [comment]
Results from staging: 
> DELETE 284

**Comment by MDunitz** [comment]
In the course of the explorer, rdev integration work, @ebezzi found 5 loom files in prod and 2 in staging. I deleted the artifacts in prod/staging (using the code posted above), and created a db migration to remove the 'LOOM; enum type. 
I'm assuming the code change to the batch process was merged into prod after we did the db cleanup but just in case I'm wrong we should check this again tomorrow to ensure we arent still creating a loom artifact somewhere.
