### ISSUE TITLE
Add batch_condition for a dataset to GET /curation/collections/{collection_uuid}

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1461]
[batch_condition](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#batch_condition) must be surfaced on the portal API for future use in [**Integrate and explore datasets**.](https://docs.google.com/document/d/1GJci4-T34u_5x8_HC2PzcA3-ydzVAlFc0GUIfiC_tzQ/edit#bookmark=id.u2y5pvbs7aon)

This should be addressed during the API refresh for the portal.

**Comment by danieljhegeman** [comment]
Moving to F&F

**Comment by brianraymor** [comment]
Per conversation with @ebezzi including with similar types of 3.0.0 changes to the curation API in [Curators can revise or submit datasets](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/306) and removing from F&F.

**Comment by brianraymor** [comment]
I'm seeing results from `GET ../collection/[{uuid}`:

```
...
None
['batchA', 'batchB']
None
['batchA', 'batchB']
['batchA', 'batchB']
['batchA', 'batchB']
['batchA', 'batchB']
['batchA', 'batchB']
['batchA', 'batchB']
['batchA', 'batchB']
None
...
```

and it's not included in the dataset preview for `GET /collections` as expected. 

Ready for production.
