### ISSUE TITLE
Enforce Python type hinting

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/single-cell-data-portal#1470]
Per the engineering staff meeting on 2021-09-17, the engineering team has decided to enforce Python type hinting moving forward. The tasks here will be to introduce linting such that future lines of Python code have enforced types and to install static type checking for our projects moving forward.

This issue will require some investigation on the right approach but one place to start would be taking a look at [`mypy`](https://github.com/python/mypy) and [how Dropbox type checked their Python codebase](https://dropbox.tech/application/our-journey-to-type-checking-4-million-lines-of-python).

While this issue is created in the `single-cell-data-portal` codebase, this should also be enforced in the `single-cell-explorer` codebase as well.

**Comment by danieljhegeman** [comment]
We should consider having people standardize their docstrings (pref Epytext in Pycharm)

**Comment by blrnw3** [comment]
Update: we did some preliminary comparisons of the various options - mypy, pyre, pyright, pytype - both analyzing the literature and running the tools on our codebase. This work is ongoing and we hope to share out a proposal within the next few weeks.

**Comment by atolopko-czi** [comment]
This would be nice to have, but enforcing type hinting will take a lot of effort to make necessary code updates.  I think we can make do with just encouraging use of type hinting via code reviews.
