### ISSUE TITLE
All dataset processing failures should trigger a slack notification

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1488]
## Need
- All failing dataset processing jobs should send a notification to the single-cell-ops channel. Currently jobs that hit the timeout limit do not send a notification.

## Approach
- call `notify_slack_failure(dataset_id)` in the upload-failure-lambda (and rename?) instead of within the processing script

## DOD
- the slack channel is notified of failures triggered by external factors (with the exception of user cancellations)

**Comment by metakuni** [comment]
In the [new step function](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/.happy/terraform/modules/sfn/main.tf), both the CXG and Seurat conversion tasks have a timeout of 36,000 seconds set so the error handler will catch and log/notify timeout errors.
