### ISSUE TITLE
Update deploy-happy script for new deployment process and repo name

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1496]
./scripts/deploy-happy.py is outdated in a few ways.

* The script expects users to really only deploy to prod from staging. Not from main to staging.
   * We need to also be checking for last successful dev deployment, not just staging
* Script references old repo names
   * This is working for now, but there may be a point that this breaks the script

**Comment by maniarathi** [comment]
deploy-happy is dead. Closing!
