### ISSUE TITLE
[SPIKE] Investigate ways to improve performance of collections page as number of collections grow

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1504]
## Need
As we've seen in the staging env, as the number of collections grows the performance/user experience of the collections page degrades.  Explore different options to improve the performance of the page and estimate the amount of work needed to implement them.

## Possible Approaches 
- pagination
- From @tihuan `If we want UI to be more performant dealing with ~1000 items, FE can do virtual scrolling, so BE can continue to return all collections and FE will only render the items that need to be in the viewport for both homepage and my collections page`

**Comment by tihuan** [comment]
Thanks so much for creating the ticket, Madison!

FE virtual scrolling will only improve browser rendering elements on the page, but if the bottleneck is actually waiting for BE response, then we'd need BE pagination 👌

**Comment by maniarathi** [comment]
Closing as performance issues have been addressed.
