### ISSUE TITLE
Improve logging in data processing pipeline

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1517]
## Need
As a developer I want to be able to determine where the pipeline failed based on the logs, however we dont currently get logs from the validation script until it successfully completes

## Approach
- call the cellxgene-schema validate function directly in the processing pipeline (instead of through a call to the cli via subprocess)
- add logging to the validation repo

## DOD
- can easily follow whats happening in the dataset processing pipeline via the logs

**Comment by metakuni** [comment]
Since the validation is now invoked directly instead of via a subprocess, no longer required.
