### ISSUE TITLE
Option to trigger individual steps in the dataset processing pipeline

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1543]
## Need
An option to trigger (or cancel/skip) individual steps in the dataset processing pipeline

## Approach
- Split the processing pipeline into individual batch jobs (or lambdas for quick steps) triggered/organized by the aws step functions

## DOD
- Can trigger individual steps in the processing pipeline for a given dataset

**Comment by metakuni** [comment]
Closing as a duplicate of #1646.
