### ISSUE TITLE
Use svgr to convert SVG files into React Components

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#1553]
1. https://dev.to/dolearning/importing-svgs-to-next-js-nna#svgr

DoD:
1. Replace the usage of `next-image` with svg file directly, and use SVGR's component, so Blueprint's css classes can control the `fill` color of SVR automatically
1. Example is available in `frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx:217`:
```
<AnchorButton
  minimal
  icon={
    <span className={Classes.ICON}>
      <StyledExplorerSvg /> // <---- THIS!
    </span>
  }
  href={dataset?.dataset_deployments[0]?.url}
  target="_blank"
  rel="noopener"
  data-test-id="view-dataset-link"
  disabled={dataset.tombstone || isOverMaxCellCount}
/>
```

Slack context: https://czi-sci.slack.com/archives/C023Q1APASK/p1634242135383000?thread_ts=1634231787.369500&cid=C023Q1APASK

**Comment by brianraymor** [comment]
See [**eng**](https://czi-sci.slack.com/archives/C023Q1APASK/p1634242135383000?thread_ts=1634231787.369500&cid=C023Q1APASK) for the background. This is related to the user experience for disabling exploration of +2M cell datasets.

**Comment by tihuan** [comment]
This is probably worth doing for me this week!

**Comment by atolopko-czi** [comment]
@tihuan still needed?

**Comment by tihuan** [comment]
Yes please! Would have helped @atarashansky today with one of his tickets actually ahaha

Is this something I can work on this week or next week, or needs to be prioritized? It's not blocking Alec right now since we have a temp solution, but probably better to use react components going forward for its flexibility
