### ISSUE TITLE
Trim down Docker images

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1565]
Docker images for Explorer, Portal are massive: 3-4GB, making them unwieldy to work with, particularly for local rdev-related image uploads.

1. Analyze Docker images to determine extraneous files for corpora-upload, corpora-explorer, corpora-frontend, corpora-upload-failures images. Consider that these images only need pkgs/libs required at run-time and not testing. E.g. Testing-only pkgs/libs like `client/node_modules/puppeteer` are not needed.
1. Determine if smaller base images can be use (e.g. alpine instead of ubuntu)
1. Make updates
1. Test rdev deploy, dev deploy

**Comment by atolopko-czi** [comment]
Check out https://github.com/wagoodman/dive

**Comment by atolopko-czi** [comment]
Possibly we just need to reorder the Dockerfile so the `ADD` command occur after the `RUN` cmds that install software. Three of the RUN layers add ~3GB, and these should be stable.

We should then focus on trimming down the data added by the `ADD client` command, since it's 757MB currently.

**Comment by metakuni** [comment]
See also:
- https://github.com/chanzuckerberg/single-cell-data-portal/pull/2730

**Comment by roaga** [comment]
PR #2803 helps with speed, but after inspecting the Docker images using Dive, there are still many duplicated files (specifically Python `dist-packages` and `site-packages`) that are causing the images to be much larger than they need to be.

**Comment by atolopko-czi** [comment]
Most images are <=1GB now, thanks to work done for other issues.  Closing this for now, as it will naturally resurface is local builds & upload times continue to be a pain point.
