### ISSUE TITLE
Skip Seurat conversion of datasets that will cause it to fail

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#1579]
#### Context

See conversations on [**ux**](https://czi-sci.slack.com/archives/C02450L5YAX/p1635211104016200) and [**ingestion**](https://czi-sci.slack.com/archives/C02JP4SALNQ/p1635184609017000). 

Also - [Seurat Failure Investigations](https://docs.google.com/document/d/1AHN3Jkz3mb3T1F-Tr3h3cTrKotE6Ls2SPHg3wB5ppiI/edit#heading=h.ukkfc1tjv8r1). 

Note: This portal change should be implemented _after_ [cellxgene-schema must warn when a Seurat conversion cannot be performed#162](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/162)

**Comment by danieljhegeman** [comment]
@brianraymor @pablo-gar We'll be skipping seurat conversion for any dataset that has at least one matrix in the anndata object that would fail seurat conversion. Based on discussion in [this issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/162) we will be considering both `X` and `raw.X`; currently I am also testing `layers` for convertibility based on the same dimensions criterion. If any of these fail (_sparse nonzero size_ or _dense size_ exceeds 2^31 - 1), then we skip seurat conversion. cc @metakuni

**Comment by brianraymor** [comment]
Reviewed further with @pablo-gar - looking at the anndata2seurat function in the scieasy code, it appears that it converts only `X` and `raw.X`, which suggests that testing `layers` for failure cases is not required.

https://github.com/chanzuckerberg/single-cell-data-portal/blob/44b98b49bd3a38bf19d[…]75e14d2b4e0586/backend/corpora/dataset_processing/make_seurat.R

https://github.com/cellgeni/sceasy/blob/f8f0628a280e0880ea94b00100b463e1f6ba1994/R/functions.R#L187

**Comment by metakuni** [comment]
Moved this into `Ready for Prod` since the fix will be deployed to prod today. The outstanding PR which installs `cellxgene-schema` from PyPI instead of Test PyPI will be merged after today's prod deployment. (This is due to our current lack of a hot fix workflow)

**Comment by metakuni** [comment]
Deployed to prod yesterday.
