### ISSUE TITLE
Reconvert existing datasets after uns metadata fix

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#1582]
After bug #1581 is fixed, all datasets will need to be reconverted to Seurat format idempotently. (i.e. preserve dataset UUIDs)

This mass Seurat reconversion should be done after:
* the [monolithic batch job has been decomposed](https://app.zenhub.com/workspace/o/chanzuckerberg/single-cell-data-portal/issues/1583)
* [automation for the conversion has been added](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1584)
* [Skip Seurat conversion of datasets that will cause it to fail](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1579)

**Comment by brianraymor** [comment]
The following datasets have successfully skipped seurat conversion. No re-conversion is required. (And we should re-run the query when the implementation is ready to ensure that there are no new cases in the interim)

Collection: Single-cell RNA-seq reveals the cell-type-specific molecular and genetic associations to lupus
UUID: 436154da-bcf1-4130-9c8b-120ff9a888f2
Dataset: multiplexed scRNA-seq of 1.2 million PBMCs from adult lupus samples
UUID: 218acb0f-9f2f-4f76-b90b-15a4b7c7f629'

Collection: Single-cell transcriptomic atlas for adult human retina
UUID: af893e86-8e9f-41f1-a474-ef05359b1fb7
Dataset: All major cell types in adult human retina
UUID: 0129dbd9-a7d3-4f6b-96b9-1da155a93748

---

The following datasets have custom RDS conversions (as .tar files). No conversion is required, but the references should no longer be returned in the `dataset_assets`.

Collection: Tabula Sapiens
UUID: e5f58829-1a66-40b5-a624-9046778e74f5
Dataset: Tabula Sapiens - All Cells
UUID: 53d208b0-2cfd-4366-9866-c3c6114081bc

Collection: DNA Methylation Atlas of the Mouse Brain at Single-Cell Resolution
UUID: 37f1f46d-6dfa-482c-9b17-d5850d8536f6
Dataset: DNA Methylation (CGN) Atlas of the Mouse Brain at Single-Cell Resolution
UUID: 7bdddd90-9428-47e2-bb80-e77d8b1cc96e
Dataset: DNA Methylation (CHN) Atlas of the Mouse Brain at Single-Cell Resolution
UUID: ccda558a-27d5-4c58-bb79-2c079abe059f

Collection: COVID-19 immune features revealed by a large-scale single-cell transcriptome atlas
UUID: 0a839c4b-10d0-4d64-9272-684c49a2c8ba
Dataset: Large-scale single-cell analysis reveals critical immune characteristics of COVID-19 patients
UUID: 9dbab10c-118d-496b-966a-67f1763a6b7d

Collection: A human cell atlas of fetal gene expression
UUID: c114c20f-1ef4-49a5-9c2e-d965787fb90c
Dataset: Survey of human embryonic development
UUID: f7c1c579-2dc0-47e2-ba19-8165c5a0e353

**Comment by metakuni** [comment]
On hold until #1761 is deployed to prod on Mon

**Comment by metakuni** [comment]
Inventory of reconverted datasets:
* [Seurat Reconversion Inventory](https://docs.google.com/spreadsheets/d/1QhHfMJlJcragsLfpoPVKRdDOtCgWShaXEX1Y8K_MMKs/edit#gid=2055544083)

**Comment by metakuni** [comment]
For posterity's sake, the query used to generate the dataset inventory:
```sql
select
p.id as collection_id,
p.name as collection_name,
d.id as dataset_id,
d.name as dataset_name,
d.cell_count,
da.s3_uri
from project p
inner join dataset d on p.id = d.collection_id and p.visibility = d.collection_visibility
inner join dataset_artifact da on d.id = da.dataset_id
inner join dataset_processing_status dps on d.id = dps.dataset_id
where
p.tombstone is false
and d.tombstone is false
and da.filetype='RDS'
order by
p.id,
d.id
;
```

**Comment by metakuni** [comment]
Spot check of 43/290 (14.8%) of reconverted RDS files complete. :thumbsup:

**Comment by metakuni** [comment]
Moving this story to `Ready for QA` since there is no code to be merged/deployed.
