### ISSUE TITLE
Tech spec for decomposed step function

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#1591]
Create a mini-tech spec for the decomposed step function in a format similar to:
* https://github.com/chanzuckerberg/single-cell/tree/main/design-documents

but as a Google Doc

**Comment by ebezzi** [comment]
Some of the docs can be found [here](https://docs.google.com/document/d/1hkX-hMq438bEvzavImTxFpRtYWSfRHdHulDcHIVxIJU/edit). Will create another issue to add these more formally to a Github file
