### ISSUE TITLE
Add "filter by metadata" feature flags

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1599]
#### Need
Metadata filter feature flags are to be implemented in an effort to avoid long-running feature branches and possibly facilitate incremental release of features

#### Approach
Explore and follow how CZI has previously implemented feature flags.

#### Definition of Done
Metadata filter features are only accessible/visible once feature flag has been added to the browser location.

**Comment by brianraymor** [comment]
Feature flags are in place but not at the base url.
