### ISSUE TITLE
Refine navigation bar UI to match mocks

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1600]
#### Approach
* Follow existing styled components pattern.

#### Definition of Done
* Navigation bar UI matches [authenticated](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1564%3A18513) and [non-authenticated](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1548%3A16262) mocks.
* Navigation link hover and active states match [tab](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2216%3A28615) and [menu](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2216%3A28653) mocks.

**Comment by brianraymor** [comment]
@hthomas-czi to review and close.
