### ISSUE TITLE
Update collections UI to match mocks

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1602]
#### Approach
* Add new collections component implementing React Table and styled components.
* Keep my collections functionality unchanged.
* "Lift" collections query to parent component (see #1601).

#### Definition of Done
* Collections sorted by recency (see superseded #1341).
* Collections UI adheres to specifications in [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1670%3A25035). Specifically:
  * Page header removed.
  * Assay and cell count columns removed.
  * Publication column added.
  * ~~Create Collection button matches [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1548%3A16539).~~ Collection button is not visible on main collections page.
  * Column widths match [spec](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2071%3A180994).
* Column widths with revisions match [spec](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2151%3A30252).
* ~~Published/Private/Revision Pending tag UI remain unchanged as per [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2151%3A30252).~~ Not required for main collections page.
* No results matches [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2151%3A30522).

**Comment by brianraymor** [comment]
@hthomas-czi to review and close.
