### ISSUE TITLE
Update +n tag to include all values

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1603]
#### Approach
* Add configuration for pluralized metadata label to `components/Collections/common/constants.ts`.
* Add `label` to prop of AsyncPopover/Popover (which is the pluralized metadata label).
* Remove visible FieldValues and add to Popover.

#### Definition of Done
* Count tag is displayed once there are more than two values.
* First two values are no longer displayed alongside the tag indicating the "more" count; all values are added to the popover and the tag alone is displayed in the cell (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1670%3A25035)).
* Pluralized metadata name is added to tag and `+` is removed. (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1670%3A25035)).
* Popover UI remains unchanged.

**Comment by brianraymor** [comment]
@hthomas-czi to review and close.
