### ISSUE TITLE
Add datasets view

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1604]
#### Approach
* Follow pattern set for collections index page.
* Create new DatasetGrid component.

#### Definition of Done
* Datasets sorted by revised_at then published_at.
* Landing page is updated to be datasets and located at `/datasets`.
* Collections view location updated to `/collections`.
* "Datasets" tab added to navigation bar (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9709)).
* Iconography updated (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9709)).
* Columns widths match [spec](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2071%3A180998).
* Collection name is displayed in datasets column.
* No results matches [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2151%3A31012).

**Comment by brianraymor** [comment]
@hthomas-czi to review and close.
