### ISSUE TITLE
Update datasets table on collection detail page

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1605]
#### Approach
* Use existing components where possible and update corresponding styled components.

#### Definition of Done
* "Cell Count" column header updated to "Cells".
* Iconography updated (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9709)).
* Columns widths match [spec](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2071%3A180998).
* Collection name is not visible in datasets column on collection detail page (only on datasets view).

**Comment by brianraymor** [comment]
@hthomas-czi to review and close.
