### ISSUE TITLE
Create collapsible sidebar component

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1611]
#### Approach
* Add collapsible sidebar component that can take any element as its body.
* Allow collapse state to be specified by parent.
* Use use existing styled component pattern for styling of expanded/collapsed states.

#### Definition of Done
* Filter bar UI matches [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2007%3A27491).
* Filter bar is collapsible (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2007%3A27495)).

**Comment by brianraymor** [comment]
Verified that the bar is collapsible. @hthomas-czi to review and close.
