### ISSUE TITLE
Add unique collection names to E2E test collections

### ISSUE THREAD

**Issue by ghost** [chanzuckerberg/single-cell-data-portal#1619]
E2E revision tests look for a collection to have a revision tag. Currently, the test collections use the same name - we ran into an issue earlier after deleting test collections with the same name to help the load time on the staging environment. For the tests to be more robust, we want to add time stamps or some unique identifier to the collection name in the BE E2E tests.

**Comment by maniarathi** [comment]
@ebezzi to rewrite this issue on Monday.

**Comment by ebezzi** [comment]
Fixed by Nayib's script.
