### ISSUE TITLE
Analytics (new): Add custom events in plausible.io to all dataset explore buttons

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-data-portal#1629]
### Overview
**Part of CELLxGENE Discover**: `portal`

**Description**:
Story: We want to be able to track movement between cellxgene pages so that we can understand how people navigate between the portal and explorer.

Issue: We are not able to tell the number of users that click to explore a dataset from a collection page. We are only able to tell the number of users that view each collection page, and separately the number of users that view the explorer page for each dataset, but are not able to connect the two actions. The explorer page can be viewed directly without going through the collection page. This would allow us to tell the percentage of users who came to each collection page and actually explored one of the datasets on that page.
- I.e. a user views the Tabula Sapiens collection page (https://cellxgene.cziscience.com/collections/e5f58829-1a66-40b5-a624-9046778e74f5) and clicks the explore button for the Tabula Sapiens - All Cells dataset which lands them on the explorer page for that dataset (https://cellxgene.cziscience.com/e/53d208b0-2cfd-4366-9866-c3c6114081bc.cxg/)

- We can tell 1 user viewed the Tabula Sapiens collection page, and 1 user viewed the Tabula Sapiens - All Cells dataset explorer page, but we cannot determine whether the user came to the Tabula Sapiens - All Cells explorer page from the Tabula Sapiens collection page.

### New events to add 
~~`DATASET_EXPLORER_CLICKED` : `{dataset_name: <fill in>}`~~
`DATASET_EXPLORE_CLICKED` : `{dataset_name: <fill in>}`
- To fire whenever any of the blue `Explore` buttons are clicked on either the datasets list page or any of the collection detail pages 
- This event is already defined and fires on the homepage when the `Explore a multi-tissue atlas` button is clicked 

#### People to cc
**PM**: @brianraymor 
**DS**: @ainfeld 

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by atolopko-czi** [comment]
@ainfeld Is this already done? Can we close?

**Comment by brianraymor** [comment]
It has not been addressed. It was included in multiple cool downs (see history above) and was not a priority in other quarters.

Would it be helpful to include documentation about the various events in https://github.com/chanzuckerberg/single-cell-data-portal/blob/2ce649ac0e28bc24da1d47f01396a304d99e433d/frontend/src/common/analytics/events.ts. It's hard to discern between some items.

**Comment by frano-m** [comment]
Hi @ainfeld and @brianraymor - would you mind confirming whether the event name should be either the existing event `DATASET_EXPLORE_CLICKED` from [events](https://github.com/chanzuckerberg/single-cell-data-portal/blob/2ce649ac0e28bc24da1d47f01396a304d99e433d/frontend/src/common/analytics/events.ts) or a new event called `DATASET_EXPLORER_CLICKED`? `EXPLORE` versus `EXPLORER`. Thanks!

**Comment by NoopDog** [comment]
Also, @ainfeld @brianraymor, assuming we stay with DATASET_EXPLORE_CLICKED from events, will we be able to tell the difference between selecting an explore link from the home page vs. selecting an explore link from the collection detail page? (and is that important?) Cheers, D

**Comment by ainfeld** [comment]
Oh apologies! That was a typo, it should be the existing `DATASET_EXPLORE_CLICKED` event. Thanks for catching that @frano-m! 

@NoopDog good question, plausible automatically tracks what page the event fired on so we will be able to differentiate between the button clicked on the homepage and the explore buttons clicked on other pages on CELLxGENE.
