### ISSUE TITLE
Analytics (new): Add custom events in plausible.io to all dataset download buttons on each collection page

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-data-portal#1630]
### Overview
**Part of CELLxGENE Discover**: `portal`

**Description**:
Story: We want to be able to track user intent to download datasets from each collection page. 

Issue: We can tell what datasets were downloaded from the S3 logs, and separately the number of users who viewed each collection page. However, we can’t tell of those who viewed each collection page, how many choose to download. This would help us determine the “bounce” rate from each collection page. 

### New events to add 
`DOWNLOAD_DATA_CLICKED` : `{dataset_name: <fill in>}`
- To fire whenever any of the blue/white `Download` buttons are clicked on either the datasets list page or any of the collection detail pages 

`DOWNLOAD_DATA_FORMAT_CLICKED`: `{dataset_name: <fill in>, data_format: <h5ad or rds>}`
- To fire whenever either of the data format buttons are clicked in the download dataset panel that pops up 

`DOWNLOAD_DATA_COMPLETE`: `{dataset_name: <fill in>, data_format: <h5ad or rds>}`
- To fire when the user actually clicks the actual blue `Download` button on the panel that pops up 

`DOWNLOAD_DATA_COPY`: `{dataset_name: <fill in>, data_format: <h5ad or rds>}`
- To fire when the user clicks to `copy to clipboard` the curl command  

#### People to cc
**PM**: @brianraymor 
**DS**: @ainfeld 

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by atolopko-czi** [comment]
@ainfeld Is this already done? Can we close?

**Comment by brianraymor** [comment]
It has not been addressed. It was included in multiple cool downs (see history above) and was not a priority in other quarters.

Would it be helpful to include documentation about the various events in https://github.com/chanzuckerberg/single-cell-data-portal/blob/2ce649ac0e28bc24da1d47f01396a304d99e433d/frontend/src/common/analytics/events.ts. It's hard to discern between some items.
