### ISSUE TITLE
Add custom events in plausible.io to buttons within explorer

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-data-portal#1631]
Story: We want to be able to determine which features within the explorer view are utilized the most.

Issue: as of right now we can only tell when a user views the explorer page, but not if they clicked on any other features within explorer
- I.e. we can see a user came to the explorer page for a specific dataset, but we can’t tell if they clicked any feature within explorer such as the color scale buttons or button to add labels

Request: add custom events to trigger when different buttons are clicked in explorer/collection pages

Plausible docs on adding custom events:
- [https://plausible.io/docs/custom-event-goals#using-custom-props ](url)
- [https://plausible.io/docs/custom-event-goals ](url)

Note: It sounds like the imaging team did something very similar with custom events and Jeremy on that team led those efforts.

**Comment by tihuan** [comment]
PR out!

https://github.com/chanzuckerberg/single-cell-explorer/pull/249

**Comment by tihuan** [comment]
In dev now!

**Comment by tihuan** [comment]
https://cellxgene.dev.single-cell.czi.technology/e/14462ca1-e6ee-45c0-9afe-c940cabd5b0a.cxg/

https://plausible.io/cellxgene.staging.single-cell.czi.technology

**Comment by tihuan** [comment]
Timmy still needs to add events in doc:

https://docs.google.com/document/d/1KH7McQd0lMZDYYx9ikD3SkExALvtRpC9B3474cPKkvY/edit

**Comment by atolopko-czi** [comment]
Transfer this story to Explorer repo?
