### ISSUE TITLE
Fix flaky test (test_v1_auth.py:75)

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1640]
`test_v1_auth.py` relies on a mechanism for testing token expiration which leads to flakiness. In particular, the variable `TOKEN_EXPIRES` shouldn't be used because that involves an expiration which isn't part of the JWT signature. Instead, use `token_duration` in `mock_auth.py` which is part of the encrypted payload.

**Comment by atolopko-czi** [comment]
assuming was addressed by testing improvements in 2022 Q4.
