### ISSUE TITLE
Add curator info to GET /collection/{collection_uuid} endpoint

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1661]
@Bento007 commented on [Mon Nov 15 2021](https://github.com/chanzuckerberg/single-cell/issues/259)

In order to support the new curator row displayed in the collection info, additional information will need to be return in in the GET /collection/{collection_uuid} endpoint. The information that needs to be added to the endpoint response are the curators first name, and last name. These fields are not stored in the data portal database. They are found in Auth0 using the foreign key Owner in the collections table. The owner of the collection is also the curator of the collection.

## Approach
- Store the curator's name in the database during collection creation or modification.
- Add the following JSON into the return response from GET /collection/{collection_uuid} response. 
```
{ 
  "curator_name": "string"
}
```

## Definition of Done
- GET /collection/{collection_uuid} returns the collection curators_name.
- POST /collections support curator_name
- PUT / collections/{collection_uuid} support curator_name

**Comment by Bento007** [comment]
@brianraymor  RE: https://github.com/chanzuckerberg/single-cell/issues/259#issuecomment-969694847
changed the response to be
```
{ 
  "curator_email": "string",
  "curator_name": "string"
}
```
