### ISSUE TITLE
Download hover overstays its welcome

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1672]
https://images.zenhubusercontent.com/228681195/c461b356-d71d-4d57-9721-f62e682732a1/screen_recording_2021_11_17_at_4_15_22_pm.mov

---

To reproduce:

1. Click on Download
2. Cancel Download modal
3. “Download” hover remains
4. Refreshing the page clears the hover

**Comment by tihuan** [comment]
Not entirely sure what could have caused this, so probably use `git bisect` to find the offending commit would be a good start!

**Comment by brianraymor** [comment]
This does not reproduce in production.
