### ISSUE TITLE
Upgrade `next` and `node-sass` to the latest version

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#1705]
Context:
We have a vuln related to `node-sass`: https://github.com/chanzuckerberg/single-cell-data-portal/pull/1248/files

Solution:
1. Upgrade `next` first at least to latest v12, since they have fixed their `node-sass` deps [here](https://github.com/vercel/next.js/pull/28710)
1. Now we should be able to upgrade `node-sass`!
2. `next` 11.1.3 upgrade alert: https://github.com/chanzuckerberg/single-cell-data-portal/security/dependabot/frontend/package-lock.json/next/open
3. https://github.com/chanzuckerberg/single-cell-data-portal/pull/1980

**Comment by seve** [comment]
Just a heads-up, if this takes too many cycles. This trim-newlines vulnerability doesn't actually affect us.  If the benefits of upgrading `next` aren't P0, I would recommend dropping the priority of this ticket.

cc: @maniarathi

**Comment by maniarathi** [comment]
@tihuan Do you think it makes sense to drop to P1 then given Seve's note?

**Comment by tihuan** [comment]
Thanks so much for the headsup, @seve ! 

@maniarathi : Yeah I think dropping to P1 sounds great, and we can just upgrade `node-sass` when we upgrade `next` in a few months once they port over Styled Components parser to SWC 🙆‍♂️ 

Github Issue: https://github.com/vercel/next.js/issues/30802

Thanks both!

**Comment by maniarathi** [comment]
Can do this sometime in Q2 2022.

**Comment by tihuan** [comment]
Since `next` finally released 11.1.3, which is a patch version bump, I'll send out a PR to upgrade it after Perf! Thank you!

https://github.com/chanzuckerberg/single-cell-data-portal/security/dependabot/frontend/package-lock.json/next/open

**Comment by tihuan** [comment]
Turned out that Next only included the patch in v12:

https://github.com/vercel/next.js/issues/34139#issuecomment-1034290706

**Comment by tihuan** [comment]
I think we've waited long enough for Next 12 to be stable, so maybe I can help upgrade to 12 this week? @maniarathi thank you!
