### ISSUE TITLE
The data submission policy must be updated.

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1725]
1.	Current curators must manually accept the updated data submission policy for **published collections** via a Google Form.
2.	When complete, the `data_submission_policy_version` for all published collections must be set to “2.0”.
3.	The policy language on the portal must be updated to the 2.0 language below AND the `portal data_submission_policy_version` must be set to 2.0 for new collections being published. 

---

- I give CZI permission to display, distribute, and create derivative works (e.g. visualizations) of this data for purposes of offering the cellxgene portal, and I have the authority to give this permission.
- It is my responsibility to ensure that this data is not identifiable. In particular, I commit that I will remove any direct personal identifiers in the metadata portions of the data, and that CZI may further contact me if it believes more work is needed to de-identify it.
- If I choose to publish this data publicly on the cellxgene portal, I understand that (1) anyone will be able to access it subject to a CC-BY license, meaning they can download, share, and use the data without restriction beyond providing attribution to the original data contributor(s) and (2) the Collection details (including collection name, description, my name, and the contact information for the datasets in this Collection) will be made public on the cellxgene portal too.
- I understand that I have the ability to delete the data that I have published from the cellxgene portal if I later choose to. This however will not undo any prior downloads or shares of such data.

**Comment by seve** [comment]
Do we want to preserve the existing styling, with popout(
![image](https://user-images.githubusercontent.com/8716829/145106987-6807a19e-585d-466d-af15-611635a4d5b4.png)
) and bolding?

**Comment by brianraymor** [comment]
> Do we want to preserve the existing styling, with popout

There's no reason to change this?
