### ISSUE TITLE
Add node engine specification / standardize node version

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#1738]
The Data Portal (and likely Explorer) does not specify the requisite node version / node engine in package.json. The developer has to figure out which node version range works; if I recall correctly it can't be the latest (~22) but has to at least be ~12. Might require settling on a common node version manager (`nvm`?) for scripting purposes.

**Comment by seve** [comment]
I think we just need a .node_version file in the frontend root folder!

**Comment by metakuni** [comment]
@danieljhegeman / @seve : Is this >1 year old issue still relevant?

**Comment by dsadgat** [comment]
@seve please either update or close, thanks!
