### ISSUE TITLE
Curator names must be added to data_submission_policy_version 1.0 collections

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1745]
Missing `curator_names` must be added for all collections with a `data_submission_policy_version` of "1.0". 

When complete, the `data_submission_policy_version` for all published collections must be set to “2.0”.

**Comment by Bento007** [comment]
All published collections have had curator name added and have been updated to data_submission_policy_version "2.0"

**Comment by brianraymor** [comment]
I ran an API query. All published collections include a `curator_name` and are set to correct policy version.
LGTM.
