### ISSUE TITLE
Require full name at account creation on Auth0

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#1755]
To ensure newly created collections have curators correctly attributed, we need to ensure that every user has a full name attached to them.  Google and GitHub will both provide full names to Auth0 (there may be some investigation needed to see if there are cases where full names aren't attached).  However, manually created accounts through Auth0 have no assigned full name by default. We'll need to edit some configurations in the Auth0 tenant to require and store full names.

https://community.auth0.com/t/how-to-set-name-as-required-field-for-user/54780/3

**Comment by brianraymor** [comment]
This is also related to [Curator name must be added for Single-cell multi-omics analysis of the immune response](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1747) which is the production collection that exposed this problem.

**Comment by Bento007** [comment]
We will also need a way to allow existing users who have created an account with auth0 to update their profile with their name.

**Comment by brianraymor** [comment]
Are you referring to their profile on the data portal?

**Comment by Bento007** [comment]
yes, their data portal profile.

**Comment by brianraymor** [comment]
Based on the limited number of funded curators in 2022, I'd recommend that we update the profile with a script rather than exposing a UI for curators ... if needed.

**Comment by Bento007** [comment]
That means reaching out to each of the users who don't have a name and asking them what name they would like before manually updating it in the DB.

**Comment by brianraymor** [comment]
The list of funded curators is quite small. I'd expect the potential name changes to be even smaller.

**Comment by Bento007** [comment]
We will be adding a [text-field](https://auth0.com/docs/libraries/lock/lock-configuration#text-fields) option to the Universal Login javascript. To find the Universal Login code, login in the Auth0 management console. Under Branding, you'll find Universal Login. Select **Universal Login**, and then select **Login**.
![Screen Shot 2022-01-04 at 10 07 28 AM](https://user-images.githubusercontent.com/1429913/148104430-2b8b02ea-8f87-4940-a369-9b29ddc7c241.png)

From here we will add a few line of Javascript
![Screen Shot 2022-01-04 at 10 07 45 AM](https://user-images.githubusercontent.com/1429913/148104712-f7bf591e-3869-4a49-8efa-2e3b0a7c60fc.png)

To add additional fields refer to the documentation on [text-fields](https://auth0.com/docs/libraries/lock/lock-configuration#text-fields).

**Comment by Bento007** [comment]
This has been updated on both prod and dev. A github user can still create an account without a name. This result in auth0 using the users email for the name which not a desired behavior.
