### ISSUE TITLE
happy does not fail on deployment if TFE cannot apply changes

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1765]
If a bad infra change is pushed to the repo, when running `happy update` (which is run by GHA in the `Update` step of a deployment), TFE will cause a silent failure, therefore the deployment will end up being green, even if no version is deployed. Instead, it should throw an error so that the oncall engineer can be notified and work on fixing the infra error.

**Comment by Bento007** [comment]
this is where update is called https://github.com/chanzuckerberg/single-cell-data-portal/blob/ebe0662671935cbb787c4f89b6a36e975340a34a/.github/workflows/deploy-happy-stack.yml#L57

**Comment by Bento007** [comment]
Here is the CLI handler https://github.com/chanzuckerberg/single-cell-data-portal/blob/ebe0662671935cbb787c4f89b6a36e975340a34a/scripts/happy#L964
