### ISSUE TITLE
Datasets tab requires horizontal scrolling 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1771]
I need to horizontally scroll the Datasets tab to reveal the `explore` glyph.

https://images.zenhubusercontent.com/228681195/8305e4f3-8d2b-4bd0-bbfe-37b25105522a/screen_recording_2021_12_17_at_1_27_16_pm.mov

**Comment by MillenniumFalconMechanic** [comment]
As per @hthomas-czi [via slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1642619479042200?thread_ts=1642572875.041000&cid=C02CF7MQPGV):

> I am curious why the first column on the Datasets page is 7.2fr . That’s what it comes out to if you do the px to fr conversion directly but it feels a little cramped to me. We should be able to just use a round 8fr right? I think we could bump down tissue from 5fr to 4fr  as well which would help accommodate.

**Comment by brianraymor** [comment]
Verified. Closing.
