### ISSUE TITLE
Collections tab requires horizontal scrolling

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1772]
I need to horizontally scroll the Collections tab to reveal clipped metadata:

https://images.zenhubusercontent.com/228681195/5450f67f-66ac-42b2-b271-2f210f3d6cf4/screen_recording_2021_12_17_at_1_30_44_pm.mov

**Comment by brianraymor** [comment]
The view for a specific collection is also slightly clipped. I can see part of the `explore` glyph.

**Comment by MillenniumFalconMechanic** [comment]
@frano-m, let's review Harley's redlines. We can review responsive snap points once we have implemented the updated `fr` spec.

**Comment by brianraymor** [comment]
Verified. Closing.
