### ISSUE TITLE
Bug: using optional extra-tag as required parameter

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#1774]
The optional parameter `extra-tag` is now a required parameter. This causes issues with trying to deploy an rdev environment locally. The parameter `tag` should be used rather than `extra-tag`.

https://github.com/chanzuckerberg/single-cell-data-portal/blob/ebe0662671935cbb787c4f89b6a36e975340a34a/scripts/happy#L1168

**Comment by maniarathi** [comment]
Closing as an old issue, please re-open if still relevant.
