### ISSUE TITLE
Revision Tracking Redesign 

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1783]
Maintain dataset revisions metadata.

See [Revision Tracking Redesign doc](https://docs.google.com/document/d/17tf_XDeXazHQ7WnuGKahcH9UEC3sXfU4v8HpgT-Jhj8/edit#heading=h.907lsu1ozewh)

**Comment by metakuni** [comment]
Could we close this epic as superceded by [Portal Data Management Redesign#3433](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3433)?

**Comment by atolopko-czi** [comment]
> Could we close this epic as superceded by [Portal Data Management Redesign#3433](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3433)?

Good call, yes!
