### ISSUE TITLE
Create docs for the ingestion pipeline

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1790]
Add GitHub documentation for the ingestion pipeline, incorporating the changes that we did this quarter. [This document](https://docs.google.com/document/d/1hkX-hMq438bEvzavImTxFpRtYWSfRHdHulDcHIVxIJU/edit) can be used to get the information from.

**Comment by metakuni** [comment]
doc:
* https://docs.google.com/document/d/1NuqQuFvTOV4PQpi1RsbZhRDRPV6O4YV0vj-l5Tj2xGg/edit#heading=h.sg0zh2s4tcql
