### ISSUE TITLE
bug( ): Readme.md mentions REMOTE_DEV.md but no file exists

### ISSUE THREAD

**Issue by dougnukem** [chanzuckerberg/single-cell-data-portal#1792]
## Describe the bug
The Readme.md references a REMOTE_DEV.md instructions but it doesn't exist in the repo.

https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/REMOTE_DEV.md

**Comment by seve** [comment]
Looks like we replaced it with a google doc here: https://github.com/chanzuckerberg/single-cell-data-portal/pull/1653

We currently have documentation on Atlassian, Google Docs, and GitHub.  When do we choose which?

**Comment by dougnukem** [comment]
Is it intended that the Google Doc requires permission to access, maybe it just needs to be made public.

**Comment by maniarathi** [comment]
Closing as the README has been cleaned up.
