### ISSUE TITLE
Add a failure recovery mechanism for Crossref errors

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1805]
We need to handle at least two cases:

1. Crossref doesn't return any data for a specific DOI
1. Crossref returns an unspecified error 

This generally forces us to make the metadata record optional, which is fine. We should decide whether to store an explicit error record in case we have one of these failures, so they can be retried later (or at least to acknowledge it). @brianraymor I will let the decision to you.

**Comment by brianraymor** [comment]
I would like to have scheduled retries similar to to the preprint case.

**Comment by MillenniumFalconMechanic** [comment]
Superseded by #1807.
