### ISSUE TITLE
Remember filter while navigating within the Portal

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1811]
#### Need
Currently the filter is cleared when:

1. Viewing a collection detail page from either collections and datasets views.
2. Navigating between collections and datasets views.

Filter open/closed state is also cleared.

#### Approach
TBD. Options for maintaining state outside of immediate component hierarchy to be discussed with @tihuan.

#### Definition of Done
* Collections and datasets have their own independent filters and open/closed state, and are remembered on navigation within the Portal. 
* Browser tab filter states operate independently.

**Comment by tihuan** [comment]
Sounds great! Do we need to make sure different tabs maintain their own filter states? If so maybe session storage would do?

As for persisting the state, my current thought is maybe each component can store/retrieve their own state via session storage, and we can have a utility function to help different components interact with session storage if needed?

Would love to hear your approach too! Thank you 😄

**Comment by tihuan** [comment]
in prod!
