### ISSUE TITLE
Filter collections by publication date

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1817]
#### Approach
* Add `publicationYear` and `publicationMonth` to `Categories`; populate from  [collections response](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1806).
* Add hidden publication date column to collections table, enable [custom date filter](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1824) on column config.

#### Definition of Done
* Publication date category is visible on collections view.
* Publication date category values are displayed as bins as per [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9713).
* Publication date category UI matches [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9713).

**Comment by tihuan** [comment]
Waiting for QA in prod!
