### ISSUE TITLE
Filter datasets by publication date

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1818]
#### Approach

-[ ] @MillenniumFalconMechanic create example set to confirm functionality with Harley.

**Categories Model**
* Add `publicationYear`, `publicationMonth` and `publicationDay` to `Categories`; populate from  [collections response](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1806).
* Create "date bins" to facilitate search such as `publication_date_bins: ["1_MONTH", "2_MONTHS",...]`.
* Use built-in JavaScript date functionality to calculate bins, or potentially use third-party library such as [Moment.js](https://momentjs.com/).

**Datasets Table**
* Add hidden publication date column to datasets React Table config.
* Reuse built-in includes functionality to execute filter.

**Filter Component**
* Filter component generates options from `publication_date_bins`.

#### Definition of Done
* Publication date category is visible on collections view.
* Publication date category values are displayed as bins as per [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9713).
* Publication date category UI matches [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9713).
* Selecting publication date bin filters corresponding datasets result set.

**Comment by tihuan** [comment]
Waiting for QA in prod!
