### ISSUE TITLE
Filter datasets by development stage

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1831]
#### Approach
* Hierarchy "hard coded" on FE for display.
* Dataset leaf development stage returned from `datasets/index`. For example, `{label: "human early adulthood stage", ontology_term_id: "HsapDv:0000088"}`.
* Development stage path calculated on FE from hard-coded hierarchy and leaf development stage. For example, `[{label: "mature stage", ontology_term_id: "HsapDv:0000204"},{label: "human adult stage", ontology_term_id: "HsapDv:0000087"}, {label: "human early adulthood stage", ontology_term_id: "HsapDv:0000088"}]`
* Filter menu options generated from hard-coded hierarchy.

**Comment by MillenniumFalconMechanic** [comment]
See #1946.

**Comment by tihuan** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/2166 in prod!
