### ISSUE TITLE
Filter datasets by ethnicity

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1833]
#### Approach

**Categories Model**
* Add ethnicity to `DatasetRow` interface, bind from `/datasets/index` response.

**Category Filter**
* Roll out author as a basic filter.
* [Disabled with tooltip](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1670%3A50787) if species other than Homo sapiens is selected.

**Datasets Table**
* Add ethnicity as hidden column to enable React Table's filter functionality. @NoopDog 
* Reuse built-in `includes` functionality to execute filter.

#### Definition of Done
* Ethnicity filter displayed in datasets filter sidebar.
* Selecting ethnicity filters corresponding datasets result set.
* Ethnicity is disable if species other than Homo sapiens is selected ([mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1670%3A50787)).

**Comment by tihuan** [comment]
in prod!
