### ISSUE TITLE
Tear down cellxgene RDS clusters

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1843]
The cellxgene RDS clusters are no longer used and should be removed from all environments via Terraform single-cell-infra changes.

Should also remove the `db_uri` attributes in the `hosted-cellxgene-{dev,staging,prod,etc}` secrets within AWS Secrets Manager. E.g. [see](https://us-west-2.console.aws.amazon.com/secretsmanager/home?region=us-west-2#!/secret?name=hosted-cellxgene-dev). Removed via Terraform?

**Comment by maniarathi** [comment]
@atolopko-czi Duplicate of #1276?

**Comment by atolopko-czi** [comment]
Yup, will transfer the part about `db_uri` secret to that other story and close this one.
