### ISSUE TITLE
Learn More placeholders

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#1854]
This will update learn more placeholders with actual documentation links

UPDATE (4/5): https://github.com/chanzuckerberg/cellxgene-documentation/blob/pablo-gar/wheres-my-gene/scExpression/scExpression-documentation.md

**Comment by tihuan** [comment]
@signechambers1 @hthomas-czi do we know what all the Learn More links will be? Thank you!

**Comment by signechambers1** [comment]
Thanks @tihuan! It will go to the documentation page, @pablo-gar do you know what the link will be?

**Comment by pablo-gar** [comment]
It currently lives here:

https://github.com/chanzuckerberg/cellxgene-documentation/blob/pablo-gar/wheres-my-gene/where-is-my-gene/where-is-my-gene-documentation.md

Final place will be here, but will likely change depending on the final name of the product:

https://github.com/chanzuckerberg/cellxgene-documentation/where-is-my-gene/where-is-my-gene-documentation.md

**Comment by tihuan** [comment]
Amazing! Thank you both 🤩 

In that case, I guess we can wait till we have the official name to update the links then 👍
