### ISSUE TITLE
Add ontology ancestor mapping to cellxgene-schema

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1873]
In order to have up-to-date information about ontology ancestors, we should think about adding the list of the ancestors as part of the validation mapping process, performed by `cellxgene-schema`.

If [pinned ontologies](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#required-ontologies) are refreshed during a schema update, we will:
1. Upgrade `cellxgene-schema` to support the new ontologies
1. Re-curate the datasets that are affected by the ontology update
1. `cellxgene-schema` will also add the ancestors to the h5ad metadata (similarly to the labels added today)
1. The portal can store them in the database as additional metadata

**Comment by brianraymor** [comment]
I question:

> 3. cellxgene-schema will also add the ancestors to the h5ad metadata (similarly to the labels added today)

This adds more _presentation_ metadata to the dataset which is not required by data consumers. We wouldn't want this field to appear in the cellxgene explorer LSB or data drawer for example. 

We should definitely be using the cellxene-schema process for updating/parsing ontologies. Could an accessor be added to [`ontology.py`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/ontology.py) to allow the portal to lookup the ancestor for the development stage and add to the database? This would be similar to the approach for calculating cell count or mean genes per cell.
