### ISSUE TITLE
Collection detail page does not refresh after editing the details

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1889]
On staging, I edited the details of a private collection. The collection detail page had to be manually refreshed.

https://images.zenhubusercontent.com/228681195/b2c9c087-5c60-4c1b-b9b8-52d4aa3a8025/screen_recording_2022_01_31_at_9_37_22_am.mov

**Comment by seve** [comment]
I suspect: https://github.com/chanzuckerberg/single-cell-data-portal/blob/a9281e45a837eac8456ff616e2be9233f2902916/frontend/src/common/queries/collections.ts#L403-426

**Comment by brianraymor** [comment]
The test case did not reproduce on September 27 2022. Closing.
