### ISSUE TITLE
Add Cloudfront caching+invalidation for datasets/index and collections/index endpoints

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1899]
The current _minimum_ response time for the `/index` endpoints (called on page load) is around 600ms, which isn't terrible but also quite slow for the average website. With some simple changes, we could make it much faster:

1. Enable Cloudfront caching for the `dp/v1/datasets/index` and `dp/v1/collections/index` routes. This will cut down the response time to a few milliseconds
1. Add a custom invalidation each time a new collection/revision is published. This will ensure that the new collections (or datasets) will be indexed immediately.

**Comment by atolopko-czi** [comment]
Work should include adding a functional test to ensure caching is working as expected.  Since TF/Cloudfront changes could possibly break the behavior, making the expected behavior explicit via a test that runs on real AWS envs (dev/staging/prod), will prevent caching behavior regressions.

**Comment by atolopko-czi** [comment]
Work should include updating the [Portal Caching Tech Overview section](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.c2c9ejdsn0ts)
