### ISSUE TITLE
Update collections and datasets sort order to include publication date

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#1903]
#### Approach
* Add recency field to both collection and dataset row models, calculate on successful response from endpoints.
* Update React Table sort config for both collections and datasets.

#### Definition of Done
Collections and datasets are sorted in the following order:

1. Publication date from publication metadata.
2. revised_at
3. published_at

**Comment by tihuan** [comment]
Waiting for QA in prod!

**Comment by brianraymor** [comment]
I tested sorting of collections.

**Comment by brianraymor** [comment]
I tested sorting of datasets. Discussing secondary sort for fit&finish.
