### ISSUE TITLE
Manually Generate Data Cube and cell ordering json files

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1923]
## Need
A data cube with the correct dimensions to be queried by the data serving API
## Approach
- [x] Get list of s3_uris for h5ad files all public, primary data of the correct assay types stored in prod
- [x] Copy datasets from prod to dev
- [x] Set up instance to run on (see [benchmarking repo](https://github.com/chanzuckerberg/aurora-scratch) and doc for instance details) in the dev env
- [x] Copy all h5ad files, apply rankit and concatenate via code in benchmarking repo, store in S3
- [x] Compute wmg stats, create cube, store in s3
- [x] Generate cell ordering json file broken down by tissue
- [x] copy cube and cell orderings between envs

## Definition of Done
- [x] Data cube & cell ordering files stored in dev env for testing/development
- [x] Data cube  & cell ordering files stored in staging env for testing/development
- [x] Data cube  & cell ordering files stored in prod env for testing/development
- [x] Data cube  & cell ordering files stored in rdev env for testing/development
- [x] Data cube  & cell ordering files manually checked by Pablo -- TODO create story for this

**Comment by MDunitz** [comment]
## Assays to include
All 10X platforms
Drop-seq
CEL-seq2
sci-RNA-seq
Visium
Seqwell
microwell-seq

**Comment by MDunitz** [comment]
I've generated a list of datasets ids and assays that are public, non tombstoned, published, primary data [here](https://docs.google.com/spreadsheets/d/189ICXhioqFXAyuwSoG7cMpEMr5EG-8jCKspkYWU2aDQ/edit?usp=sharing)
There are a few datasets that have multiple assays -- with some combos of assays we want to include and assays to exclude, how should we handle datasets with multiple assay types?

**Comment by MDunitz** [comment]
` select id, assay from dataset where published='TRUE' and is_primary_data='PRIMARY' and collection_visibility='PUBLIC' and tombstone='f';`

` select id, items from dataset,jsonb_to_recordset(dataset.assay) as items(ontology_term_id text) where assay!='null';`

**Comment by MDunitz** [comment]
Final query for dataset ids that are primary, published data of the appropriate assay type
```
select id, items
from dataset,
     jsonb_to_recordset(dataset.assay) as items(ontology_term_id text)
where assay != 'null'
  and published = 'TRUE'
  and is_primary_data = 'PRIMARY'
  and collection_visibility = 'PUBLIC'
  and tombstone = 'f'
  and items.ontology_term_id in ('EFO:0008722','EFO:0010010', 'EFO:0010550', 'EFO:0010961', '', 'EFO:0030002', 'EFO:0009901', 'EFO:0011025', 'EFO:0009899', 'EFO:0009900', 'EFO:0009922');
```

When run in prod this returns the ids of 67 datasets

included_assay_ontology_ids = ('EFO:0008722','EFO:0010010', 'EFO:0010550', 'EFO:0010961', 'EFO:0030002', 'EFO:0009901', 'EFO:0011025', 'EFO:0009899', 'EFO:0009900', 'EFO:0009922') # currently missing the id for seqwell

**Comment by MDunitz** [comment]
Final query to get s3_uris for appropriate datasets
```
select s3_uri from dataset_artifact where filetype='H5AD' and dataset_id in (
    select id
from dataset,
     jsonb_to_recordset(dataset.assay) as items(ontology_term_id text)
where assay != 'null'
  and published = 'TRUE'
  and is_primary_data = 'PRIMARY'
  and collection_visibility = 'PUBLIC'
  and tombstone = 'f'
  and items.ontology_term_id in ('EFO:0008722','EFO:0010010', 'EFO:0010550', 'EFO:0010961', 'EFO:0030002', 'EFO:0009901', 'EFO:0011025', 'EFO:0009899', 'EFO:0009900', 'EFO:0009922')
);
```
Currently returns a list of 57 datasets
See [list of s3_uris](https://docs.google.com/spreadsheets/d/189ICXhioqFXAyuwSoG7cMpEMr5EG-8jCKspkYWU2aDQ/edit#gid=53001094)

**Comment by MDunitz** [comment]
Originally used `c6i.8xlarge` instance type but ran into memory issues on the 3 largest datasets (larger than 10GB) Rerunning on `c6i.16xlarge` instance

**Comment by MDunitz** [comment]
RE copying datasets
I ran a script to generate presigned urls (for the datasets we needed in dev) from an account with access to prod then in used those urls to download the datasets to a instance in the dev env and wrote them to s3

**Comment by MDunitz** [comment]
To manually generate the cube
1. Tunnel in to prod database and run
```
select s3_uri from dataset_artifact where filetype='H5AD' and dataset_id in (
    select id
from dataset,
     jsonb_to_recordset(dataset.assay) as items(ontology_term_id text)
where assay != 'null'
  and published = 'TRUE'
  and is_primary_data = 'PRIMARY'
  and collection_visibility = 'PUBLIC'
  and tombstone = 'f'
  and items.ontology_term_id in ('EFO:0008722','EFO:0010010', 'EFO:0010550', 'EFO:0010961', 'EFO:0030002', 'EFO:0009901', 'EFO:0011025', 'EFO:0009899', 'EFO:0009900', 'EFO:0009922', 'EFO_0030003', 'EFO:0030004', 'EFO:0008919')
);
```
2. ssh into an EC2 instance (large enough to process/stoer all of the data) in the dev env with the Bruce-power-user role
Copy s3 uris from prod env to machine, and then copy to s3 in dev (I've been using the madison-tmp bucket, subset by date of the copying)
3. From the ec2 instance fetch `origin/dunitz/cube-creation` branch from single-cell-data-portal
4. Install reqs
5. USING TMUX... open ipython and  import load_data_and_create_cube from backend.wmg.cube_creation.load_cube
6. run `load_data_and_create_cube('$PATH_TO_DATASETS_DIRECTORY', '$CUBE_NAME')`
7.  import get_cells_by_tissue_type from backend.wmg.cube_creation.load_cube
8. import generate_cell_ordering from backend.wmg.cube_creation.load_cube 
9. run 
```hold = get_cells_by_tissue_type('$CUBE_NAME')```
10. run
`generate_cell_ordering(hold)`

**Comment by maniarathi** [comment]
I wonder if the above instructions could be written as a guide [here](https://drive.google.com/drive/u/0/folders/1U_5pBm3AzcE6oeLo9EYuQFT8yvb2K_Kl)?

**Comment by MDunitz** [comment]
@maniarathi let me know what you think [of this](https://docs.google.com/document/d/1s4thgd0UNjtaolfDw3vNpsUZGTSmO0QEDOuIviYN9nI/edit#)
