### ISSUE TITLE
Store and Access ontology mapping arrays

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1924]
## Need
A way to map the ontology ids to the human readable values
## Approach
- [ ] Copy ontology mapping to S3 bucket in each environment
- [ ] Manually test to ensure the server has access to the files

## Definition of Done
- [ ] Ontology file in each env
- [ ] Mock ontology file available for unit tests
- [ ] Update schema_curation repo readme with instructions to update ontology files in s3 on schema updates OR write script to manually copy files on schema updates

**Comment by atolopko-czi** [comment]
Not needed. The API layer takes care of this mapping.
