### ISSUE TITLE
Audit data-portal dependencies

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1955]
Make sure that the data portal is using up-to-date dependencies as much as possible. In particular, we should verify:

- Numpy 
- Scipy (currently pinned to 1.7.x due to a sceasy issue)
- Numba (caused issues in the past)
- click (version 8 causes problems with Black)

For R, we know that Seurat and SeuratObject are pinned because the most recent versions break the R conversion script.

**Comment by Bento007** [comment]
This is how we automatically updated python dependencies in an older project https://github.com/HumanCellAtlas/fusillade/blob/5634b77440bb71aa075b6ca442baccbdd436dfd7/Makefile#L80-L95

**Comment by atolopko-czi** [comment]
closing; all dep upgrades intended to handled as ongoing on-call responsibility: https://docs.google.com/document/d/1n5cngEIz-Lqk9737zz3makXGTMrEKT5kN4lsofXPRso/edit#heading=h.dwtheu2ul0rk.  Will be revisited with team.
