### ISSUE TITLE
Implement WMG API metrics reporting

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1964]
Acceptance Criteria:
- Dashboard exists to graph request rates, P95/P99 response times, and response status codes for each endpoint
- PagerDuty incident created if P95, P99 response times fall below SLOs per requirements.
- PagerDuty incident created if API endpoints 5xx statuses exceed 1% of all response statuses

Tasks:
- [ ] Metrics reporting
    - Option 1 (Minimal): Requests are logged and Cloudwatch Insights queries exist to report metrics (docs); dashboards & monitors configured in AWS Cloudwatch
    - Option 2 (Stretch): API Gateway in use for reporting metrics; ; dashboards & monitors configured in AWS API Gateway
    - Option 3 (Stretch): Use Datadog metric reporting library; dashboards & monitors configured in Datadog
- [ ] Create dashboard (Datadog or AWS, depending upon metrics reporting approach, above)
- [ ] Configure monitors/alerts

**Comment by atolopko-czi** [comment]
For now I think we're on barod to just:
- Add json/structured logging
- Data synthetics (we have another story for this!)

**Comment by dsadgat** [comment]
@atolopko-czi is there another ticket for the monitoring via datadog? is this still needed?

**Comment by atolopko-czi** [comment]
I think we can close this. Adding API request metrics should be addressed across all APIs at once, not just for WMG. We only have this [Datadog proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.5j8sxz6f3e6n) for now.

**Comment by dsadgat** [comment]
@atolopko-czi  Is there not a zenhub ticket to complete the prototype for the datadog metrics work?
