### ISSUE TITLE
WMG Front end polish

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#1968]
**Must have for launch:**
- [x] Page should not have nested scrolling elements
- [x] Signe & Meg are seeing a scroll grey bar at the bottom of the page even if there is only 10 genes
- [x] Dot plot should use all available space to minimize scrolling
- [x] Cell type names are cut off
- [x] Tooltip: "Cell Name" should be "Cell Type"
- [x] Update filter state using API differently
- [x] #2250
- [x] #2249
- [x] #2247
- [x] #2248
- [x] #2206 

**Nice to have for launch:** tracked here: #2272

**Comment by tihuan** [comment]
@seve thanks so much for helping with finishing up the rest of the work 🙌

Please check the following doc for the top priority items. Most important ones at top:

https://docs.google.com/document/d/1WxE7pBUzJ49yURc10Mth34B7uYQ9ThwuOTAfb_P1cY4/edit?usp=sharing

Once that's done, please help tackle the rest of the must have items, and then the nice to have ones 🙏

Thanks again!!
