### ISSUE TITLE
Patch sceasy to fix the incompatibility with scipy 1.8.0

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1973]
We recently found out that scipy 1.8.0 breaks the R conversion script that mostly relies on sceasy. This is now "fixed" by pinning scipy to 1.7.x in our repo so that the transitive dependency is overridden, but this isn't a great solution.

What we should do instead is:

1. Try to replicate the issue using sceasy only (likely goes back to reticulate), possibly with a unit test
1. Attempt a fix
1. If the fix fails, pin scipy in sceasy

**Comment by brianraymor** [comment]
@ebezzi - does this need to be pulled into [Update cellxgene to 3.0.0](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/306)?

**Comment by ebezzi** [comment]
@brianraymor yes, I'd do that as part of the 3.0.0 work.
