### ISSUE TITLE
Curators can upload a local dataset to a private Collection

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2003]
All Curators MUST be able to use the Curator API to add new Datasets to the Collection via uploads of local files to S3

session policy passed inline when creating the token.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "testWriteOnlyPolicy2",
      "Effect": "Allow",
      "Action": [
        "s3:PutObject"
      ],
      "Resource": [
        "arn:aws:s3:::<fill_in_bucket>/<fill_in_collection_id/*"
      ]
    }
  ]
}
```

Serve Role to get generate credentials
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::401986845158:role/<name_of_role_that_we_call_with_assume_role>"
        }
    ]
}
```

and finally the role that we call with the 'assume role' call from the server (to get the temp tokens), simply needs to have write access to the s3 bucket

So there's
1. the role of the server
1. the role that the server calls with 'assume role' to get tokens
1. the inline policy that the server passes with the 'assume role' call to restrict the write access down to one specific collection_id path

**Comment by Bento007** [comment]
https://feeney.mba/refreshable-aws-boto-credentials.html

**Comment by Bento007** [comment]
We ended up only being able to create a token with a max time of 1 hour. This does not work for our curator who often need to upload much larger files that cannot complete in that time. As a stop gap, we are providing a code snippet that will automatically refresh the user's AWS credentials. We are also in the process of implementing a more permanent solution that will allow the user to generate AWS crednetials that can live up to 12 hours. In the future the user will also be able to automatically refresh those crednetials all using AWS tools.
