### ISSUE TITLE
Create Auth0 Infra

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2009]
## References
- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1862

**Comment by atolopko-czi** [comment]
Looks like the [TF changes were applied](https://si.prod.tfe.czi.technology/app/single-cell-infra/workspaces/accounts-single-cell-dev/runs) to the single-cell-dev AWS account.  This covers both the dev and staging deployments, right? I assume similar changes will be needed for single-cell-prod AWS account? If so, should this story remain at "In Progress"? Or should we close it and make a new story for the prod changes?

**Comment by Bento007** [comment]
complete
