### ISSUE TITLE
Create Collection Index Endpoint

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2013]
GET `/curation/collections` should return all Collections for which the user is authorized. For the shape of the response refer to [the spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148).

**Comment by Bento007** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/1982/files#diff-2ecdf5ab1df6ebdd7b0ac8850a7c29711c2283e1519a255e3b917bc88e12617bR83

**Comment by metakuni** [comment]
Unassigning myself to work on the upload handler

**Comment by danieljhegeman** [comment]
Making fixes to schemas.
