### ISSUE TITLE
Create the FE components for managing Curator API keys

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2015]
A button needs to be added in the profile drop-down at top right of the cellxgene UI. This button will cause the (re)generation of an API key on the backend (separate work) and its display in a modal on the FE.

The button and modal should be added per the design demonstrated in [this figma doc](https://www.figma.com/file/3OBNVJ2Wn6aF4MdNnhVhnt/Curation-API?node-id=0%3A1)

**Comment by danieljhegeman** [comment]
@seve If we _do_ end up deciding to display the key identifier, we will just do so directly beneath the `Generate API Key` button in the drop-down. Its inclusion will _not_ require a redesign, so it can be done at the end if desired.

Please proceed with the FE additions exactly as shown in the figma design.

**Comment by brianraymor** [comment]
Still pending editorial changes per feedback in [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1646791495690969?thread_ts=1646790211.219629&cid=C02UGUV5R3J).
