### ISSUE TITLE
Remove visibility from API queries

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2028]
- update DELETE `collections/{collection_uuid}` to 1) tombstone a public collection, and 2) delete a private collection or revision.
- Remove visibility from query parameters for both GET _and_ DELETE for `collections/{collection_uuid}`

**Comment by atolopko-czi** [comment]
@danieljhegeman ok to close? (it's merged to prod branch)

**Comment by atolopko-czi** [comment]
@danieljhegeman closing now, to keep board sane; undo if wrong!
