### ISSUE TITLE
Update slack dataset processing notification wrt primary key migration

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2031]
- Update https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/corpora/dataset_processing/slack.py#L36

**Comment by danieljhegeman** [comment]
moving to F&F

**Comment by brianraymor** [comment]
@danieljhegeman - is this assigned to you?

**Comment by danieljhegeman** [comment]
> @danieljhegeman - is this assigned to you?

No it is not. @Bento007 ?

**Comment by metakuni** [comment]
@danieljhegeman will add more details

**Comment by brianraymor** [comment]
@metakuni @ebezzi - no further details were added per Kuni's request above. Can you advise on this ?

**Comment by ebezzi** [comment]
I have no idea what this is about. @danieljhegeman please add more details or close it if no longer relevant.

**Comment by metakuni** [comment]
@danieljhegeman , could you provide more details? The link in the description is also broken.
