### ISSUE TITLE
Remove null values from collections/index API endpoint

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2042]
See [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1646345615873449?thread_ts=1646270813.858399&cid=C02CF7MQPGV).

**Comment by MillenniumFalconMechanic** [comment]
See [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1646345615873449?thread_ts=1646270813.858399&cid=C02CF7MQPGV).

**Comment by brianraymor** [comment]
Updated title to reflect that the dataset/index API endpoint does not return null values.
