### ISSUE TITLE
WMG API query endpoint - development_stage ontology ancestor terms

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#2052]
The  WMG API query endpoint response must also include the ancestor terms for each development stage to allow the FE to provide visual grouping. The ancestor terms are fixed [TODO: where defined?] and must be returned even if they do not occur in the cell corpus data.

- [ ] The `/query` response's `filter_dimensions` must provide 2-level nested dict structure (i.e. depth=1) for ancestor/child terms. e.g.: `development_stage_terms: [{HsapDv:0000204: "Mature (13+ years)", children: [{HsapDv:0000087: "human adult stage"}, {HsapDv:0000146: "52-year-old human stage"}, ...]}]`
- [ ] Add unit test to ensure that (ancestor) ontology terms that do _not_ occur in the corpus are admissible to the `/query` endpoint as filtering criteria. They should be effectively ignored.

**Comment by atolopko-czi** [comment]
Signe writes:

> [this functionality is] nice to have, we can punt it and fix it in the week or two following launch if thats helpful. not doing this work will make that filter unusable. ideally, we would probably just hide that filter for launch until we can do the work

**Comment by atolopko-czi** [comment]
@signechambers1 @tihuan This feature needs some more discussion before the backend can complete its work. Proposing this design:
- Backend returns development stage terms in hierarchical structure
- Front end displays hierarchical terms in filtering drop down.
- [Option 1] For any user-selected non-leaf terms, UI expands filtering values to include all child terms. Backend query unlogic works without further modification.
- [Option 2] UI sends only explicitly selected terms to backend. Backend query logic expands non-leaf terms to include all child terms prior to executing the query.

**Comment by tihuan** [comment]
Thanks so much for the options, Andrew!

Looking at how collection/dataset filters work, it feels like maybe Option 1 is better, so the users know exactly what options are included in the query, and UI can display all the selected options explicitly too. What do you think?

**Comment by atolopko-czi** [comment]
In fact, you've identified a subtlety I wasn't considering--that the UI would automatically select and thus _visibly show_ the child terms that will become part of the query. Yes! So in that case, Option 1 makes total sense. Thanks!

**Comment by signechambers1** [comment]
Sounds good to me! thanks to you both!

**Comment by atolopko-czi** [comment]
@MDunitz This is probably worth closing as we have a full OKR about how to properly handle complex ontology filtering.

**Comment by atolopko-czi** [comment]
> @MDunitz This is probably worth closing as we have a full OKR about how to properly handle complex ontology filtering. May also be fully handled now by #2339?

Closing
