### ISSUE TITLE
Add processing status for datasets to GET /curation/collections/{collection_uuid}

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2057]
How does the curation API return the processing state of the private collection or a private revision of a public collection? For example, a dataset may be uploaded, but invalid. A conversion may have failed.

The curator can query per dataset using `GET /curation/collections/{collection_uuid}/datasets/status`, but similar information is not included in `GET /curation/collections/{collection_uuid}`.

The current portal API returns this for each dataset in `datasets` :

```
"processing_status": {
     "created_at": 1639080087.310423,
     "cxg_status": "UPLOADED",
     "dataset_id": "c7775e88-49bf-4ba2-a03b-93f00447c958",
     "h5ad_status": "UPLOADED",
     "id": "d2aeb937-1281-47c2-a212-3cf1ee54846f",
     "processing_status": "SUCCESS",
     "rds_status": "CONVERTED",
     "updated_at": 1640062492.775752,
     "upload_progress": 1.0,
     "upload_status": "UPLOADED",
     "validation_status": "VALID"
    },
```

---

**Open questions**

@jahilton 

> Related, for the per dataset state via curation/collections/{collection_uuid}, is there a distinction for a dataset that has been revised vs one that has not been updated from its published state, in this property or another?

@brianraymor 
> Let me do a quick test to see what's currently returned in processing_status when I upload a new dataset in a revision.What would you like/expect to see to enable you to determine which datasets have changed?

@jahilton
> I would like to either get a different processing_status (so SUCCESS becomes 2 categories)
Or some sort of a revised: true/false flag would also work

**Comment by danieljhegeman** [comment]
@brianraymor I realized that I actually added `processing_status` to the dataset_preview model for the index endpoint `GET /v1/collections`.

I'm now having trouble remembering if I did that absentmindedly... or if I saw a note somewhere that said we wanted that included there as well, and I just can't find the ticket/conversation where we decided either way.

Can you jog my memory on this? Either way is fine from a technical standpoint of course -- just let me know which you prefer.

**Comment by brianraymor** [comment]
Are you speaking of a different communication than the conversation in  [Add processing status for collection to GET /curation/collections](https://github.com/chanzuckerberg/single-cell/issues/284)?

**Comment by danieljhegeman** [comment]
Yes. I remember that conversation separately. 

The question is do we want 
```
collection: {
  name: collection_name,
  processing_status: success  # <- I know we want this
  datasets: [
    {  
      id: <dataset_id_1>,
      processing_status: success  # <- But do we also want this?
      ...
```

**Comment by jahilton** [comment]
Yes

**Comment by brianraymor** [comment]
I really need to create a "Jason approved" github label.

**Comment by jahilton** [comment]
>I really need to create a "Jason approved" github label.

More cherished than a Paul Hollywood handshake
