### ISSUE TITLE
Data Source must removed as a filter

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2063]
**April 18** - @hthomas-czi and I agreed to deprecate this filter. We agree with @jahilton that this is much less useful when filtering by dataset rather than filtering by cell. This must be removed prior to launch. Decision also documented on the slack thread below.

Capturing [review notes](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1646429443528099) from @jahilton.

**Data Source**

1. Data consumers will not understand the meaning or use of "Data Source" as a filter.  Furthermore,  "Data Source" is already a collection link type with a different meaning. 

2. Is it useful to filter on `Data Source` prior to cell-based search? There are datasets in the corpus that contain both primary and secondary data. 

If `Data Source` is retained as a filter, it must be renamed.

**Comment by tihuan** [comment]
in prod!
