### ISSUE TITLE
Disease filter for collections and datasets must pin "normal" to the top

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2065]
Capturing [review notes](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1646429453513719) from @jahilton.

> Organism values, I think, should be ranked by Dataset/Collection count high->low so human/mouse don't get buried.  Disease, as well, so get 'normal' on top

Per _filter by metadata_ call on March 7, there was agreement to pin "normal" to the top of the "Disease" filter values for both collections and datasets. @hthomas-czi to provide a design. 

This design may be reused in the future for `Organism` but currently, the list of organisms is small, so human/mouse are not buried. 

**UX**
[Figma](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=3398%3A34024)

**Comment by MillenniumFalconMechanic** [comment]
* Pinned and non-pinned values should be in the same scroll view.
* On search within a category, the pinned section is hidden and any pinned values matching the search criteria are returned as normal in the search results.
