### ISSUE TITLE
publisher_metadata fields annotated as required

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2076]
RE - https://app.swaggerhub.com/apis/danieljhegeman/Curation/1#/publisher_metadata

It documents that "some" of the fields are required. All are required to be present. There are heuristics for missing day or month (default to 1) in _filter by metadata_. 

**But** the values are acquired from crossref and set by the BE based on the DOI passed when creating or editing a collection and returned in query information, so it's unclear why **required** (*) is annotated in responses.

**Comment by danieljhegeman** [comment]
I had copied straight from [this PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/1995/files) by Emaneule. I will add `month` and `day`.

Regarding the usage of `required` in responses: it is sort of like a gating mechanism for our own testing. We have a number of instances of it being used to help define responses in the v1 API for the FE. It makes sense as a last check in prod, too, where we might consider our generated response invalid (and thus better to return a 400) unless it contains certain fields.

**Comment by danieljhegeman** [comment]
@brianraymor Swagger updated.
