### ISSUE TITLE
Issues with Bearer Authentication

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2078]
1. [POST curation/auth/token](https://app.swaggerhub.com/apis/danieljhegeman/Curation/1#/default/post_curation_auth_token) displays a warning:

![Screen Shot 2022-03-08 at 3.15.20 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/c067208f-7d1a-437a-be69-e2d6a555e8ca)

Is the intention to return the token in the header or in the response for future use in the `Authorization` header of other API requests?

2. Is the token defined/included in all relevant curator API(s)?
Also see [Bearer Authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/)

3. The description is confusing - "Your curator API key with Bearer prepended, joined by a single space."

**Comment by danieljhegeman** [comment]
@Bento007 pulling you in here since you'll be more familiar.

Also, I have no idea why I wrote the description for that endpoint as I did:

> Returns a bearer access token that must be passed as a parameter to requests that
        require authorization such as creating a new Collection.

**Comment by Bento007** [comment]
you don't need to define this as a header directly. You only need to setup the security schema https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by danieljhegeman** [comment]
@Bento007 confirm this can be closed?

**Comment by Bento007** [comment]
closing
