### ISSUE TITLE
The description for GET /curation/collections needs more detail

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2083]
https://app.swaggerhub.com/apis/danieljhegeman/Curation/1#/default/get_curation_collections

_Fetch all Collections metadata. Authorization required for private collections._

It neither fetches _all collections_ nor _all collections metadata_.  Perhaps something more like:

1. When the `visibility` parameter is unspecified or set to `"PUBLIC"`, a list of all public collections is returned. The Authorization header is not required.  If a collection in the list has been deleted, then it is annotated with `tombstone` set to `True`.
1. When the `visibility` parameter is set to `"PRIVATE"`, a list of all private collections that the user is authorized to access is returned. The Authorization header is required. If a collection in the list is a private revision of a public collection, then it is annotated with `revision_of`.
1. Each collection in the list contains a subset of collection metadata as a preview.
1. To retrieve full collection metadata for a specific collection, `GET /curation/collections/{collection_uuid}` must be used.

**(danieljhegeman note: despite lengthy discussion below, these rules still stand as stated)**

**Comment by danieljhegeman** [comment]
> It neither fetches all collections nor all collections metadata

What collection metadata does it not fetch? Do you mean to refer to the fact that _dataset_ metadata is only a preview?

**Comment by danieljhegeman** [comment]
> Each collection in the list contains a subset of collection metadata as a preview.

what do you mean by subset? Are you intending to contrast that with what is returned for a single collection with GET `/curation/collections/{collection_id}` ?

**Comment by brianraymor** [comment]
> Is this a reference to the fact that the metadata for the associated datasets is different?

Yes. There is a _preview_ of the dataset metadata which is part of the collection metadata.

**Comment by brianraymor** [comment]
Quick assessment:

|                                     | GET collections | GET collection |
|-------------------------------------|:-----------:|:----------:|
| access_type                         |      x      |      x     |
| contact_email                       |      x      |      x     |
| contact_name                        |      x      |      x     |
| created_at                          |      x      |      x     |
| curator_name                        |      x      |      x     |
| datasets/assay                      |      x      |      x     |
| datasets/batch_condition            |             |      x     |
| datasets/cell_count                 |             |      x     |
| datasets/cell_type                  |             |      x     |
| datasets/curator_tag                |      x      |      x     |
| datasets/dataset_assets             |             |      x     |
| datasets/dataset_deployments        |             |      x     |
| datasets/disease                    |      x      |      x     |
| datasets/ethnicity                  |             |      x     |
| datasets/id                         |      x      |      x     |
| datasets/is_primary_data            |             |      x     |
| datasets/mean_genes_per_cell        |             |      x     |
| datasets/name                       |             |      x     |
| datasets/organism                   |      x      |      x     |
| datasets/revised_at                 |             |      x     |
| datasets/revision                   |             |      x     |
| datasets/schema_version             |             |      x     |
| datasets/sex                        |             |      x     |
| datasets/tissue                     |      x      |      x     |
| datasets/tombstone                  |      x      |      x     |
| datasets/X_approximate_distribution |             |      x     |
| datasets/X_normalization            |             |      x     |
| description                         |      x      |      x     |
| id                                  |      x      |      x     |
| links                               |      x      |      x     |
| name                                |      x      |      x     |
| published_at                        |      x      |      x     |
| publisher_metadata                  |      x      |      x     |
| revised_at                          |      x      |      x     |
| revision_of                         |      x      |      x     |
| tombstone                           |      x      |      x     |
| visibility                          |      x      |      x     |

**Comment by danieljhegeman** [comment]
@brianraymor I've updated the description (and the Swagger API doc).

**Comment by danieljhegeman** [comment]
@brianraymor can you confirm that you still wish for _only_ a curator's _public_ Collections to be returned in the case where they provide authentication but do not specify a `visibility`? The alternative being that both public _and_ private Collections would be returned.

> When the visibility parameter is unspecified or set to "PUBLIC", a list of all public collections is returned.

cc @Bento007

**Comment by brianraymor** [comment]
I proposed something different above. Emphasis added:

Fetch all Collections metadata. **Authorization required for private collections**.

1. When the `visibility` parameter is unspecified or set to `"PUBLIC"`, a list of **all** public collections is returned. The Authorization header is not required.  If a collection in the list has been deleted, then it is annotated with `tombstone` set to `True`.

Public collections do not require authorization because they're accessible to everyone.

**Comment by jahilton** [comment]
Agree w/ ☝️

**Comment by danieljhegeman** [comment]
@brianraymor my mistake: I accidentally caused the focus to be on "all public collections" vs "just the curator's public collections" because I worded my question poorly. My mistake! 

I meant for the focus to be on the following: when a curator _does not_ specify a `visibility` query parameter, and they DO provide authentication, do we want to return 

- all public collections

OR

- all public collections AND all of the curator's private collections

?

I know that you have said we should return "all public collections" when the `visibility` is not set, as a default, but I was wondering if we should return _all_ possible authorized collections instead, both public and private.

**Comment by danieljhegeman** [comment]
Also, the `dataset_assets` child attribute of `datasets` seems redundant in its name: shouldn't it just be `assets`?

`datasets/assets` rather than `datasets/dataset_assets`

**Comment by danieljhegeman** [comment]
One more issue: for the Collection-level attribute `access_type`, which will be included in both the `GET /v1/collections` and `GET /v1/collections/{collection_uuid}`, I was thinking we might want to return `None` if the user does not include credentials in their request. That way, if they see `"READ"` as their access level, they will know "ah, yes, I included my access token and so I _know_ my access has been evaluated, but if they see `None`, then they will be reminded "Ah, I didn't include my access token in my request, so if I want to know for sure, I should resend the request _with_ my access token".

**Comment by brianraymor** [comment]
RE questions in [comment](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2083#issuecomment-1160201244)


```
datasets/X_approximate_distribution
datasets/X_normalization
```

> Do you actually want/need these columns to be `X_...` or can they be `x_...` (as they are in the database)?

I wonder why Leslie(?) lowercased them since there was no requirement to do so. These fields are[ referenced in the schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#x_approximate_distribution) as `X_` so I would like them to be returned as I specified.


I'm also struck out X_normalization in the [table above](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2083#issuecomment-1063267917) because we plan to deprecate this field in Q3.

**Comment by jahilton** [comment]
I don't have a good handle on our use case for looking at access_type (and I anticipate having all access to everything, so especially not helpful). But from the options in that comment, I would think if you're trying to communicate that I didn't provide credentials then explicitly state `No credentials provided`

**Comment by danieljhegeman** [comment]
> I seems to me that access_type is only valuable when an access token is present. Then a curator can filter for access_type == "WRITE" as the long way round to My Collections which suggests that we should simply provide a convenience endpoint?

I think the write/right 😉 way to do this would be to have an `access_type` query param option for the `GET /collections/{collection_uuid}` endpoint.

**Comment by danieljhegeman** [comment]
> Distress. Where are my private collections and private revisions of public collections? Bang on the side of the API. What's the matter with this thing!? And then I notice the access_type values in the response and achieve enlightenment?

In that case, yes. It's not a panacea but it seems better than seeing "READ" under the exact same circumstances. What do you think, especially combined with the suggestion I made directly above for adding `access_type` as a query param?

> I'm oblivious and decide to revise one of the public collections. It fails. Hopefully, there's helpful error message in the response that shows me the error of my ways?

Yes

**Comment by brianraymor** [comment]
> I think the write/right 😉 way to do this would be to have an access_type query param option for the GET /collections/{collection_uuid} endpoint.

Did you mean `GET /collections` endpoint?

**Comment by danieljhegeman** [comment]
Thank you, yes, my mistake. `GET /collections`

**Comment by brianraymor** [comment]
Would the only options be either "READ" or "WRITE"?

If so, would it be easier to:

1. Deprecate `access_type`
2. Use `GET /collections?MyCollections` which is _familiar_ to the curators from the UX - which returns nothing without an access token and is specifically for curators since all other consumers only have "READ" access.

**Comment by brianraymor** [comment]
>  it would return an error if the `MyCollections` flag is passed but without an access token

Even better.

**Comment by danieljhegeman** [comment]
As long as Jason is ok with it. Can you get his approval? Specifically, the deprecation of `access_type`.

**Comment by jahilton** [comment]
Better yet @danieljhegeman , _you_ can get his approval. 
👍

**Comment by danieljhegeman** [comment]
Haha @jahilton I lacked the ability to tag you in issues until the last couple of days, when Ambrose added you to the repo! 😅 😅

**Comment by danieljhegeman** [comment]
Added the `MyCollections` query param flag as [an issue ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2793)in Fit & Finish
