### ISSUE TITLE
Deletion of published collections in the Curation UX must be removed

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2099]
Currently, curators are presented with a `Delete Collection` button in the collection detail page for all published collections that they're authorized to delete. This UX must be completely removed to avoid accidents, track deletion occurrences and justifications, and to validate that the redirect is in place for the permanent links to the collection and its CXG(s). 

Curators are still allowed to `Cancel a revision` in a private revision of a published collection.

**Comment by Bento007** [comment]
The current user types I'm aware of are: 
- visitor:
  - unauthenticated
  - permissions: read collections
- curator:
  - authenticated
  - permissions: read, write, delete, and modify own collections
- super curator:
  - authenticated
  - permissions: read, write, delete and modify all collections

Are we adding an additional user type, or is this a modification of the `curator` user type?

**Comment by brianraymor** [comment]
This is a modification to the `curator` user type.

- curator:
  - authenticated
  - permissions: read, write, ~delete~, and modify own collections
