### ISSUE TITLE
TF for wmg_config secret create & value set 

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#2101]
AWS Secrets Manager secrets need to be created automatically by TF: `corpora/backend/{rdev,dev,staging,prod}/wmg_config`.

Contents:
```
{"bucket": f"wmg-<env>", "tiledb_mem_gb": "16"}
```

**Comment by atarashansky** [comment]
@atolopko-czi 

Hey Andrew, I can't find the `wmg_config` file in the noted path `corpora/backend/dev/wmg_config` in the repo. Please advise.

Thanks!

**Comment by atolopko-czi** [comment]
> @atolopko-czi
> 
> Hey Andrew, I can't find the `wmg_config` file in the noted path `corpora/backend/dev/wmg_config` in the repo. Please advise.
> 
> Thanks!

That path is actually a AWS Secrets Manager "secret" path. Will explain & show you more during our pairing tomorrow!
