### ISSUE TITLE
The original dataset should be saved as a mitigation for potential data corruption during processing

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2124]
**August 29 Update** - Team should review @atolopko-czi 's guidance in the [Curation API specification](https://docs.google.com/document/d/1OpBpkST75rRqTAXhPKxwYEVA2ddfU4HvjbU7BYoNi6M/edit?disco=AAAAVH1yrU8). 

**August 10 Update** - See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660155815198679?thread_ts=1660086715.773679&cid=C02UGUV5R3J):
1. @ebezzi to review caching the original dataset as part of this epic per @atolopko-czi 's [recommendation](https://docs.google.com/document/d/1OpBpkST75rRqTAXhPKxwYEVA2ddfU4HvjbU7BYoNi6M/edit) as a backup in cases of data corruption. 
1. There is no Q3 work for the curation API at this time. If `1` is implemented, it can be exposed later in the API if needed.

### Context

See [**wrangling**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1646270820321339) for reference. If the technical requirement is implemented, then there are potential product uses. 

When a dataset is submitted to the cellxgene portal, human-readable labels are applied for gene and ontology terms. If a dataset is later downloaded to be revised by a curator, these terms must be deleted before re-submitting the dataset to the portal; otherwise, validation fails. 

One mitigation is to add a label remover to `cellxgene-schema` or to overwrite the labels if present. (This was included in 3.0.0).

Another approach is to allow curators to download the original dataset if available. Once the curation API is implemented, all submitted datasets are stored during ingestion in their original format.

#### Updating ontology versions

The pinned ontology versions in the cellxgene schema are updated. Many datasets in the corpus must be updated to reflect the change, including:

1. Addressing obsolete terms
1. Addressing changes to human readable names (re-labeling)
1. Updating cases where a less specific CL term was used until a new version of the CL ontology was supported

It would be more efficient if a curator could simply download the original dataset to make such changes.

#### (Temporary) differences in submission and download file formats

The second case is more theoretical. Imagine a case where cellxgene allows a curator to submit multimodal or multiomic datasets in a format such as `mudata` instead of `anndata`. (There's a desire to capture this data now rather than requiring the curators to return to the contributors later.) The ingestion process ignores unsupported modalities because end-to-end support is incomplete. This requires one format for ingestion, while using the current formats (.h5ad, .rds) for downloads of the RNA data.  In this case, the curator would require access to the original submission in its original format.

---

Dan's notes from [Curators can download the original dataset submission](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2156).

Curators must be able to get download links for dataset assets for

1) all PUBLIC Datasets, and 
2) those PRIVATE Datasets for which they are authorized

This should likely be bundled in as another asset, perhaps with an attribute label (`file_name`) of `original`, in the response for `GET` to `/curation/collections/{collection_uuid}/asset`. This is TBD and must be approved by the other members of the Curator API project.

Remember to refer to [the API spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148).

**Comment by Bento007** [comment]
We can add a path in the submission pipeline to upload the original file to s3 before or after we finish processing it. Since we will be resubmitting all of the datasets during the migration, this will allow us to update all of the datasets with a copy of the original.

**Comment by Bento007** [comment]
We need to decide how we will mark the asset as the original. 
Options:
1. use `filename` and name it `original`. 
   - Easy, doesn't require database migration. 
   - Could be problematic if we want to save the original name of the file in the future.  
1. add a new column to the asset table to indicate its original
   - requires migration and adding a new column to the database
   - uses more space on the database
1. add a new enum to the `DatasetArtifactFileType` to indicate it is the original file.
   - requires migration and adding an enum
   - uses less space than adding a new column to the database.

**Comment by Bento007** [comment]
The reason we are moving forward with this is to be overly cautious. If our pipeline corrupts a dataset, we will have the original data to correct the mistake. Another benefit of this approach is allowing users to download the original dataset if they wish, without our added labels.
