### ISSUE TITLE
Upgrade base images used in Dockerfiles

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#2127]
Review `Dockerfile`s in all Github repositories and upgrade the base images as appropriate.

e.g. https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/Dockerfile#L1

**Comment by metakuni** [comment]
See also #1565

**Comment by ebezzi** [comment]
There is little benefit in using Alpine instead of Ubuntu. Once you install numpy, which is required by all of our applications, you end up with an extremely similar image. I recommend closing this ticket - base images are being upgraded as part of other ticket (#564, #4131)

**Comment by metakuni** [comment]
Closing as per @ebezzi
