### ISSUE TITLE
Add unit tests for validating dates and journals are included in Crossrf response

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2135]
See [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1646693094116279).

**Comment by ebezzi** [comment]
Unit tests have been added as part of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1972
