### ISSUE TITLE
Provision {dev,staging,prod} "data staging" buckets

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2141]
Curators will achieve local uploads directly to the data portal by uploading to our s3 "data staging" bucket (named `cellxgene-dataset-submissions-{dev,staging,prod}`), where we will act on the data.

The buckets should be private and otherwise have the same policies as our current general-use s3 buckets, with the notable exceptions of
- A auto-deletion policy that deletes items a week after they land
- Automated dispatch of an [S3 Event](https://docs.aws.amazon.com/AmazonS3/latest/userguide/NotificationHowTo.html) that can be listened for by the lambda in order to make sure the dataset gets processed.

Access to the buckets is mediated by temporary AWS access tokens, the creation of which will be in a different issue.

**Comment by metakuni** [comment]
Confirmed S3 bucket creation for environments: [rdev](https://si.prod.tfe.czi.technology/app/single-cell-infra/workspaces/dev-dp-rdev/runs/run-7V1MkHE5xNYkWiSh), [dev](https://si.prod.tfe.czi.technology/app/single-cell-infra/workspaces/dev-dp-dev/runs/run-B93TwyTwavBucpvi), and [staging](https://si.prod.tfe.czi.technology/app/single-cell-infra/workspaces/staging-dp-staging/runs/run-s5Q87a5Gvk9FDRiq):
```
m1 ➜  ~ AWS_PROFILE=single-cell-dev aws s3 ls s3://cellxgene-dataset-submissions-dev --summarize

Total Objects: 0
   Total Size: 0
m1 ➜  ~ AWS_PROFILE=single-cell-dev aws s3 ls s3://cellxgene-dataset-submissions-staging --summarize

Total Objects: 0
   Total Size: 0
m1 ➜  ~ AWS_PROFILE=single-cell-dev aws s3 ls s3://env-rdev-cellxgene-dataset-submissions --summarize

Total Objects: 0
   Total Size: 0
```

Prod infra isn't auto-deployed so `s3://cellxgene-dataset-submissions-prod` hasn't been created yet but will be deployed/created tomorrow by the on-call engineer:
- https://si.prod.tfe.czi.technology/app/single-cell-infra/workspaces/prod-dp-prod/runs/run-7qYaqM9iug4vGAn8
