### ISSUE TITLE
Provisioning of lambda function handler for dataset uploads

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2143]
In order to initiate dataset processing for datasets that have gone through the 'local upload' route to our s3 bucket, we will need a lambda to listen for S3 upload events for this bucket and respond accordingly.

The lambda should parse the key name of the S3 object as follows:

**s3://cellxgene-curation-submissions-{dev,staging,prod}/<collection_id>/<curator_tag>**

Lambda function: 

- the curator tag is everything in the pseudo-path key after the second `/`.
- the collection_id is determined by everything between the first and second `/`.
- the handler function must check the given collection, as indicated by the `collection_id` in the key, to see if a dataset with `curator_tag` already exists. If so, the lambda must follow the current paradigm for [canceling processing of / deleting] a dataset that the v1 API uses.
- the handler function must then initiate processing of the dataset

**Comment by metakuni** [comment]
Temporarily moving this story to the backlog to maintain board hygiene.

**Comment by atolopko-czi** [comment]
`ready for qa` now?
