### ISSUE TITLE
Curators can query for their Collections and Datasets using the Curation APIs

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2150]
Curators must be able to retrieve Collections and Datasets [per the spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148). An individual curator must be able to access ONLY those Collections and constituent Datasets for which that curator is AUTHORIZED ('Lead-curator' privileges entail access to ALL Collections and Datasets).

**Comment by brianraymor** [comment]
Long strange trip.
