### ISSUE TITLE
Curators can modify a private Collection

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2151]
Curators must be able to modify a private Collection.

- Collection metadata updates via `PUT` to `/curation/collections/{collection_uuid}`
- Dataset updates (replacements) via local uploads **for Datasets that were locally uploaded and therefore already have a tag**. This specifically DOES NOT include the work for `PATCH` to `/curation/collections/{collection_uuid}/datasets` to change / add a `curator_tag` for a Dataset.

Refer to [the API spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148) for confirmation of endpoints.

**Comment by brianraymor** [comment]
Long strange trip.
