### ISSUE TITLE
Curators can use S3 links to upload datasets to a Collection

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2153]
We must also support Dataset uploads by receiving upload links from curators. In this case, curators must be able to provide upload links along with dataset `curator_tag` and/or `id` to upload new Datasets or replace existing ones.

- `PUT` to `/curation/collections/{collection_uuid}/datasets/upload-link`

As always, [consult the spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148) for endpoint details.

**Comment by Bento007** [comment]
https://feeney.mba/refreshable-aws-boto-credentials.html
