### ISSUE TITLE
Curators can use the Curation API to get download links for Datasets

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2154]
See [the API spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148) for endpoint details and request/response shape.

`GET` to `/curation/collections/{collection_uuid}/asset`

**Comment by brianraymor** [comment]
Long strange trip.
