### ISSUE TITLE
Curators can add/update curator tags to manage datasets and dataset uploads more easily

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2155]
Inclusion of a curator-provided arbitrary string as a `dataset.curator_tag` is required for Datasets that are uploaded from a curator's local machine and processed via our lambda. This tag designates a unique Dataset _within a Collection_. In order to replace (update) a Dataset via a local upload, the existing Dataset _must_ have a non-null `curator_tag`. Because datasets uploaded via the UI by default will not have a `curator_tag`, we wish to provide curators with a way to add the tag to existing Datasets so that they may be replaced via a local upload; the tag also provides a more intuitive way for a curator to _specify_ a Dataset with other portions of the API, such as when trying to delete or download a Dataset. The curator may wish to change a `curator_tag` for a Dataset that already has a tag, just for organizational purposes and their own future workflows.

`PATCH` to `/curation/collections/{collection_uuid}/datasets`

As always, consult [the API spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148) for endpoint specifications.

**Comment by brianraymor** [comment]
Long strange trip.
