### ISSUE TITLE
Curators can download the original dataset submission

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2156]
Curators must be able to get download links for dataset assets for

1) all PUBLIC Datasets, and 
2) those PRIVATE Datasets for which they are authorized

This should likely be bundled in as another asset, perhaps with an attribute label (`file_name`) of `original`, in the response for `GET` to `/curation/collections/{collection_uuid}/asset`. This is TBD and must be approved by the other members of the Curator API project.

Remember to refer to [the API spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2148).

**Comment by brianraymor** [comment]
Closing as a duplicate.
