### ISSUE TITLE
Curators can cancel an in-progress Dataset upload

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2157]
In addition to permitting deletes of existing private Datasets, a `DELETE` to `/curation/collections/{collection_uuid}/datasets` must also permit the cancelation of an in-progress Dataset upload, using query parameters to specify either the `id` or the `curator_tag` of the Dataset in question.

**Comment by brianraymor** [comment]
@danieljhegeman - I converted this epic to an issue because it was NOT an epic - there are no child issues. Was there some missing refinement?

**Comment by danieljhegeman** [comment]
This epic/issue is redundant, so I'm closing. Everything is captured in [this issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2170). Canceling a Dataset upload is the same as deleting a private Dataset.

cc @Bento007
