### ISSUE TITLE
Complete documentation of APIs in the OpenAPI spec

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2161]
Each API must have detailed, clear `description` sections sufficient to guide a less-informed user on how to interact with the API.

---

### Specific cases:

- [x] @jahilton asks [Has the Collection schema been documented somewhere yet?](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1661180825423539)
- Required fields
- Format requirements for values (I know link_url has restrictions when link_type:DOI, possibly email or other links?)
- [x] Document that `link_name` is ignored/overwritten for DOI links](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660089617562009)
- [x] The description for `processing_status` - _Processing status for a Dataset or Collection_ is potentially meaningless to a new reader of the swagger. Also document that `None` is returned when no datasets are present in the collection. 
- [x] The requirements for PUT .../upload-link are [unclear](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660162834937169).
- [x] Document how to cancel an upload.  EDIT: that _canceling_ is accomplished by _deleting_ and that uploaded datasets may not appear as entries in the corpus for several seconds, possibly up to a minute, after initially completing upload.
- [x] For `POST .../revision`, the 409 failure case is poorly documented as "File conflict" instead of documenting that there is an existing revision and only one revision for a public collection is allowed to be _in progress_ at a time. If a curator attempts to revise a revision, the 403 (Forbidden) failure cause is NOT documented in the current swagger. Why is there not one common status code used for these cases? 
- [x] Due to [bug(API): Presigned S3 urls don't last long enough](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2266), the documentation must include the mitigation - `GET ../assets` MUST be called prior to each download to access the `presigned_url` which currently has a TTL of 1 hour or less. 
- [x] The [technical specification](https://docs.google.com/document/d/1OpBpkST75rRqTAXhPKxwYEVA2ddfU4HvjbU7BYoNi6M/edit) states: _(if source=link) link: the URL to the file to upload. It can be a dropbox shared link or a presign s3 URL_, but the swagger states _The Dataset will be uploaded from the **provided link**_ with no constraints on the link. This has resulted in [confusion](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660778105668779) about what is supported.
- [x] The swagger documentation is inconsistent about Descriptions for status codes. Sometimes, it uses the HTTP definition like `200 (OK)`; other times such as for `401 (Unauthorized)` it uses _Failed to Authenticate_ instead. In general, if we're not going to document why a specific status code is returned, then we should simply use the [standard HTTP names](https://datatracker.ietf.org/doc/html/rfc9110). 
- [x] @jahilton reports that invalid collection uuid, returns inconsistent results:

get_dataset - “Collection not found!”
get_assets - “Dataset not found!”
delete_dataset - “Dataset not found.”
update_curator_tag - “Dataset not found.”
get_collection - “Resource not found.”
delete_collection - “User is not authorized to access this resource.”
create_revision - “User is not authorized to access this resource.”
upload_local_datafile - “User is not authorized to access this resource.”
upload_datafile_from_link - “User is not authorized to access this resource.”

- [x] Despite multiple attempts the dataset schema fields are still not completely sorted in order.

**Comment by brianraymor** [comment]
For `GET ../collections`

> Each collection in the list contains a subset of collection metadata as a preview.

This is true, but the subset is specific to the datasets and is not general to the collection. Perhaps more precisely:

For each collection in the list, the datasets for that collection include a subset of **dataset** metadata as a preview.


> To retrieve full collection metadata for a specific collection, GET /v1/collections/{collection_id} must be used.

To retrieve full **dataset** metadata for a specific collection ...

**Comment by brianraymor** [comment]
RE _visibility_

> Determines the visibility of the collection, that will either make the collection visible on the public sites or only viewable through obfuscated URLs.

**determine** and **will make** sounds like a curator could change the value to flip it back and forth between public and private.

`visibility` reports on whether a collection is published on the portal (PUBLIC) or is an unpublished private collection or a private revision of a public collection (PRIVATE). There is no requirement to document the mechanism for private collections in the API?

**Comment by brianraymor** [comment]
Most of the metadata fields for collections and datasets lack descriptions. For example, what is the difference between `created_at` and `published_at` ?

For fields from the schema, schema description could be reused?

**Comment by brianraymor** [comment]
**revising_in**

> the id of the associated revision Collection, if one exists and the user is authorized

If there is a private revision for a public collection, then `revising_in` is set to the id of the private revision in the metadata of the public collection. The value is `None` if the user is not authorized or no private revision exists.


**revision_of**

> the id of the published version of this Collection

If a private collection is a revision of a public collection, then `revision_of` is set to the id of the public collection in the metadata for the private collection. The value is `None` if no private revision exists.

**Comment by Bento007** [comment]
> Most of the metadata fields for collections and datasets lack descriptions. For example, what is the difference between `created_at` and `published_at` ?
> 
> For fields from the schema, schema description could be reused? Can there be simply links to the schema sections - for example - [tissue](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#tissue).

open API doesn't support formated URL in the description. We can put a URL but it will be the raw URL an d wont be hyperlinked. This is a limitation of openapi.
