### ISSUE TITLE
Add tooltip to disabled filters indicating no values matching current filter criteria

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2183]
See [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1647541091045539?thread_ts=1647454939.265359&cid=C02CF7MQPGV).

Tooltip text: "There are no values that meet the current filter criteria".

**Comment by tihuan** [comment]
in prod!
