### ISSUE TITLE
Added (but unsaved links) disappear when clicking away from window

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-data-portal#2204]
## Describe the bug
When trying to add links to a private Collection (or revision), any unsaved links that you add disappear if you click to a new tab or window.

## To Reproduce
Steps to reproduce the behavior: (shown in video)
1. Go to a private collection (or revision)
2. "Edit Details"
3. "Add Link"
4. select any Link Type
5. Click to a new tab or window (say to copy the link)
6. back to the cxg window
7. see the link you've just added go away

## Expected behavior
The links should remain fixed unless the 'x' is clicked to remove them.

## Environment
**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: chrome
 - Version: 99

## Additional context
If you add one or more links, then click away, all of those will go away upon clicking back (in the video)
If you have already added links & Saved, then redo the steps above to add more, the saved links will not go away in these steps (not shown in video)

https://user-images.githubusercontent.com/15098808/160214776-92914c44-4ec2-444a-bfaa-2831ec509b87.mov

**Comment by tihuan** [comment]
in prod!
