### ISSUE TITLE
Filter out low coverage cells

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2219]
## Need
- To remove cells with gene expression values for less than 599 unique genes
- To set expression levels of 3 or less to zero (and set the accompanying rankit value to 0) after the rankit normalization has been run

**Comment by atolopko-czi** [comment]
@MDunitz can be closed now, right? I'm not sure which PR is linked to the 500-gene count filtering, but I know we implemented that! :) The 3-count cell filtering is on a new (PR)[https://github.com/chanzuckerberg/single-cell-data-portal/pull/2360], of course.

**Comment by ebezzi** [comment]
Yeah, I think we can close this. The 500-gene count filtering was done in [this PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/2232)
