### ISSUE TITLE
Remove datasets containing non whitelisted assays

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2222]
## Need
- To remove datasets that contain cell expression data from non white listed assays

## Approach
- currently we retrieve all datasets that have an assay of the included type, for datasets with multiple assays types if all of the assay types are not whitelisted those datasets shouldnt be included if we arent doing cell level filtering

**Comment by atolopko-czi** [comment]
@MDunitz Is this story different from #2220?

**Comment by MDunitz** [comment]
@atolopko-czi yes. This is regarding dataset level filtering and that one is for cell level filtering. If we implement #2220 we wont need this one

**Comment by MDunitz** [comment]
closing this as we implemented cell level filtering in #2220 which merged to main yesterday
