### ISSUE TITLE
Fix failing test

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2223]
## Need
To unskip and fix `test__get_all_collections_for_index` in `tests/unit/backend/corpora/api_server/test_v1_collection.py` so it isnt flaky but is still being used

**Comment by roaga** [comment]
I'm not sure of this but could this be the reason for the flakiness?
```        
actual_collection = body[-1]  # last added collection
```
It looks like the test is relying on the order of the response body (containing a list of collections in the database), and I don't believe we can rely on SQL preserving insertion order like this test assumes.

Perhaps we need to select an item from the body using an id or some other attribute, or use ORDER BY in the API endpoint.

**Comment by metakuni** [comment]
`test__get_all_collections_for_index` is no longer being skipped and isn't flaky so closing.
