### ISSUE TITLE
Restrict available development stage and ethnicity filters by both selected organism and result set

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2225]
See [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1648514385705839).

#### Definition of Done
**Development Stage**
_All three lists are visible by default. When the user filters by organism, the lists are limited to the ontologies matching the organisms. The other lists are removed from the filter. For example, if the consumer selects 'Homo sapiens', then the lists for 'Mus musculus' and 'Other organisms' are removed from the filter._

**Ethnicity**
_When 'Homo sapiens' is not selected, then this filter must be disabled._

**Comment by tihuan** [comment]
in prod!
