### ISSUE TITLE
A refresh is required to show the deleted tag when deleting a dataset from a revision.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2244]
A refresh is required to show the deleted tag when deleting a dataset from a revision.

_Originally posted by @Bento007 in https://github.com/chanzuckerberg/single-cell-data-portal/issues/2197#issuecomment-1087829395_

# Step to reproduce
1. start a revision
2. delete a dataset(the dataset never changes to deleted)
3. refresh or navigate from the window.
4. return to the window and the dataset will be marked as deleted.

**Comment by brianraymor** [comment]
Closing since we're removing the UX to delete published datasets in a revision - see #3037.
