### ISSUE TITLE
Fix failing WMG TileDB backend  tests

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#2264]
Fix this [failing test](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/wmg/test_query.py#L20), which usually only fails on GHA, not locally. Likely an OOM issue, due to TileDB memory allocation. This skipped test is not necessarily the sole culprit, but rather the apparent victim of test ordering--it currently the last test to be run in that test class.

**Comment by atolopko-czi** [comment]
Unsuccessfully attempting to reproduce QueryTest `realloc()` failures locally, forcing these settings:
```
        "py.init_buffer_bytes": 1 * MB
        "sm.tile_cache_size": 1 * MB
```

**Comment by atolopko-czi** [comment]
WIP branch: https://github.com/chanzuckerberg/single-cell-data-portal/tree/atolopko/2264-fix-gha-tiledb-tests.  Idea is to run GHA test quickly and iterate on different TileDB settings to see if realloc() error goes away. Some possibly pertinent TileDB mem Q's asked [here](https://github.com/chanzuckerberg/single-cell-data-portal/tree/atolopko/2264-fix-gha-tiledb-tests).

**Comment by atarashansky** [comment]
Is this test being run currently as a github action? I pushed a new branch to trigger `push_tests.yml` but couldn't see where `tests/unit/backend/wmg/test_query.py` was getting executed.

https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/2486001886

**Comment by MDunitz** [comment]
yea I think I merged a fix for this a few weeks ago. I'll close the ticket now.
