### ISSUE TITLE
bug(API): Presigned S3 urls don't last long enough.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2266]
## Context

[**wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1647969108486359)

@jahilton concluded:
_The problem is for non-curators. Anyone (data consumers) that would like to do 'batch downloads' e.g. download all of the kidney datasets in h5ad format_

---

## Describe the bug
Presigned s3 URLs are not lasting the 1 week we claim.

## To Reproduce
1. generate a presigned URL and wait a few days. 
2. The URL will deny access to the file after a few days.

## Expected behavior
A presigned URL to download and s3 file should last 6 day< expiration <= Days

## Additional context
A presigned URL is only valid as long as the token that generated them is valid, even if a longer time was requested for the presigned URL. 

[Why is my presigned URL for an Amazon S3 bucket expiring before the expiration time that I specified?](https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/)

**Comment by brianraymor** [comment]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660770391191809). Most recent tests demonstrate that the `presigned_url` expires within an hour.

**Comment by brianraymor** [comment]
@brianraymor - to add the mitigation for the MVP to the swagger issue.
@Bento007 - to add more details to this issue about the next steps (security review) to address longer term.

**Comment by atolopko-czi** [comment]
If the expiration occurs during the upload, being able to refresh the presigned URL likely won't help unless we can resume the upload after the refresh. Apparently, you need to be using the "low-level api" for multipart uploads:
```
Use the low-level API when you need to pause and resume multipart uploads
```
[https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-upload-object.html]

In Python, this presumably means using https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#multipartupload. Are we using this?

This might be a good time to call a meeting w/Todd  to discuss the resurgent tool (https://github.com/chanzuckerberg/resurgam-uploader/#quick-start): `Infrastructure to allow your users to upload large files to S3 and resume where they left off if their upload is interrupted`. If nothing else, I'm sure he'll have advice for us.

**Comment by brianraymor** [comment]
@atolopko-czi - the scenario in question is **downloads**. of datasets We use presigned URLs to provide temporary access to private S3 objects.

**Comment by brianraymor** [comment]
Per Feb 6 2023 triage, @metakuni and I agreed to include this in [Review GET /v1/collections/{collection_id}/datasets/{dataset_id}/assets response based on portal redesign](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3798) and close this issue.
