### ISSUE TITLE
Remaining Front End Polish

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2272]
High Priority (revisit if takes more than 1 hr):
- [x] All colors and text styles should reference variables in `theme.ts`
- [x] Tooltip labels should be `fontWeight: 400` and values should be `foregroundColor: .secondary`
- [x] Less spacing between sections in the tooltip
- [x] Selecting a gene or tissue with the keyboard or mouse should not clear the search text - pair with Harley
- [x] Add question mark icon next to Scaled, on hover add definition: "Expression is scaled to the range [0,1]. Scaling is done by assigning the minimum value in the current view to 0 and the max is assigned to 1."
- [x] Move tool tip above cursor when viewing dots at the bottom of the page so tool tip does not get cut off

Lower priority:
- [ ] Less spacing after a tissue
- [ ] Upgrade `echarts` to the latest version to get rendering improvement from [5.3.0](https://github.com/apache/echarts/releases/tag/5.3.0)

**Comment by tihuan** [comment]
>  but if I select a filter, then I close the filter sidebar and then reopen the filter sidebar, I lose my filter.

Should we add this as high pri or low pri bucket? Thank you!

**Comment by tihuan** [comment]
Closing this, since high pri items are all addressed! Thank you!
