### ISSUE TITLE
Add WMG processing docker unit test support

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#2280]
As the wmg_processing container has its own pip package requirements, unit tests for `backend.wmg.data` code will need to be run within this container, rather than in the `backend` container. Can follow this Makefile target [pattern](https://github.com/chanzuckerberg/single-cell-data-portal/blob/a967b3cc157987c6feecf305f077209a9485d470/Makefile#L32). Will need to _exclude_ these test from the backend container tests. This might benefit from a directory restructure, to separate the code and units at a higher directory level.

**Comment by MDunitz** [comment]
@ebezzi is the separate reqs file necessary due to package version incompatibilities? Could we just consolidate in 1? 

Or do we want to take this as an opportunity to break up our unit tests so we can run them in parallel and speed up the CICD pipeline

**Comment by atolopko-czi** [comment]
I think differing pip package requirement version diffs are one example of why we should run  a service's unit tests within its own container. The larger reason is that running tests within the container of the code that the tests are exercising is the safest practice. As we segregate code more aggressively to maintain logical separation of services/components within this repo, we want to ensure that the code that is built into the image is sufficient and correct; each image may end up only having a subset of the code from the overall repo.

As for separate requirements.txt files, this would also allow package versions to be updated independently and keeps the required packages to a minimum per built image. Though I think there are also good arguments to be made for having a single requirements.txt file--development-time ease being one of them, as that allows for development work to be done on all service/components within a shared, single virtual env.

**Comment by MDunitz** [comment]
I think this ticket should be included in the wmg-refactor work because it will require separating the wmg api tests from the data generation tests (and a lot of that work is already being done as a part of the refactor)
