### ISSUE TITLE
scExpression Prod QA - Firefox nav bar issues

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2314]
Steps tp reproduce:

Browser: Firefox
1. https://cellxgene.dev.single-cell.czi.technology/scExpression
2. Datasets and Collections tabs are not visible

**Comment by maniarathi** [comment]
@signechambers1 This may be due to not having the `filter=true` set. Datasets and Collections tabs are only visible right now if you have the feature flag set. This will be fixed when filters are unhidden.
