### ISSUE TITLE
scExpression Prod QA - Firefox filtering funkiness

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2315]
Steps to reproduce:

1. Firefox
2. https://cellxgene.dev.single-cell.czi.technology/scExpression
3. Homo Sapiens, lung, genes: LAP3, CD99, AOC1, CTFR, SARM1
4. Ethnicity: African American

Notice blue box shows up around ethnicity filter.

**Comment by tihuan** [comment]
Hmm can we got a screenshot or video/GIF please? I can't repro with Firefox locally 😆 Sorry!

Note that the blue box should show up when you use keyboard tabbing, since that's part of the a11y web standard. But it shouldn't show up if you select ethnicity filter using mouse click!

Thank you!

**Comment by signechambers1** [comment]
@tihuan it is happening to me on mouse click. See here https://images.zenhubusercontent.com/228681195/6ad1f4e7-8d13-452f-9a6a-006af6751cf9/firefox_filter_.mov

**Comment by signechambers1** [comment]
@hthomas-czi did you have anything additional to add here?

**Comment by tihuan** [comment]
> @tihuan it is happening to me on mouse click. See here https://images.zenhubusercontent.com/228681195/6ad1f4e7-8d13-452f-9a6a-006af6751cf9/firefox_filter_.mov

HMM! This is so weird 😆 I cannot reproduce 🤔 

What's your Firefox version? Mine is the latest (v99.0)

![demo](https://user-images.githubusercontent.com/6309723/162803950-0c63e139-5ca4-42c1-84da-059373374ca3.gif)

@signechambers1

**Comment by signechambers1** [comment]
@tihuan ack i thought i was on the latest version but just updated and now i cannot reproduce! so sorry. closing.

**Comment by tihuan** [comment]
Awesome thank you so much for confirming 🚀 !!
