### ISSUE TITLE
scExpression: Remove cell cultures from tissue drop down

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2335]
Remove cell cultures from tissue drop down. These datasets are not widely applicable and confusing to have show up at the top of the tissue drop down.

**Comment by seve** [comment]
capture by "(cell culture)"

**Comment by tihuan** [comment]
Thanks, Seve!

It looks like fixing BE primary filter endpoint fixes this one for free! But I'll keep an eye on it till the BE fix goes to prod before closing this ticket!

**Comment by tihuan** [comment]
Will get this commit merged into `staging` today!

https://github.com/chanzuckerberg/single-cell-data-portal/pull/2429

**Comment by tihuan** [comment]
In staging now 👌

**Comment by tihuan** [comment]
in prod!
