### ISSUE TITLE
scExpression: Once a user selects a tissue, visualization should update

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2336]
Right now, the app does not seem to respond to a user selecting a tissue. Ideally, once user selects a tissue the Getting started page would update to show the tissue and associated cell types (w/o a user selecting a gene). The ideal behavior matches the experience in the old prototype.

**Comment by tihuan** [comment]
Ahh I just tested this out, and we can't do this anymore because, unlike the prototype, BE only returns cell types information after we have selected genes 😔 Sorry!

CC: @signechambers1 @hthomas-czi

**Comment by signechambers1** [comment]
@hthomas-czi @tihuan we need to give the user some indication that they selected the tissue, could the tissue name show up at least? Any other ideas?

**Comment by hthomas-czi** [comment]
Agreed that we need to give the user feedback that their action was successful. I like your solution @signechambers1

**Comment by tihuan** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/2431 PR out!
