### ISSUE TITLE
scExpression: Secondary filters affect each other but not themselves

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2338]
A filter's available options should be limited only by the options selected in other filters.

Example ideal work flow:

Assume we have male and female data for African, female data only for European, and male data only for Asian.
1. User selects organism, tissue, genes
2. User selects "male" from Sex filter. User continues to see male and female in the dropdown for Sex.
3. User clicks on Ethnicity, they see African and Asian as options.
4. User selects Asian. User continues to see African and Asian as options.
5. User clicks back to Sex and only sees male as an option.
6. User clears male as a filter, user now sees African, European and Asian as options in Ethnicity.

From slack, we may need a separate internal query per filter. [Relevant slack thread](https://czi-sci.slack.com/archives/C0247APK621/p1650920787830669)

**Comment by tihuan** [comment]
Slack discussion now for likely implementing this in BE:

https://czi-sci.slack.com/archives/C0247APK621/p1650920787830669

**Comment by tihuan** [comment]
@signechambers1 I added backend label on this. Not sure if BE will commit to getting this done in Q2? Thank you!
