### ISSUE TITLE
scExpression: Disable secondary filters until user selects primary filters

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2342]
- [ ] Disable secondary filters until user has selected primary filters (organism and tissue and at least one gene)
- [ ] Add a tool tup at the filter div level when filters are deselected saying "Please select an organism, tissue and at least one gene to use these filters."

**Comment by tihuan** [comment]
PR out! https://github.com/chanzuckerberg/single-cell-data-portal/pull/2432
