### ISSUE TITLE
Precompute primary filters so that load time is <1 second.

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2343]
Precompute primary filters so that load time is <1 second.

**Comment by MDunitz** [comment]
Approach
- add a step calling the primary_filters function to the pipeline
- save the results to s3 under the expected snapshot
- update the api endpoint to read the data from s3 instead of querying the cube
- test

**Comment by MDunitz** [comment]
Duplicate of [2411](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2411)
