### ISSUE TITLE
consolidate tfe environments for prod

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2365]
## Need
- We currently have [4 different terraform workspaces](https://si.prod.tfe.czi.technology/app/single-cell-infra/workspaces) from which we need to manually apply changes to the prod env
    - prod-hosted-cellxgene
    - prod-dp-prod
    - prod-corpora 
    - prod-cloud-env

This introduces complexity and mental overhead that increases the likelihood of inadvertently introducing issues to the prod env

## Approach
- consolidate the various envs

## DOD
- all terraform changes are applied from 1 workspace which is clearly indicated in our deployment docs

**Comment by maniarathi** [comment]
Closing as recent conversations decided that this would be a lot of work and the benefit would be minimal.
