### ISSUE TITLE
Freeze dependencies after deploying to dev

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2366]
## Need
- to ensure consistency between envs. If a deployment runs in one env we want to be confident that deploying it to the next env (Staging, prod) will be successful. Currently we pin our reqs to a particular version or to anything larger than a particular version. 
If an update to a pinned package is released between deployments to different envs that creates the possibility of introducing breaking changes

Additionally we have reqs that need to be kept in sync in 3 or 4 different files, this is only somewhat documented

## Approach
- check that package_lock.json is being correctly generated (and used)
- after a successful deployment to dev we run `pip freeze` 
- copy the results to requirments_deployment.txt
- update the code to use requirments_deployment.txt when building the image for staging/prod

## DOD
- the same reqs are used across all environments for a particular image/deployment

**Comment by MDunitz** [comment]
Notes from discussion with @atolopko-czi 
Something Akin to npm's packages-lock.json or Ruby's Gemfile.lock .

In fact, we should do that at dev deploy time, rather than staging, right?

I'm surprised a lock file feature like this is not a first-class feature of pip, as it is for other pkg managers, which have conventions around what the file is called, how it gets used, etc.  Probably should dig to see if we're missing out on anything.  But maybe pip freeze is the full feature.
Thinking aloud, so we'd want to write out to a specially named deploy-time file, like requirements-deploy.txt(explorer uses that name in single-cell-infra), and commit that, yeah? I think all the Docker builds use the requirements.txt file directly, but we should check. And I know there's some pip file manipulations going on in some cases as well.  So we'd need to review the Dockerfiles and update as needed.

**Comment by maniarathi** [comment]
Closing as low priority.

From Emanuele:
"Moreover, since Docker uses caching by layer, I am pretty sure that, if no dependency gets manually updated, the Docker image wouldn't rebuild any of the dependencies. That said, if we want to enforce 100% parity, the best way is to just reuse Docker images completely, which unfortunately requires a few changes in our deployment pipeline."
