### ISSUE TITLE
scExpression fix gene add box

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2389]
Following behavior is expected
* Press enter to search for comma separated genes
* User should be able to type in a list of genes
* Remove No Options from dropdown when commas are detected

[Figma](https://www.figma.com/file/htICFl7zihfs1z9eIYVwzw/Gene-Search?node-id=3441%3A529981)

**Other UI Fixes**
* Change color scale to `interpolateMagma`
* Update color scale legend image
* Add Tissue and Add Gene should be [Small Primary Icon Button](https://zeroheight.com/009eaf17b/v/latest/p/47778c-buttons/b/065f46/t/751f0b)
* Scaled checkbox Info icon should be [Icon Size Small](https://zeroheight.com/009eaf17b/v/latest/p/529e08-icons)

**Comment by seve** [comment]
Change placeholder copy to “search or enter comma separated gene list”

**Comment by seve** [comment]
![image](https://user-images.githubusercontent.com/8716829/164123938-1a735360-57ca-4506-a2cd-24f4552efb33.png)
