### ISSUE TITLE
Internally force enable of filter flag

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2391]
#### Notes
Part 1/2 for enabling filter functionality (see #1718 for part 2/2).

#### Definition of Done
* Filter functionality is always enabled.
* Filter query string param is ignored.
* The following is added to next.config.js to enable redirect from "/" to "/datasets":

```
  // Redirect / to /datasets.
  async redirects() {
    return [
      {
        destination: "/datasets",
        permanent: true,
        source: "/",
      },
    ];
  },

```

**Comment by tihuan** [comment]
in prod!
