### ISSUE TITLE
Circular import issue with Dataset and Collection entities in Data Portal

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2395]
[This class method](https://github.com/chanzuckerberg/single-cell-data-portal/blob/3570af7876f4c901ef730d0b3ef2f545b36a0fe6/backend/corpora/common/entities/collection.py#L155-L203) *used* to live in the Dataset entity class, but the introduction of the primary key changes forced a move to the Collection entity class since a join with the Collection table was introduced; keeping it in Dataset.py results in a circular import error despite my best efforts to get around the issue. 

It seems like we're either doing something wrong with our imports or we should reorganize the code to allow this function to live in its semantically-appropriate class. It's possible I've missed a simple fix for this.

**Comment by metakuni** [comment]
@danieljhegeman : Does this issue still exist post-portal redesign?

**Comment by atolopko-czi** [comment]
Closing, because if it's still an issue, someone will recreate it. :)
