### ISSUE TITLE
Alert on failure

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2406]
## Need
- As a dev I want to be alerted when the atlas asset generation pipeline fails

## Approach
- [x] set up a slack bot to ping the single-cell-ops channel when the pipeline fails
- [ ] Alternatively set up a separate pipeline slack channel for all alerts

## DOD
- [ ] Failing runs of the pipeline generate slack alerts with links to the pipeline failure

**Comment by danieljhegeman** [comment]
@MDunitz closing
