### ISSUE TITLE
Baseline Pipeline Metrics

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2407]
## Need
- as a dev I want to know how the pipeline generally performs in order to identify deviations from the baseline

## Approach
- [ ] log the time for each step
          - extract
          - transform
          - load
 for each job in the pipeline 
          - integrated corpus
          - expression summary cube
          - cell count cube
          - cell ordering file
- [ ] Document the baseline in the tech spec

## DOD
- [ ] the approx time for each pipeline step is documented in wmg tech spec
- [ ] Stretch -- add alerting when any step takes significantly longer than expected

**Comment by dsadgat** [comment]
likely need to prioritize testing over this, closing as we wont get to this anytime soon
