### ISSUE TITLE
Update the official tech documentation 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2408]
## Need
As a dev I want the documentation to cover all aspects of the code

## Approach
- [ ] ~Create rough diagram of data flow ([see meta example](https://lucid.app/lucidchart/80992499-e855-4f01-8f54-6e53a8e4ebc1/edit?page=0_0#))~
- [x] Update [single cell arch doc](https://lucid.app/lucidchart/9d08a67d-1baf-4645-beb7-0eb1bc96e6af/edit?page=0_0&invitationId=inv_292f3561-6044-40d2-9c1d-e6f33648d19d#)
- [x] update tech overview to include data generation (use diagram from tech spec)
- [x] Instructions for accessing the instance and manually creating the cube

## DOD
-  An engineer from outside the project can read pipeline specific documentation and understand what is happening, how it works, how to trigger a pipeline run, how to update the pipeline, troubleshooting tips and how to ensure the data generated is correct

**Comment by signechambers1** [comment]
@atolopko-czi to assess priority

**Comment by signechambers1** [comment]
@atolopko-czi is this ticket a priority? If so, what's the plan for completing?

**Comment by atolopko-czi** [comment]
Done! Madison added extensive docs [here](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.3h08sd3otwfq) and [here](https://docs.google.com/document/d/1xo4-9mOtAXzCc_leQNsO0FG5HvaGEwbAyHQjqVV4MSE/edit#heading=h.qbt92zidqywe). Arch diagram was earlier updated.
