### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2409]
## Need
- as a dev I want to understand what happened within the data generation pipeline, particularly when trying to diagnose issues/debug

## Approach
- [x] set up logging structure (See Trent's work)
- [x] log errors
- [x] log total creation time (see separate ticket for timing individual jobs)
- [x] log datasets included
- [ ] log cube dimensions
- [x] log summary stats

## DOD
- [ ] checking the logs is helpful and not an exercise in frustration/despair

**Comment by metakuni** [comment]
To be revisited once Andrew's back next week. We'll keep this issue `In Progress` til then so that it doesn't get lost in the `Disorder` pile.

**Comment by danieljhegeman** [comment]
@Bento007 this was moved to `Ready for Prod` 2 weeks ago... closing now
