### ISSUE TITLE
Data Validation Tests

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2414]
## Need
- As a user I want to be confident the data I'm working with is accurate

## Approach
- [x] Walk through manual verification with @pablo-gar 
- [ ] Check that housekeeping genes are present at expected values (MALAT1 - high)
- [ ] cells with high expression values have high rankit values
- [ ] slice out subsection of data and compare to expected results

## DOD
- [ ] Validation tests run automatically after a cube is generated (before the snapshot id is updated in s3)

**Comment by pablo-gar** [comment]
I don't know if you want to add the following qualitative checks along with MALAT1

In the human lung, the following genes should be observed as markers of the indicated cell types:

- FCN1: monocytes
- TUBB4B: ciliated cells, and this gene is expressed to lower values in most other cell types 
- CD68: macrophages
- AQP5: goblet cells and secreting cells

**Comment by MDunitz** [comment]
@pablo-gar so if we slice on cell type we should see high expression levels for those genes (in the specified cell type)? 

Is it worth comparing to the expression value in a different type of cell?

**Comment by MDunitz** [comment]
XIST is a gene that’s primarily expressed in women, as it is the gene responsible for silencing one of the two X chromosomes in women.
So expression of this gene disappears when selecting only “male”

**Comment by MDunitz** [comment]
ACTB is should also be expressed in most cells (at a lower level than MALAT1)

**Comment by MDunitz** [comment]
lung map dataset uuid 3de0ad6d-4378-4f62-b37b-ec0b75a50d94
genes ["MALAT1", "CCL5"]
