### ISSUE TITLE
Include all primary data in the cube

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2419]
## Need
We want GE to match census so users have a cohesive, replicable experience across our platforms. right now, GE does not include primary data from datasets with both primary and secondary data in them. We'd like to update the query to include all primary data.

## Approach (from Madison - may be outdated)
- [ ] Update db query to include 'PRIMARY' and 'BOTH' for is_primary_data enum
- [ ] when generating the integrated corpus, filter out any non primary data

## DOD
- [ ] corpus and cube contain all primary data stored in the data portal

**Comment by signechambers1** [comment]
Waiting until Q4 so that all of the cellxgene Data Resource is behind SOMA API.

**Comment by dsadgat** [comment]
@signechambers1 is this still needed?

**Comment by signechambers1** [comment]
@dsadgat ill close for now - not a priority.

**Comment by signechambers1** [comment]
Reopening as a priority so GE matches census
