### ISSUE TITLE
copy cxg datasets from prod to dev

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2434]
## Need
All public Cxg datasets that are available in prod to be available in dev to test migrating to a new cxg format

## approach
- [x] update infra code to allow for reading the cellxgene-prod bucket from dev
- [x] run db script to grab dataset id/s3 uri for relevant datasets
- [x] copy datasets to an instance in dev
- [x] copy datasets to s3 dev bucket

**Comment by atolopko-czi** [comment]
@MDunitz Can this be closed?
