### ISSUE TITLE
All ingestion failures MUST be reported to #single-cell-ops

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2438]
Per @jahilton in [#single-cell-data-wrangling](https://czi-sci.slack.com/archives/C024HCSH9PT/p1651072467672089), curators were blocked when CZI failed to investigate and contact them per the message in the portal UX:

![Screen Shot 2022-04-27 at 12.10.54 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/ea568bba-d2b1-4b1a-8970-ad24dd0fc205)

Currently, only validation failures are reported to #single-cell-ops, but as noted by [Madison's comment ](https://docs.google.com/document/d/1NuqQuFvTOV4PQpi1RsbZhRDRPV6O4YV0vj-l5Tj2xGg/edit?disco=AAAATnreg2c) in the ingestion pipeline design document, ALL failures **MUST** be reported. Otherwise, _on calls_ will have no visibility into failures to investigate.

See also:
- https://docs.google.com/document/d/16xPhBQb1nOaAAMEfpr9sq4nz18DM0GuAIgUFQN6Zr20/edit?disco=AAAAcOrDTMM

**Comment by metakuni** [comment]
[Example](https://czi-sci.slack.com/archives/C024HCSH9PT/p1661534310715979) of ingestion failure that didn't get reported to #single-cell-ops:
```
jahilton
 Today at 10:18
@ebezzi
 
@kuni
 Dataset failing in https://cellxgene.cziscience.com/collections/a3d5316d-f953-46dd-95b8-a4a11e22e175
h5ad & rds generated appears successful, but no cxg
```

**Comment by metakuni** [comment]
Side note: We might want to remove 'and follow-up in an email' from the error message displayed by the FE since we don't actually do this.

cc: @brianraymor

**Comment by nayib-jose-gloria** [comment]
Currently, we set processing_status to SUCCESS so long as the h5ad is validated and uploaded successfully, even if then there are subsequent conversion failures for CXG or RDS. Do we want to maintain that status quo? It will change how I approach the solution.

**Comment by brianraymor** [comment]
@jahilton @danieljhegeman @Bento007 ...

For the curation API, I would prefer that `processing_status` returns FAILURE with a note that the problem must be addressed by CZI OPS. In general, conversions SHOULD NOT fail under ordinary circumstances. The validator should catch cases that would blow up conversions. Testing should catch any cases related to internal dependency updates.
