### ISSUE TITLE
If an author has a family name but not a given name, the author is ignored when processing the crossref response

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2445]
See [**single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1651160354482199) for details on the private collection and its DOI.

The **first** author has a family name but not a given name. This is correctly returned by crossref.

"author":[{"family":"Swechha","sequence":"first","affiliation":[]},{"given":"Dylan","family":"Mendonca","sequence":"additional","affiliation":[]},{"given":"Octavian","family":"Focsa","sequence":"additional","affiliation":[]},{"given":"J. Javier","family":"D\u00edaz-Mej\u00eda"
so Swecha should be the author.

But the portal starts with the **second** author, resulting in an incorrect summary citation:

"publisher_metadata": {
    "authors": [
      {
        "family": "Mendonca",
        "given": "Dylan"
      },
      {
        "family": "Focsa",
        "given": "Octavian"
      },
      {
        "family": "Díaz-Mejía",
        "given": "J. Javier"
      },
      {
        "family": "Cooper",
        "given": "Samuel"
      }
    ],

**Comment by MillenniumFalconMechanic** [comment]
| given | family | name | authors filter | summary citation |
| -- |  -- | -- | -- | -- |
| 0 | 0 | 0 | - | - | 
| 0 | 0 | 1 | -  | name et al. (year) Pub |
| 0 | 1 | 0 | -  | family et al. (year) Pub |
| 0 | 1 | 1 | -  | family et al. (year) Pub |
| 1 | 0 | 0 | - | - |
| 1 | 0 | 1 | - | name et al. (year) Pub |
| 1 | 1   0 | family, given | family et al. (year) Pub |
| 1 | 1   1 | family, given | family et al. (year) Pub |


`0` indicates no value, `1` indicates a value and `-` indicates not displayed/included

**Comment by brianraymor** [comment]
Tested the original error case on staging. LGTM.
