### ISSUE TITLE
Inconsistent hints for links that users can click

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2448]
@brianraymor commented on [Tue Apr 26 2022](https://github.com/chanzuckerberg/single-cell/issues/288)

### Context
See [**#single-cell-filter-by-metadata**](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1650563782430509) for related conversation. 

Between the views there are inconsistencies for how the Collection title (which is clickable) is presented to users. In addition, the Download and Explore buttons are blue, but the Collection title is not.

### Dataset view

1. The Download and Explore links are blue which is a hint.
2. The Collection title is in a smaller gray font. It is necessary for users to hover to turn the link blue.

![Screen Shot 2022-04-26 at 9.37.59 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/b8297f66-2906-4c8b-8b1b-cb507e05527e)

### Collections view

1. The Collection title is bolded and in a larger font than in the Dataset view. It is still necessary for users to hover to turn the link blue.

![Screen Shot 2022-04-26 at 9.38.55 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/a327590a-6405-43c8-8342-261dc514e613)

**Comment by MillenniumFalconMechanic** [comment]
Update collection title link on both collections and datasets to primary blue. Keep collection title bolded on collections.
