### ISSUE TITLE
scExpression bug when removing genes

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2500]
Steps to reproduce:

1. https://cellxgene.cziscience.com/scExpression
2. Organism: Homo sapiens
3. Tissues: Large intestine, Lymph node
4. Add genes: PALB2, PALMD, PALM, NIPAL2
5. Click on gene names to select
6. Hit delete on keyboard
7. Gene names still appear and cell types start to overlap

Desired result:
Gene names no longer show up and cell types remain spaced correctly.

[Screen Shot 2022-05-09 at 10.50.05 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/2aee5af3-502c-4c8a-b4a8-f90932f9cb99)

**Comment by signechambers1** [comment]
@tihuan P1, we don't need to do an emergency release for it but I would like to prioritize it in the next couple weeks before you go on leave.

**Comment by tihuan** [comment]
Got it thank you! I'll aim to get this fixed this week 👍

**Comment by signechambers1** [comment]
@tihuan I think [this bug](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2521) is also related, can you fix at the same time?

**Comment by tihuan** [comment]
Hmm yeah likely related. Will fix this week too. Thank you!

**Comment by tihuan** [comment]
PR out! https://github.com/chanzuckerberg/single-cell-data-portal/pull/2525
