### ISSUE TITLE
A user should be able to select either ontological cell type ordering

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#2501]
JSON structure:

```ts
{tissue_id : [{id = "", name = "", depth = 10}, ... ], ...} 
```

**Comment by tihuan** [comment]
@signechambers1 is it fair to say ontological cell type ordering is p1 or is it actually p0? Thank you!

**Comment by signechambers1** [comment]
P1 sounds good! Thanks @tihuan!

**Comment by tihuan** [comment]
Got it! Thanks so much, Signe! If we can get BE done this week, FE should be able to get it done the next week!

**Comment by tihuan** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/2600
