### ISSUE TITLE
A user should be able to select h-clustered genes ordering

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#2503]

**Comment by tihuan** [comment]
@signechambers1 I added P1 label to this instead of P0, because it doesn't seem as mission-critical as h-clustering by cell types? What do you think? Thank you!

**Comment by signechambers1** [comment]
Agreed, thanks @tihuan.

**Comment by tihuan** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/2531
