### ISSUE TITLE
Use AssumeRoleWithWebIdentity to generate AWS credentials

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2508]
To allow users to generate long lived AWS credentials that can be easily refresh we will utilize **AssumeRoleWithWebIdentity** to give the user access other S3.

1. setup auth0 as an identity provider in AWS
2. create IAM role that allows users restricted access to a specific bucket path in s3 that is prefixed with the user's identifier. The role can allow up to hours of access time and is attached to the AWS idenity provider.
3. update instruction on how to generate AWS credentials using AssumeRoleWithWebIdentity

**Comment by Bento007** [comment]
related PR https://github.com/chanzuckerberg/single-cell-infra/pull/593

**Comment by danieljhegeman** [comment]
@Bento007 what's going to be the process for the curator to obtain their openid, which they need to include in their s3 credential request?

**Comment by Bento007** [comment]
it's part of the response when they retrieve an access token.
