### ISSUE TITLE
bug: scExpr rendering

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#2521]
Choose Tissue=Intestine,Lung, Gene=MALAT1,Ethnicity="African American or Afro-Caribbean"

Tissues overwrite eachother on rendering:
![image.png](https://images.zenhubusercontent.com/610843107e13051155c43d3a/9f4c23cd-47ab-44bd-a7cb-63a3d1f951b2)

**Comment by tihuan** [comment]
PR out!

https://github.com/chanzuckerberg/single-cell-data-portal/pull/2525
