### ISSUE TITLE
feat(secrets): Auto refresh container secrets when they are updated in AWS 

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2534]
## Need
If a secret changes in AWS Secrets Manager(SM), the deployed containers will not pick up the changes until they restart. The containers should periodically query the secret for changes and update if needed. This will make it easier to keep the containers with the latest secret.

## Approach

**Describe the solution you'd like**
Update  [secret_config.py](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/corpora/common/utils/secret_config.py) to periodically update and check if the secret it is derived from has changed. If it has, it pulls in the new value.

**Describe alternatives you've considered**
Create a lambda to restart the associated containers whenever the secret is updated. This is not the ideal solution because:
- restarting the containers takes longer
- there is an n:m association between containers and secrets. So the lambda will need to know which containers to update per secret, which is significant maintenance and metal overhead.
- containers use multiple secrets and maybe restarted many times if multiple secrets are updated. This could result in significant downtime and a queue of container restart requests.

## Definition of Done
- The containers stay up to date with the lasted configuration information from AWS secrets manager.

**Comment by Bento007** [comment]
This may or may not be useful. @ebezzi expresses that his was an antipattern and should be avoided. I still think there is a benefit in keeping the docker code running the current secret and staying up to date in some way.

**Comment by atolopko-czi** [comment]
Do we have past issues where we needed a dynamic update to occur? I do agree that this is a dangerous practice since we don't have a formal process for updating config settings. I would vote to close this.
