### ISSUE TITLE
Enable MockCrossrefProvider for test environments

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2550]
See [#Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1652824031119679?thread_ts=1652463956.714899&cid=C02CF7MQPGV).

#### Approach
As per @ebezzi :

```
1. create a factory method for it
1. create MockCrossrefProvider() with an embedded validation logic
1. if deployment_stage == "test" return new MockCrossrefProvider()
```

**Comment by metakuni** [comment]
@ebezzi : Given the portal redesign, is this still relevant?

**Comment by metakuni** [comment]
Closing as per @ebezzi
