### ISSUE TITLE
feat(curation api): Allow super curators to upload local files to any revision in s3

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2552]
## Need
super curators need permission to upload a file to any revision to assist our curators.

## Approach
- Add an [auth0 rule](https://auth0.com/docs/customize/rules) to add additional claims to the JWT Access token. The tags must follow [add tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html)

- If the user is a super curator, then we need to add an AWS tag with the role `super-curator`. The decoded JWT should look something like this:
```
{
    "sub": "johndoe",
    "aud": "https://somedomain",
    "iss": "https://xyz.com",
    "https://aws.amazon.com/tags": {
        "principal_tags": {
            "Roles": ["super-curator"],
        }
    }
}
```

- Modify the AWS IAM submission role policy to grant a web id token with the claim "https://aws.amazon.com/tags:PrincipalTags:Role" of super-curator, to write to the bucket path `super_curator/*` of the submission bucket.
```
        {
            "Sid": "SuperSubmitDataset",
            "Effect": "Allow",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::cellxgene-dataset-submissions-dev/super/*",
            "Condition": {
                "ForAnyValue:StringEquals": {
                    "aws:PrincipalTag/Roles": [
                        "super-curator"
                    ]
                }
            }
        }
```
- Update the data-submission lambda to allow files written to the `super_curator` bucket path to process the dataset.
- Update data-submission lambda tests to verify a super-curator can upload a dataset to a revision they do not own.

## Definition of Done
- a super curator can write to a revision they do not own.

connect to https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2158

**Comment by danieljhegeman** [comment]
Additional ideas:
1. use nested roles to prevent the role with s3 write access from being called externally OR restrict which roles can assume the current role; by forcing usage of the endpoint, we can then perform logic on their access token to determine whether or not the user is a super curator
OR
2. Use lambda to call Auth0 management endpoint and check if user (derived from s3 key prefix) is a super curator.

It should be noted that Trent's current (original) proposed solution has benefits in that it prepares us to better use nuances of Auth0 to scope permissions for AWS access. This would be good for other uses/applications later. But the above two solutions are likely going to be easier to implement.

cc @Bento007 for accuracy

**Comment by danieljhegeman** [comment]
Also, to be precise: super curators should be able to write to _all_ private Collections and private revisions, including private unpublished Collections which they did not create, correct? cc @brianraymor 

None of the technical details above (related to the logistics of performing local uploads) seem to differentiate between private unpublished and private revisions anyways.

**Comment by brianraymor** [comment]
> Also, to be precise: super curators should be able to write to all private Collections and private revisions, including private unpublished Collections which they did not create, correct?

Correct. Although generally, Stanford only revises public collections. They review private collections/revisions prior to publication.

**Comment by Bento007** [comment]
related work:

https://github.com/chanzuckerberg/single-cell-infra/pull/621
https://github.com/chanzuckerberg/single-cell-data-portal/pull/2663

**Comment by danieljhegeman** [comment]
Confirmed working in dev.
