### ISSUE TITLE
Add regex validation/interpretation of s3 write key to curator notebooks

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2573]
We can add some convenience code to the curator notebooks that will inform them of whether the upload is going to be treated as using a Dataset id or as a curator tag. Use [the regex from the lambda](https://github.com/chanzuckerberg/single-cell-data-portal/blob/994f29ab694bca43783647c8b9d7c7b36e43cc9d/backend/corpora/dataset_submissions/app.py#L16).

- Will be treated as dataset id if uuid regex matches (don't forget to flank the regex with `^` and `$`), else treated as curator tag

**Comment by Bento007** [comment]
We should have them use this endpoint instead https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2659 to avoid duplicating code logic.
