### ISSUE TITLE
replace references to corpora-data-portal

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2590]
## Need
- consistent naming of the single-cell-data-repo

## Approach
- replace references to corpora-data-portal with single-cell-data-portal

**Comment by MDunitz** [comment]
604 references to corpora in single-cell-infra
847 reference in single-cell-data-portal

**Comment by atolopko-czi** [comment]
too large of an issue to tackle at once; will have to work towards this progressively with other work.
