### ISSUE TITLE
Filter by suspension type

### ISSUE THREAD

**Issue by LuckyMD** [chanzuckerberg/single-cell-data-portal#2622]
See [suspension type](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#suspension_type) in the 3.0.0 schema. 

1. The suspension type filter MUST be available as both a collection and dataset filter.
2. The plausible event MUST be added.

@ainfeld proposed:

```

event name: FILTER_SELECT_SUSPENSION_TYPE
payload: {suspension_type: <fill in value>}

```

---

Original request:

### Need
It would be incredibly useful to be able to sort also by cells vs nuclei in the data portal. I've been looking for lung data to use as example query data to map onto the HLCA, and the only human, 10X data from the lung that only consists of 1 dataset is from lungMap, and that's all single-nucleus data, which might not be the best test case.

Just to add a second feature that would be useful (but harder to do I'm sure), would be the ability to load only the lung data from datasets with multiple tissues.

### Approach

**Describe the solution you'd like**
An additional filter option for cell vs nucleus

**Describe alternatives you've considered**
The alternative would be go to through all dataset descriptions and then come back to download the data that fits the bill.

### Definition of Done
Some automatic filter for sc vs sn to immediately gauge relevant datasets.

---

**Comment by jahilton** [comment]
First step to a filter is a required metadata field...
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/227

**Comment by LuckyMD** [comment]
I'm slowly learning how zenhub works ^^.
