### ISSUE TITLE
Consolidate uuid and curator_tag under same parameter name for client for Curation API

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2631]
When interacting with the Data Portal via the Curation API and needing to specify a dataset, the curator client should only have to consider a single `identifier` (or similarly-named) field, regardless of whether they use a dataset uuid or a curator_tag to identify the dataset in question.

See mention: https://github.com/chanzuckerberg/single-cell-data-portal/pull/2566/files#r877966613

When trying to delete the dataset `01234567-89ab-cdef-0123-456789abcdef` in collection `fedcba98-7654-3210-fedc-ba9876543210` which also has tag `arbitrary-tag`, either of the following should be allowable:

`DELETE` to `/v1/collections/fedcba98-7654-3210-fedc-ba9876543210/datasets?identifier=fedcba98-7654-3210-fedc-ba9876543210`

`DELETE` to `/v1/collections/fedcba98-7654-3210-fedc-ba9876543210/datasets?identifier=arbitrary-tag`

**Comment by Bento007** [comment]
Only add this functionality if we get push back from curators about the existing API.

**Comment by brianraymor** [comment]
Based on triage with @Bento007 and @jahilton - closing as not needed. We want to keep these separated because Jason does not plan to use the curator tag which may be deprecated in the future.
