### ISSUE TITLE
These collections may have lost links 

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2632]
The following collections may have lost link data as a result of [a couple bugs](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2580). The curator/owner should be contacted.

https://cellxgene.cziscience.com/collections/c8565c6a-01a1-435b-a549-f11b452a83a8
https://cellxgene.cziscience.com/collections/a238e9fa-2bdf-41df-8522-69046f99baff

**Comment by brianraymor** [comment]
I had an older metadata snapshot that included https://cellxgene.cziscience.com/collections/c8565c6a-01a1-435b-a549-f11b452a83a8

   "links": [
      {
        "link_name": "",
        "link_type": "DATA_SOURCE",
        "link_url": "https://kriegsteinlab.ucsf.edu/datasets/arealization"
      },
      {
        "link_name": "",
        "link_type": "DOI",
        "link_url": "https://doi.org/10.1038/s41586-021-03910-8"
      },
      {
        "link_name": "",
        "link_type": "LAB_WEBSITE",
        "link_url": "https://kriegsteinlab.ucsf.edu/"
      },
      {
        "link_name": "",
        "link_type": "RAW_DATA",
        "link_url": "https://data.nemoarchive.org/biccn/grant/u01_devhu/kriegstein/transcriptome/scell/10x_v2/human/processed/counts/"
      }

**Comment by jahilton** [comment]
The updates were stuck in a Revision that I Published this week. All good now.

**Comment by brianraymor** [comment]
Thank you @jahilton. Closing.
