### ISSUE TITLE
Curators can filter Collections by curator and status

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-data-portal#2638]
## Need
**Is your feature request related to a problem? Please describe.**
As lead curators, we need to be able to easily identify private & revision Collections, and see who the curator of those Collections is. This will help us better understand in progress submissions, anticipate upcoming reviews, and avoid multiple curators working on the same dataset.

## Approach

**Describe the solution you'd like**
I would like to visit https://cellxgene.cziscience.com/my-collections and have a new column that displays "Curator" for each collection. I would like to filter for any value in the "Curator" column and a separate filter for "Private" collections, collections with "Revision pending", and "Public" collections (which would include those with revisions pending).

**Note:** There was agreement to deprecate _My Collections_ in favor of adding additional curation specific filters to the Collection view for authorized curators. See [**single-cell-discover-ux**](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1677015227541529). 

**Describe alternatives you've considered**
A solution via the an API is insufficient because the immediate next step after filtering for Collections is to investigate by viewing the Collection pages. The API would not offer this direct/immediate link from the filter results into the Collection pages like the UI.

---

### UX Design
[Lead Curator](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4626%3A43440&t=sY2woWOqDWPxIMDc-1)
[Non-Lead Curator](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4626%3A43446&t=sY2woWOqDWPxIMDc-1)

Design Note: Please update all Tag styles (color, font size, font weight, padding) to match Figma

### Technical Design

[Design document](https://docs.google.com/document/d/1oRcDxBTK9QjTvePX7bl7T2sXjA1WqBVKM3UuO3S9aw8/edit#heading=h.1n6qxl7571q)

**Comment by danieljhegeman** [comment]
>A solution via the an API is insufficient because the immediate next step after filtering for Collections is to investigate by viewing the Collection pages. The API would not offer this direct/immediate link from the filter results into the Collection pages like the UI.

@jahilton because UI changes for this sort of thing require extra work (front end), might I suggest a scenario where you hit the API for this information, and we return formatted Collection urls for each curator? At least in the python notebook setting, when the API response is printed out, these links are clickable, so you would be able to navigate to them pretty much just as easily. The current version of the `create_collection.ipynb` python notebook in the curation repo does exactly this when you create a new Collection.

Let me know if that would be sufficient.

**Comment by danieljhegeman** [comment]
(...though I would want to hear an estimate from FE folks about the engineering costs for doing this in the UX. If it's only a couple days for a single engineer, perhaps it is worth it.)


>I would like to filter for any value in the "Curator" column and a separate filter for "Private" collections, collections with "Revision pending", and "Public" collections (which would include those with revisions pending).

I would like to note that the extra filtering options here are, for our purposes, probably better handled on the lead curator's end (i.e., by having a couple lines of their own code which performs the filtering on an API response). Easy to customize, change, don't have to wait on us to add new filtering capabilities. We just have to provide a way to click into the filtered Collection results, and with clickable links in notebooks, Jason would have that.

**Comment by jahilton** [comment]
The API would, of course, be better than nothing, but still not as desirable as the UI.
Curious to hear @BAevermann 's thoughts as I am guessing he'd see a lot of utility in this feature, as well.

**Comment by BAevermann** [comment]
I do second Jason's preference to handle this in the UI, but I fully understand that the front end work would significantly increase the effort required. As a first pass solution, I'd be ok using the API. Thanks!

**Comment by danieljhegeman** [comment]
I'm actually on Team UI now too, because providing the ability for the curator to query for specific curators via the Curator API is nontrivial. Much easier to provide the curator those entities in the UI and allow them to select manually.

**Comment by BAevermann** [comment]
Can you explain "easier to provide the curator those entities in the UI and allow them to select manually" a bit more? This feature, to query for curator names, is for admin/management to find and track datasets submitted by external funded teams and potentially by program projects (Seed Networks, etc..). I might be over interpreting the above text, but I would anticipate this filter being only available to those with admin credentials. So the statement "the ability for the curator to query for specific curators" should read "the ability for an admin to query for specific curators". Just making sure we are aligned. (@jahilton does that track with your expectations?). But I am glad this moving back toward a UI implementation!

**Comment by danieljhegeman** [comment]
> Can you explain "easier to provide the curator those entities in the UI and allow them to select manually" a bit more? This feature, to query for curator names, is for admin/management to find and track datasets submitted by external funded teams and potentially by program projects (Seed Networks, etc..). I might be over interpreting the above text, but I would anticipate this filter being only available to those with admin credentials. So the statement "the ability for the curator to query for specific curators" should read "the ability for an admin to query for specific curators". Just making sure we are aligned. (@jahilton does that track with your expectations?). But I am glad this moving back toward a UI implementation!

@BAevermann yes, I should have said "easier to provide the [super curator / admin] those entities in the UI..."

It will not be available to regular curators. If it needs to be a specific subset of super curators (not _all_ super curators), then we can generate a new "admin" (or similar) role, and make it available only for those individuals. 👍 

Just for posterity, my main point in that original comment is that it's going to be easier, technically, for us to _provide_ a list of curators that can be filtered through (for the super curators / admins to look through) on the UI than it would be for us to take in a query string via the API and decide which curators match that query string on the backend, which would involve implementing some sort of search which we don't want to have to do.

**Comment by brianraymor** [comment]
> If it needs to be a specific subset of super curators (not all super curators), then we can generate a new "admin" (or similar) role, and make it available only for those individuals.

I think that "admin/management" introduced confusion. The _filter-by-curator_ feature would be limited to users where CZI assigned  _super curator_ authorization. 

The _filter-by-status_ feature **might** be useful for other curators. I'd need to review current collection count by curator to assess. My assumption is that Jenny (as a super curator) has most of the collections because we just reassigned all the collections from retired curators to her.
