### ISSUE TITLE
Redesign UX for count filters

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2639]
@MaximilianLombardo shared a design approach from the [Cancer Single-Cell Expression Map](https://ngdc.cncb.ac.cn/cancerscem/browse) for modeling counts such as `cell count`. 

[Figma](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4096%3A36705)

![Screen Shot 2022-06-03 at 5.36.20 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/2745f45a-0092-475e-b25b-58b02a051388)

**Comment by brianraymor** [comment]
@jahilton shared on [**filter-by-metadata**](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1662763985127329):

The Cell Count filter isn't currently offering much resolution in the range where the majority of Datasets live (0 - 200k). Move it just a little and I'm already down to <10 out of 500.

Idea: Make the majority of the length 0 - 1 million (or 500k?). Then just have tick marks to 'jump' to 2 million, 3 million, 4 million, 5 million
So you wouldn't actually be able to select any number above 1 million except the millions

```

|--------------------------------|---|---|---|---|
0                                1M  2M  3M  4M  5M

```

**Comment by jahilton** [comment]
I'm also a fan of displaying a histogram of datasets on the range like [HuBMAP](https://portal.hubmapconsortium.org/search?entity_type[0]=Sample
![Screen Shot 2022-09-12 at 11.40.53 AM.png](https://images.zenhubusercontent.com/5cb8e6d2f3da61486280e8ce/065a5a69-c5c4-4310-8ccd-0c35823cd845))
