### ISSUE TITLE
Curators can start a revision from the Collection page

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-data-portal#2647]
## Need
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am looking at a Collection, identify an update to make in the Title, Description, Links or Contacts (non-dataset information). To make the update, I need to copy the title, go to My Collections, then search for the title, then Start Revision.

## Approach

**Describe the solution you'd like**
I would like to be able to click a button on the Collection page to Start Revision. I could be redirected to the new Revision page, or a new tab could open to the Revision page - either would be OK.

## Design

[Start revision from Collection Detail page](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4461%3A39456&t=gVeFYp4JnUWIrvke-1)
[Public collection, pending revision banner](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4531%3A39402&t=gVeFYp4JnUWIrvke-1)
[Private revision, public collection banner](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4532%3A39739&t=gVeFYp4JnUWIrvke-1)

**Comment by brianraymor** [comment]
@metakuni @NoopDog - I'm assuming that this epic is complete, but the on-call failed to close its _Ready for Prod_ issues?
