### ISSUE TITLE
Add endpoint to verify the s3 upload name.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2659]
the goal is to save a user from wasting their time uploading a dataset that will be rejected. The endpoint will look at the path the user is uploading to and check if they have permission do upload there, and if a new dataset will be created or upated.

**Comment by danieljhegeman** [comment]
>The endpoint will look at the path the user is uploading to and check if they have permission do upload there

This is handled by retrieving the `UploadKeyPrefix` from the s3-upload-credentials response.

> and if a new dataset will be created or upated.

consider: this could be done with some pretty simple client-side logic using `GET /collections/{collection_uuid}`.

**Comment by danieljhegeman** [comment]
I suppose this endpoint would provide the logic for distinguishing between uuid and tag, which would be nice. 

Either way, whether we put this logic on the client side or make an endpoint for it, it points to the utility of modular, tested client-side code (client side code still needed to hit this potential endpoint and then interpret / log the results) for this API.

I'm leaning toward (eventually) taking the notebook modules and distributing them via pypi. I think that would be more wieldy than require that curators import from src in the curation repo. Also better than a CLI, which would be a lot more work as well. Thoughts, @Bento007 ?
