### ISSUE TITLE
Improve scExpression Getting Started experience

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2675]
First time users are having trouble getting to a dot plot. Based on user research and our brainstorm we'd like to make the following changes:

- [x] Left and right side bars should be collapsed by default
- [x] Add Tissue and Add Gene buttons should be larger
- [x] Add Tissue and Add Gene labels should be the correct font and size 
- [x] Remove all text and headings for Step 1, Step 2, Step 3
- [x] Replace text under Getting Started with "Use the Add Tissue and Add Gene buttons to find where genes are expressed, powered by data from the [Cellxgene Data Portal](https://cellxgene.cziscience.com/collections)."

**Comment by atarashansky** [comment]
Addressed in PR #2683, further discussion can take place there.
