### ISSUE TITLE
I don't think `project_link.link_url` should be nullable

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2690]
It seems odd that `link_url` would be nullable for links. I might say the same for `link_type`, which is also currently nullable, but that one is less certain.

**Comment by atolopko-czi** [comment]
@brianraymor This is a product decision, so comment if you want to keep this. Otherwise will close, since we're trying to clean up aspirational stories.

**Comment by brianraymor** [comment]
Based on the UX implementation, the following should be enforced:
1. The link_type is required.
2. The link_url is required.
3. The link_name is optional.

**Comment by danieljhegeman** [comment]
@brianraymor I will make the change
