### ISSUE TITLE
scExpression Reduce padding between cell type names and dot plot

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2694]
1. Go to https://cellxgene.cziscience.com/scExpression
2. Add Lymph node as a tissue
3. Add some genes

Notice the cell type names are preemptively cut off - there is more room for them to show before hitting the dot plot. this is not true for all cell types (CD141 positive myeloid dendritic cell shows up correctly but others do not - see screenshots)

![Screen Shot 2022-06-13 at 12.34.20 PM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/7ca566ad-d579-417e-991c-e153ea0283d8)
![Screen Shot 2022-06-13 at 12.36.35 PM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/51f13ce5-7820-4f53-9d48-de55aa25fbdc)

**Comment by ashin-czi** [comment]
Just curious while I'm working on this, would it be preferred if the whole cell name was displayed?

**Comment by signechambers1** [comment]
@ashin-czi i think we want to maximize dot plot space while holding enough room for the cell type name - some of the cell type names are very long so we haven't found it feasible to display the entire cell type name in all circumstances.

**Comment by ashin-czi** [comment]
Hi all, I've made some changes but wanted to do a quick run by you guys before I commit anything. Here are some examples:
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/e0a687d2-5853-402b-b0c6-5b85d16fb509)
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/96ae55ff-c4d4-4185-bc85-96df27efb3ff)

You can see that the text cut off is much more uniform now. I've played around with some tissues and it seems to look good, but wanted to see if this was along the lines of what was being asked for this ticket.

**Comment by atarashansky** [comment]
This looks great! @signechambers1 can correct me if I'm wrong, but this seems to address the problem. Feel free to go ahead and open a PR.

**Comment by signechambers1** [comment]
looks great to me! thanks andrew!
