### ISSUE TITLE
scExpression add cell count to dot plot

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2696]
We got user feedback from @BAevermann users of scExpression need to know when there are only a few cells for a given cell type,  in order to interpret the results correctly and determine how strong of a signal the dot plot is reporting. 

We discussed many different implementations (removing cell types with a certain number of cells, creating visual indicators, etc) and landed on surfacing cell counts to the user because we thought this was the most informative and flexible option. It also provides the user with feedback when they select a filter that reduces the number of cells powering the visualization. This ticket covers the work to add cell counts to the dot plot. These cell counts should change if the user updates the filters.

If the cell count is greater than 10,000, UI should show ">10K."

[Figma](https://www.figma.com/file/htICFl7zihfs1z9eIYVwzw/Gene-Search?node-id=3757%3A640373)

**Comment by atarashansky** [comment]
In the Figma, cell types with zero expression for a particular gene have small dots and their number of cells are reported.

In the current implementation, cell types with zero expression display no data and so the number of cells within them are not passed to the frontend.

There are two possibilities:
1) Only display the # of cells for cell types with non-zero expression
2) Make scExpression report information about cell types with zero expression.

What are your thoughts @signechambers1 ?

**Comment by atarashansky** [comment]
I'm sorry, @signechambers1, I am not sure what conversation you are referring to!
