### ISSUE TITLE
feat: Update scex batch job to accept validate_cubes arg

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2704]
## Need
As a developer sometimes I need to debug the scex batch job. I'd like to be able to trigger the batch job with an arg validate_cubes -- when set to false it will skip the validation step and upload the cube/other artifacts to s3 without updating the active snapshot id. This will allow a developer to access a cube for debugging purposes.

## Approach
- update batch def to use container override to pass in an arg when triggering from the command line
https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerOverrides.html
```
"ContainerOverrides": {
          "Environment": [
            {
              "Name": "DATASET_ID",
              "Value.$": "$.dataset_uuid"
            },
            {
              "Name": "STEP_NAME",
              "Value": "cxg_remaster"
            }
          ]
        }
```

**Comment by MDunitz** [comment]
note: could also just update to auto write failures to dev when sending a slack alert of failure

**Comment by signechambers1** [comment]
@atolopko-czi to assess priority

**Comment by atolopko-czi** [comment]
This is a "nice to have" troubleshooting feature, so I think it can be kept in the backlog until a developer actually needs to debug an erroneously generated snapshot, at which time they can implement this first.

**Comment by signechambers1** [comment]
Thanks @atolopko-czi. Removing this from the Q3 planned work and we can pick up when something goes wrong with the snapshot. fyi @maniarathi
