### ISSUE TITLE
Update RDS engine version

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2763]
## Need 
To update from 10.14 - > 10.20 based on this conversation

https://czi-sci.slack.com/archives/C023Q1APASK/p1655830775328629

## DoD
- [x] RDS in all environments (dev, staging, prod) are updated to 10.20
- [ ] Ensure that Docker images used for tests are using the same version
- [x] Verify that applications using RDS are functional after the upgrade
- [x] Document the RDS upgrade procedures in our [on-call guide](https://docs.google.com/document/d/1n5cngEIz-Lqk9737zz3makXGTMrEKT5kN4lsofXPRso/edit#heading=h.88nz21uu8s19) or adjacent doc
- [ ] Quick overview of the process is shared at the biweekly engineering meeting for visibility

**Comment by metakuni** [comment]
From [Eduardo's post](https://czi-sci.slack.com/archives/C023Q1APASK/p1655830775328629):
```
* For PostgreSQL Minor Versions 10.13, 10.14 and 10.16, the recommended minimum minor version is 10.17
```
and [AWS console recommends](https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#recommendations:):
```
Your DB cluster is running aurora-postgresql version 10.14. Upgrade to version 10.20.
```
so we might as well upgrade to 10.20 or whatever the most recent 10.x version is when we address this upgrade.

**Comment by metakuni** [comment]
Also, deadline for upgrading RDS is July 15, 2022!

**Comment by metakuni** [comment]
Moved to cool down since we need to get this upgrade done during Q2 cool down
