### ISSUE TITLE
change `UploadKeyPrefix` to use `/super/` when `GET ../s3-upload-credentials` endpoint is hit

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2777]
We want to make things as smooth as possible for curators. The credentials endpoint should determine whether or not the access_token used has the super-curator role and adjust the `UploadKeyPrefix` attribute in its response accordingly to use `<bucket>/super/<collection_uuid>/` instead of `<bucket>/<user_id>/<collection_uuid/`.

Also, make a minor cosmetic change for semantic accuracy: the `upload_key_prefix` variable in the `post_s3_credentials` handler should include the trailing `/` from the outset (an [AWS s3 prefix](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html) _includes_ the trailing slash) rather than tacking it on when the `UploadKeyPrefix` attribute is set on the response object.

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria have you tested this in prod yet by chance?

**Comment by danieljhegeman** [comment]
I just tested it in prod and I got `/<oauth username>/` in the prefix, not `/super/`

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman this is because of the combo of RBAC being added + the scopes bug addressed by https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2928

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria Make sense! Thanks @nayib-jose-gloria
