### ISSUE TITLE
is it `collection_uuid` or `collection_id`??

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2778]
At present we return a `collection_uuid` when we create a new collection.

But we return a `revision_id` when we create a revision.

We reference the `uuid` part frequently in Curation documentation and it is a useful reminder (to users) that a uuid is a specific format.

But our backend entities refer to things like `id` and `collection_id` (for developers).

Are we fine with labeling all instances of id exposure to users as `uuid`? Do we currently expose them as `id` anywhere? Do we care?

**Comment by brianraymor** [comment]
> Are we fine with labeling all instances of id exposure to users as uuid? 

I would recommend that the API names are consistent. @atolopko-czi - do you have guidance for naming conventions?

**Comment by danieljhegeman** [comment]
cc @Bento007 @metakuni for vis

I think my short term solution is to have all client-exposed instances be `uuid`. So all API responses should use `uuid`.

I'm less concerned about making sure our variable names on the backend are consistent. 😅

**Comment by atolopko-czi** [comment]
> > Are we fine with labeling all instances of id exposure to users as uuid?
> 
> I would recommend that the API names are consistent. @atolopko-czi - do you have guidance for naming conventions?

My $0.02 is that we should use `id` consistently throughout, in both API JSON property names and in backend code.
