### ISSUE TITLE
feat(scExpression): secondary filters should enable preemptive filtering of the data (BE ONLY)

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#2785]
## Need
I ran into an issue where I wanted to use scExpression for a particular dataset, but I didn't know what tissues belonged to that data ahead of time. I had to select all the tissues, filter for the data, and then remove tissues with no data displayed (not knowing if they weren't displaying data because the tissues don't exist in the filtered dataset or simply because the genes were not expressed in them).

## Proposal
I'd like the filtering to be preemptive. 

1) The filter buttons should open a searchable dropdown menu of all available metadata in the corpus for each dimension/attribute.
2) Selecting a filtering option should remove all tissues that are not included in the selected filter

**Comment by seve** [comment]
@atarashansky To update ticket based off of previous work

**Comment by seve** [comment]
Alec marked as possibility to parallelize with validation work

**Comment by seve** [comment]
Needs priority revisit
