### ISSUE TITLE
Proposals: improve handling of `dataset_uuid` and `curator_tag` in API interactions

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2801]
I propose a few pieces of "tidying up" work with regard to the way that we wrangle the curator_tag and/or dataset_uuid in the local dataset upload case as well as other API interactions. **These are discussion items and do not represent approved, mandated units of work yet.**

-  `DELETE /v1/collections/{collection_uuid}/datasets` should instead use a path variable `identifier` at the end like `/v1/collections/{collection_uuid}/datasets/{identifier}`, rather than asking for a dataset_uuid or curator_tag passed in as a query parameter. It is more semantically logical. The identifier identifies a singular resource, and since we do not allow curator_tags to take the form of a uuid, we can use the logic we already have in the dataset submission lambda to distinguish between the two. Plug-and-play! This should be extended to other applicable endpoints as well.

- All endpoints should be configured to handle `01234567-89ab-cdef-0123-456789abcdef.h5ad` as the communication of a dataset uuid. There could easily end up being confusion given that we are, at present, requiring uploads to include a `.h5ad` suffix, whether for a dataset_uuid or a curator_tag, but then when the curator uses one of those as an identifier for a different API endpoint (such as the `DELETE` mentioned above), then suddenly the `.h5ad` is dropped from the uuid but _not_ from the tag. This is a bizarre behavior that we should try to avoid from the client standpoint.

**Comment by danieljhegeman** [comment]
In general I'd like to see us move toward "identifier" as a term that could mean either a uuid or a tag. We've begun using this terminology in variable naming where appropriate.

**Comment by brianraymor** [comment]
Per triage with @jahilton and @Bento007 closing as not required.
