### ISSUE TITLE
Endpoint for updating Collection metadata should be PATCH instead of PUT

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2806]
At present, the HTTP method for updating Collection metadata is `PUT`. It should be changed to `PATCH`.

https://github.com/chanzuckerberg/single-cell-data-portal/blob/1ae80bfe1c164710ded1d610b9e932d4a1dc5cfd/backend/config/curation-api.yml#L146

PUT - full representation of resource (or sufficient instructions to create full representation of resource) is sent to server and resource is created if it does not exist and replaced if it does. Idempotent, permits creation of resource.

PATCH - partial, though possibly full, representation of resource is sent to server and existing resource has the included edits applied. It does _not_ permit the creation of a resource. Not required to be idempotent.

**Comment by Bento007** [comment]
Include the links to where you found the definition of PATCH and PUT for future reference.
