### ISSUE TITLE
Should a public collection include a reference to its revision for authorized users?

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2810]
The private revisions of public collections will include a `revision_of` attribute that is the UUID of their public collection so a curator can map from a revision to the original collection. And perhaps this should be named `revision_of_collection_id`. 

Should there be a symmetrical attribute in the public collection such as `revised_in_collection_id` that is the UUID of the private revision?

There is a security issue because this attribute MUST only be returned in responses to authorized users which is a different model from how public collections will be accessed.

Another proposal from @jahilton is:
> boolean if a revision is in progress or not?

**Comment by danieljhegeman** [comment]
I plan on adding a 'view' to the db, constructed by the equivalent of 
```create view project_revising_in as select * from project as p left join (select id as revising_in, revision_of as id from project) t using(id);```

**Comment by danieljhegeman** [comment]
I rebased my code changes on [3019](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3019)

**Comment by brianraymor** [comment]
@Bento007 @danieljhegeman - let's discuss [https://github.com/chanzuckerberg/single-cell-data-portal/pull/3045#discussion_r941701575] here.

Per the top-level summary comment:

**There are still security concerns. revising_in MUST only be present in the response if the curator is authorized to access the revision. Otherwise, the portal would be leaking the bearer token.**

**Comment by Bento007** [comment]
I don’t think we need both the None response and the Not authorized response. One or the other would be sufficient. We should keep the None response and remove the Not Authorized response and eliminated the need for an extra code path.

**Comment by brianraymor** [comment]
Clarifying:

So - instead of filtering out the `revisioning_in` if I'm not authored to access the revision in question, then value is set to "None"? 

Example:

Brian creates a revision.
Brian is returned the UUID.

Jason is a super curator.
Jason is returned the UUID because he's authorized.

Trent is a curator or consumer.
Trent is returned "None" because he's not authorized.

**Comment by Bento007** [comment]
@brianraymor yes. That is how I see it.

**Comment by brianraymor** [comment]
I have no objections to this alternative. It matches the _house style_. It will still need careful testing similar to an implementation that would _filter out_ the field for unauthorized users to ensure that information is not leaking.

**Comment by danieljhegeman** [comment]
@Bento007 @brianraymor that is not quite how the current code works.

At present, here is the scheme:

- A `revising_in` value of `NOT_AUTHORIZED` is returned for all public Collections _except_ for those which the curator is authorized, in which case the value is `None` if the public Collection does not have an ongoing revision, or `<revision_id>` if the public Collection _does_ have an ongoing revision.
- A `revising_in` value of `None` is returned for all private Collections.

**Comment by danieljhegeman** [comment]
>filter out the field for unauthorized users to ensure that information is not leaking.

Correct; this is happening.

**Comment by danieljhegeman** [comment]
if you prefer, we can take the scheme I've laid out above and simply substitute `None` for `NOT_AUTHORIZED` in all cases, though that results in some signal loss; the curator has to _know_ that they are authorized for a given Collection before they can interpret `None` to mean that there is no revision open for that Collection. But perhaps that's fine? I suppose the benefit of making that substitution would be a programmatic one: a user can now test for presence/absence of `revising_in` value without having to ask if it's a str or an int before proceeding to use it to try to fetch the revision Collection...

**Comment by brianraymor** [comment]
I approve the use of "None" rather than "NOT_AUTHORIZED". It's closer to the spirit of _filtered out_ and matches the _house style_.

**Comment by danieljhegeman** [comment]
Can you elaborate, for my own edification, on where the 'house style' is coming from for this?

**Comment by brianraymor** [comment]
@maniarathi - this has not been tested.

**Comment by brianraymor** [comment]
Tested curator role - revision_of and revising_in are correctly returned.
