### ISSUE TITLE
bug: cube validation failing in prod

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#2812]
## Need
- update 7/8 failing due to low rankit value for ACTB. Working with @pablo-gar to determine if its a change in the data or an issue with the underlying code

**Comment by MDunitz** [comment]
link to https://github.com/chanzuckerberg/single-cell-data-portal/pull/2845

**Comment by danieljhegeman** [comment]
@MDunitz closing
