### ISSUE TITLE
Add Curator API to Cellxgene Architecture document

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2825]
All relevant details about the architecture and intended usage patterns of the Curator API should be added to [this document](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.7wimlorgnmka) so that others may find technical information about the API more easily.

**Comment by atolopko-czi** [comment]
Dan, can you enumerate what additional documentation should be added for this story?

The only things I can think of are:
* Add mention of the upload S3 bucket to the doc and to the [Data Flow](https://lucid.app/lucidchart/9d08a67d-1baf-4645-beb7-0eb1bc96e6af/edit?beaconFlowId=3ca436ce0ba79817&name=docs&referringApp=google+docs&callback=close&callback_type=back&invitationId=inv_292f3561-6044-40d2-9c1d-e6f33648d19d&page=0_0#) diagram.
* Any changes that may have been made to the [Dataset Lifecycle](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.ilj0ko1g3jeq), though I'm not sure there any changes.

**Comment by atolopko-czi** [comment]
@danieljhegeman Diagram is up-to-date, so you could just add a bullet [here](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.415jrraq75id) to describe how the curation api invokes the pipeline (s3 event triggers lamba, right?), and that should be enough to close story.

**Comment by brianraymor** [comment]
@atolopko-czi - do you have a home for orphaned Dev _tidying and housekeeping_ issues or should we just close this as a lost cause?

**Comment by atolopko-czi** [comment]
> @atolopko-czi - do you have a home for orphaned Dev _tidying and housekeeping_ issues or should we just close this as a lost cause?

Keep it as is with `tech` label intact, as this identifies issues we'll pick off as "on-call" work.

@danieljhegeman Can you suggest some bullet points to elaborate on `All relevant details about the architecture and intended usage patterns`? I don't think we need to further document anything that is already described in the OpenAPI spec.

**Comment by ebezzi** [comment]
The document has been updated with redesign changes. Closing.
