### ISSUE TITLE
Review & validate all analytics metrics

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#2828]
* consider whether we can implement some simple validation plan (e.g. in staging)
* minimally, review metrics computation code for _correctness_
* can we add any unit tests for additional confidence?

**Comment by atolopko-czi** [comment]
@ambrosejcarr Worth carving out time for this? I'm apt to close it and revist if/when analytics system undergoes larger changes.

**Comment by ambrosejcarr** [comment]
let's close it for now and proactively validate future changes to analytics, as you suggest.
