### ISSUE TITLE
Analytics (new): Track interaction with the new landing page 

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-data-portal#2831]
### Overview
**Tool**: `Data portal`
- Feature (Optional): `New homepage`

**Description**: `Creating a new landing page for cellxgene and we want to understand how visitors are interacting with the page`

### New events to add 
Below, section headers denote parts of the page, and bulleted lists denote the items for which instrumentation should be added.

**P1:**
Quickly find the single-cell data you need
- Browse data collections `BROWSE_COLLECTIONS_CLICKED`, {`button`: `browse data collections`}

Explore gene expression across tissues and cell types
- See how it works `WMG_CLICKED`

Execute on-demand interactive analyses of single-cell datasets
- Explore a multi-tissue atlas `DATASET_EXPLORE_CLICKED`, {`dataset_name`: `<fill in>`}
- Explore the studies `BROWSE_COLLECTIONS_CLICKED`, {`button`: `explore the studies`}
- Browse tutorials `BROWSE_TUTORIALS_CLICKED`

Download and integrate with zero wrangling
- Browse datasets for download  `BROWSE_COLLECTIONS_CLICKED`, {`button`: `browse datasets for download`} (until the path is changed to take users to the datasets list page)

**P2:**
Nav Bar
- Datasets `DATASETS_CLICK_NAV`
- Collections `COLLECTIONS_CLICK_NAV`
- scExpression (already instrumented)
- Help & Documentation `BROWSE_DOCUMENTATION_CLICKED`

Secondary Nav Bar
- Find single-cell data `HOMEPAGE_LEARN_FIND_SINGLE_CELL_DATA_CLICKED`
- Explore gene expression `HOMEPAGE_LEARN_EXPLORE_GENE_EXPRESSION_CLICKED`
- Analyze datasets `HOMEPAGE_LEARN_ANALYZE_DATASETS_CLICKED`
- Download data `HOMEPAGE_LEARN_DOWNLOAD_DATA_CLICKED`
- Expedite collaboration `HOMEPAGE_LEARN_EXPEDITE_COLLABORATION_CLICKED`

**P3:** 
Publications
- Journal links 
- BioRxiv links 
- cellxgene links `VIEW_COLLECTION_PAGE_CLICKED`,  {'collection_name':`<fill in >`}

Expedite collaborative data analysis
- Learn how it works `DESKTOP_QUICK_START_DOC_CLICKED`

Nav Bar
- We're Hiring! `BROWSE_CAREERS_CLICKED`, {`button`: `we're hiring`}

Bottom bar
- Github `GITHUB_CLICKED`
- Careers `BROWSE_CAREERS_CLICKED`, {`button`: `careers`}
- Contact us `CONTACT_US_CLICKED`

#### People to cc
**PM**:  @ambrosejcarr 
**DS**: @ainfeld 

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by ainfeld** [comment]
Since the `We're hiring` and `Help & Documentation` aren't part of the navigation bar on other pages I didn't follow the same button naming structure for "Adding a tab to the navigation bar"

**Comment by ainfeld** [comment]
Note: copy over of this original [issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/297) to be in this repo

**Comment by tihuan** [comment]
Hey @ainfeld !

Expedite collaborative data analysis

Learn how it works `DESKTOP_QUICK_START_DOC_CLICKED` <--- the text copy for this has changed to "Explore CZ CELLxGENE Annotate" on the page, so I changed the payload to `{ button: "Explore CZ CELLxGENE Annotate" }` accordingly. Is that alright?

Thank you!

**Comment by ainfeld** [comment]
@tihuan thank you for pointing that out! I would actually change the event to `EXPLORE_CZ_CELLXGENE_ANNOTATE_CLICKED` with no payload. 

The reason is that button takes you to a very specific page within documentation. The use of the `button` payload is when there are multiple buttons within the landing page that take visitors to the same page. For example, there are 3 different buttons on the landing page that take visitors to the collections list. So I needed to include the button name in the payload so I knew which one they actually clicked that took them to the collections list.

**Comment by ainfeld** [comment]
@seve totally understand if it's too late, but would it be possible to change the button name for ``Help & Documentation`` in the navigation bar to ``DOCUMENTATION_CLICK_NAV`` ?
