### ISSUE TITLE
Delete obsolete S3 data in prod

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#2864]
* s3://corpora-data-prod/**/*.loom
* s3://hosted-cellxgene-prod/user_annotations/
* s3://hosted-cellxgene-prod/s3 (TBD)
* s3://hosted-cellxgene-prod/prod-config.yaml
* s3://corpora-data-portal-prod (empty)
* s3://temp-corpora-prod-cxg-artifacts (it's temporary and has old data)
* s3://elasticbeanstalk-us-west-2-231426846575 (beanstalk no longer used)

**Comment by atolopko-czi** [comment]
I remember we started assessing what S3 data can be deleted? https://docs.google.com/document/d/15JqTV-nd73lthNyHKcr4u0iaeGAiJBLW9tBmeu3L0lk/edit

@maniarathi We still need to perform these deletions, right? We can make this on-call work, if so.

**Comment by maniarathi** [comment]
Ah sorry about the delayed response. Yes, these deletions still need to happen.

**Comment by atolopko-czi** [comment]
Thanks! If we know the cost savings will be significant, we can adjust the priority upward.
