### ISSUE TITLE
scExpression Firefox cell type scrolling bug

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2866]
1. Go to scExpression on Firefox
2. Add Tissue, Add Genes
3. Scroll to the bottom
4. dots scroll but not cell types

Desired Behavior: dots scroll with cell typeshttps://images.zenhubusercontent.com/228681195/94c4dfcc-7f23-47b4-9388-517139ab0b0b/img_7691.mov

**Comment by atarashansky** [comment]
It's amazing, you can keep scrolling the dotplot forever and it just goes higher and higher.
