### ISSUE TITLE
chore: set up code coverage for tests

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#2867]
Code coverage will need to be set up properly -- currently broken (and will be straight up removed in #2865).

**Comment by metakuni** [comment]
Consider adding this as an optional manual step that can be run on-demand instead of integrating it into CI/CD to avoid slowing down every build.

**Comment by metakuni** [comment]
@atarashansky / @Bento007 : Could you confirm/deny whether #3904 fixes this and if we can close this issue? 🙏

**Comment by dsadgat** [comment]
@atarashansky is this still broken?

**Comment by atolopko-czi** [comment]
codecov has been working; closing
