### ISSUE TITLE
Match RDS version used for testing to version used in deployed environments

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#2870]
Currently, our dockerized data-portal database (used for local dev and in our testing suite) uses an image running PostgreSQL v13.0. In our deployed environments, however, we use v10.x

Let's downgrade our local, dockerized data-portal database to match the version we use in dev/stage/prod and ensure tests still pass.

**Comment by nayib-jose-gloria** [comment]
note: I attempted to downgrade to 10.20 locally and it caused several unit tests to fail

**Comment by atolopko-czi** [comment]
Or we could upgrade RDS to 13, or both to 14. But since we have hopes of removing RDS altogether from our infrastructure, we might consider deprioritizing this task unless we're running into problems due to the version mismatch.

**Comment by atolopko-czi** [comment]
not causing problems as is, and will be obsolete once we move away from RDS
