### ISSUE TITLE
bug(infra): Fix frontend docker container

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#2873]
Smoke tests aren't running properly in frontend docker container. Seeing dependency issues when running github workflow.

Potential issue with node:14.

We've tried bumping the version number, but that leads to permission issues with the container. Since we already have an open issue to address container build times, we could potentially build the container from the ground up on node:15/16.

See: https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

**Comment by dsadgat** [comment]
@seve is this still an issue?

**Comment by tihuan** [comment]
Yeah still an issue, because we're not running e2e tests in container right now 😭

**Comment by atolopko-czi** [comment]
@tihuan Still an issue? Or did recent CI/CD work resolve this possibly? 

Are E2E tests running successfully, but just not in Docker process? This issue could use some clarity on what is not working exactly and what the desired end state is.

**Comment by tihuan** [comment]
This is no longer an issue, since we run tests against rdev now 🙌✨ Thanks so much, Andrew!
