### ISSUE TITLE
feat: replace AWS RDS with TileDB

### ISSUE THREAD

**Issue by roaga** [chanzuckerberg/single-cell-data-portal#2874]
## Need
RDS logic and infrastructure is complicated and sometimes results in data loss, as well as being difficult to maintain. Not having a history of revisions is also problematic.

## Approach

Replacing RDS and SQL-related code in the database with TileDB may simplify logic, infrastructure, and history without introducing a new tool into our stack.

## Definition of Done
Corpora, WMG, and Curation APIs all work as expected through the new database, as well as all existing pipelines and expected new improvements.

**Comment by ebezzi** [comment]
The implementation by Rohan can be found [here](https://github.com/chanzuckerberg/single-cell-data-portal/tree/feature/replace-rds)
