### ISSUE TITLE
scExpression padding between genes and cell type moves

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2878]
When you only have one gene there is a lot of padding between gene and cell type label, then when you add additional genes, all the genes move to the left, closer to the cell type label. 

Desired behavior: genes do not move and when you add more genes, genes are added to the right hand side.

**Comment by atolopko-czi** [comment]
@signechambers1 still relevant?

**Comment by signechambers1** [comment]
Still an issue but I'll close, not a high priority.

**Comment by atarashansky** [comment]
Fixed by #3811.
