### ISSUE TITLE
Explorer Performance Improvements

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#2881]
This epic captures the work required to meet our Q3 2022 goals:

- Coloring by a gene is interactive for datasets up to 2M cells (<400 ms)
- Coloring by a geneset is interactive for datasets up to 2M cells (<400 ms)
- Loading a gene is interactive for datasets up to 2M cells (<400 ms)
- Unfurling a gene set is interactive for datasets up to 2M cells or has a loading indicator (>1 sec must have loading indicator)

Related Docs:
- https://docs.google.com/document/d/1CBy8mHuOgWcScHcBZ8V-oYdQfZsjKo_1MqEC8ovYr4k/edit#
- https://docs.google.com/document/d/1kAOv6F_WBAfDymz38EOgQyZMIeOb4CToxUS7qPhBIl0/edit#
- https://docs.google.com/document/d/1MkDPIrS14skI-WxFB-BIIJmvRF4SBnOipx9Q6dkcsuI/edit

Test Datasets:
- [Azimuth](https://cellxgene.dev.single-cell.czi.technology/e/d838ca32-0623-4ec9-8eb5-39525dbfb926.cxg/) (4M cells)
- [Covid Immune](https://cellxgene.cziscience.com/e/9dbab10c-118d-496b-966a-67f1763a6b7d.cxg/) (1.5M cells)

**Comment by signechambers1** [comment]
@pablo-gar was there a dataset around 2M cells that you were trying to use (maybe from the Satija lab?) that didn't work that might be a good test dataset for this?

**Comment by brianraymor** [comment]
@signechambers1 - we do have a live dataset in the corpus if that helps. See _Survey of human embryonic development_ in https://cellxgene.cziscience.com/collections/c114c20f-1ef4-49a5-9c2e-d965787fb90c

**Comment by atarashansky** [comment]
Improves color-by of categoricals: https://github.com/chanzuckerberg/single-cell-explorer/pull/326
