### ISSUE TITLE
bug( ): 502 errors in browser console 

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2898]
## Describe the bug
Sometimes the frontend receives 502 from the backend for various endpoint calls. There are no logs in the backend to indicate the 502 originated from the backend server. It could be caused by Cloudfront or any of the services in between the frontend request and the backend server.

## To Reproduce
1. go the the cellxgene frontend
2. open the network console
3. generate an API key, or start a revision. 
4. Eventually 502 errors will show up.

## Expected behavior
We should not be receiving 502s

## Environment
 - Browser chrome

**Comment by metakuni** [comment]
@Bento007 , any chance this could be a duplicate or related to #3535 ?
