### ISSUE TITLE
fix(smoke-test): Seed test user's collection before smoke-test

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2919]
## Need
- smoke tests run unreliably due to variation in the collections assigned to the test users.

## Approach
- Before starting the smoke test, clear the collections owned by the test user and create 10 test collections.
- 

## Definition of Done
	• Smoke tests always  run with a clean slate of test data

**Comment by tihuan** [comment]
Thanks so much for creating the issue, @Bento007 🙏 !!

**Comment by metakuni** [comment]
See also #1375

**Comment by atolopko-czi** [comment]
@Bento007 OK to close? We have dup data seeding stories in CI/CD epic now (and I removed this issue from that epic as well)
