### ISSUE TITLE
Refine and update tombstoned collection toast functionality

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2926]
See original bug report in [Slack](https://clevercanary.slack.com/archives/C023Q1APASK/p1658445222870689).

#### Refinements
1. Should a "tombstoned collection" redirect the user to the collections or datasets page?
2. If the user is to be redirected to the collections page, the current toast text of "You’ve been redirected to the cellxgene Data Portal homepage." will need updating (as the collections page is no longer the Portal homepage).

**Comment by brianraymor** [comment]
1. I don't have a strong preference, but it seems like it should be whatever the new default page is.
2. I defer to @hthomas-czi on the language. 

We only have one collection that we deleted during launch - but, we discovered that someone was using that collection in a class when they contacted us prior to having the toast.

**Comment by seve** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/blob/503e67238cd37ba311baef64e087a5891bd4c0a4/frontend/src/views/Collection/index.tsx#L90-L93

**Comment by brianraymor** [comment]
Closing in favor of #5004.
