### ISSUE TITLE
bug(curation API): Super Curator scopes not appearing in curation API generated access tokens

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#2928]
## Describe the bug
Super Curators do not have their expected scopes in their access tokens. This blocks them from Super Curator specific actions gated by the backend. 

## To Reproduce
1. As a super curator, generate an access token for the curation API (for example, locally follow the steps outlined in [this notebook](https://github.com/chanzuckerberg/single-cell-curation/blob/main/notebooks/curation_api/python/upload_local_datafile.ipynb) until _Set url and access token env vars_, and print/decode the generated access token and check what scopes are granted.

## Expected behavior
We expect super curators to have the "write:collections" and "read:collections" scopes in their access tokens, which we use in the backend to gate super curator specific features (such as: uploading datasets to the super curator specific s3 bucket directory).

**Comment by danieljhegeman** [comment]
For posterity: this resulted from the recent inclusion of RBAC, which Trent added recently in Auth0

**Comment by Bento007** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/issues/2964
