### ISSUE TITLE
Update technical spec for ontologized tissue and cell type filter modifications

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2940]
[Tech spec](https://docs.google.com/document/d/1CRX0_lYJ_iKUVsd6mgrQQFiiapnqWF3F8LKkSjcKO1A).

#### To Dos 
- [x] Update tissue and cell type filters to match updated functionality.
- [x]  Update BE implementation for productionalization
- [x] Add section on how to run notebooks against updated pinned ontologies.
- [x] ~~Possibly document approaches on integrating with CLI.~~ See [upgrade document.](https://docs.google.com/document/d/1R3a43eLVtWLOxgSu2HCMdD8QK5hddHjtY7uZJrC4VuE/edit)

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog, [please review](https://docs.google.com/document/d/1CRX0_lYJ_iKUVsd6mgrQQFiiapnqWF3F8LKkSjcKO1A).

**Comment by NoopDog** [comment]
Complete
