### ISSUE TITLE
Refactor Backend Code

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2963]
Remove the Corpora Directory and organize the code to be consistent.

## Backend APIs are scattered in the backend code base
We should consolidate to a single directory for all APIs that are hosted in the same container. Here is my suggestion:
- move backend/corpora/api_server up to backend/api_server
- The portal API lives in backend/corpora/lambda/api. It's not a lambda. Move it to backend/portal
- Move open_api specs from backend/config into backend/api_server

## Group submission related code
move all submission-related code to _backend_. These are the related directories:
- _backend/dataset_processing_
- _backend/dataset_submissions_ 
- _backend/upload_failures_
- _backend/upload_success_, 

## backend/corpora/common is used by other libraries
- move _backend/corpora/common_ to _backend/common_ 

**Update the test directory to match the above changes**

**Comment by atolopko-czi** [comment]
https://docs.google.com/document/d/1H3IdC8frpvJsmm6Z3XTO-fQd3XNkIPvNvcvp8j380OE/edit#
