### ISSUE TITLE
bug(Authz):RBAC not enforced in curation API

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#2964]
## Describe the bug
RBAC not working for curation API. Assigning the role of super-curator does not affect the user's permission.

## Step to Reproduce
1. generate an access token in the curation API as a no none super-curator. The access token will not have write:collections
2. assign super-curator to user
3. generate an access token in the curation API as a no none super-curator. The access token will not have write:collections

**Comment by danieljhegeman** [comment]
@Bento007 just want to confirm: as far as I can see, the related changes are in staging, so this should be in `Ready for QA` -- but I'm seeing you reopened and moved specifically to `Ready for Staging` _after_ I did the staging deploy today so I wanted to check

**Comment by Bento007** [comment]
Thank you for moving.
