### ISSUE TITLE
Internal test collections that were tombstoned must not be returned by GET /v1/collections

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2970]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1658872043283579?thread_ts=1658868624.213879&cid=C02UGUV5R3J). 

Currently 'dan test' is included in the results of collections with `tombstone: true`.

**Comment by danieljhegeman** [comment]
This bug has been obviated by https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3002 which removes all tombstones from `GET /collections` and `GET /collections/{collection_uuid}`
