### ISSUE TITLE
Return withdrawn collections and datasets

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2971]
This originated as a bug that returned _false positives_ for withdrawn (published but then deleted) collections and datasets due to the dependency on _tombstones_ :

> See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1658868624213879).

> The intent of reporting tombstone status was to document the small number of collections or datasets that had been published and then withdrawn.

> The current implementation is returning thousands of results for datasets. Potentially, this is an artifact for how tombstone is used internally? 

The mitigation was to remove tombstone fields for both collections and datasets until a better mechanism could be designed.

**Comment by danieljhegeman** [comment]
Documenting here: as of the primary key changes introduced back in April, tombstoning now _only_ occurs when a dataset is deleted from a _published_ collection.

**Comment by brianraymor** [comment]
Per triage with @jahilton and @Bento007 - there was agreement to move this requirement to _curation api futures_ because it is not blocking the Q4 migration and requires further discovery.

**Comment by brianraymor** [comment]
Triaging with @metakuni  - With the transition to manual deletion tracked in github issues, there's less of a need for this reporting for curation scenarios. There was a previous request by a bulk downloader for such support (quick detection of what has changed in the corpus), but that is lower priority at this time. CC: @jahilton
