### ISSUE TITLE
editorial: update_collection.ipynb instructions are misleading

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3009]
_(Required) Provide the updated Collection form metadata for your existing Collection. **Do not include attributes that you do not wish to change.** If the links attribute is included, the existing links on the Collection will all be removed and replaced with the list of links that you provide here._

I edited to only include name and description because I did not wish to change other attributes. The operation failed:

`HTTPError: 400 Client Error: BAD REQUEST 
`
 I added only `#required` fields. The operation succeeded. It appears that all #all `#required `fields MUST be present?

**Comment by danieljhegeman** [comment]
I'm investigating. This should not be the case as of ~a month ago.

**Comment by danieljhegeman** [comment]
@brianraymor I could not reproduce the error. My attempt to update _just_ the name and description, as you did, was a success. Can you reproduce and/or share more specifics about the _exact_ collection and the format of the collection metadata?

**Comment by brianraymor** [comment]
Probably addressed by [PATCH /collections/{collection_uuid} descriptions and examples do not conform to the schema](https://github.com/chanzuckerberg/single-cell-data-portal/issues/3010).
