### ISSUE TITLE
PATCH /collections/{collection_uuid} descriptions and examples do not conform to the schema

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3010]
**August 3**

RE links: capturing design discussion from [curation-api](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1659561250170139?thread_ts=1659476056.513829&cid=C02UGUV5R3J).

**MVP [now with BAD REQUEST}**
1. Links are in the request. Completely replaces the existing links in the collection. This must be clearly documented. If Links are [], then return BAD REQUEST.
2. Links are not in the request. The existing links in the collection are not changed.

--- 

See the [Swagger API](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.collection_id.actions.patch). See also [editorial: update_collection.ipynb instructions are misleading](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3009). 

For the record, I prefer an implementation that allows curators to only pass the fields that need to be changed since this is a PATCH of an existing collection that has already contains the required fields.

The description states:

_Update a private Collection or a Revision. **If any Collection metadata fields are included in the body of the request, these fields SHALL be updated for the specified Collection**._

This is reinforced by the examples:

1. Update a description

```
{
  "description": "New Collection description"
}
```

2. Update a name

```
{
  "name": "New Collection name"
}

```

But the schema indicates that the following fields are required:

```
collection_form_metadata {
contact_email*	string email of contact person for the collection

contact_name*	string name of the primary person of contact for the collection

description*	string description of the collection

links	links[...]

name*	string name of the collection
}
```

**Comment by brianraymor** [comment]
@danieljhegeman - I connected the PR. Is this issue assigned to you?

**Comment by danieljhegeman** [comment]
Ah, I see that my 'mention' of this issue in the PR is not the same as actually _connecting_ the issue to the PR. Noted. 📝

**Comment by brianraymor** [comment]
@danieljhegeman - Please ensure that the swagger api is also updated.

**Comment by brianraymor** [comment]
Failed testing because existing links are deleted during a partial update:

In the current implementation:
1. A collection has links.
1. Only its description is updated with PATCH.
1. A collection no longer has links, but does have a new description.
