### ISSUE TITLE
Dropbox API change results in different error passed to user when uploading Datasets from bad Dropbox links

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3012]
The Dropbox API has started returning 200's for `HEAD` calls to a dropbox resource link even if the resource doesn't exist. Strangely, _sometimes_ the _same_ url returns a 200; sometimes it returns a 400 (as previously expected); [we updated the unit tests](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3003) to account for this. ([see this conversation also](https://czi-sci.slack.com/archives/C023Q1APASK/p1659097988468819))

Unfortunately this means that some or most instances of dead Dropbox links submitted by users via the UI will generate a missing header exception, which will return a bizarre message detail return to the user ([here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/9af989384aaf660182036996655f817186f5978d/backend/corpora/lambdas/api/v1/collection_id/upload.py#L53)) about `'content-disposition'` header being absent (technically true, but irrelevant to user), instead of the more meaningful message associated with an http error immediately above in the same block of code.

Outstanding question: how is the `InvalidParametersHTTPException` handled by the FE?

**Comment by brianraymor** [comment]
Reviewed with @metakuni - almost a year has passed since this was opened. I also expect that more curators are using the Discover API for uploads.
