### ISSUE TITLE
The curation API notebooks do not print human readable error message for failures

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3017]
See [**curation-api**}(https://czi-sci.slack.com/archives/C02UGUV5R3J/p1659380082383059). 

[PUT /v1/collections](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.collection.create_collection) documents that a BAD REQUEST status code includes diagnostic information will be returned such as:

```
{'detail': "'description' is a required property",
 'status': 400,
 'title': 'Bad Request',
 'type': 'about:blank'}
```

Currently, the HTTP request is caught, but is then re-thrown in `failure`:

def failure(logger: logging.Logger, e: Exception, message=None):
    logger.error("\n\033[1m\033[38;5;9mFAILED\033[0m")  # 'FAILED' in bold red
    if message:
        logger.error(message)
    **raise e**

resulting in:

FAILED
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Input In [28], in <cell line: 1>()
----> 1 create_collection(collection_form_metadata)

File ~/Notebooks/curation_api/python/src/collection.py:25, in create_collection(collection_form_metadata)
     23     data = res.json()
     24 except Exception as e:
---> 25     failure(logger, e)
     26 else:
     27     collection_id = data.get("collection_id")

File ~/Notebooks/curation_api/python/src/utils/logger.py:43, in failure(logger, e, message)
     41 if message:
     42     logger.error(message)
---> 43 raise e

File ~/Notebooks/curation_api/python/src/collection.py:22, in create_collection(collection_form_metadata)
     20 try:
     21     res = requests.post(url, data=json.dumps(collection_form_metadata), headers=headers)
---> 22     res.raise_for_status()
     23     data = res.json()
     24 except Exception as e:

File ~/.pyenv/versions/3.9.11/envs/env/lib/python3.9/site-packages/requests/models.py:960, in Response.raise_for_status(self)
    957     http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
    959 if http_error_msg:
--> 960     raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: BAD REQUEST for url: https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections

**Comment by danieljhegeman** [comment]
This is discussed [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3042). It actually is not due to my catching and rethrowing -- it's a Python issue that requires that error messages be extracted manually.

**Comment by brianraymor** [comment]
Thanks for the clarification Dan.
