### ISSUE TITLE
GET /v1/collections/{collection_uuid} incorrectly documents a 400 status code

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3021]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1659395848834919?thread_ts=1659395488.309489&cid=C02UGUV5R3J).

The [Swagger API](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.collection_id.actions.get) incorrectly documents that a 400 can be returned.

In general, it would be helpful to document the cause of error conditions because it helps to validate whether there is a scenario that might result in a specific status code.

**Comment by danieljhegeman** [comment]
I looked into easily adding validation of path/query parameter id's. It can be done easily using `pattern: <uuid regex pattern>` in the API definition, but that messes up our testing since we use human-readable (and meaningful) id's for our unit tests. Not worth it at the moment.
