### ISSUE TITLE
Change name of scExpression to Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3030]
We've gotten feedback that the name scExpression is not intuitive. Full [documentation](https://docs.google.com/document/d/1aeW9HGIXFZqieQin-CKUGPdhlGMqFGNW0aTKClIwm84/edit) on feedback here. Based on this feedback and changes in branding work, we are changing the name to Gene Expression. This ticket covers the following work to change the name:

- [x] Change name of tab in nav bar to Gene Expression (keep beta symbol)
- [ ] Changing URL from https://cellxgene.cziscience.com/scExpression => https://cellxgene.cziscience.com/geneExpression
- [ ] Change title in [survey](https://docs.google.com/forms/d/e/1FAIpQLSde_zIFZPQD2p0ovaX3Pb7lDOajWJCmOeuX4wQ8Z8Ab5NXUjw/viewform) to Gene Expression (feel free to ping signe to do this)
- [ ] Change references in user [documentation](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__scExpression%20Documentation/4_2_2__Cell%20Type%20Ontology%20Ordering) to Gene Expression (ask pablo to review PR)

**Comment by signechambers1** [comment]
fyi @ainfeld

**Comment by ashin-czi** [comment]
Seems like there might need to be more discussion for what exactly needs to change to "Gene Expression", or what we can keep as "scExpression"

- Will we be changing the URL as well? example: https://cellxgene.cziscience.com/scExpression => https://cellxgene.cziscience.com/geneExpression
- Will we need to update internal references to "scExpression" to "Gene Expression"? Such as internal documentation or code. I want to avoid having references to WMG vs. scExpression vs. Gene Expression

**Comment by signechambers1** [comment]
@ashin-czi thank you for catching, we do want to change the URL but do not need to change internal documentation or code from my perspective. I think all our code refers to this feature as WMG. I defer to eng on any changes you think would be helpful on eng documentation and code.

**Comment by seve** [comment]
keep internal refrences as wmg
