### ISSUE TITLE
Deletion of published datasets in the Discover API must be restricted

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3039]
### Context

Authorization to delete published datasets MUST be limited to CZI engineering to avoid accidents, track deletion occurrences and justifications, and to validate that the redirect is in place for the permanent links to the collection and its CXG(s). 

### Current Experience

In a private revision of a public collection, a curator MAY use [`DELETE
​/v1​/collections​/{collection_id}​/datasets​/{dataset_id}`](https://api.cellxgene.cziscience.com/curation/ui/#/Collection/backend.curation.api.v1.curation.collections.collection_id.datasets.dataset_id.actions.delete) to delete a published dataset. The collection can then be published in the curation UX.

### Updated Experience

For all curators:
1. If a dataset is _New_ either in an unpublished collection or private revision of a public collection, `DELETE` is allowed.
2. If a dataset is _in the public collection_, then `DELETE` MUST fail.
3. If a dataset is _in the public collection_ and  _Updated_, then `DELETE` MUST fail.

For CZI engineering:
1. If a dataset is _New_, `DELETE` is allowed.
2. If a dataset is _in the public collection_, `DELETE` is allowed.
3. If a dataset is _Updated_, `DELETE` is allowed.

**Comment by brianraymor** [comment]
@danieljhegeman - let's review together when you're ready to start on this one.

**Comment by danieljhegeman** [comment]
@brianraymor sounds good, will come to you when ready 👌

**Comment by danieljhegeman** [comment]
Going to introduce `CXG_ADMIN` env variable which will be set for situations when admin-override functionality is desired, to be used primarily in backend business logic; pair with context manager for unit tests to permit usage of CXG_ADMIN env var only for subsequences of logic (because normal, non-admin functionality is generally the global behavior that is desired for unit tests).

**Comment by danieljhegeman** [comment]
Confirmed working in dev -- deletes of new Datasets are allowed during a revision, but deletes of a previously-published Dataset yields a 405, even when that Dataset has been updated with a new Dataset.

As an aside/separate issue, I discovered staging is failing when trying to generate an auth token.
