### ISSUE TITLE
bug(curation-api): curator-api or curation-api

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#3040]
## Describe the bug
We need to keep naming consistent within the code. In someplace we use curation-api in other we use curator-api. The name should be curation-api. **Curator** should only appear when we are referring to the user curating. Anywhere curator is used that is not directly referring to the user should be changed to curation.

**Comment by Bento007** [comment]
The answer is curation-api

**Comment by danieljhegeman** [comment]
Yeah I just did a look-through of all instances of `curator` and didn't see any that were misused in the data portal repo.

**Comment by danieljhegeman** [comment]
@Bento007 though be advised that we're still naming directories in the data portal repo `curator/` when they should probably be `curation/`...
