### ISSUE TITLE
scExpression landing page changes

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3054]
We'd like to increase the percent of people who click Add Tissue or Add Gene and get to a fully loaded dot plot. This ticket captures the work to update the landing page for scExpression.

Full design [here](https://www.figma.com/file/JS5ThqTBcpAVuBFglAItKf/Gene-Search?node-id=4131%3A256314).

Work includes:
- [ ] Removing right side bar, moving legends to the main visualization and methodology to help and documentation. Also add links to methodology in legend hover overs.
- [x] Add skeletons for genes, tissues, and main plot
- [x] Updated styling for Add Tissues and Add Genes Buttons

**Comment by signechambers1** [comment]
FYI @hthomas-czi created this ticket and linked the design. If there are any design changes please update the link. Thanks!

**Comment by tihuan** [comment]
Thanks so much, @signechambers1 and @hthomas-czi !

@hthomas-czi we also need to add source data to right panel when the new "Source Data" button is clicked, right? And the Source Data panel will list out all selected tissues and their corresponding datasets in sections? If so, it'd probably be very helpful for Seve and Andrew to see what that will look like in Figma 🙏 Thank you!

**Comment by signechambers1** [comment]
@ashin-czi what is the status of this ticket?

@hthomas-czi i think you addressed @tihuan's comment above in the figma link but @ashin-czi let us know if you have any questions.

**Comment by ashin-czi** [comment]
@signechambers1 Still working on this ticket, there is a PR out right now that removed the right sidebar: https://github.com/chanzuckerberg/single-cell-data-portal/pull/3220

Still working on the skeleton feature

**Comment by signechambers1** [comment]
thanks @ashin-czi ! Do you have an ETA? Download images is a higher priority but I'd like this to be in production by the end of the month if possible.

**Comment by ashin-czi** [comment]
By end of the month is possible, I'm estimating either sometime next week or the week after I should be finished

**Comment by signechambers1** [comment]
great thanks!

**Comment by ashin-czi** [comment]
Hi all

I'm so sorry this has been taking as long as it is, had some unexpected delays.

I am thinking this will get done at some point next week since there's still a bit to do, specifically the source data and methodology sidebar and moving the footer links to the help and docs dropdown.

Just wanted to let everyone know! 

Here's how it looks currently though:
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/11e476c4-bebb-4526-aacd-ef5ee2e1f2fc)
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/a43ba667-9879-4f98-a19e-3b4fe57f0b06)
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/94ab56c7-efca-4b8a-a32b-c1fece90966c)

**Comment by signechambers1** [comment]
fyi @hthomas-czi to review, @ashin-czi it looks great to me from the screenshot! what is your plan for merging in?

**Comment by ashin-czi** [comment]
@signechambers1 I'm trying to figure out how to deploy to rdev right now, but I recorded a video of the functionality in my local instance

https://user-images.githubusercontent.com/109984998/192336213-44dddb59-457d-437a-af9e-4ba95ab09812.mov

Hope this helps!

**Comment by signechambers1** [comment]
thanks @ashin-czi will review! fyi @hthomas-czi and @ainfeld

**Comment by signechambers1** [comment]
@ashin-czi it looks really good. 2 questions:
