### ISSUE TITLE
type should be removed from HTTP responses

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3067]
@brianraymor commented on [Tue Aug 09 2022](https://github.com/chanzuckerberg/single-cell/issues/322)

See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1659389475027609). If `type` is never set, it is meaningless to include this field. 

```
{'detail': 'Unable to parse authentication token.',
 'status': 401,
 'title': 'Invalid Authentication Credentials',
 'type': 'about:blank'}
```

**Comment by danieljhegeman** [comment]
Ok so I can get this `type` removed from the error response text for most errors, but not all. Anything that is rejected by 'Swagger API definition'-level configuration, such as Auth errors (401), I have not figured out how to get access to--anything ahead of the Flask layer. Some others report [similar issues ](https://github.com/spec-first/connexion/issues/854) with Connexion and it is not clear it is easily resolvable.

Given that, should we just leave `type` in for now and revisit it later? The options on the table are

1. Remove `type` from most, but not all, error responses from the Curation API -- inconsistent error message shape
2. Keep `type` in all error messages

cc @brianraymor @Bento007

**Comment by brianraymor** [comment]
> Given that, should we just leave type in for now and revisit it later? 

I defer to @Bento007 and @ebezzi - but my sense is to leave in place and NOT revisit later (close as Won't Fix) if it's more than a _finish_ issue. It's doubtful that we'll address in the future based on past experience.

**Comment by danieljhegeman** [comment]
Ok. I'm fine with that. It is a very minor cosmetic detail that is surely never going to interfere with a user's programmatic handling of the error anyways.

**Comment by danieljhegeman** [comment]
Closing as insignificant for now.
