### ISSUE TITLE
Remaining documentation updates

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3069]
I think it'll be easier to package all documentation changes into a single PR as testing proceeds today.

- [note that `link_name` is ignored/overwritten for DOI links](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660089617562009)
- The description for `processing_status` - _Processing status for a Dataset or Collection_ is potentially meaningless to a new reader of the swagger?

**Comment by brianraymor** [comment]
Closing as duplicate.
