### ISSUE TITLE
Script to pull specific dataset info

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#3081]
## Need
- a script to pull 
`id, name, organism, tissue, assay, sex, cell_count, explorer_url, S3 uris` 
for all public datasets

**Comment by MDunitz** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/3057

**Comment by brianraymor** [comment]
@MDunitz 

Out of curiosity, what is this for?

**Comment by MDunitz** [comment]
@brianraymor Sorry I should have included in the ticket description, this was requested by @pablo-gar.

**Comment by pablo-gar** [comment]
This to gain programatic access to all the datasets in the portal and their S3 URIs, there's a few tasks that Signe has asked me about the entire data corpus. We also have a collaboration going with Joshua Campbell that will require me to get programatic access in lieu of SOMA not being ready.

**Comment by brianraymor** [comment]
I shared the v0 portal API swagger + notebook with Pablo.
