### ISSUE TITLE
feat: Add extra dimension to integrated corpus, summary cubes, and snapshot of scExpression

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#3084]
To address the cube creation step of the [eng design ](simplify tissue dropdown) to simplify tissue dropdown of scExpression.

We need to:

In the dimensions of the integrated corpus and summary cubes:

- Rename the following of the tiledb objects:
   - Dimension: tissue_ontology_term_id --> tissue_original_ontology_term_id
   - Attr: tissue--> tissue_original 
- Add the following:
   - Dimension: tissue_ontology_term_id (for now a copy, but in the future high-level definition of tissue)
   - Attr: tissue (for now a copy, but in the future high-level definition of tissue)
- Modify the cube creation to account for added dimension and attribute
- Modify the snapshot and its querying to account for added dimension and attribute

**Comment by metakuni** [comment]
Oops, I just noticed that the PR merged for this issue was merged to a feature branch, not main! Moving this back to `In Progress` until the feature branch is merged to main.
