### ISSUE TITLE
The processing_status for an invalid dataset returns PENDING and not FAILURE

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3092]
When an invalid dataset is uploaded and fails validation, its `processing_status` is reported as `PENDING` and not `FAILURE`.

**Comment by Bento007** [comment]
Was this uploaded through a link or uploaded directly to s3.

**Comment by Bento007** [comment]
Was this uploaded through a link or uploaded directly to s3.

**Comment by brianraymor** [comment]
It was uploaded directly.

**Comment by Bento007** [comment]
can you send me a link to the dataset you're using?

**Comment by brianraymor** [comment]
I just used one of the old small(er) schema 1.0.0 datasets in that dropbox folder. This will immediately fail validation.

https://www.dropbox.com/s/jgunwv8amblvjk1/7MB.h5ad?dl=0

Here's a [private collection with the invalid dataset](https://cellxgene.dev.single-cell.czi.technology/collections/0ff1eb4f-d818-4eaf-9ef4-fd9ca87805a3).

When I GET /collection and check the dataset status for the tag:

'tag: badcurator.h5ad PENDING'

**Comment by brianraymor** [comment]
This failed on [re-test](https://cellxgene.dev.single-cell.czi.technology/collections/632c301c-0a3a-4009-ab1f-ff949a75ca7b).

**Comment by brianraymor** [comment]
@Bento007 - please do not move bugs to _Ready for Prod_ until either @jahilton  or I have re-tested and verified. This is the second re-test for this case. Testing was blocked by the x_normalization issue earlier.

That said, it looks correct:

The collection `processing_status` is "'FAILURE'.

The individual dataset `processing_status` are:

'tag: badcurator.h5ad FAILURE'
'tag: goodcurator.h5ad SUCCESS'
