### ISSUE TITLE
Unauthorized user can update curator_key for dataset in  private collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3093]
**IF** a user (no API key set) has access to a private collection+dataset uuid, then they are authorized to change the curator key.  The operation will succeed.

**Comment by Bento007** [comment]
@brianraymor do you have an example of the request?

**Comment by brianraymor** [comment]
I updated to Dan's latest notebooks this morning. I cannot reproduce today from a fresh start. It returns a 401.

UNAUTHORIZED

{
  "detail": "Unable to parse authentication token.",
  "status": 401,
  "title": "Invalid Authentication Credentials",
  "type": "about:blank"
}

**Comment by Bento007** [comment]
I was also unable to reproduce. Closing for this reason
