### ISSUE TITLE
Misleading lambda error log when the wrong Dataset id is used for local file upload

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3095]
The following lambda log error is for internal use only and does not get surfaced to users:

The case of a local datafile being submitted via s3 upload where a uuid is used as the identifier _but_ it does not correspond to a `dataset_id` in the given Collection results in a misleading error log. [This line](https://github.com/chanzuckerberg/single-cell-data-portal/blob/9af989384aaf660182036996655f817186f5978d/backend/corpora/dataset_submissions/app.py#L47) returns `None` because it is asking for the case where the supplied `dataset_id` exists within the Collection with the supplied `collection_id`. And it does not, because it is a nonexistent `dataset_id`. But it is reported as the Collection not existing.

**Comment by brianraymor** [comment]
@Bento007 believes that this is required for debugging.
