### ISSUE TITLE
Malformed tags are producing generic errors

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3096]
When a curator_tag query parameter has a suffix other than `.h5ad`, the error returned is a generic 400 ("One or more parameters is invalid.").

In such an event, the error message should contain detail about the suffix since this logic will need to be done in a function that does some forgiving parsing of curator tags and dataset ids. See [this issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2631) and [this conversation thread](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660162834937169).

**Comment by brianraymor** [comment]
This is no longer relevant since the .h5ad suffix requirement is being deprecated per curator request.
