### ISSUE TITLE
Remove`.h5ad` suffix requirement for identifiers

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3102]
See conversation [here](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660162834937169)

The curator should not be required to, but _may_, include the `.h5ad` suffix when communicating either the curator tag OR the dataset id to the API. The backend must handle the determination accordingly _for all endpoints_. This includes the lambda logic that parses the s3 key.

Updated tag and id handling rules: 
- a tag may not match a uuid. (cc @Bento007 for approval)
- A curator tag may not be an empty string.
- Curators may not assign their own ids. They _must_ assign a curator tag when uploading to s3, but are not required to use it thereafter; they may reference it by the dataset id which they can retrieve via GET /collections/{collection_id} and filtering for the new dataset, whether manually or by searching with the curator tag.

**Comment by brianraymor** [comment]
I would avoid special-casing .h5ad, because it increases the test matrix.

**Comment by Bento007** [comment]
no h5ad at all please. We only need to add the h5ad suffix when they download the file, but even then they can modify the name themselves.

**Comment by danieljhegeman** [comment]
Ok.

I think we should make the change by allowing files whose url includes `s3://cellxgene-dataset(env?-)submissions` to skip [this check](https://github.com/chanzuckerberg/single-cell-data-portal/blob/9af989384aaf660182036996655f817186f5978d/backend/corpora/common/upload.py#L63)

**Comment by brianraymor** [comment]
See a [recent case](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660779700824279?thread_ts=1660778105.668779&cid=C02UGUV5R3J) where Jason tripped over the .h5ad requirement.

**Comment by brianraymor** [comment]
Per triage with @jahilton and @Bento007 - there was agreement that this refinement was required to simplify the API.

**Comment by jahilton** [comment]
Special attn to one of the cases I hit, in case it isn't covered in the '.h5ad' work.
I believe it was rooted in uuid-formatted curator_tags, which should be blocked according to the notebook documentation. There was no error, file reports uploading but then nothing happens on the portal.

**Comment by brianraymor** [comment]
> There was no error, file reports uploading but then nothing happens on the portal.

I captured this case [above](https://github.com/chanzuckerberg/single-cell-data-portal/issues/3102#issuecomment-1218676449).

**Comment by brianraymor** [comment]
@Bento007 - you'll also update the notebooks?

**Comment by Bento007** [comment]
Yes, I'll update the notebooks as well

**Comment by Bento007** [comment]
Update the requirements of this ticket.

**Comment by brianraymor** [comment]
@Bento007 - Have the references to ".h5ad" been scrubbed from notebooks? For example - https://github.com/chanzuckerberg/single-cell-curation/blob/main/notebooks/curation_api/python/example_workflow.ipynb:

`identifier = "topdir/subdir/file.h5ad"  # Or "<dataset_id>.h5ad"
`
