### ISSUE TITLE
feat: Update scExpression docs to reflect tissue roll up

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#3111]
## Need

- To update scExpression docs to indicate how tissues are being aggregated into high-level tissues. 
- [Optional] if it does not affect readability, a tissue mapping table could be included

**Comment by signechambers1** [comment]
@pablo-gar is this work complete? Can we close this ticket?

**Comment by signechambers1** [comment]
Done as of 9/26!
