### ISSUE TITLE
The curation API should match the schema names/values and not annoy Jason

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3120]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660764498247119).

1. dataset - `title` is the schema field, but returned as `name`
1. dataset `is_primary_data` values are True,False in the schema, but returned as PRIMARY, SECONDARY, or BOTH (and is not a list of all unique values in the dataset like the other schema fields) - See **is_primary_data** section in [Introduce cellxgene schema 2.0.0 to cellxgene](https://github.com/chanzuckerberg/single-cell/issues/212) which captures a slack conversation with @ambrosejcarr. 

Per triage with @jahilton and @Bento007 - there was agreement to accept these changes prior to the MVP release to ensure consistency with the schema naming.

The values for `is_primary_data` are:

1. PRIMARY -> [True]
2. SECONDARY -> [False]
3. BOTH -> [True, False]

**Comment by jahilton** [comment]
Some error messages can be improved to help diagnose the issue more quickly

When providing an invalid Collection ID, the desired response would be something like "Collection not found". Here's what I documented as the current responses...
get_dataset - “Collection not found!”
get_assets - “Dataset not found!”
delete_dataset - “Dataset not found.”
get_collection - “Resource not found.”
delete_collection - “User is not authorized to access this resource.”
create_revision - “User is not authorized to access this resource.”
upload_local_datafile - “User is not authorized to access this resource.”
upload_datafile_from_link - “User is not authorized to access this resource.”

Similar, when providing an invalid Dataset ID, the desired response would be ~"Dataset not found in specified Collection". Here's what I see now...
get_dataset - “One or more parameters is invalid”
get_assets - “One or more parameters is invalid”
delete_dataset - “One or more parameters is invalid”

**Comment by Bento007** [comment]
The error message we can improve on. I'd like to get feedback from @brianraymor before moving forward with these changes.

**Comment by brianraymor** [comment]
Per triage with @jahilton and @Bento007 - I moved the inconsistent error messages for invalid collection id(s) to the openapi documentation issue. This issue is limited to the API changes now.
