### ISSUE TITLE
editorial: get_dataset_assets should demonstrate how to use presigned_url to download a dataset in a specific format

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3121]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660690035040539).

The notebook example should also document our [recommendations related to TTL](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660770391191809). 

1. Do we document a known TTL?
2. Do we recommend that `GET ../assets` is immediately called before downloading the dataset. It is not recommended to share `presigned_url`(s) for a workshop or class that may have expired.

**Comment by danieljhegeman** [comment]
> Do we recommend that GET ../assets is immediately called before downloading the dataset. It is not recommended to share presigned_url(s) for a workshop or class that may have expired.

@brianraymor is [this](https://github.com/chanzuckerberg/single-cell-data-portal/blob/5d629ebb6561d894f6602aafa284d7d1a295bad2/backend/config/curation-api.yml#L515-L518) sufficient as-is?

**Comment by brianraymor** [comment]
It is sufficient to document the constraints, but I'd still expect the notebook to demonstrate the download workflow for completeness.
