### ISSUE TITLE
PUT ../upload-link must support HTTPS scheme for S3 URL(s)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3122]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660838077260049?thread_ts=1660778105.668779&cid=C02UGUV5R3J). 

I've added a related note to [Update and complete all documentation of APIs in the OpenAPI spec](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2161) about user confusion over which links are supported.

**Comment by Bento007** [comment]
I still need to update the opnepapi spec to document what URLs are supported

**Comment by brianraymor** [comment]
@jahilton to re-test his case per the thread in the top-level comment.

**Comment by brianraymor** [comment]
@jahilton reported some _odd UX behavior_ on [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1661374966291379) that needs review.

**Comment by brianraymor** [comment]
Also regarding the swagger:

> Upload a Dataset. The Dataset will be uploaded from the provided link. MUST include a curator_tag in the request body; if an existing Dataset has this tag, the existing Dataset SHALL be replaced, otherwise a new Dataset will be added. MAY include the id of an existing Dataset, in which case the existing Dataset SHALL be replaced. Only presigned AWS S3 URLs and Dropbox shared file links are supported.

May I suggest a minor rewrite to move related information closer?

> Upload a Dataset. The Dataset will be uploaded from the provided link which must either be a presigned AWS S3 URLor Dropbox shared file. MUST include a curator_tag in the request body; if an existing Dataset has this tag, the existing Dataset SHALL be replaced, otherwise a new Dataset will be added. MAY include the id of an existing Dataset, in which case the existing Dataset SHALL be replaced.

**Comment by Bento007** [comment]
I'll add this to the swagger docs update PR I'm working on.

**Comment by brianraymor** [comment]
@jahilton's [seal of approval ](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1661466887273089?thread_ts=1661374966.291379&cid=C02UGUV5R3J)- _Then we're all good here_. Ready for production.
