### ISSUE TITLE
editorial: get_all_datasets

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3124]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660757948856919).

**Comment by danieljhegeman** [comment]
The correct way to retrieve all datasets for a Collection is `GET /collections/{collection_id}` and grabbing the `.datasets` array off of the response body.

We should not create a new endpoint for this. We can add the `collection_id` to the attributes for each dataset if that is desired cc @jahilton

**Comment by jahilton** [comment]
Generating a Dataset table will be a common occurrence. I would see an endpoint to be consistent with UI behavior (I can browse all Collections or I can browse all Datasets).
Without an endpoint for this, I believe my process will be to GET /collections, append the id to a list of all dataset ids, then run GET /dataset for each of those ids. (this will return more full metadata than getting the dataset 'preview' in GET /collections). Adding `collection_id` to the response from GET /dataset will be incredibly helpful.

**Comment by brianraymor** [comment]
I also disagree with @danieljhegeman - the mitigation requires N*dataset API calls to get the full metadata for each dataset. The number of datasets will not be getting smaller.

**Comment by danieljhegeman** [comment]
Acknowledged, if we need to be able to, given a `dataset_id` and _not_ a `collection_id`, fetch a dataset, then that is a valid need for this proposed endpoint, assuming I am understanding the need correctly

**Comment by danieljhegeman** [comment]
>Adding collection_id to the response from GET /dataset will be incredibly helpful.

@jahilton is this related to the central issue? I'm still a bit fuzzy on the workflow here.

**Comment by danieljhegeman** [comment]
>the mitigation requires N*dataset API calls to get the full metadata for each dataset. The number of datasets will not be getting smaller.

As long as the number of calls is not scaling past constant O(1) per dataset retrieved, I am not worried. One call per dataset will work out just fine. 

There _could_ be reason to support batch retrieval of datasets, but that would also require some retooling on the backend to parallelize certain operations, things which are currently sequential, because it's easier and because we do not yet need to return (tens of) thousands of datasets with extremely low latency.

**Comment by brianraymor** [comment]
Per triage with @jahilton and @Bento007 - there is a request to include a convenience function in the notebooks. No endpoint required at this time.

**Comment by danieljhegeman** [comment]
Per agreement with @jahilton , this will be accomplished by (trivial) custom programming on the client side to loop over Collections and populate a list with the full dataset metadata that is returned for each `GET /collections/{collection_id}` call. No further work needed from us.
