### ISSUE TITLE
Non-printable characters are (wrongly) being accepted for Collection names

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3134]
_I could've sworn I made an issue for this already a month or so ago, so don't be surprised if you find a duplicate (the one which I can't seem to find right now)_

The [validation of Collection metadata](https://github.com/chanzuckerberg/single-cell-data-portal/blob/5fa765b0a030a04ba28f9901e1e946bc85234bf5/backend/corpora/lambdas/api/v1/collection.py#L202-L216) is not adequate. It currently permits [characters which do not yield a physical character representation aka grapheme](https://www.google.com/search?q=non-printable+ascii+characters&oq=non-printable+&aqs=chrome.2.69i57j0i512l9.3035j0j7&sourceid=chrome&ie=UTF-8) (anything with a decimal code 1 thru 31; I take issue with the linked post claiming that line feeds and vertical tabs are "non-printable" because they can be/are printed--they just can't be used for hyperlink text).

This is a problem because it would produce scenarios we don't want on the FE, among them being nonexistent Collection links on the Collections page(s) in the Data Portal (I've already demonstrated this can be done), which means no way to click into a Collection.

**Comment by danieljhegeman** [comment]
can use `re.sub(r'[\x00-\x1f]', " ",` to replace each such character with a single space (though perhaps not on the trailing end, in which case just remove? I don't know if we want to worry about that). At the very least use it to remove the characters.

**Comment by brianraymor** [comment]
> edit: on second thought, simply reject an attempt to create/update a Collection with any of those characters present in the name.

Assuming that we went with the second thought. I'm seeing a 400 when I attempt to include these characters during either creation of the private collection or update of collection information:

FAILED

```
BAD REQUEST

{
  "detail": [
    {
      "name": "description",
      "reason": "Invalid characters detected."
    }
  ],
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

@Bento007 - This is now ready for production.

**Comment by danieljhegeman** [comment]
This was intended to be applied _only_ to the Collection `name` field because we need hyperlinks to be functioning on the UI; the `name` is used for the hyperlink.

It should *NOT* be applied to `description`.

Additionally, the main point of this issue was to prevent non-printable characters. I suppose 7F (DEL) is a good character to include as unacceptable, but many characters in the `\x7f-\xa0` range that was introduced [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/2eb67762965ce597cd0d61ed71867f4435918c70/backend/corpora/common/utils/regex.py#L8) should be considered acceptable, not unacceptable.

So maybe let's just include `\x7f\x81\x8d\x8f\x90\x9d\xa0` in the regex (i.e., unacceptable chars) per [this table](https://www.ascii-code.com/) rather than the broad swath of the extended ascii chars that is currently there.

**Comment by danieljhegeman** [comment]
On this note, however, we should also make sure that the FE is properly representing to the user that their chosen Collection `name` is not acceptable if it contains these characters. I don't think that's happening right now.
