### ISSUE TITLE
feat(wmg-download):allow download of single tissue with correct layout

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#3174]
Needs:
- [x] Correct layout of:
   - [x] Heatmap
   - [x] Axes
   - [x] Legend
       - [x] temporary pull out of legend?
   - [x] general styles
      - [x] padding
- [x] Rough attempt at download button + dialog
---
Out of scope:
- Multiple Tissues

----
Feature Branch: `feat/wmg-download-1`

**Comment by ashin-czi** [comment]
Showing progress:
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/3e6ebbf4-8b77-409c-b72a-e873510b66db)

Also curious whether the Beta message should be a Callout or [Notification](https://chanzuckerberg.github.io/sci-components/?path=/story/notification--default)? Currently it's coded as a Callout but in Figma it looks like a Notifcation. But when I try to switch it to Notification it doesn't seem to take the CSS styles:
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/b75acd42-fa69-40a3-8acc-203e57800b32)

Open to any thoughts or suggestions!

**Comment by seve** [comment]
* Planning on landing #3220 today.  

* Currently working on tweaking aspects of html-to-image to allow for custom styles for copied + captured nodes.
   * Hopefully these changes will be accepted upstream by the maintainer
   * If not, we could use my fork while determining course of action

**Comment by seve** [comment]
* #3220 is ready to merge
* Made really solid progress today on adapting the html-to-image library to our needs. Will post some screenshots tomorrow!
