### ISSUE TITLE
Add test outcome dashboard for DX

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3190]
Source:

https://elaichenkov.medium.com/allure-report-integration-with-playwright-8c1570c67dda

Goal:
1. This ticket aims to spin up an allure test report after `npm run test` via adding npm `postrun` command as described in the doc above
1. We have a separate ticket to generate a test dashboard in [GHA here](https://app.zenhub.com/workspace/o/chanzuckerberg/single-cell-data-portal/issues/3193), which will be utilizing a [different GHA plugin](https://github.com/marketplace/actions/allure-html-reporter-github-pages) than the one used in the doc, in order to get test run history support

**Comment by seve** [comment]
What's DX?

**Comment by tihuan** [comment]
Developer experience!

**Comment by tihuan** [comment]
@ashin-czi I updated the ticket description, hopefully that's enough! If not please let me know 🙏 Thank you!

**Comment by tihuan** [comment]
Actually it doesn't seem super useful to have the dashboard locally, so let's close it! Thank you!
