### ISSUE TITLE
Allow reference to revision Datasets via `original_id`

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3208]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1661819222477019). 

When a revision is created, not only does the revision Collection have a different `id` than the published Collection, but each Dataset in the revision has a different `id` than each published Dataset (with revision Datasets tracking their published counterparts through `dataset.original_id`.

Revision Datasets should be specifiable by both their `id` and their `original_id`. Otherwise, it is much more difficult for users to make meaningful use of the dataset id through the revision iteration process.

Nothing should change for the handling of `curator_tag`. Tags are copied from published Dataset to revision Dataset as-is. If the tag gets updated, which would only ever happen by direct action taken by the curator, then it's on the curator to use the new tag to specify that revision Dataset going forward during that revision rather than the original/old tag for that Dataset.

## Requirements
- Update `GET collection/{collection_id}` to return `revision_of` for each dataset.
- -Update `GET collection/{collection_id}/datasets/` to return `revision_of` for each dataset.
- `revison_of` in a dataset is the dataset_id of the published dataset. This field is only populated when retrieving a collection by is ID or a dataset by its identifier. Otherwise, the field is None.
- `revision_of` for a dataset is *not* returned when listing collections from `GET collections/` 
_**\*\*\*SEE FIRST COMMENT BELOW\*\*\***_

**Comment by danieljhegeman** [comment]
Ok, so, the one problem with actually _allowing_ this reference-by-proxy thing as described above is that it opens Pandora's box when it comes to how all revision entities might be treated, aka "why not allow a curator to refer to a revision Collection with it's public id when making edits?". It would be sort of unclear where we would draw the line.

I am leaning toward adding `original_id` to the `dataset` schema that is returned by `GET /collections/{collection_id}`. From there, curators can programmatically grab the revision `id` by looking for the dataset with `original_id` == <published dataset id>.

With the convenience methods, it's quite trivial:
```
published_dataset_id = <some uuid>
collection = get_collection(<collection_id>)
for dataset in collection["datasets"]:
    if dataset["original_id"] == published_dataset_id:
        revision_dataset_id = dataset["id"]
        ...
```

Thoughts, @Bento007 and @brianraymor and @jahilton ?

**Comment by jahilton** [comment]
>why not allow a curator to refer to a revision Collection with it's public id when making edits

I agree that if we use the published ID as a synonym/alias for the revision dataset, then one would also expect to do the same with the published ID for a Collection. But I am not seeing the issue with that.

**Comment by Bento007** [comment]
This would be better as an update to the DbDataset table.

In addition to the changes proposed by @danieljhegeman, we can also modify the code to accept both the original and new id for operations on the dataset. This would only require modifying a DB query to get the correct dataset to update.

**Comment by brianraymor** [comment]
Decisions from the call with @danieljhegeman and @Bento007 

1. The API will **NOT** support the ability to specify `revision_id` or (original)`id` as _synonyms._ That adds too much complexity and could be addressed by the use of `curator_tag`. 
2. The API will add `revision_of` to the dataset detail to allow easy mapping between the original and revision dataset id(s) in convenience functions.

**Comment by jahilton** [comment]
>could be addressed by the use of curator_tag.

I am fine with the outcome, but should note the faulty logic of relying on `curator_tag` as a solution when #3153 exists

**Comment by brianraymor** [comment]
> faulty logic
It was noted as one scenario for _what curator_tag might be good for_.  I consider futures to still be _in play_ to some degree.

**Comment by danieljhegeman** [comment]
We absolutely should not deprecate `curator_tag`. I have commented accordingly on #3153.
