### ISSUE TITLE
Authorization headers are not consistently documented in the swagger API

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3212]
Is there a [formal way](https://swagger.io/docs/specification/authentication/) to document security schemes in swagger? 

For example>

POST ../token - Returns a bearer access token t**hat must be passed as a parameter to requests that require authorization** such as creating a new Collection.

but when I review one example:

POST ../collections - Create a new Collection

There is no reference for how the access token is passed in the request? 

It only seems to be documented in the description for:

GET ../collections - 
When the visibility parameter is unspecified or set to PUBLIC, a list of all public collections is returned. **The Authorization header is not required.** If a collection in the list has been deleted, then it is annotated with tombstone set to True.

When the visibility parameter is set to PRIVATE, a list of all private collections that the user is authorized to access is returned. **The Authorization header is required**. If a collection in the list is a private revision of a public collection, then it is

**Comment by Bento007** [comment]
We only documented it when it is an optional parameter that affects the response. We can add more documentation to the `/v1/auth/token: POST` endpoint with instructions on how it should be used.

The openapi spec does inform the user when authentication is required. What other details would you like?

**Comment by brianraymor** [comment]
I was curious about whether there is *formal* markdown that can be added as a security schema to all requests that MAY require an authorization header.

**Comment by Bento007** [comment]
I'll add some markdown to endpoint that required auth. Openapi doesn't do it for us. It only gives us the little padlock next to the endpoint.

**Comment by brianraymor** [comment]
For example, I was wondering about - https://github.com/OAI/OpenAPI-Specification/issues/14#issuecomment-297457320

**Comment by Bento007** [comment]
We have that defined in the openapi spec. https://github.com/chanzuckerberg/single-cell-data-portal/blob/6404a803a1650ed414c585a5f3e39e3725445262/backend/config/curation-api.yml#L60-L62

**Comment by brianraymor** [comment]
GET /v1/collections/{uuid}

**Optional: provide your access token in the request header as Authentication: Bearer <access_token>.**

Is it optional or is it required in specific scenarios? 

---

PATCH /v1/collections/{uuid}

**Optional: provide your access token in the request header as Authentication: Bearer <access_token>.**

Isn't it always required?

---

POST /v1/collections/{uuid}/datasets

No reference to authentication token?

---

GET /v1/collections/{uuid]/datasets/{uuid}

No reference to authentication token?

---


GET .../assets

No reference to authentication token?

---

**Comment by Bento007** [comment]
The endpoints with no authentication token reference do not use the token. I added further details to the other two https://github.com/chanzuckerberg/single-cell-data-portal/pull/3332

**Comment by brianraymor** [comment]
So - `POST /v1/collections/{uuid}/datasets `- does not require a authentication token?

**Comment by Bento007** [comment]
You're right we do. My mistake. Thank you @danieljhegeman for adding it in.
