### ISSUE TITLE
Analytics (update): update add_gene event for explorer

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3218]
### Overview
**Tool**: Explorer
- Feature (Optional):

**Description**: Right now, the ADD_GENE_AND events do not capture the use case of a user creating a gene set and then adding a gene. We would like to include this as part of the explorer engagement metric

### Updates needed
`ADD_GENE_AND` events
- Current: User adds a gene to quick add gene section
- Requested change: Include when a user creating a gene set and then adds a gene

#### People to cc
**PM**: @signechambers1 
**DS**: @ainfeld 

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by tihuan** [comment]
Closing! Amanda confirmed that this is not needed anymore!
