### ISSUE TITLE
Accept and return a DOI reference

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3224]
**September 7 Refinement**

See [curation-api](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1662569310534489?thread_ts=1662512390.544879&cid=C02UGUV5R3J).

Historically, DOIs were simply another type of link in the set of links with no special requirements such as "only one". When we decided to use the DOI for Data consumers can use publication metadata to find datasets in the portal, we made multiple changes to the UX:

1. There can be only one DOI.
1. The curator is prompted with "doi:" and only types in the doi curie reference and not a URL.
1. Using the DOI, publication metadata is queried from crossref.
1. That information is used to create a standard citation - the human readable name for the anchor link. - instead of allowing the curator to provide a name.

Based on this context, there was agreement to refactor the DOI as a separate field in the collection information instead of including with the other links. This also makes it easier for consumers to access the DOI without iterating through all links looking for a link type of "DOI".

---

See [curation-api](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1662054584720389). 

Instead of a URL, endpoints that accept or return a DOI must model the DOI as a **reference**:

` curie       :=   [ [ prefix ] ':' ] reference`

For example, the reference for doi:10.1016/j.cell.2021.01.053 curie is 10.1016/j.cell.2021.01.053 - eliminating the "doi" prefix and the ":" separator. 

This matches the curator experience from the curator UX which prompts with a read-only 'doi:' `prefix` and separator. The curator only adds the **DOI reference**.

Returning the DOI reference in responses, helps consumers of the metadata because no information needs to be stripped before the `DOI` can be passed to services such as crossref or semantic scholar:

```

https://api.crossref.org/works/10.1016/j.cell.2021.01.053

```

**Comment by danieljhegeman** [comment]
@brianraymor do you have any more context on what _does_ and what _doesn't_ count as an acceptable `prefix`?

Also... see the [official doi docs](https://www.doi.org/overview/DOI_article_ELIS3.pdf) on `prefix`. This doesn't seem to comport exactly with what you've outlined above. Is it possible that, in your description above, you meant to use the term `proxy`?

**Comment by brianraymor** [comment]
I'm using the syntax from [CURIE Syntax 1.0](https://www.w3.org/TR/2010/NOTE-curie-20101216/#s_syntax).

> The following definition makes the set of CURIEs a syntactic superset of the set of QNames. It is comprised of two components, a prefix and a reference. The prefix is separated from the reference by a colon (:).

**Comment by danieljhegeman** [comment]
Ah. Ok. So that is a 'CURIE prefix' and not a 'DOI prefix'.

**Comment by brianraymor** [comment]
Also see [**Registry**  Digital Object Identifier](https://bioregistry.io/registry/doi) for examples and regex.

**Comment by danieljhegeman** [comment]
Ok, final clarification: you, @brianraymor, have indicated that you would like to see just the reference returned in responses. This make sense to me.

@jahilton 's initial comment in Slack was to the effect of wanting the Curator API to _reject_ any attempt to create or update a Collection with a DOI that contains prefixes (or anything other than just the reference). 

Am I to follow Jason's wishes here? In my thinking, it makes the most sense to permissively accept as many different forms of (valid) DOIs as possible, and then _store_ (and return in responses) _only the reference_.

**Comment by brianraymor** [comment]
> it is unclear to me if that means you agree with @jahilton 's request 

I agree with @jahilton. Let me attempt to be more precise. 

---

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED" "MAY", and "OPTIONAL" in this document are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14), [RFC2119](https://www.rfc-editor.org/rfc/rfc2119.txt), and [RFC8174](https://www.rfc-editor.org/rfc/rfc8174.txt) when, and only when, they appear in all capitals, as shown here.

**Endpoints that accept a DOI value**

Endpoints that accept a DOI value **MUST** reject a value that is not a valid DOI curie reference, as "reference" is specified in [CURIE Syntax 1.0](https://www.w3.org/TR/2010/NOTE-curie-20101216/#s_syntax). Other [valid DOI formats](https://bioregistry.io/registry/doi) such as `https://doi.org/<identifier>` or `doi:<identifier>` MUST fail and return an error. 

**Endpoints that return a DOI value**

Endpoints that return a DOI value **MUST** model the value as a valid DOI curie reference.

---

> it makes the most sense to permissively accept as many different forms of (valid) DOIs as possible

It makes the most sense to whom? Unfortunately, it would increase our test matrix which is already complex. 

Your perspective is basically Postel's _Be liberal in what you accept, and conservative in what you send"_.  [The Harmful Consequences of the Robustness Principle](https://datatracker.ietf.org/doc/html/draft-thomson-postel-was-wrong-03) might be informative.

**Comment by danieljhegeman** [comment]
Excellent, thank you for the clarification!

**Comment by brianraymor** [comment]
Just a reminder to update the swagger which in @Bento007's version is:

If the link_type is DOI, then the link_url must be a valid DOI link and the link_name will be ignored or overwritten if provided. For example, https://doi.org/00.0000/science.abc1234 is a valid DOI link_url. All other links types can be any valid URL.

**Comment by danieljhegeman** [comment]
So, just for full transparency, here's the plan:
- reject all requests via the Curation API that contain DOIs that are not strictly a curie reference
- use legacy code to process & convert the curie reference to a link (which the FE expects)
- trim the stored links back down to curie reference before returning anything requested via Curation API

**Comment by brianraymor** [comment]
Or you could let the FE slap a "https://doi.org/" prefix on the DOI reference for its use in the citation link.

**Comment by danieljhegeman** [comment]
>The long term objective is to deprecate the portal v0 API.

Sure, but is explicitly rejecting link-formatted DOIs also a longterm objective?

One thing here is that it requires zero work to accept link-formatted DOIs via the Curation API because it is already implemented and tested with legacy Corpora API code. Actually rejecting these requires engineering effort.

Returning just the curie reference requires the same effort either way.

**Comment by danieljhegeman** [comment]
I know there's been a lot of back-and-forth on this topic, but I am having a hard time justifying the engineering effort to disallow link-formatted DOIs and I am worried there might have been a miscommunication about how we can best satisfy the genuine desires of the curators like Jason.

I presume his primary concern is _receiving_ the curie reference only when he pings the Curation API. This makes sense.

But is it also important for a procedural or data quality reason (one on the curation side which I am missing) that we _reject_ link-formatted DOIs? Again, I get that if we were building anew, we would not accept them. But the code is already there.

**Comment by danieljhegeman** [comment]
Oh, hold on. Do you wish for me to reformat the way the _Corpora_ API works as well for the UX, and to start rejecting all DOIs that are not curie reference format?

**Comment by brianraymor** [comment]
I do not strongly care (choose your own adventure) as long as the requirements for the Curation API are met. 

No curator is typing in DOI links in the UX based on the earlier simplification. The only reason that the v0 API uses links is for legacy reasons and a quick implementation. We did discuss changing it back then. 

The UX only needs a link for the citation in the Collection that it can construct itself. Happy to wait until we deprecate v0 to make additional changes.

**Comment by danieljhegeman** [comment]
>as long as the requirements for the Curation API are met.

This means I must reject link-formatted DOIs, correct? Confirm, and proceed I shall.

**Comment by danieljhegeman** [comment]
might I suggest that we _allow_ link-formatted DOIs for now, and then at a later date, once we are ready to update the Corpora API as well, we start rejecting them. This way we can avoid doubled-engineering effort to produce two separate processing pathways when, as you've said, they should both be the same eventually.

**Comment by brianraymor** [comment]
> This means I must reject link-formatted DOIs, correct? Confirm, and proceed I shall.

Confirmed that you must reject link-formatted DOIs in the **curation API.** That is the requirement as [stated above](https://github.com/chanzuckerberg/single-cell-data-portal/issues/3224#issuecomment-1235051586).

**Comment by danieljhegeman** [comment]
Please see most recent comment.

**Comment by danieljhegeman** [comment]
Will be rejecting, via the Curation API, DOIs that are not curie reference format. The Corpora API will continue to accept link-formatted DOIs for now.

**Comment by danieljhegeman** [comment]
Must decide how to handle the fact that the CURIE reference's intended field at the moment is `"link_url"` which is a bit of a misnomer.

**Comment by danieljhegeman** [comment]
@brianraymor with regard to moving from having the doi in the links to having it as a separate field: should we just plan on leaving the FE as-is for now, where the doi will continue to be received from the curator as a link, even though we will _store_ it on the BE under `dataset.doi`?

**Comment by danieljhegeman** [comment]
Nevermind, the db change is going to be too complicated. I'm only going to change the request/response shape for the Curator API for now.
