### ISSUE TITLE
The mysterious affair of the hesitant collections

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3232]
Simple code loop to fetch full collection details for all collections using the curation API notebooks:

```

collections = get_collections() 
for collection in collections:
    c = get_collection(collection['id'])

```

Yesterday, I noticed consistent timeout exceptions for the "baff" collection in my original portal v0 notebooks that include a retry strategy in `requests` I had to increase the timeout value as a mitigation. This code has been stable for more than a year with no issues. (I use it to generate metadata snapshots for review) 

Today, I tested with the new curation API. Instrumenting with`timeit` shows two collections that are consistently slower to access than most collections:

'a238e9fa-2bdf-41df-8522-69046f99baff - time - 4.0769691670000014'
'a238e9fa-2bdf-41df-8522-69046f99baff - time - 4.0899842910000075'

'0b9d8a04-bb9d-44da-aa27-705bb65b54eb - time - 1.145810333'
'0b9d8a04-bb9d-44da-aa27-705bb65b54eb - time - 1.1261931669999967'

Most others are in this range:

'83ed3be8-4cb9-43e6-9aaa-3fbbf5d1bd3a - time - 0.18544224999999415'
'92fde064-2fb4-41f8-b85c-c6904000b859 - time - 0.14699704200000951'
'eb735cc9-d0a7-48fa-b255-db726bf365af - time - 0.18146912500000667'

**Comment by danieljhegeman** [comment]
Wait, this is the Curation API? I assumed it was the corpora API since you said "This code has been stable for **more than a year** with no issues"

**Comment by danieljhegeman** [comment]
```corpora_dev=> select count(id) from dataset where collection_id = 'a238e9fa-2bdf-41df-8522-69046f99baff';
 count 
-------
  1025

corpora_dev=> select count(id) from dataset where collection_id = '0b9d8a04-bb9d-44da-aa27-705bb65b54eb';
 count 
-------
   297
```

**Comment by danieljhegeman** [comment]
These dev collections both have a ton of tombstoned datasets

**Comment by brianraymor** [comment]
> These dev collections

I was testing in production. I was under the impression that we had disabled the _tombstone_ code until we could redesign it to NOT return false positives.

**Comment by danieljhegeman** [comment]
We have a filter in the query for `GET /collections` and `GET /collections/{collection_id}` that means we do not return tombstoned Datasets.

However, the `dataset.tombstone` column is not indexed in our db, so the query is taking a little extra time.

We had a discussion somewhere else that was tracking the issue of "too many tombstones" in the prod db... do you happen to remember where this was?

Also, do you know if we have the requirements for tombstoning (when it should/shouldn't occur) written out somewhere? I should probably revisit to make sure things line up.

**Comment by brianraymor** [comment]
There were multiple threads related to _tombstones_ :

[curation-api](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1659637804548329?thread_ts=1659634685.805479&cid=C02UGUV5R3J)
[curation-api](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660002464125269?thread_ts=1660001965.293949&cid=C02UGUV5R3J)
[curation-api](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660072092992529).

Also see the summary and notes in [Return withdrawn collections and datasets](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2971).

**Comment by danieljhegeman** [comment]
Thanks. Unfortunately none of those give us an answer on whether we deleted tombstoned Collections/Datasets at any point in the last few months. 

But I took a closer look at the two Collections that you had pointed out (with ~1000 and ~250 tombstoned Datasets) -- their tombstoned Datasets were all created about a year ago. For one of them, it's clearly an artifact since all of the tombstoned Datasets were created at the exact same time.

Do you wish to draw up a plan to (manually) delete tombstoned entities that should no longer exist in the db?

**Comment by brianraymor** [comment]
My understanding was that this feature was to be removed as part of the earlier bug fix:

> The mitigation was to remove tombstone fields for both collections and datasets until a better mechanism could be designed.

We have a tracking issue for future designs related to tombstones that I included above. As we've also discussed, we're only aware of one collection and its datasets that have been withdrawn since launch. Another was deleted and then restored.

**Comment by danieljhegeman** [comment]
> My understanding was that this feature was to be removed as part of the earlier bug fix:

What feature?

> We have a tracking issue for future designs related to tombstones that I included above. As we've also discussed, we're only aware of one collection and its datasets that have been withdrawn since launch. Another was deleted and then restored.

Ok. Then presumably we can specify the one Collection and its associated Datasets that need to be kept, and then we can delete everything else that is tombstoned.

**Comment by brianraymor** [comment]
> What feature

The code and documentation for the feature that uses _tombstones_ to report on withdrawn collections and datasets per the comment:

> The mitigation was to remove tombstone fields for both collections and datasets until a better mechanism could be designed.

> Then presumably we can specify the one Collection and its associated Datasets that need to be kept, and then we can delete everything else that is tombstoned.

That would be a future. The understanding for Q3 was that tombstones were to be disabled and not returned in the API until we had an opportunity to reassign and redesign.

**Comment by brianraymor** [comment]
Closing an a duplicate of @bkmartinjr 's [Receiving spurious 502 HTTP errors from Discover API](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3535)
