### ISSUE TITLE
Differentiate between validation and conversion failures

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3240]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1661965957394719).

Curators can respond to validation failures, but **NOT** conversion failures. 

@jahilton, @danieljhegeman, @Bento007, @brianraymor met and agreed on this refinement:

1. `collection.processing_status` will continue to return `FAILURE`. 
1. For `dataset.processing_status` replace `FAILURE` with `VALIDATION_FAILURE` and `PIPELINE_FAILURE`. 
1. Add `dataset.processing_status_detail` for `VALIDATION_FAILURE` to report the validation failures.
1. Clear `dataset.processing_status_detail` on successful uploads.

**Comment by Bento007** [comment]
Validation fields in the database https://github.com/chanzuckerberg/single-cell-data-portal/blob/9d79c5b66f40216480c44e742a47270b7bb6edc7/backend/corpora/common/corpora_orm.py#L463-L464
