### ISSUE TITLE
Single 400 schema differs from multiple 400 schema

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3242]
[Schema for a single 400 error](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fc0b18d8a19998cbd9e97e717c4594c3341659e4/backend/config/curation-api.yml#L854-L863)

- detail
- title
- type

[Schema for a multiple 400 error](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fc0b18d8a19998cbd9e97e717c4594c3341659e4/backend/config/curation-api.yml#L976-L992)

- name
- reason
- value

I would think these should be identical... @Bento007 you committed both of these sections. Is there context I am missing on these?

**Comment by Bento007** [comment]
Change it to 
```
{ 
"details": str,
"title": str,
"type": str,
"invalid-param": {
 "name": str,
 "reason": str,
 "value": str
```

**Comment by Bento007** [comment]
Trying to follow the spirit of this https://www.rfc-editor.org/rfc/rfc7807 the best we can.

**Comment by danieljhegeman** [comment]
I'm not clear on whether your answer is intended to apply to one or both of '400' and '400 multiple'.

**Comment by brianraymor** [comment]
Does this mean that we expect to fill in the [template](https://www.rfc-editor.org/rfc/rfc7807#section-3.1)? 

 >  This document defines a "problem detail" as a way to carry machine-
   readable details of errors in a HTTP response to avoid the need to
   define new error response formats for HTTP APIs.

This RFC is focused on a specific problem/solution.

**Comment by Bento007** [comment]
We will be doing the latter @brianraymor.

**Comment by Bento007** [comment]
@danieljhegeman  If we can consolidate it into a single error that'd be great.

**Comment by Bento007** [comment]
keep in mind that the UI also uses these error messages. We might need to update the frontend to match that new error shape, or reshape the errors for the curator API specifically.

**Comment by Bento007** [comment]
This does not seem like a P0. What is the motivation for this issue?

**Comment by danieljhegeman** [comment]
@Bento007 we have been treating all issues with documentation--and especially error messages--as p0
