### ISSUE TITLE
SSR Collection Page

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3254]
Context:
SSR DP Collection page currently takes 3 seconds to render:

https://search.google.com/search-console/core-web-vitals/drilldown?resource_id=sc-domain%3Acellxgene.cziscience.com&item_key=CAMQARgC&hl=en

SSR: https://tanstack.com/query/v4/docs/guides/ssr

**Comment by metakuni** [comment]
Hi Timmy, should this issue be closed? Noticed that its [parent epic](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3245) and [blocked by issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3253) have both been closed.

**Comment by tihuan** [comment]
Thanks Kuni! Since it doesn't seem like SEO team has issues with page loading performance so far, I'll close it and reopen it if needed in the future 😄🤘
