### ISSUE TITLE
GET ../collections/{uuid}/datasets/{uuid} MUST document that dataset_id is required

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3258]
@brianraymor commented on [Fri Sep 09 2022](https://github.com/chanzuckerberg/single-cell/issues/343)

Reported by @bkmartinj while experimenting with the API. 

[GET ../collections/{uuid}/datasets](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.collection_id.datasets.actions.get) suggests that both curator_tag and dataset_uuid are optional - rather than one identifier is required. 

With the deprecation of curator_tag, the swagger should be updated to indicate that dataset_id is now required.

**Comment by Bento007** [comment]
this endpoint was replaced with /collection/{collection_id}/datasets/{dataset_id}

**Comment by brianraymor** [comment]
See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1663707013684849).

The latest swagger describes:

**If** a dataset_id is provided as a **query**, the associated Dataset metadata is returned.

but dataset_id is no longer a query parameter but part of the resource path and is required.

**Comment by Bento007** [comment]
corrected those areas https://github.com/chanzuckerberg/single-cell-data-portal/pull/3332

**Comment by brianraymor** [comment]
@Bento007 - LGTM.
