### ISSUE TITLE
Update Gene Expression cell count in tool tip

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3293]
Currently the cell count “cell count” column values don’t always match the tooltip table cell count values. The Cell Count column queries the cube directly, where we suspect the tool tip back calculates the number. This ticket encapsulates the work to update the tool tip so the values match
![Screen Shot 2022-09-15 at 4.24.02 PM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/9f149a3d-7256-4a02-bb83-9102fed9d73b)

**Comment by tihuan** [comment]
Per Alec, we now have cell count directly in API response, so use that for tooltip too!

https://czi-sci.slack.com/archives/C0247APK621/p1663337171342269
