### ISSUE TITLE
Improve delete gene discoverability in Gene Expression

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#3304]
Users are having a hard time discovering the functionality for deleting genes (and likely cell types). This is our top area of feedback with over 7 survey responses. Improving this functionality would make using our tool easier and more intuitive for users.

We'd like to make the trash can icon appear on hover as a simple solution.

[Figma](https://www.figma.com/file/JS5ThqTBcpAVuBFglAItKf/Gene-Search?node-id=5355%3A571308&t=ebsOeiwNMeva7tlz-1)

cc @signechambers1 @hthomas-czi for questions

**Comment by signechambers1** [comment]
@hthomas-czi to add design.

**Comment by ashin-czi** [comment]
@signechambers1 @hthomas-czi rdev can be viewed here! https://delete-gene-frontend.rdev.single-cell.czi.technology/gene-expression

**Comment by ashin-czi** [comment]
Waiting on analytics

**Comment by signechambers1** [comment]
@ashin-czi looking good! Thank you. A couple questions FYI @hthomas-czi :

- The gene name is still clickable, but clicking it doesn't do anything. Can we make the gene name unclickable?
- The delete functionality is very fast, but the loading indicator still shows up which is kind of distracting. Is it necessary in this instance?

**Comment by ashin-czi** [comment]
@signechambers1 The gene labels should now be unclickable! PTAL when you get the chance! Hoping to get this out to Staging tomorrow

https://delete-gene-frontend.rdev.single-cell.czi.technology/gene-expression

**Comment by signechambers1** [comment]
@ashin-czi looks great! thank you so much!
