### ISSUE TITLE
chore: Remove redundant Gene Expression documentation page

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#3311]
The following pages are redundant:

1. https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_2__Cell%20Type%20and%20Gene%20Ordering
2. https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_3__Algorithms%20and%20Ontologies

Remover the second one

**Comment by maniarathi** [comment]
Closing as not reproducible.
