### ISSUE TITLE
feat: Standardize cell type ontological ordering across different tissues. 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#3318]
## Need

The tree structure of cell types in Gene Expression can vary from tissue to tissue even if the same cell types are shown.

The tree paths should be the same across all tissues

### Example: 

Monocytes in Lung are shown under myeloid cells:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/29237819/191341522-6cca3a29-be50-4d86-9f27-7b77ce579152.png">

But they are not for Blood:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/29237819/191341675-bd3fc753-73fa-4d9b-a109-eb9aa3502e76.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/29237819/191341753-52b4aa72-1a63-4796-8853-ba6d89c66298.png">

## Approach

Currently the tissue ordering (tree path) is constructed by tissue, the current algorithm can take different tree paths depending on the list of cell types to order.

The solution for this is issue is to build ONE path for all data Gene Expression, and subset this tree for each tissue. This will conserve the tree structure across tissues

**Comment by signechambers1** [comment]
@pablo-gar is this still an issue?

**Comment by pablo-gar** [comment]
No, this was resolved long ago.
