### ISSUE TITLE
make a notebook that demonstrates `POST /datasets`

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3323]
With the addition of the `POST /datasets` endpoint we'll need a new sample notebook. The two notebooks that reflect the two methods for _uploading_ ('local file' and 'upload link') should reference this new notebook since the Dataset must be created before a datafile can be uploaded (whether via local upload to s3 or via upload link provided via API).

Be sure to update the 'example workflow' python notebook.

**Comment by brianraymor** [comment]
I'm not sure that it requires a new notebook. You could have separate add_dataset and replace_dataset where add_dataset returns a dataset id?  The POST could be hidden in add_dataset. Then the example workflow would use add_dataset and replace_dataset in its examples.

**Comment by danieljhegeman** [comment]
It does not require it for the python 'convenience function' approach (`python/`). But it does for the set of Python (`python_raw/`) and R (`R/`) notebooks that demonstrate manual construction of the individual requests.

**Comment by danieljhegeman** [comment]
> Then the example workflow would use add_dataset and replace_dataset in its examples.

I don't think we want to have separate `add_dataset` and `replace_dataset` functions anywhere. The convenience functions will just remain `upload_local_datafile` or `upload_datafile_from_link`, as they have been. No distinction between adding and replacing since everything is now done by specifying the dataset_id. Technically everything is a "replace" operation, even for newly-created empty Datasets.
