### ISSUE TITLE
A refresh is required to display the explore glyph after a dataset is uploaded to a collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3329]
After a dataset has been uploaded, the download glyph is displayed, but not the explore glyph. A manual refresh is required. 

https://images.zenhubusercontent.com/280546849/9049af6d-9b35-4e23-a120-da7e72d2d33a/screen_recording_2022_09_21_at_9_45_05_am.mov

**Comment by danieljhegeman** [comment]
Is this a regression?

**Comment by brianraymor** [comment]
I have not seen this reproduce lately when I've been testing other scenarios.
