### ISSUE TITLE
INVESTIGATE - Smoke test failure from last few weeks

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3372]
**This may not be related to the Curation API work. Need to investigate to confirm.**

https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3160938742/jobs/5146044751#step:7:5188

A 200 response is coming back when the DOI is invalid for Collection creation (smoke test). We need to ensure that refactoring of the BE code didn't mess up the FE. 

This appears to have started [happening prior to Monday Sept 19](https://czi-sci.slack.com/archives/C0244PQK934/p1664477372683019?thread_ts=1664460075.282289&cid=C0244PQK934). Haven't nailed it down yet.

**Comment by metakuni** [comment]
Should we reassign this to @nayib-jose-gloria ?

**Comment by danieljhegeman** [comment]
it is a duplicate; he has the above linked issue assigned to himself
