### ISSUE TITLE
Update cell type and tissue filter ancestor and descendant artifacts

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#3375]
See details in [**filter-by-metadata**](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1664580067792369).

**Comment by brianraymor** [comment]
@NoopDog - I moved this to the epic that we're using for post-migration tidying.

**Comment by brianraymor** [comment]
Discussed on Oct 24 call. @NoopDog verified. Closing.
