### ISSUE TITLE
feat( ):

### ISSUE THREAD

**Issue by bryan3t** [chanzuckerberg/single-cell-data-portal#3396]
## Need
How to download the data and do my own analyses/graphing on Seurat, ScanPy, and other popular single cell analysis toolchains

## Approach

I think it would be super helpful for the community to have a white paper/user guide that provides step by step instructions on how to do so

**Comment by MaximilianLombardo** [comment]
thanks @bryan3t!

**Comment by brianraymor** [comment]
There is documentation for downloading datasets in the AnnData or Seurat formats from CELLxGENE Discover. Please see https://cellxgene.cziscience.com/docs/03__Download%20Published%20Data.

The related _toolchains_ offer step by step tutorials such as https://scanpy.readthedocs.io/en/stable/tutorials.html or https://satijalab.org/seurat/articles/get_started.html.
