### ISSUE TITLE
chore: Delete "n_cells" column from the expression summary cube

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#3401]
Scenario:

Let's say I am querying the expression summary cube by:
 - a cell type
 - a tissue
 - an organism
 - all genes

The result is the following:
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/16548075/194371374-8dd63f6d-848e-4fa7-8161-b4bf5d2d5886.png">

Now, let's say I wish to group by genes and sum to get the total number of cells, expression, etc:
<img width="602" alt="image (1)" src="https://user-images.githubusercontent.com/16548075/194371545-5edef260-754d-4a4c-9f41-d7ccaacb16e9.png">

In parallel, I did the same query for the cell counts cube, grouped by the cell type, and summed:
<img width="470" alt="image (2)" src="https://user-images.githubusercontent.com/16548075/194371652-01ad107c-4d52-45a5-ab3b-b27486ee7834.png">

As you can see, each row in the second image has a different value for "n_cells" and these values are less than the total number of cells identified in the cell counts cube (third image).

This is because of [this line](https://github.com/chanzuckerberg/single-cell-data-portal/blob/400cc28df8429a47b38bf9415b7cf26f0f4afedd/backend/corpus_asset_pipelines/summary_cubes/expression_summary/load.py#L49). Basically, if for a particular combination of filters a gene is not detected whatsoever, it is omitted from the dataframe.

As a result, when constructing the dot plot dataframe in the WMG backend (where we aggregate by genes, tissues, and cell types), the "n_cells" column is incorrect (compare to `n_cells_cell_type`):
<img width="668" alt="image" src="https://user-images.githubusercontent.com/16548075/194372613-a16f5810-78e4-447b-8b2e-7080f982229d.png">

In fact, the "n_cells" column isn't even used anywhere, so it is both misleading and irrelevant. Thus, we should get rid of it from the `expression_summary` cube.

**Comment by atolopko-czi** [comment]
Yes, it can and should be deleted! I believe "misleading and irrelevant" captures its essence. :)
