### ISSUE TITLE
Review existing tests and create test taxonomy

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#3411]
Create a taxonomy classifying all our test types, and documenting differences in which tests are run per environment. It should cover both single-cell-explorer and single-cell-data-portal. 

Should include at least the following test types and basic definitions for what each is meant to provide coverage for: unit tests, smoke tests (push-tests), smoke tests (post-deployment), functional tests, performance tests, and datadog tests. 

If there are environment-specific tests within any of those test types, flag them and why that is the case. 

The taxonomy should be written such that it can be used as a 'rule of thumb' guide for contributing to test coverage, and to help determine whether we have any redundancies, gaps, or tests that aren't consistent with our taxonomy in our testing ecosystem.

**Comment by seve** [comment]
Assigned to myself with plans to work on this and the blocked issue when I return next week.
