### ISSUE TITLE
Investigate and resolve failing 'Invalid DOIs' smoke tests

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#3412]
Address flakey 'Invalid DOIs' tests. Determine if they are providing value as tests. If not, remove them. If so, investigate and update them to fix failures, or otherwise reduce their flakiness or replace them with less flakey test(s) that still provide the expected coverage. 

Example failures (different reported issues): 
- https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3201753174/jobs/5230126887 
- https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3276702818/jobs/5395088931

**Comment by danieljhegeman** [comment]
I think [this](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3372) is the same issue, right?

**Comment by nayib-jose-gloria** [comment]
> I think [this](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3372) is the same issue, right?

yeah, that's a dupe. I'd like to keep this one since its in the context of the improve testing confidence epic
