### ISSUE TITLE
Future Playwright optimizations

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3422]
- [ ] Run blocks in parallel: https://playwright.dev/docs/api/class-test#test-describe-configure
- [ ] Add a11y test: https://playwright.dev/docs/accessibility-testing
- [x] Investigate if we could switch on login in `globalSetup` through Playwright test runner

**Comment by atolopko-czi** [comment]
We should move this to the [Proposal doc](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.3jy6phty684z). Marked as "refine me" as a means to flag that.

**Comment by tihuan** [comment]
1. Run parallel tests is WIP and almost done: https://github.com/chanzuckerberg/single-cell-data-portal/pull/4926
1. a11y tests still need to be added
1. Investigate if we could switch on login in globalSetup through Playwright test runner - done
