### ISSUE TITLE
chore(gene-expression ): legend colorbar label can be improved

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#3426]
The maximum expression value is not "1.0". The tooltips report gene expressions greater than 1.0. If this is meant to signify a normalized scale, this is not clear. I would replace "1.0" with "max" or something. Or actually report the maximum value.

Speaking of which, is there per-column/row normalization? Or are the colors all relative to each other globally? 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/16548075/194952917-e106ae27-b217-42d2-9498-3dcb8ce1c88b.png">

EDIT: Actually, this isn't a bug as I only just realized users could toggle between scaled and unscaled. Perhaps a minor improvement could be to have the legend label reflect the toggle state ("Gene Expression" vs "Gene Expression, Scaled").

**Comment by pablo-gar** [comment]
The fix should not be to change the legend but to correct the calculation so that the values stay in the range [0,1]

**Comment by atarashansky** [comment]
actually, the fix for above should just be to change the label in the legend to "Gene Expression, Scaled" since we do report the scaled expressions in the tooltip.
