### ISSUE TITLE
bug(documentation nit): Curation API OpenAPI Spec refers to 'Authentication' bearer token request header, rather than 'Authorization'

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#3432]
## Describe the bug
Curation API OpenAPI Spec, in the description of multiple endpoints, instructs the user to provide a request header labeled 'Authentication' for bearer token scheme auth. However, the standard HTTP request header for passing bearer tokens is 'Authorization', and that is the header that will be checked for bearer token auth. If a user follows the instructions as written to use the API, they will get a 401 Unauthorized for bearer token security gated endpoints even if they had a proper, authorized bearer token

## Expected behavior
Docs replace instances of 'Authentication' request header with 'Authorization'

**Comment by danieljhegeman** [comment]
I don't think this impacts any of the actual code... so I will be making the fix in the Swagger doc only
