### ISSUE TITLE
Portal Data Management Redesign

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#3433]
Rework the data portal architecture to enhance our data integrity and enable faster development, to better support new types of datasets in 2023.

Tech spec can be found [here](https://docs.google.com/document/d/1tY45bhkd9GzUn6jH_l_UrTFOcbgWYIF-Se1_JYYW9zs/edit#)

**Comment by metakuni** [comment]
This epic will be closed this week once the final PRs are deployed to production.
