### ISSUE TITLE
Write tests for the DatabaseProvider

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#3443]
Write the database tests. These should use a real database rather than a mock. These tests should focus mostly on schema correctness.

**Comment by metakuni** [comment]
Is this work complete or being deferred?

**Comment by ebezzi** [comment]
We don't have explicit tests for the DatabaseProvider, but the code is implicitly tested via the integration test pipeline. Therefore, these aren't immediately necessary but they could be a good improvement for the future.
