### ISSUE TITLE
There MUST be an error message for datasets that exceed UPLOAD_SIZE_LIMIT_BYTES

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3451]
See [#single-cell-three](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1666031935254049).

In the curation UX, there was no requirement for an error message, because the dropbox choose includes:

```
    // Optional. A limit on the size of each file that may be selected, in bytes.
    // If specified, the user will only be able to select files with size
    // less than or equal to this limit.
    // For the purposes of this option, folders have size zero.
    sizeLimit: 1024, // or any positive number
```

For the API, there should be an error message surfaced to inform curators that the dataset has exceed size maximums (currently 30 GB).

**Comment by danieljhegeman** [comment]
The wrinkle here is that both the local-upload-to-s3 and the usage of `PUT /datasets/{dataset_id}` (providing link for downloading the datafile) do not provide an easy means of informing the user directly.

I think the "correct" way to do this would be to surface the error in the UI, although that does break the current UI flow, since as you mentioned @brianraymor the UI prevents even _selecting_ files that would exceed the size limit.

**Comment by danieljhegeman** [comment]
@brianraymor does our `cellxgene-schema` validator tool inform the user that a datafile exceeds the 30 gb limit? Perhaps we can consider that sufficient for now? Theoretically everyone should be validating prior to uploading, though perhaps in the case of a migration this isn't happening...

**Comment by brianraymor** [comment]
Alas, it would be inconsistent. In all other cases, the CLI fails validation locally and on the portal for the same reasons. If the curator neglected local validation (which happens) and uploaded a dataset that exceeds the maximum size, then the operation would silently fail because portal validation would never execute.

And wouldn't it be even simpler to ask the curator to:

```
braymor@CZIMACOS3974 Notebooks % ls -lah zero.h5ad
-rw-r--r--@ 1 braymor  staff   252M Jul 14 09:50 zero.h5ad
```

**Comment by danieljhegeman** [comment]
>and the usage of PUT /datasets/{dataset_id} (providing link for downloading the datafile) do not provide an easy means of informing the user directly
This statement of mine is incorrect. This endpoint _does_ warn of a file being too large, because it checks the remote file size metadata before returning a response to the client.

**Comment by danieljhegeman** [comment]
>Alas, it would be inconsistent. 

In consideration of _consistency_ with respect to Curation API and UX, this file size check should be performed on the client side by the notebook code. The solution there would be to simply state the file size limit, clearly, in the Curation API documentation, and then implement a pre-upload file size check in the notebooks. But, based on the description in the title for this issue, which has a clear ask, I'm going to _assume_ that is not sufficient, and that we need to handle the case where the curator still uploads a file that is too large.

**Comment by danieljhegeman** [comment]
@brianraymor cc @ebezzi @Bento007 After considering a few approaches, I have a fix coming that will ensure that files that are too large and that _do_ manage to get into the processing queue get their `dataset_processing_status.validation_status` marked as `INVALID`; we will return the dataset `processing_status` as `VALIDATION_FAILURE`.

**Comment by brianraymor** [comment]
How will the curator know that the failure is specifically due to size? I'd also recommending solutions with @jahilton prior to implementation.

**Comment by danieljhegeman** [comment]
I am investigating the logic required to specify a [processing_status_detail](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.collection_id.actions.get:~:text=%22processing_status_detail%22%3A%20%22string%22%2C) for this case

**Comment by Bento007** [comment]
`processing_status_detail` is the `validation_message`

**Comment by danieljhegeman** [comment]
The `processing_status` is not getting reported correctly. I need to make changes and add an appropriate unit test for that portion of the logic as well.
