### ISSUE TITLE
Data consumers prefer text labels for download and viewer

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3465]
See [**#single-cell-ux**](https://czi-sci.slack.com/archives/C02450L5YAX/p1663102096344029) for context.

Data consumers struggle to interpret the image for the button that opens CELLxGENE explorer:

![Screen Shot 2022-10-19 at 1.39.48 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/f0bfe034-73d4-4557-8b16-f8daaec8bfca)

General feedback has been that text labels would be preferable. All instances of the current download and explore image on the collection detail and datasets view:

![Screen Shot 2022-10-19 at 1.37.42 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/d30f02a6-3633-449a-a42a-636ecd6a5b49)

must be replaced with [Download and Viewer text labels](https://www.figma.com/file/5X1Y2CHUjLOIu6MiuMsut1/Consortia-Collection?node-id=11%3A31357)

**Comment by metakuni** [comment]
See also #1629 regarding Plausible events for analytics

**Comment by brianraymor** [comment]
There are actually two analytics issues (see also #1630) but based on my conversation with Amanda, @maniarathi intends to assign that work to another Dev. It's intentionally not in scope for this issue.

**Comment by metakuni** [comment]
Ah, gotcha, was just referencing it to connect the dots after chatting with @ainfeld .

**Comment by NoopDog** [comment]
Hi, @hthomas-czi can you give Fran and me access to the attached Figma above? Thanks, D

**Comment by NoopDog** [comment]
This is deployed to prod.
