### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#3483]
Update relevant docs including but not limited to:
* [Cellxgene Platform Technical Overview](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.7wimlorgnmka)
* [CELLxGENE Technical Improvements Roadmap](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.3jy6phty684z) - If any residual work that couldn't be completed in Q4 and/or to capture ideas for future improvements

**Comment by ebezzi** [comment]
Docs have been updated and proposals have been issued. Closing.
