### ISSUE TITLE
Investigate enabling svg for download image for Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3487]
FEATURE BRANCH:

https://github.com/chanzuckerberg/single-cell-data-portal/pull/3998

Investigate what it would take to enable svg for download image for Gene Expression. Currently the svg isn't a full vectorized image.

[Figma](https://www.figma.com/file/JS5ThqTBcpAVuBFglAItKf/Gene-Search?t=7HKrKhbK4D3Faxc4-0)

Value - Increase the number of downloads, increase our chances of publishing GE dot plots in publications due to the high-quality SVG, and raise our standards to the gold standard of image quality for users.
Reasoning - We want more users to download our dot plots and use them in their work via publication or the ability to share and collaborate. SVG image quality is much higher than our current format, allowing them to visualize/analyze the dot plot. This reasoning is also consistent with multiple users requesting this via the UXR feedback process.

**Comment by tihuan** [comment]
@seve I might be able to look into this during HQ week! Can you please add some context and discovery work that's been done so far, and I'll take it from there. Thank you!

**Comment by signechambers1** [comment]
@seve can you add a little more background on what you've done so far to this ticket? @tihuan are you still picking this up? fyi @dsadgat

**Comment by tihuan** [comment]
I think @dsadgat said to not work on this in Q4, so it's not on my todo list at the moment. But having the context ready from Seve will help resolve the issue faster later for sure!

Thank you 😄

**Comment by dsadgat** [comment]
Updating the urgency here because i recently became aware that this might be an issue with eCharts, and we need to understand if implementing this is blocked by the UI tech spike

**Comment by tihuan** [comment]
Echarts supports SVG rendering, so I think this ticket shouldn't be blocked by the tech spike

A solution I have in mind is that when a user wants to download the SVG option, we re-render the heat map in SVG, save the screenshots, and then render the heat map in canvas again for interaction

If things go well, the solution can be done in a day or two!

**Comment by seve** [comment]
Generate a new heatmap using Echart's SVG renderer. Take the screenshot, then destroy the heatmap. All while the heatmap is tinted.

**Comment by seve** [comment]
Worth implementing this for both PNG and SVG rendering

**Comment by seve** [comment]
Risk: SCG render takes a long time, slowing down the download process

**Comment by seve** [comment]
Alternative backups:
* Open new window/tab do render there and download
* Do rendering and image generation on the server and send the image over the wire

**Comment by tihuan** [comment]
Currently testing out generating SVG for labels ourselves to avoid foreignObject, which is invalid for image editor. Hopefully can be done in 3 days

After that’s done, will go back to adding SVG option in WMG

**Comment by tihuan** [comment]
The new approach of re-creating SVG is working, so I'll split this ticket into smaller chucks to fit into sprints better!
