### ISSUE TITLE
Gene Expression survey must be updated to include link to Data We Collect in privacy policy

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3495]
**Placeholder until the policy draft is finalized and published.**

Wyatt reviewed the survey and noted that it should contain a link to the **Data We Collect** section in the updated privacy policy.

**Comment by brianraymor** [comment]
@signechambers1 @MegUrisko - The Privacy policy was updated on December 15 so this is unblocked.

**Comment by signechambers1** [comment]
@MegUrisko reports this has been addressed with legal and no further action is required, closing.
