### ISSUE TITLE
Add temporary redirect notice on Gitbook site

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3510]
We have SEO plan to add a redirect from docs.cellxgene.cziscience.com to https://cellxgene.cziscience.com/docs, but until the work is done, we need to temporary solution on the Gitbook site to let the current users know where to find the new content!

Gitbook: https://app.gitbook.com/o/-McoHix1O4OcxwAcIqZi/c/-MeSvEjvftHK47ocOlpc

Please ask Ambrose or Nik for Gitbook access to add the redirect notice

Thank you!

**Comment by metakuni** [comment]
Hi @tihuan , is this still relevant? Sorry, I have zero context on the issue!
