### ISSUE TITLE
chore(WMG): Add server timings to the query API

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#3512]
The query endpoint has periodically exhibited unexpected slowness.

We should add server timings to different blocks of the code to easily see which chunks (e.g. the tiledb query) are the cause of the slowness.

**Comment by metakuni** [comment]
Example of recent performance degredation:
- https://github.com/chanzuckerberg/single-cell-data-portal/issues/3512

**Comment by atolopko-czi** [comment]
Wait on this until #3511 is completed.  The performance issues could be caused by web server capacity being exceeded (i.e. requests are enqueued for too long), rather than WMG queries taking longer than usual.
