### ISSUE TITLE
remove `--fix` in lint and add `--fix` to both `next lint` and `stylelint` in `npm run format`

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#3519]
Hmm great point! Maybe we should remove `--fix` here and add `--fix` to both `next lint` and `stylelint` in `npm run format`?

Thanks for catching this!

_Originally posted by @tihuan in https://github.com/chanzuckerberg/single-cell-data-portal/pull/3517#discussion_r1010648681_

**Comment by tihuan** [comment]
Thanks for creating this ticket, @seve ! Added to e2e test epic!
