### ISSUE TITLE
[Staging] `/userinfo` endpoint occasionally takes 40s to resolve

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3530]
Examples:
 
x-request-id: 824bd98d-9a28-473d-84b2-36d2c5db37e2
x-request-id: 1668ee3a-d4f8-48b0-9112-9799817633a6

**Comment by metakuni** [comment]
@tihuan , have you seen this issue since the redesigned portal was deployed to prod?

cc: @nayib-jose-gloria

**Comment by tihuan** [comment]
Oh wow nice! Can confirm this no longer happens ✨ Thanks all!
