### ISSUE TITLE
Receiving spurious 502 HTTP errors from Discover API

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/single-cell-data-portal#3535]
## Describe the bug

The api.cellxgene.cziscience.com REST API periodically returns a 502.  Retrying the same URI a few seconds later will work, and there does not appear to be a consistent pattern to which endpoints fail.  

Running the test script below will usually fail in < 1 minute, after 1000-2000 requests, suggesting that ~0.1% of the requests fail.  Given the API structure, which requires many per-dataset requests to grab the dataset catalog, this is a high failure rate.

A sampling of URIs that have failed in a recent test (but which work upon retry):
* https://api.cellxgene.cziscience.com/curation/v1/collections/c353707f-09a4-4f12-92a0-cb741e57e5f0/datasets/124744b8-4681-474a-9894-683896122708
* https://api.cellxgene.cziscience.com/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/ce19be17-f066-452f-922e-b1f232ce8af5
* https://api.cellxgene.cziscience.com/curation/v1/collections/2d2e2acd-dade-489f-a2da-6c11aa654028/datasets/4023a2bc-6325-47db-bfdf-9639e91042c2/assets
* https://api.cellxgene.cziscience.com/curation/v1/collections/29f92179-ca10-4309-a32b-d383d80347c1/datasets/eeacb0c1-2217-4cf6-b8ce-1f0fedf1b569/assets

## To Reproduce
Test script included below.

## Expected behavior
We should not generate a 502 in the normal course of API use.

## Environment
N/A

## Additional context
N/A

```python
import argparse
import concurrent.futures
import logging
import multiprocessing
import sys
import urllib.parse
​
import requests
​
CXG_BASE_URI = "https://api.cellxgene.cziscience.com/"  # default - can override on the CLI
​
​
def load_datasets_manifest_from_CxG(args: argparse.Namespace) -> dict[str, dict]:
    logging.info("Loading datasets manifest from CELLxGENE data portal...")
​
    # Load all collections and extract dataset_id
    collections = fetch_json(urllib.parse.urljoin(args.api_url, "curation/v1/collections"))
    datasets = {
        dataset["id"]: {
            "collection_id": collection["id"],
            "collection_name": collection["name"],
            "dataset_title": dataset.get("title", ""),  # title is optional in schema
            "dataset_id": dataset["id"],
        }
        for collection in collections
        for dataset in collection["datasets"]
        if dataset["tombstone"] is False  # ignore anything that has been deleted
    }
    logging.info(f"Found {len(datasets)} datasets, in {len(collections)} collections")
​
    # load per-dataset schema version
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.max_workers) as tp:
        dataset_metadata = tp.map(
            lambda d: fetch_json(
                urllib.parse.urljoin(
                    args.api_url,
                    f"curation/v1/collections/{d['collection_id']}/datasets/{d['dataset_id']}",
                )
            ),
            datasets.values(),
        )
    for d in dataset_metadata:
        datasets[d["id"]].update(
            {
                "schema_version": d["schema_version"],
                "dataset_title": d["title"],
            }
        )
​
    # Grab the asset URI for each dataset
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.max_workers) as tp:
        dataset_assets = tp.map(
            lambda d: (
                d["dataset_id"],
                fetch_json(
                    urllib.parse.urljoin(
                        args.api_url,
                        f"curation/v1/collections/{d['collection_id']}/datasets/{d['dataset_id']}/assets",
                    )
                ),
            ),
            datasets.values(),
        )
​
    no_asset_found = []
    for dataset_id, assets in dataset_assets:
        assets_h5ad = [a for a in assets if a["filetype"] == "H5AD"]
        if len(assets_h5ad) == 0:
            logging.error(f"Unable to find H5AD asset for dataset id {dataset_id} - ignoring this dataset")
            no_asset_found.append(dataset_id)
        else:
            asset = assets_h5ad[0]
            datasets[dataset_id].update(
                {
                    "corpora_asset_h5ad_uri": asset["presigned_url"],
                    "asset_h5ad_filesize": asset["filesize"],
                }
            )
​
    return datasets
​
​
def main():
    parser = create_args_parser()
    args = parser.parse_args()
​
    level = logging.DEBUG if args.verbose > 1 else logging.INFO if args.verbose == 1 else logging.WARNING
    logging.basicConfig(
        format="%(asctime)s %(process)-7s %(levelname)-8s %(message)s",
        level=level,
        datefmt="%Y-%m-%d %H:%M:%S",
    )
​
    # code elsewhere assumes base URI ends with a slash
    args.api_url = args.api_url + "/" if not args.api_url.endswith("/") else args.api_url
​
    while True:
        load_datasets_manifest_from_CxG(args)
        if not args.repeat:
            break
​
    return 0
​
​
def create_args_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="api_thrasher")
    parser.add_argument(
        "--api-url", type=str, required=False, default=CXG_BASE_URI, help=f"Base API URL (default: {CXG_BASE_URI})"
    )
    parser.add_argument("-v", "--verbose", action="count", default=0, help="Increase logging verbosity")
    parser.add_argument("--repeat", action=argparse.BooleanOptionalAction, default=False, help="Loop until killed")
    parser.add_argument("--max-workers", type=int, default=None, required=False, help="Thread pool size")
    return parser
​
​
def fetch_json(url: str) -> dict:
    logging.info(f"fetch {url}")
    response = requests.get(url)
    response.raise_for_status()
    return response.json()
​
​
if __name__ == "__main__":
    if multiprocessing.get_start_method(True) != "spawn":
        multiprocessing.set_start_method("spawn", True)
​
    sys.exit(main())
```

**Comment by danieljhegeman** [comment]
Do you suppose the "connection failures at TCP / SSL connection setup" was just another flavor of the [502](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html)? 

I think this is one of the ways that we find out that our API -- at least with current infra scale -- is not suited for high concurrent usage. I do not know to what extent this involves Cloudfront settings. But I saw no evidence of errors in the server logs. So, all in all, not terribly unexpected. cc @brianraymor @metakuni

**Comment by bkmartinjr** [comment]
> Do you suppose the "connection failures at TCP / SSL connection setup" was just another flavor of the 502?

Maybe, but I tend to doubt it if the requests are going through CloudFront -- it is battle hardened in this area.  The SSL issue could easily be a client-side issue (ie, in the test script or in Python's SSL lib), rather than backend, as it was a failure to even connect.

I suggest we focus on the 502, as it commonly happens, whereas the SSL was less common - it only showed up once, when I had a single client host trying to drive multiple scripts simultaneously.  

Does cloudfront have separate logs per endpoint, that might shed some light?

**Comment by danieljhegeman** [comment]
>Does cloudfront have separate logs per endpoint, that might shed some light?

@Bento007 I looked for logs in our cloudfront but I do not see any logs associated with [the distribution associated with the data portal dev API](https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-west-2#/distributions/EMPNGVKA33O95). Also, a search of cloudwatch does not turn up anything for cloudfront specifically.

**Comment by bkmartinjr** [comment]
AFAIK, 502 indicates CloudFront can't connect to the origin server (as opposed to some sort of error after it connects).  For example:  failures to connect at the TCP layer, establish an SSL handshake, etc.  If it is only happening occasionally (my measurements typically fail after ~1500 requests), I wonder if this could be related to a system-level issue on the origin server?  Just brainstorming: 
* the origin server running out of ports temporarily (ie, kernel config) - maybe CloudFront isn't configured to re-use connections between the LB and the origin server?
* is there autoscaling, and maybe it is trying to use a new server before it is ready?
Do you have system level logs on the hosts that might shed some light?

this might also be a good place to ask the AWS support for best practices in debugging.  I'm sure they have seen it before :-)

**Comment by metakuni** [comment]
@atolopko-czi [ran into this issue again today](https://czi-sci.slack.com/archives/C04796YB4Q2/p1674511907370169):
```atolopko
  [38 minutes ago](https://czi-sci.slack.com/archives/C04796YB4Q2/p1674511907370169)
I maybe DOS'ing Curation API again with census builder. I'm getting 502 Server Error: Bad Gateway when iterating through datasets to download. I'm going to slow down the requests.  Just a heads up for now.```

using https://github.com/chanzuckerberg/cell-census/blob/main/tools/cell_census_builder/manifest.py

**Comment by metakuni** [comment]
From [Slack](https://czi-sci.slack.com/archives/C023Q1APASK/p1674775920926559?thread_ts=1674769315.651269&cid=C023Q1APASK):

```
atolopko
  [1 hour ago](https://czi-sci.slack.com/archives/C023Q1APASK/p1674775920926559?thread_ts=1674769315.651269&cid=C023Q1APASK)
And manifest.py is pretty much the same thing
:+1:
1






bruce
  [2 minutes ago](https://czi-sci.slack.com/archives/C023Q1APASK/p1674781035031619?thread_ts=1674769315.651269&cid=C023Q1APASK)
One last update - even with Andrew's work-around (ie., a 1 second delay between requests, half of the concurrency), I'm still getting the errors.   I believe I'm seeing them with increasing frequency today....although that is anecdotal.
```

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria @bkmartinjr @atolopko-czi Bruce's script works on my machine BUT I don't think we're launching requests concurrently as desired. Here's what logging looks like with `--max-workers 32 --verbose`:

```2023-02-01 18:11:01 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/d98ea49e-b70d-4434-b850-bbe217c9b66e
2023-02-01 18:11:01 44518   INFO     fetching...
2023-02-01 18:11:01 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/c2dec445-4116-4b6d-9253-a73f9516460f
2023-02-01 18:11:01 44518   INFO     fetching...
2023-02-01 18:11:02 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/deb385b8-8030-42a4-af1f-aa28932c7344
2023-02-01 18:11:02 44518   INFO     fetching...
2023-02-01 18:11:03 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/34cb364a-c405-478e-8cdd-48a69ae5c5b4
2023-02-01 18:11:03 44518   INFO     fetching...
2023-02-01 18:11:04 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/5f84ba14-4431-4d49-a88f-514cad5a30c8
2023-02-01 18:11:04 44518   INFO     fetching...
2023-02-01 18:11:05 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/a1e16320-801b-4d0a-b60d-ebf9b4130bb4
2023-02-01 18:11:05 44518   INFO     fetching...
2023-02-01 18:11:05 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/9df7a9ce-4298-4d65-9e89-33d83ac8bb69
2023-02-01 18:11:05 44518   INFO     fetching...
2023-02-01 18:11:06 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/a5ecb41a-d1e8-4d6a-954c-30472a2f1007
2023-02-01 18:11:06 44518   INFO     fetching...
2023-02-01 18:11:07 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/df4f1358-4a19-44f5-b136-bc7274c29789
2023-02-01 18:11:07 44518   INFO     fetching...
2023-02-01 18:11:08 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/7f479f74-5a7e-4666-9f0d-3af0b341eb0d
2023-02-01 18:11:08 44518   INFO     fetching...
2023-02-01 18:11:09 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/cb97280b-1c7c-4c55-a921-481062abd9f7
2023-02-01 18:11:09 44518   INFO     fetching...
2023-02-01 18:11:10 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/e6722845-9377-4b34-80a2-7921921e1396
2023-02-01 18:11:10 44518   INFO     fetching...
2023-02-01 18:11:10 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/c97f9167-f7f7-40d4-babf-a47663290c09
2023-02-01 18:11:10 44518   INFO     fetching...
2023-02-01 18:11:11 44518   INFO     received https://api.cellxgene.dev.single-cell.czi.technology/curation/v1/collections/8e880741-bf9a-4c8e-9227-934204631d2a/datasets/6a7c4462-334e-45a4-8aa4-28d3733bbbac```

**Comment by danieljhegeman** [comment]
Fortunately we're not getting 502's

**Comment by danieljhegeman** [comment]
We're getting 2... maybe 4 max... rps 😂

**Comment by danieljhegeman** [comment]
ok I've used a `<urls.json> | parallel -j 32 -P 32 curl {}` script and have verified 32 request in flight simultaneously -- we're still only getting 2-4 rps, so it's a limitation of our current dev server.

Perhaps Bruce's script was tailored to not exceed more than a few dozen requests in flight at once and my reading of the logs was merely the rate at which they were getting processed and not fired off.

**Comment by danieljhegeman** [comment]
I bumped the backend task count from 1 to 6 in the dev env and the same cmd as above ran flawlessly with zero instances of 502s.

**Comment by atolopko-czi** [comment]
At 6 dev service instances, are we at resource parity with prod? Same count & instance types?  

A reasonable outcome of this issue investigation would be to simply record the known RPS rate for a given deployment configuration, in support of [Backen thed API Load Testing](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.kjs0u98nxvnu) proposal. We can then use this to inform discussions (w/PMs) about what our SLOs should be, so that we can later build monitoring/alerting around those SLOs.

**Comment by nayib-jose-gloria** [comment]
@atolopko-czi Yes, that matches prod. Agreed, we should do that as part of this work of performance tuning / tooling

With these tests, I feel good about the keep-alive timeout increase resolving this issue once it reaches prod. Right now, it'll be deployed during next Thursday's production release. Are the 502s enough of a blocker that we should think about a hotfix for today's prod deploy or will regular cycle next week suffice?

**Comment by atolopko-czi** [comment]
> Right now, it'll be deployed during next Thursday's production release. Are the 502s enough of a blocker that we should think about a hotfix for today's prod deploy or will regular cycle next week suffice?

No need for hotfix, thanks!
