### ISSUE TITLE
(FMG): Remove feature flag after PM approval

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#3554]

**Comment by signechambers1** [comment]
I reviewed on staging! Everything looked good except I'm still seeing info icons for cell types with less than 25 cells. This should be hidden per [3689](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3689). We can fix this in next week's release though.
