### ISSUE TITLE
docs(workflow): complete README

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#3555]
Complete descriptions of workflows and jobs not captured by initial test scope

-----
Mind opening an issue to fill out these remaining job steps and link it in the Improve Testing Confidence Documentation epic?

_Originally posted by @nayib-jose-gloria in https://github.com/chanzuckerberg/single-cell-data-portal/pull/3517#discussion_r1014353092_

**Comment by nayib-jose-gloria** [comment]
overflow from test improvement [subepic](chanzuckerberg/single-cell-data-portal#3408), to be worked on by on-call as ongoing work

**Comment by atolopko-czi** [comment]
@nayib-jose-gloria Issue could use more detail as to what documentation is needed and where to put it. Please update or close, if no longer relevant. Ty!

**Comment by atolopko-czi** [comment]
Now a dup of #5942, closing
