### ISSUE TITLE
Ensure that dependencies actually appear where they are required

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3557]
In at least one instance, in single-cell-data-portal, we accidentally rely on `wmg/` dependencies for `api_server/` requirements: `flask` is not list in `backend/api_server/requirements.txt` when it should be.

Would probably be best to find a tool to determine dependencies for different modules within a project/repo.

**Comment by atolopko-czi** [comment]
@danieljhegeman Still relevant?

**Comment by danieljhegeman** [comment]
> @danieljhegeman Still relevant?

Unless this was fixed, yes. I haven't re-assessed.

**Comment by atolopko-czi** [comment]
> > @danieljhegeman Still relevant?
> 
> Unless this was fixed, yes. I haven't re-assessed.

Can you re-assess when you have time? 🙏  (There's too many old issues for a single person to re-confirm the need for each)

**Comment by metakuni** [comment]
Closing due to lack of response. It should also be addressed by #5024.
