### ISSUE TITLE
Bug: when i download the image for gene expression the dot plot scrolls

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3569]
Steps to reproduce:

1. https://cellxgene.cziscience.com/gene-expression
2. Add blood, lung as tissues
3. Add DPM1, FGR, CFH as genes
4. Scroll to the bottom of the dot plot
5. Click download image
6. Dot plot auto scrolls to the top of the dot plot

Desired behavior: dot plot does not scroll when you click download.

**Comment by ashin-czi** [comment]
`  &.CLONED {
    overflow: hidden;
    height: fit-content;
    width: fit-content;
    & ${Wrapper}, ${Container} {
      **height: fit-content;       <--------------- this is what's causing the jump because the height is being changed on the page**
      width: fit-content;
      overflow: hidden;
    }
  }`

Figuring out how to change this behavior

**Comment by ashin-czi** [comment]
finding this a bit more complicated than expected 
@seve @tihuan might need a second pair of eyes on this

**Comment by tihuan** [comment]
Huh interesting! Will take a look later today. Thanks so much, @ashin-czi !
