### ISSUE TITLE
Investigate test__login_flow flaky unit test

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#3571]
https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3415194028/jobs/5684047420#step:7:4122

Determine whether this backend unit test can be made more robust, as it occasionally fails then succeeds on a retry

**Comment by nayib-jose-gloria** [comment]
Overflow work from testing improvement subepic, to be tackled by on-call as ongoing tech debt work

**Comment by metakuni** [comment]
Doh! Apparently, logs from GHA expire! 😅

https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3415194028/jobs/5684047420#step:7:4122

now shows: `The logs for this run have expired and are no longer available.`
