### ISSUE TITLE
feat: Develop system to maintain Gene Expression's Tissue Mapper class in sync with pinned UBERON ontology of h5ad schema 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#3573]
## Need
Currently the Tissue Mapper class used in Gene Expression uses the latest Uberon ontology for mapping tissues to a high-level tissue:

https://github.com/chanzuckerberg/single-cell-data-portal/blob/b80625116f218322e7c83a356790ca2c2aff2f69/backend/wmg/data/tissue_mapper.py#L108-L110

It is straightforward to change the owl file to a pinned version on L108. However a system to retrieve the specific owl based on the [definitions of the schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#required-ontologies) needs be developed.

This information _could_ be taken from this [yaml](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml)

**Comment by brianraymor** [comment]
Also see [Integrate all required ontology processing into ontology preparation](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/357) ...
