### ISSUE TITLE
Enable Biological Consumers to select a version of the Cell Census as basis data in Gene Expression

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3592]
**Description**: Ability for users to select different versions of the Cell Census from GE. Software versioning is crucial because it makes it easier for our users and software developers to keep track of the many releases that we will make. Users want a logical manner to understand when and what updates are made, and they rely on us to keep them up to date. Currently, our process is to release a new version of the census every 6 months. Therefore versioning each census release will be crucial for users in between cycles, publications, and collaborating with other users etc.

**Full Product Options:**
Ability to select different versions in a dropdown within GE
Documented version changes included in each census version should be in a change log

**Priority:** 
Must Have

**User Segment:** 
Computational Biologists
Expert Users
Experimental Biologists
First Time/Naive Single Cell Biologists
General Genomic Researchers

**Dependencies**
Updating GE API for census version selection in collaboration with Data Team

**Risks**
Need to decide with the Data Team and other stakeholders which type of versioning practice we want:

Semantic (SemVer)
Date of Release
Sequential Numbering
Hybrid

**UX/UI Wireframes:**
Not available

**Design Sizing Effort**
Design- small
UXR - none

**Eng Sizing Effort**
XS

**Timeline**
Delivery in Q2 2023

**Comment by dsadgat** [comment]
We did some discovery already and came up with this document https://docs.google.com/document/d/1QnsBbo4c7hCjIGy2It6sLIru7UEHmQp6SJfJvs9SFcg/edit#heading=h.deg5w3fvyfym 

That said, due to the complexity of reproducibility and the requirements we might need to refine, we are removing this requirement for the half.
