### ISSUE TITLE
Bug: Links in Gene Expression documentation are broken

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3593]
All the links in the [body on this documentation page](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_1__Get%20Started) for Gene Expression are broken.

**Comment by pablo-gar** [comment]
Please do not close this issue. The links need to be tested live.
