### ISSUE TITLE
fix flakey wmg func test: test_secondary_filters_extreme_case

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#3594]
The _functional_ test `tests.functional.backend.wmg.test_wmg_api.TestWmgApi.test_secondary_filters_extreme_case` failed transiently on staging deploy. Staging [deployment log](https://docs.google.com/document/d/1G2NTjXTJJeHyhqvnyzYmcO0Um24Ph0dCLUyMIWZvLfg/edit#heading=h.oe3ulww8w91m). Failing [GHA job](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3474111568/jobs/5807046114). Finally succeeded, next day [GHA job](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3474111568/jobs/5822130693).

The _performance_ test `performance.test_wmg_apis.TestWmgApiPerformanceProd.test_secondary_filters_extreme_case` also failed transiently on prod post-deploy.

Suggest adding retries, but this may be due to more data in the snapshots.

**Comment by atolopko-czi** [comment]
See also proposal for [Reduce flakiness of performance & functional tests](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.mzmtsqkw7lyi).

**Comment by atolopko-czi** [comment]
At this point, it is just worth checking the pass/fail history of the test since this issue was reported. If no problems since, we can de-prioritize the issue to a P2.

**Comment by atarashansky** [comment]
Closing because I have not seen it fail in recent times. Reopen if it begins being flakey again.
