### ISSUE TITLE
Update cell type and tissue filter ancestor and descendant artifacts (Nov 2022)

### ISSUE THREAD

**Issue by NoopDog** [chanzuckerberg/single-cell-data-portal#3596]
#### Need
Currently, the cell type and tissue ontology filter artifacts (descendent and ancestor mappings) require updating when new tissue types or cell types are added to the system. In the medium term, a less manual solution is being developed to update the files in sync with new data being added.  In the short term, we will periodically update the files by running the [Ancestor and Descendant Mappings for Tissues and Cell Types notebook](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/scripts/compute_tissue_and_cell_type_mappings.ipynb) and committing the new files to the codebase. We will also take this opportunity to make any updates to the category/subcategory menu options.

#### Approach
- [x] Determine if we have any new tissues/cell types that are orphans in the ontology filter.
- [x] Check with @pablo-gar and @jahilton if we need to add any / change categories/sub-categories 
- [x] Update the prod tissue and cell types and any new categories/subcategories in the notebook and run.
- [ ] Update the data-portal code with the updated artifacts and review with stakeholders on Rdev
- [x] Update notebook to pull prod tissue and cell types when it runs.
- [x] Update notebook to allow running on Mac, adding instructions on how to set up and run.

### DOD
- No orphan cell or tissue types exist in the tissue and cell type filters.
- Categories/subcategories reflect SME intent.
- The notebooks and the data-portal are updated with new artifacts.
- Notebook can be setup and run on Mac/Apple silicon using instructions from the notebook.

**Comment by seve** [comment]
new handle who dis

**Comment by NoopDog** [comment]
@NoopDog = Dave Rogers

**Comment by brianraymor** [comment]
We'll need to see some ID sir.
