### ISSUE TITLE
Discovery: Ingestion of larger datasets

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#3607]
Kickoff meeting notes:
* [Large Dataset Handling Kickoff](https://docs.google.com/document/d/1nqp-r25o_fTe7WeUjHl7hLJh_dSuCMGxzZm3EHVuxxY/edit#)

Discovery notes:
* [Discovery: Large Dataset Handling](https://docs.google.com/document/d/1GSTNlLPsfwtW5yEVi7idy4LEmt0PXp61ErRTXuSe5Fo/edit#heading=h.wwumcqs9gkjy)

---

Manually ingest the [Allen Institute Whole Taxonomy dataset](https://s3.console.aws.amazon.com/s3/object/kuni-tmp?prefix=75e6eee5-d0e3-4291-9360-f288ffe6c7c4_300.h5ad&region=us-west-2#) so that it is available for download via [Discover Portal](https://cellxgene.cziscience.com/datasets) and the [Discover API](https://api.cellxgene.cziscience.com/curation/ui/).

Possible impacts to investigate include, but are not limited to:
* cellxgene-schema CLI
* ingestion pipeline
* Portal API
* Discover API

The scope of this epic specifically *_excludes_*:
* displaying this dataset in Explorer
* displaying this dataset using cellxgene desktop
* integration into Cell Census v1.0
* integration into Gene Expression

These exclusions will be addressed in separate future projects. However, discovery work will include testing and documenting any issues arising from large dataset ingestion on Cell Census builder and Gene Expression and shared with those teams.

Discovery from this exercise will be documented to use as input for future platform enhancements to enable regular, automated ingestion of large datasets. This work should include a spike to estimate the cost of implementing these enhancements.

Estimate the engineer time cost to manually ingest the Whole Taxonomy dataset so that it can be compared against the cost of implementing the platform enhancements required.

**Comment by metakuni** [comment]
Note, as discussed, this objective will be deferred from 2022Q4 to 2023Q1.

**Comment by atolopko-czi** [comment]
Overlap with or dup of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/365https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/245?

**Comment by brianraymor** [comment]
The original tracking/placeholder issue was [What to do about embiggened datasets?](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/245) but was broader in scope.

**Comment by atolopko-czi** [comment]
Keep both then? Or worth collapsing now?

**Comment by metakuni** [comment]
Oops, sorry, @atolopko-czi , just saw your comments now. [What to do about embiggened datasets?](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/245) was closed, so we'll be tracking the work in this issue.
