### ISSUE TITLE
Data Portal - update BE dependencies

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3615]
- [ ] Update and pin BE dependencies
- [ ] Deploy and sanity check that nothing is broken
- [ ] Update [how-to-upgrade-dependencies.md](https://github.com/chanzuckerberg/single-cell/blob/main/how-we-work/how-to-upgrade-dependencies.md)

#5024 is scheduled to be implemented Jul 10 - Jul 21 so suggest addressing this update after then.

**Comment by atolopko-czi** [comment]
Now P1, as @maniarathi has asked us to address sooner than later. (Also Explorer BE dependencies is already a P1.)

**Comment by metakuni** [comment]
Some dependencies were updated here:
- https://github.com/chanzuckerberg/single-cell-data-portal/pull/4986

**Comment by metakuni** [comment]
Labeled as `dp` and `data-viz` since the Portal repo contains both Portal and Gene Expression

**Comment by metakuni** [comment]
See also #5024

**Comment by metakuni** [comment]
See also #5024

**Comment by metakuni** [comment]
Created #5075 to separate the Gene Expression BE dependency update work.

**Comment by metakuni** [comment]
Assigning to @danieljhegeman to address during next DP on-call rotation starting 2023-12-11.

**Comment by metakuni** [comment]
@Bento007 , since we've assigned [dependency file owners](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/.github/dependabot.yml), can we close this issue?
