### ISSUE TITLE
Biological Consumers can download summarized data (cell types, gene expression) 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3634]
### Placeholder

From [2023/2024 Single CellPlan](https://docs.google.com/document/d/1mq6LB_mU5rlhH5xHvu_2jUZ6wxdCwrwwNi_lBaw5JnM/edit#): **_v1.0 Gene Expression summarized data (cell types, gene expression)can be downloaded by users._**

**Comment by dsadgat** [comment]
Closing this as a duplicate for now. This is noted specifically in the gene expression improvements ticket in our other epic [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3721).
