### ISSUE TITLE
Filter by consortia

### ISSUE THREAD

**Issue by NoopDog** [chanzuckerberg/single-cell-data-portal#3644]
- Stretch goal for Q4 2022.
- add consortia filter to the collections list

Use `noopdog/348-add-consortia-to-collections` as the base branch.

**Comment by brianraymor** [comment]
[Research groups can aggregate their collections on a dedicated landing page ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/312) would be the model preferred by submitters. Closing.
