### ISSUE TITLE
feat(FMG): Add info button to cell type labels on x-axis

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#3658]
https://www.figma.com/file/fgDQf6RSNyPeZpZoZRph0H/Alpha-Find-Marker-Genes?node-id=393%3A269940&t=RcyHyj1Zf9HSKcK1-4

![image](https://user-images.githubusercontent.com/8716829/204934438-c0466ff4-843b-4843-90c0-c267a9c97809.png)

Cell type labels need an info button that call the soon-to-be implemented reducer action `addCellInfoCellType` 

https://github.com/chanzuckerberg/single-cell-data-portal/blob/897476d5190daf9ab062a719f908741240fb0037/frontend/src/views/WheresMyGene/common/store/reducer.ts#L370

**Comment by ashin-czi** [comment]
@seve Is this feature still needed? I think we talked about closing it out but I might have misheard
