### ISSUE TITLE
Delete deprecated code

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#3669]
Ensure all directories, files, scripts, etc. unused by the redesigned data portal are deleted

**Comment by nayib-jose-gloria** [comment]
Files/Directories related to 
- [Processing](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3911) 
- [API layer](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3916) have been addressed in PRs. 

Remaining files/directories to deprecate or clean-up: 
- Deprecated Backend files (corpora_orm, deprecated backend.common.entities, etc)
- Deprecated backend.common.utils, if any

**Comment by metakuni** [comment]
@nayib-jose-gloria / @Bento007 : Can/should this issue be closed?

**Comment by nayib-jose-gloria** [comment]
Not yet--still have a few things to clean up:
- Deprecated Backend files (corpora_orm, deprecated backend.common.entities, etc)
- Deprecated backend.common.utils, if any

Could spin those off into separate tickets if you prefer

**Comment by metakuni** [comment]
If we can easily complete the remaining work this week, cool. If not, please split off into a separate issue that can be picked up by a future on-call shift.

**Comment by Bento007** [comment]
replacing this with #4086 and #4085
