### ISSUE TITLE
feat(FMG): hide i icon when cell type has <25 cells

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#3689]
marker genes can't be found if cell counts is < 25, so we should disable the functionality by hiding the i button

**Comment by signechambers1** [comment]
Suggested language: Marker genes are unavailable for cell types with less than 25 cells.

**Comment by signechambers1** [comment]
Suggested language: Marker genes are unavailable for cell types with less than 25 cells.

**Comment by ashin-czi** [comment]
> Suggested language: Marker genes are unavailable for cell types with less than 25 cells.

Was something like this what you had in mind?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/109984998/208993775-27a606ed-992a-4d45-9e9a-fa1591e118cd.png">

**Comment by signechambers1** [comment]
Looks good to me! fyi @karenliang0

**Comment by signechambers1** [comment]
good catch by @karenliang0, @ashin-czi im sorry, we had a convo in slack yesterday and I forgot to update this ticket. We had actually decided to remove the i icon for cell types with less then 25 cells instead of having the panel because we think it is less misleading to users.
