### ISSUE TITLE
Export normalized, aggregated data as a csv underlying dot plot from Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3721]
**Background**
We have gotten a lot of user feedback requesting the ability to download the data powering the Gene Expression dot plot as a CSV. This functionality would allow users to generate their own visualization or input into another tool for further analysis (excel, python, R, etc). This functionality is meant to easily support users in using the normalized expression data in Gene Expression.

Note: Once the cell census is live, we will want to either notify our users of its existence and keep the download data option in Gene Expression, or replace the download data option in Gene Expression with instructions on how to access the data in the Cell Census. We will decide the appropriate course of action based on user feedback and Cell Census capabilities.

**Design (Finalized)**
[Figma](https://www.figma.com/file/blyEMZDsi7EMopyyIX4XAg/Q1-2023-Gene-Expression-Improvements?node-id=225%3A419631&t=nJ2EOv4Zq79Ws1c9-1) 

**Example CSV**
[Default](https://docs.google.com/spreadsheets/d/1oocWdsjCAyzC8sUfsrRi0n1XLKRJEjoBdnTKV2auzv8/edit#gid=0)
[With Compare Dimension](https://docs.google.com/spreadsheets/d/1DgJxVe4ZKIZW8i1xaycKedsqPCqZzTLhLYaSV2ZFxt4/edit#gid=1054975896)

**Product Requirements**
1. User can download a csv file containing the following information:
- [ ] Tissue
- [ ] Cell types
- [ ] Cell count
- [ ] Tissue composition
- [ ] Gene Symbol
- [ ] Expression
- [ ] Expression, scaled
- [ ] Number of cells expressing given gene
- [ ] Dimension added if Compare has been utilized
2. CSV should reflect any filters applied
* Nice to have: CSV includes share link so they can get back to the dot plot that created the file.
* Alternative: File reports filters applied
3. CSV uses the same naming convention as image download
* File named with tissue name
4. Loading indicator should be present as csv is generated.

**User Feedback**
* “Allow data export to csv, txt, or xls”
* “Add export to table option”
* “Download csv raw counts data”
* “save/download the gene expression data (count, expression %, cell type, etc)”
* See feedback in our [Data Viz Feedback tracker](https://airtable.com/app8fNSQ8ieIiHLOv/tblqoYEr9Ee7rYrut/viwFPtZPfH7r2hIzk/recGHfF95tnUGOBJW?blocks=hide)

cc @signechambers1 for product, @karenliang0 for design, @ainfeld @dsadgat

**Comment by dsadgat** [comment]
Updated this to P0 as it is on the roadmap

**Comment by hthomas-czi** [comment]
@signechambers1 I'm having trouble visualizing the structure of the csv. The challenging part is the fact that cell types and genes are already a 2d matrix, so we need to figure out how to represent multiple values (expression, scaled expression, number of cells expressing gene) per cell-gene pair. I can think of two solutions, but I'm sure there are others. 

1. Use gene symbol as a column and combine expression, scaled expression, and number of cells expressing gene into a single value (separated by a slash, for example)

_Tissue, Cell type, Cell count, Tissue composition, Dimension [optional], Gene symbol (expression/scaled expression/number of cells expressing gene)_

2. Have three separate columns for each gene symbol for expression, scaled expression, and number of cells expressing gene

_Tissue, Cell type, Cell count, Tissue composition, Dimension [optional], Gene symbol (expression), Gene symbol (scaled expression), Gene symbol (number of cells expressing gene)_

**Comment by signechambers1** [comment]
@hthomas-czi good question! I put together what I was thinking [here](https://docs.google.com/spreadsheets/d/1oocWdsjCAyzC8sUfsrRi0n1XLKRJEjoBdnTKV2auzv8/edit#gid=0), which is closer to your number 2. Feel free to comment in the google sheet directly. Also curious @pablo-gar what you think.

**Comment by hthomas-czi** [comment]
Ah, that makes sense as well. Would also be curious to hear from @atarashansky

**Comment by atarashansky** [comment]
Personally, I think the best way to do multi-dimensional data in a table is to make it tidy (kind of like option 2). 

Tissue -- Cell type -- Gene -- Numeric metrics

**Comment by dsadgat** [comment]
@signechambers1 to add aggregated view to csv

**Comment by tihuan** [comment]
@tihuan will find the commit we implemented for CSV

**Comment by tihuan** [comment]
This is the CSV PR we had in the past:

https://github.com/chanzuckerberg/single-cell-data-portal/pull/990

**Comment by ashin-czi** [comment]
@signechambers1 

> One csv per tissue? Or all in the same csv?

Have we decided on this yet?

**Comment by signechambers1** [comment]
@ashin-czi yes, all in the same csv would be the most helpful i think.
