### ISSUE TITLE
Gene Expression Saved State URL

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3722]
The ability for users to share their GE data visualization analysis via a URL link, similar to this ticket here - [https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/345](url)

Value: 
- Increase user engagement and collaboration among users
- Increase sharing amongst users with the potential to introduce new users to our product

Reasoning
- Introduce the ability for users to share their filters/dot plots via a URL link that is present.
- Allow users to collaborate in a near real-time manner collaboration
- Sharing allows users to save time when recreating their filters/dot plots.

---

Functionality will be achieved by changing the download button to a share button. The modal will include an option to copy the share link to the user's clipboard.

[Figma](https://www.figma.com/file/JS5ThqTBcpAVuBFglAItKf/Gene-Search?node-id=4872%3A490291&t=d1tBRfJYFgAuslka-1)

**Comment by brianraymor** [comment]
@signechambers1 @niknak33 

Is this similar to [Data consumers want to share filter selections with collaborators](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/345) ?

**Comment by dsadgat** [comment]
@brianraymor yes it is.

**Comment by brianraymor** [comment]
@dsadgat - It would be helpful if there was a solution that could be reused across the platform then.

**Comment by dsadgat** [comment]
@brianraymor I actually dont really understand the solution you are proposing there, as it seems like (adding a request body) is not something easily usable (would require command line/interface) as opposed to being to directly stick that into the URL? I may be missing something, but I thought the idea was to be able to share the actual url.

**Comment by brianraymor** [comment]
I'm not proposing response bodies as a solution. Just documenting an earlier experience where OData heavily relied on complex query strings  and was surprised by the maximum length _wall_. 

The length limitation needs to be considered in a design. There may be opportunities to compress the query string per JSONCrush.

**Comment by seve** [comment]
@seve to check in with @niknak33
