### ISSUE TITLE
Add Gene Info cards to Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3723]
Gene Info cards has been a very helpful feature in Explorer, with about 20% of users continuing to utilize it. With the launch of Find Marker Genes, we want to bring this functionality into Gene Expression as well.

[Design](https://www.figma.com/file/blyEMZDsi7EMopyyIX4XAg/Q1-2023-Gene-Expression-Improvements?node-id=96%3A351323&t=sGgBfXR4809qDtyM-1)
[Prototype](https://www.figma.com/proto/blyEMZDsi7EMopyyIX4XAg/Q1-2023-Gene-Expression-Improvements?page-id=58%3A324240&node-id=456%3A395190&viewport=341%2C-36%2C0.19&scaling=scale-down&starting-point-node-id=456%3A392108)

https://images.zenhubusercontent.com/228681195/50226199-93f9-4957-8011-74dc454a77ee/gene_info_card_interactions_1.mov

https://images.zenhubusercontent.com/228681195/a8969e59-241b-4071-9c4e-2df6a88e33d7/gene_info_card_interactions_2.mov

cc @signechambers1 for product, @karenliang0 for design

**Comment by atarashansky** [comment]
Note: replace minimize behavior for marker gene panel with an (x) to permanently close (same behavior applies to gene panel).

**Comment by ashin-czi** [comment]
Posting figma for gene info cards for my reference https://www.figma.com/file/blyEMZDsi7EMopyyIX4XAg/Q1-2023-Gene-Expression-Improvements?node-id=96%3A351323&t=sGgBfXR4809qDtyM-1

**Comment by ashin-czi** [comment]
Progress so far

https://images.zenhubusercontent.com/228681195/d101eced-9b9e-4175-897c-f4f6effda09a/gene_info_progress_1.mov

**Comment by ashin-czi** [comment]
Progress so far

https://images.zenhubusercontent.com/228681195/d49c9d72-a23b-4fb4-9f95-7d2fb19f4b62/gene_info_progress_1.mov

One thing to note that it can take some time to load the gene summary, so I think there should be some decision made to determine what the loading state would look like. In the recording I had a simple "Loading..." text while it's retrieving the data

**Comment by ashin-czi** [comment]
@atarashansky when the show_warning_banner is true, what should be shown instead of the NCBI URL? Do we just omit the link entirely?

**Comment by atarashansky** [comment]
It's just that it may not be an exact hit.

**Comment by ashin-czi** [comment]
Demo!

https://user-images.githubusercontent.com/109984998/227580819-953ab2ab-6397-47b9-803f-596e3ebfce3c.mov
