### ISSUE TITLE
is_primary_data missing opening bracket for data type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3731]
https://api.cellxgene.cziscience.com/curation/ui/#/

There's only a closing bracket for the array of booleans?

> Describes whether cellular observations for this Dataset are all canonical (True), all non-canonical (False), or contain a mixture (True, False).

`boolean]`

**Comment by danieljhegeman** [comment]
same as [3732](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3732) @brianraymor for vis
