### ISSUE TITLE
suspension_type missing opening bracket for data type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3732]
https://api.cellxgene.cziscience.com/curation/ui/#/

There's only a closing bracket for the array of suspension types?

> List of unique suspension types represented in the dataset, corresponding to dataset's assay(s). Possible item values are 'nucleus', 'cell', and/or 'na'.

`string]`

It's also missing the link to its [schema reference](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#suspension_type).

**Comment by danieljhegeman** [comment]
This is also occurring with `batch_condition`

**Comment by danieljhegeman** [comment]
Ah, so this is actually the intended display format for Connexion's API reference. The opening `[` is found up above on the first line, and the example/definition/default/type are all contained with the `[` and `]`. I agree the notation is a bit odd but it is consistent.

**Comment by danieljhegeman** [comment]
@brianraymor for confirmation on closing

**Comment by danieljhegeman** [comment]
reopening because of the afterthought at the bottom:
> It's also missing the link to its schema reference.
