### ISSUE TITLE
Add missing curator names to collections

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3793]
See [**wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1671135253363469).

The following collections are missing a curator name:

 `e9eec7f5-8519-42f6-99b4-6dbd9cc5ef03` is "Batuhan Cakir" per Jason. 

` bf325905-5e8e-42e3-933d-9a9053e9af80` is "Batuhan Cakir" per Jason.

Batuhan is correctly assigned as a curator on other collections. Is he using multiple oauth providers - one which does not have a human readable name?

**Comment by metakuni** [comment]
Added `tech` label so it's easier to find as on-call work.

**Comment by danieljhegeman** [comment]
I've set `CollectionVersion.curator_name` to `Batuhan Cakir` for both of the Collections mentioned and confirmed this comes through when fetching these Collections via the Discover API.

**Comment by danieljhegeman** [comment]
> Is he using multiple oauth providers - one which does not have a human readable name?
Confirmed he used the same oauth identity for these collections as well as others; that was not the cause.

**Comment by danieljhegeman** [comment]
the curator name is pulled from the id token on the front end when using the UI to create a Collection via the portal API; the portal API handler requires a curator name. The curation API currently does not accept a curator_name field and simply instantiates a new Collection with an empty string as the curator_name value; I do not see anywhere that it ever gets updated.

I believe we can use the management API to query Auth0 to get the user name (which I assume is what the UI is using) with the Curation API handler. I'm not sure why we never did this... or if we did and it got scooped out during the redesign on accident...? Shall I create a ticket for this @brianraymor ?

**Comment by danieljhegeman** [comment]
@brianraymor @jahilton the `curator_name` gets filled in on _publish_ (which occurs via the UI) for Collections that are created via the Curation API. If it is helpful, we can create a ticket as described above to use the management API to get the curator name and fill it in immediately on creation so that there won't be any Collections with an empty `curator_name`.

**Comment by brianraymor** [comment]
@danieljhegeman - I just published a collection on Dev. My curator name is "".  I believe that this was working back in the day when we tested the Discover API. Not sure if it's a regression.

**Comment by brianraymor** [comment]
>  If it is helpful, we can create a ticket as described above to use the management API to get the curator name and fill it in immediately on creation so that there won't be any Collections with an empty curator_name.

Please do. The curator name needs to be available in private collections.
