### ISSUE TITLE
Batch delete gene requests to app isn't overwhelmed

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3800]
From Alec: If users use the gene selector to unselect many (e.g. 30) genes in a row (instead of refreshing the page), that will trigger 30 queries to be sent to the BE. This will DOS the site. I accidentally shut down staging for 5 minutes because I unselected like ~50 genes.

**Comment by tihuan** [comment]
@seve is the plan to add `Apply` `Cancel` to `QuickSelect` like how SDS Dropdown works?

![Screenshot 2023-01-04 at 9.12.48 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/7f3356e6-14a8-4f0c-a3dd-05d7d289c096)?

**Comment by seve** [comment]
The plan is to only send the request once the dropdown has closed

**Comment by tihuan** [comment]
Got it!
