### ISSUE TITLE
Fix SDS related table problems in FMG panel

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3806]
SDS changes created a few small design issues in our FMG panel:

Table Header Row
 - [ ] Bottom padding 4px, top padding 0px
 - [ ] Table Header text should be 500 weight, and Gray/500 (like below)
 - [ ] Headers themselves should not have a hover state or be clickable (currently, there is a click cursor when you hover over the header cells). There should only be a hover state / click cursor on the ‘Copy’ Action.
 - [ ] Table header text should all be horizontally aligned to one another (currently, the ‘gene’ header is misaligned with the rest)
 - [ ] Table header divider should be the same as the table row dividers (1px, Gray/300)

Table Rows
 - [ ] Remove hover state on rows, It signals to users that there is an action that can be taken when there isn’t
 - [ ] Make top and bottom padding 8px for each table row. It currently takes up a lot of real estate, especially as we think to the future where they may be other types of content in this panel

cc @karenliang0 for questions

**Comment by karenliang0** [comment]
https://docs.google.com/document/d/11PSF2OEVkuGqVT556KR4dcEiScroocRj1C4WRTOkj70/edit?usp=sharing

here's some additional photos if that provides more clarity! feel free to ping me with any questions :)
