### ISSUE TITLE
Fix Dataset filter for Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3840]
Currently the dataset filter for gene expression only reports the Dataset name. This is confusing since the dataset name only makes sense in the context of the collection (such as All Cells, this doesn't make sense unless you know it is Tabula Sapiens - All Cells). This ticket encompasses the work to incorporate the collection name into the filter.

**Value:** Without this work, users will not be able to use the Dataset filter and filter to the datasets they are interested in.

[Figma](https://www.figma.com/file/JS5ThqTBcpAVuBFglAItKf/Gene-Search?node-id=4866%3A435673&t=MPDwuQncw3evHPVp-1)

**Comment by seve** [comment]
Reference source data information

**Comment by seve** [comment]
If the filters are using SDS, there's a caption prop available.

**Comment by tihuan** [comment]
SDS DropdownMenu has a storybook example of adding caption to the menu item!
![Screenshot 2023-01-04 at 9.26.49 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/98d42841-7bda-4850-8f1a-7dd834f58091)
