### ISSUE TITLE
Bug: Application error when trying to get to a dot plot on Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3849]
Steps to reproduce:

1. Prod, latest version of chroms
2. Select blood, TSPAN6
3. Select dataset 49 year old males - Fresh PBMCs (2 days post intubation)
4. See error messages attached
![Screen Shot 2023-01-04 at 10.26.57 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/9fcf5738-378e-4694-b82a-3d96aa619fc0)

**Comment by seve** [comment]
@tihuan to add details

**Comment by tihuan** [comment]
Looks like `deserializeCellTypeMetadata()` is getting `undefined` for argument `cellTypeMetadata`. Not sure if we're now expecting passing `undefined` to `deserializeCellTypeMetadata`, if so, we need to handle that case in the helper function now. If we are not expecting passing `undefined`, then we need to fix that!

**Comment by seve** [comment]
This is no longer occurring in dev, I believe the issue with the bug was related to the removal or cell types when narrowing the dataset scope

**Comment by signechambers1** [comment]
@seve I'm still seeing this issue in prod, is that expected?

**Comment by signechambers1** [comment]
Ah I see should be out with the prod deploy this week. Thanks!
