### ISSUE TITLE
Analytics (new): Add tracking for gene expression tool tip

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3854]
### Overview
**Tool**: Gene Expression
- Feature (Optional): Dot plot tool tip

**Description**: We'd like to understand better if users are seeing and using the tool tips in Gene Expression. In FMG ux research, users had toruble discovering hover over functionality. Is this an issue on the dot plot?

### New events to add 
`WMG_HEATMAP_DOT_HOVER`
- Track the number of tool tips that are activated for >= 2 sec on the Gene Expression Dot plot. Please exclude "No data" tool tips.

#### People to cc
**PM**: @signechambers1 
**DS**: @ainfeld 

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by tihuan** [comment]
Event name maybe `WMG_HEATMAP_DOT_TOOLTIP`? @ainfeld ?

**Comment by ainfeld** [comment]
Slight tweak, my suggestion is `WMG_HEATMAP_DOT_HOVER` so it includes something about the action taken. @tihuan what do you think? 

@signechambers1 do we want to track any other information about the hover? i.e. what tissue/cell type the hover occurred on?

**Comment by tihuan** [comment]
Ooh adding action in the name sounds perfect! Thanks Amanda 😄👌

**Comment by signechambers1** [comment]
Hmm. I'm tempted to say we don't need to track the tissue/cell type hover over since we track the tissue/cell type added to the dot plot but let me know if you disagree @ainfeld

**Comment by ainfeld** [comment]
If the goal is to just understand if users are discovering the hover functionality I don't think we need to track the tissue/cell type. Just to clarify we track what tissues and genes are selected, but not which ones actually end up in loaded heat maps.

**Comment by signechambers1** [comment]
Thanks amanda! agree and thanks for clarifying my statement.

**Comment by ashin-czi** [comment]
@ainfeld 
I wanted to get this out to staging today but I found a bug where it keeps sending the event erroneously, so going to need to keep working on this. Most likely will be in next sprint's deployment

**Comment by ainfeld** [comment]
no problem! thanks for the update @ashin-czi
