### ISSUE TITLE
Analytics (new): Add analytics tracking to secondary gene expression filters

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3857]
### Overview
**Tool**: Gene Expression
- Feature (Optional): Add tracking to filters

**Description**: We can make more informed product decisions about filter functionality if we know which filters users are using. Should we change default filter settings? Update the design? Move filters? Additional analytics will be helpful for informing these decisions. Ideally I'd like to see the frequency of the values users select for each filter, but this is a nice to have.

### New events to add 
`FILTER_SELECT_DATASET` : `{dataset_name: <fill in>}`

`FILTER_SELECT_DISEASE`: `{disease: <fill in>}`
- the event has already been created, but right now the category name in the payload is `payload`, we should change it to `disease` 

`FILTER_SELECT_SELF_REPORTED_ETHNICITY`: `{ethnicity: <fill in>}`

`FILTER_SELECT_SEX`: `{gender: <fill in>}`
- the event has already been created, but right now the category name in the payload is `payload`, we should change it to `gender` 

`WMG_OPTION_SELECT_CELL_TYPES`: `{sort_cell_types_view_option: <dropdown selection>}`
- to fire if the user actively changes the sort cell types option 

`WMG_OPTION_SELECT_SORT_GENES` : `{sort_genes_view_option: <dropdown selection>}` 
- to fire if the user actively changes the sort genes option

`WMG_OPTION_SELECT_COLOR_SCALE`: `{color_scale_view_option: <dropdown selection>}`
- to fire if the user actively changes the color scale option 

#### People to cc
**PM**: @signechambers1 
**DS**: @ainfeld 

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by ainfeld** [comment]
@signechambers1 are we not interested in tracking usage of any of the view options?

**Comment by signechambers1** [comment]
@ainfeld sorry what do you mean? I'm interested both in what filter people use and the selections they make.

**Comment by ainfeld** [comment]
Ah sorry @signechambers1! let me try to clarify, I meant these options in the left side filters panel
<img width="234" alt="image" src="https://user-images.githubusercontent.com/83672566/213017892-f5fa216d-295d-4631-8b3b-736c5816a57a.png">

**Comment by ashin-czi** [comment]
This will be worked on this sprint but won't go out until next sprint's deployment!

**Comment by ainfeld** [comment]
good to know, thanks @ashin-czi!

**Comment by ashin-czi** [comment]
@ainfeld For the selectable filters, would you like we sent sent an array of all of the currently selected items? Or did you want us to send only what the user clicked on?

**Comment by ainfeld** [comment]
@ashin-czi thanks for checking! it can just fire once for each value that is selected. That should be how it's currently set up when used on the collections/datasets list pages  :slightly_smiling_face::
* `FILTER_SELECT_DISEASE` : `{disease: "respiratory system"}`
* `FILTER_SELECT_DISEASE` : `{disease: "influenza"}`

**Comment by signechambers1** [comment]
@ashin-czi is it possible to instrument the Sort Sell Types drop down as part of this ticket? We thought we were going to remove that option as part of the parent / child node work but we are no longer going to do that.

**Comment by ashin-czi** [comment]
@signechambers1 Yup I can add it to this ticket, I just need to know the Event name and payload
