### ISSUE TITLE
Marker genes can recapitulate cell type clustering

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3867]
Marker genes should uniquely specify groups of cells and should be able to be used to cluster groups of cells accordingly.

This ticket covers creating notebook that:

* Identifies marker genes for all cell types in a tissue (e.g. lung).
* Select one or more seminal datasets (e.g. Lung Map). 
* Subset the dataset to only contain the marker genes identified in the first step. 
* Perform clustering of cells in the dataset. 
* Validation entails that all cells are separated into tight clusters representing cell types.

More validation tests other than clustering are left to the discretion of the person performing this task.

Start with lung, ~1 week, then try blood, and if blood doesnt work not blocking.

**Value:** Validating marker genes so that users can trust and use them to identify groups of cells.

**Comment by atarashansky** [comment]
For this analysis, I am taking only the top **5** marker genes per cell type. This usually yields around 250-350 unique genes. If this set was not enriched in biologically relevant genes, subsetting the data down to such a small number of genes would give very low quality results (take a look at the random gene analysis UMAPs for an example of this).

Excitingly, we do not observe any decrease in clustering accuracy when subsetting down to ~300 marker genes. I tested this for lung and two blood datasets. Please see the attached pdfs.

Here are links to each of them:
[clustering_validation_blood2 - Jupyter Notebook.pdf](https://github.com/chanzuckerberg/single-cell-data-portal/files/10726706/clustering_validation_blood2.-.Jupyter.Notebook.pdf)
[clustering_validation_blood - Jupyter Notebook.pdf](https://github.com/chanzuckerberg/single-cell-data-portal/files/10726707/clustering_validation_blood.-.Jupyter.Notebook.pdf)
[clustering_validation_lung - Jupyter Notebook.pdf](https://github.com/chanzuckerberg/single-cell-data-portal/files/10726708/clustering_validation_lung.-.Jupyter.Notebook.pdf)

 - [Lung](https://cellxgene.cziscience.com/collections/5d445965-6f1a-4b68-ba3a-b8f765155d3a)
 - [Blood 1 (from tabula sapiens)](https://cellxgene.cziscience.com/collections/e5f58829-1a66-40b5-a624-9046778e74f5)
 - [Blood 2](https://cellxgene.cziscience.com/collections/b9fc3d70-5a72-4479-a046-c2cc1ab19efc) (a covid study)

Notably, the COVID blood dataset's clustering accuracy did not decrease when using marker genes calculated from only healthy cells. Although merely anecdotal (and slightly roundabout) evidence so far, this further supports the decision to include all cells in the marker gene calculation.

With this, I think we have enough to victoriously conclude this part of the validation work.
