### ISSUE TITLE
bug(redesign): list of tests not running

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#3890]
## Describe the bug
The following tests that should be run are not being run in our current test suite:

- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/dataset_processing/test_common.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/dataset_processing/test_downloader.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/dataset_processing/test_process_cxg.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/dataset_processing/test_process_download_validate.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/dataset_processing/test_process_seurat.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/dataset_processing/test_process_seurat.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/api_server/test_v1_auth_keys.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/api_server/test_version.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/api_server/test_app.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/common/test_auth0_manager.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/gene_info/test_v1.py
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/dataset_submissions/test_dataset_submissions.py

**Comment by metakuni** [comment]
@Bento007 : Are these tests still not running?

**Comment by ebezzi** [comment]
[This PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3892) reintroduces some of those tests. The processing tests have been moved to a single test_processing.py, although it's still missing some edge cases.

**Comment by metakuni** [comment]
@Bento007 : Please update this issue with details of the current status and create a new issue to cover the missing edge cases to be queued up for future on-call work.

**Comment by ebezzi** [comment]
See: https://github.com/chanzuckerberg/single-cell-data-portal/pull/3892
