### ISSUE TITLE
fix flakey deploy failures

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#3956]
Upgrades keep failing on the first run of dev deploys...been happening a lot recently. This was investigated in December and found to be cause by slow rolling devstack-frontend tasks.

**Comment by tihuan** [comment]
Ah I this is a duplicate you created before the holidays heehee

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3830
