### ISSUE TITLE
Outcome 4: The cost and feasibility of computing and filling missing Census metadata from sequence o

### ISSUE THREAD

**Issue by BAevermann** [chanzuckerberg/single-cell-data-portal#3962]

**Comment by norbid** [comment]
[HANCESTRO new term request process](https://docs.google.com/document/d/18dhx55C1aFD5p_v5ykO-TMdTK5sDqXq5CiUWNFSkRQc/edit#heading=h.nr7gckduyov) has been developed and circulated with grantees. Issues/progress can be tracked/viewed on [GitHub](https://github.com/EBISPOT/ancestro/issues).
