### ISSUE TITLE
[WMG] Render Legend in SVG for download

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3989]
Context:
When a user wants to download an SVG representation of the heat map, we need to manually create the SVG, since we can't rely on the existing library (`html-to-image`) to do so for us. (They use `foreignObject` element to wrap HTML in the SVG, which is invalid for image editing software, thus it won't show the SVG at all)

So on download event, we will manually re-create x-axis, y-axis, dots, and legends in pure SVG, and then align and stitch them all together as one SVG file for the user to download. 

Goal:

![Screenshot 2023-01-17 at 9.54.13 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/1539fe68-0d0e-4136-b6f7-bcdbd84e1a9f)

To avoid using `foreignObject`, we need to re-create the legend in SVG, only using SVG elements (no HTML elements)

NOTES:
1. Might be worth asking Karen or Harley to replace the color scale image `plasma.png` with an svg file instead, so we don't need to create the image in SVG every time a user downloads. **IMPORTANT**, since we have `scaled` and `unscaled` modes, the color scale numbers change from 0 - 1 and 0 - 6 accordingly, so depends on which mode the user selects, we need to spit out the right numbers for the SVG
2. The grey circles we could probably just use SVG `<circle />` element to create, but if needed, we could ask our designers to create an SVG file for them too

**Comment by ashin-czi** [comment]
@karenliang0 Do you happen to have sn SVG of the color scale image? 
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/edb32c6a-a8b0-45f1-8577-b4797fb51a06)
