### ISSUE TITLE
bug(Processing Pipeline): Success Handler Failed

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#3992]
## Describe the bug
The success and fail handler associated with the processing pipeline can fail to initialize for unknown reasons. This causes issue with cleaning up the processing job and can block or delay datasets from being publish unless the on call engineer intervenes.

Add retries to both the success and failure handler to make sure they run if they fail. Double check that rerunning them for the same job wont cause any issues.

## To Reproduce
Unknown, the problem is transient.

## Expected behavior
The handler should not fail for any reason. If it does it should be retried.

**Comment by metakuni** [comment]
Added `P0` label since this can also result in silent failures (no ingestion failure notification in #single-cell-ops)
