### ISSUE TITLE
UX Regression when deleting a dataset in a revision

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#4013]
In the original design for revisions, the UX displays hints to the curator about the state of their revision:

1. New datasets are tagged "New" for review.
2. Updated datasets are tagged "Updated" for review.
3. Deleted datasets are tagged "Deleted" for review.

Currently, 1 and 2 correctly appear. In the case of 3, the dataset simply disappears from the list when the dataset is deleted in the revision.

See [REVISION_STATUS](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fffa8650be96027a3ce[…]components/Row/DatsetRow/components/RevisionStatusTag/index.tsx).

**Comment by danieljhegeman** [comment]
I consider this a p0. Please let me know if you disagree @brianraymor

**Comment by brianraymor** [comment]
There was a previous regression that occurred during the curation api development - #2244.

**Comment by brianraymor** [comment]
Closing since we're removing the UX to delete published datasets in a revision - see #3037.
