### ISSUE TITLE
Bug: Gene Expression application error when organoid is selected

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4018]
Steps to reproduce:

1. Prod
2. Select UBERON: 0000966 (organoid) as the tissue
3. Application errors, see screenshot

Desired behavior: No error.![Screenshot 2023-01-20 at 9.26.42 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/5875907a-4047-4677-a8f5-b69307b58b49)

**Comment by atarashansky** [comment]
I can't reproduce anymore, so hurray for silent fix? If you can still reproduce please re-open @signechambers1

**Comment by signechambers1** [comment]
ha! you are right it is fixed!
