### ISSUE TITLE
Investigate Flakey Functional Tests

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4020]
Examples of transient failures in post-deploy functional tests: 

https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3970093257/jobs/6805874057

https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3970093257/jobs/6806511953

What can we do to make functional tests more consistent?

**Comment by metakuni** [comment]
Dang, the above links return: `The logs for this run have expired and are no longer available.` 😭 

@nayib-jose-gloria : Do you recall any details? e.g. Which functional tests were flaky. Or can we just close this issue and open a new one later?

**Comment by nayib-jose-gloria** [comment]
Whatever this was, I'm pretty certain we resolved it. Closing
