### ISSUE TITLE
Refine Discover API

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#4028]
See the [Technical Specification](https://docs.google.com/document/d/1wkbV67CI-jWgwjzDAtlpZ4qE3evZdHEaETaK0Y7RnSo/edit#).

### [Refine design for downloading datasets](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3798).

See [**#single-cell-portal-redesign**](https://czi-sci.slack.com/archives/C04796YB4Q2/p1670885676767169)

The response to [GET /v1/collections/{collection_id}/datasets/{dataset_id}/assets](https://api.cellxgene.dev.single-cell.czi.technology/curation/ui/#/collection/backend.portal.api.curation.v1.curation.collections.collection_id.datasets.dataset_id.assets.get) must be reviewed in light of portal design, including the addition of a dataset version id.

Also see [Include in "dataset_version_id" in "datasets" table of Cell Census schema](https://github.com/chanzuckerberg/cell-census/issues/6)

---

### Downloading specific versions of datasets

To address emerging requirements for reproducibility and the data reuse policy:

1. The response must include a permanent link (url) to each version of a dataset and its artifact. 
2. It must be possible to easily download the related dataset - preferably through a simple GET operation. 

Requirements from ongoing reproducibility discussions:

_As a scientist who shares a finding based on versioned CZ CELLxGENE Discover data assets, I want to be equipped to explain how other scientists can reproduce my finding from the versioned CZ CELLxGENE Discover data assets so that they can review, trust, build on and cite my work._ 

**Requirement**: Scientists can access long term supported versions of h5ad and rds assets. All versions upon publication/revision are long-term supported.

---

### Can presigned URLs be eliminated?

As noted in [bug(API): Presigned S3 urls don't last long enough.](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/2266):

@atolopko-czi noted:

> Might we be able to do away with pre-signed URLs entirely for downloads by making these data artifacts public S3 objects? If we need to maintain our ability to revoke access (e.g. for tombstoned data), then we can also look into using https://aws.amazon.com/s3/features/access-points/.

---

### Remove filename from the response for GET /collections/{collection_id}/datasets/{dataset_id}/assets

This was reported by an early reviewer of the Discover API. 

In `GET /collections/{collection_id}/datasets/{dataset_id}/assets`, there is no rationale to surface the dataset `filename` which is always "local.[h5ad|seurat]". It also is echoed in the `presigned_url`.  Consumers select downloads by format and can rename the file. 

```
[{'filename': 'local.rds',
  'filesize': 837811485,
  'filetype': 'RDS',
  'presigned_url': 'https://corpora-data-dev.s3.amazonaws.com/05b1dbc7-0add-4da1-9e77-39dc1bfdc1f0/local.rds...},
 {'filename': 'local.h5ad',
  'filesize': 703248747,
  'filetype': 'H5AD',
  'presigned_url': 'https://corpora-data-dev.s3.amazonaws.com/05b1dbc7-0add-4da1-9e77-39dc1bfdc1f0/local.h5ad...'}]
```

---

### Refine and document new dataset asset for curator submitted H5AD

See [**single-cell-portal-redesign**](https://czi-sci.slack.com/archives/C04796YB4Q2/p1674858023105119).

The curator submitted H5AD is now returned in dataset_assets as 'raw.h5ad'.

```

'dataset_assets': [{'filename': 'raw.h5ad', 'filetype': 'H5AD'},
  {'filename': 'local.h5ad', 'filetype': 'H5AD'},
  {'filename': 'local.rds', 'filetype': 'RDS'}],

```

This is the H5AD without ontology and gene labels.

This was not reviewed with product before it was surfaced in the API. It is not currently documented in the swagger which may cause confusion for early access consumers - "Which H5AD do I download and what is the difference between the two". 

In addition, the unlabeled H5AD is only useful for curators. It saves them the step of stripping the labels prior to revalidation and submission. I need to verify if it's only returned for curator roles and not consumers. 

---

### Can bulk downloads be optimized?

Including cell census, there are cases where consumers want to perform a bulk download of the entire data corpus. Should we consider a more optimized endpoint that requires less API calls to return a list of datasets and relevant collection metadata? 

---

### Analytics Requirements

https://docs.google.com/document/d/1YLH23M7Fk2_0DIo41aLEtnTzy5RtgMq-2Y9EBXJwv-k/edit

---
---
---

### [Refine design for private revisions of public collections](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4095).

See [**single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1675188086801089). 

The portal redesign introduced ambiguity to the revision flow and related dataset metadata. The current behavior appears to be:

1. Datasets in a fresh revision immediately receive a new UUID.
2. A new field, `datasets.original_id` is set to the published dataset UUID. `datasets.revision_of` is set to `None`.
3. IF a published Dataset is updated in the revision, then it receives another new UUID. `datasets.revision_of` is then set to the published dataset UUID which matches the `datasets.original_id`. 

Perhaps a cleaner design might be:

1. Datasets in a fresh revision DO NOT receive a new UUID.
2. IF a published dataset is updated in the revision, then it receives a new UUID. `datasetss.revision_of` is then set to the published dataset UUID. 

This eliminates the need for `datasets.original_id`.

During testing, there were related conversations in [**single-cell-portal-redesign**](https://czi-sci.slack.com/archives/C04796YB4Q2/p1674089098166789?thread_ts=1673990031.034169&cid=C04796YB4Q2) about original behavior after the redesign - dataset UUIDs were not updated UNLESS the dataset was updated in the revision (copy on wriite model) where I noted in the thread:

> To be clear, I'm fine with the policy of not changing original uuids until there's an update to an existing dataset.

### Documentation issues

In addition, it appears that `datasets.revision_of` has never been documented in the API (swagger).

The description for the Null value for `datasets.original_id` is unclear and incorrect?

> For Datasets in private revisions of published Datasets, a unique identifier of the published Dataset counterpart if applicable. Null if the published Collection does not contain the revision Dataset.

Perhaps:

> For previously published datasets in a private revision of a collection, original_id is set to the id of the corresponding published dataset. If new datasets are added to the private revision of a collection, then original_id is set to Null. 

---

### Deprecate datasets.revisions

See [**single-cell-data-portal-redesign**](https://czi-sci.slack.com/archives/C04796YB4Q2/p1674670777273089). Further investigation has determined that `datasets.revision` is not strongly required by our current users. Rather than patching the current regression, the field should simply be deprecated.

**Comment by metakuni** [comment]
@danieljhegeman / @nayib-jose-gloria : As your first task on this epic, please review the proposed issues and priorities and provide estimates. Based on that info, we'll scope this epic to fit in the allotted time.

**Comment by atolopko-czi** [comment]
`Remove filename from the response for GET /collections/{collection_id}/datasets/{dataset_id}/assets`: isn't this endpoint going to be removed entirely? @danieljhegeman
