### ISSUE TITLE
API docs?

### ISSUE THREAD

**Issue by will-vevotx** [chanzuckerberg/single-cell-data-portal#4047]
is there programmatic access to the dataset portal? for example to download multiple datasets

**Comment by brianraymor** [comment]
We do have an API. It's in _early access_ review with a small number of internal and external partners. We have some refinements to complete in Q1. I expect that general release will be early Q2. 

Can you share a bit more about yourself and the background for your question?

**Comment by brianraymor** [comment]
We do have an internal stress test based on the use of the Discover API for an internal project, tracked in [Receiving spurious 502 HTTP errors from Discover API](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3535). Performance  is part of the refinements planned for Q1. 

> let me know if you'd like more details, this fits into a a larger publicly available modeling project.

I'd love to hear more. I'm also on CZI Science Community slack if that's a better channel for you.

**Comment by brianraymor** [comment]
Reviewing options with Will in other channels.
