### ISSUE TITLE
Discover API Swagger docs not showing data model image

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4066]
This worked in rdev and dev (and I think staging) but is now broken. Investigate & fix. 

Blocks https://github.com/chanzuckerberg/cell-census/issues/21

**Comment by metakuni** [comment]
Weird! I swear I saw that data model diagram too! 

Confirmed broken on:

**Comment by atolopko-czi** [comment]
@atolopko-czi Update w/tech template

**Comment by atolopko-czi** [comment]
Fixed on dev by https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-infra/716

**Comment by ebezzi** [comment]
On track for a prod fix on Thursday Feb 16th.
