### ISSUE TITLE
Dataset upload not appearing until refresh after dataset upload

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4076]
The 'my collections' page is not displaying a pending dataset after it is successfully selected from Dropbox. The dataset is not visible until after a refresh occurs, which the expected behavior is that the dataset appears async, once the API recognizes it.

It should be noted that the current main/prod branches display aberrant behavior after seemingly-successful dataset selection as well, with the dataset _sometimes_ not appearing until after navigating away and coming back. With this particular code branch, however, the dataset _never_ appears until after refresh.

**Comment by brianraymor** [comment]
There is a whole class of UX *rust*  bugs requiring manual refresh as changes have been made that need to be revalidated and investigated. See [curation ux + bug](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/board?labels=curation%20ux,bug&repos=105615409,228681195,245246384,280546849,313382406,397736859,383621589&showClosed=false&showPipelineDescriptions=false&showReleases=false&showReviewers=false).

**Comment by danieljhegeman** [comment]
Ah yes, thanks for adding, Brian!

**Comment by brianraymor** [comment]
@NoopDog - would it be safe to assume that this problem is now resolved with the recent changes?

**Comment by brianraymor** [comment]
Closing per this morning's call ...
