### ISSUE TITLE
Cleanup: remove/update Auth Secret key-values

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4081]
After successful deployment and verified functionality.

Remove:
`api_authorize_url`
`api_token_url`
`callback_base_url`
`cookie_name`

Update:
`redirect_to_frontend` should probably just be `frontend` -- no longer referenced as a redirect, but is used to define frontend url for allowed origins

**Comment by atolopko-czi** [comment]
@danieljhegeman Please update the issue with then new Tech Issue template structure. Thanks!

**Comment by danieljhegeman** [comment]
@metakuni @atolopko-czi this is not a `tech` issue. This is work to be done _specifically_ as part of the epic that it is in, when PKCE is finally introduced, and only _after_ PKCE has been introduced.
