### ISSUE TITLE
Refine design for private revisions of public collections

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#4095]
### Context

See [**single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1675188086801089). 

The portal redesign introduced ambiguity to the revision flow and related dataset metadata. The current behavior appears to be:

1. Datasets in a fresh revision immediately receive a new UUID.
2. A new field, `datasets.original_id` is set to the published dataset UUID. `datasets.revision_of` is set to `None`.
3. IF a published Dataset is updated in the revision, then it receives another new UUID. `datasets.revision_of` is then set to the published dataset UUID which matches the `datasets.original_id`. 

Perhaps a cleaner design might be:

1. Datasets in a fresh revision DO NOT receive a new UUID.
2. IF a published dataset is updated in the revision, then it receives a new UUID. `datasetss.revision_of` is then set to the published dataset UUID. 

This eliminates the need for `datasets.original_id`.

During testing, there were related conversations in [**single-cell-portal-redesign**](https://czi-sci.slack.com/archives/C04796YB4Q2/p1674089098166789?thread_ts=1673990031.034169&cid=C04796YB4Q2) about original behavior after the redesign - dataset UUIDs were not updated UNLESS the dataset was updated in the revision (copy on wriite model) where I noted in the thread:

> To be clear, I'm fine with the policy of not changing original uuids until there's an update to an existing dataset.

### Documentation issues

In addition, it appears that `datasets.revision_of` has never been documented in the API (swagger).

The description for the Null value for `datasets.original_id` is unclear and incorrect?

> For Datasets in private revisions of published Datasets, a unique identifier of the published Dataset counterpart if applicable. Null if the published Collection does not contain the revision Dataset.

Perhaps:

> For previously published datasets in a private revision of a collection, original_id is set to the id of the corresponding published dataset. If new datasets are added to the private revision of a collection, then original_id is set to Null. 

---

### Deprecate datasets.revisions

See [**single-cell-data-portal-redesign**](https://czi-sci.slack.com/archives/C04796YB4Q2/p1674670777273089). Further investigation has determined that `datasets.revision` is not strongly required by our current users. Rather than patching the current regression, the field should simply be deprecated.

**Comment by jahilton** [comment]
The part that sticks out to me is
>IF a published Dataset is updated in the revision, then it receives another new UUID

Seems unnecessary as I think you'll only ever need 2 UUIDs - published + revision.
But also `original_id` & `revision_of` seem redundant. Why not have `original_id` + a boolean `revised`?

I think the only issue that I have with @brianraymor 's "cleaner design" is that it would be inconsistent with Collection revisions, which receive a new UUID immediately. Not a deal-breaker but ideally there is consistent behavior.

**Comment by atolopko-czi** [comment]
Related to [tech proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.xstveu87afut)

**Comment by danieljhegeman** [comment]
> I think the only issue that I have with @brianraymor 's "cleaner design" is that it would be inconsistent with Collection revisions, which receive a new UUID immediately. Not a deal-breaker but ideally there is consistent behavior.

@jahilton so I actually think that not producing a new id for a Dataset until it has been updated during a revision **is consistent** with the way we treat Collections*, because at present we are not supposed to allow a Collection revision to be published until something has been changed (whether in metadata or constituent Datasets), which would mean that a new Collection _version_ could not be produced without actually making changes. 

* though see [existing bug](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4223)

**Comment by brianraymor** [comment]
Copied into [Refine Discover API](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4028). Closing.
