### ISSUE TITLE
Create Tech Spec proposing Performance metrics + monitoring tools and Performance tuning

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4101]
Metrics + Monitoring Tools to explore:
- Datadog integrations (APM, Dashboards, etc.) 
- AWS Cloudwatch metrics (add access logs for load balancer?)
- Propose load testing job -- regularly scheduled, manual? If automated, how often? What load should we simulate and what are our SLOs? 

Performance Points of Interest: 
- Query Optimizations in redesign persistence layer (esp for index endpoints)
- Optimize SessionMaker in redesign persistence layer (
- Increase number of Gunicorn workers (currently just 1) 
   - Decreased to 1 due to previous issues with overly large TileDb memory allocation per worker, but this issue should be resolved now. Increase should be done safely, with these memory concerns in mind
- Investigate options to further optimize Gunicorn config
- Look into DB Machine Sizes, see if increase is necessary based on CPU during load testing
- If still seeing performance issues after above have been addressed, look into increasing # of web server instances

The tech spec should be shared out to the team for feedback and, before this issue is closed, result in issues for approved proposals of work towards performance tuning

**Comment by nayib-jose-gloria** [comment]
https://docs.google.com/document/d/19seVzLKgtIFLfGRudv1pH7Mza1wuxITim4KOYgadpMU/edit#

**Comment by metakuni** [comment]
Postponed review meeting til Mon due to late-breaking updates from meeting with central infra on Thu.

**Comment by metakuni** [comment]
Adding tech spec link for posterity:
- https://docs.google.com/document/d/19seVzLKgtIFLfGRudv1pH7Mza1wuxITim4KOYgadpMU/edit#
