### ISSUE TITLE
Tissue Composition % is not consistent for cell type

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4106]
Steps to reproduce:

1. Prod
2. Tissue = lung
3. click info icon for neuroendocrine cell type, add marker genes to dot plot
4. When hovering over GRP or NKAIN2, tissue composition = 0.03%. When hovering over NRXN1 or RALYL, tissue composition = 0.02%

I'd expect tissue composition to be linked to the cell type, so tissue composition % would be the same regardless of the gene I am hovering over![Screenshot 2023-02-01 at 3.41.09 PM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/6ea016dd-c8cf-4f2f-913d-db53a0f87c9b)![Screenshot 2023-02-01 at 3.41.15 PM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/e4e2f165-d33a-475b-8056-00bd86ada93e).

**Comment by atarashansky** [comment]
@signechambers1 Turns out that tissue composition is actually the number of cells expressing a gene divided by the number of cells in the tissue, so you would expect it to be different across genes. Closing this issue as the bug is actually a feature.

**Comment by signechambers1** [comment]
Thanks @atarashansky. Calculating tissue composition in that way is not intuitive to me, I think because in the tool tip tissue composition is grouped with cell type, not with the gene.

I'm wondering what is the most valuable number for tissue expression. @atarashansky @pablo-gar do you agree with calculating tissue composition as the number of cells expressing a gene divided by the number of cells in the tissue, versus the number of cells in the cell type divided by the number of cells in the tissue?
