### ISSUE TITLE
Compare Selection Dropdown

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#4112]
- [x] Users can select Dataset, Disease, Self-Reported Ethnicity, or Sex (aka Selected Dimension)  
    - [x] Users can clear the Selected Dimension
    - [ ] The Selected Dimension will reflect any applied filters
    - [x] Users can only select one Selected Dimension at a time (in a future improvement we may want to allow for multiple)
    - [ ] Analytics should track the usage of this functionality, and what dimensions users are selecting. We expect ~20% of weekly engaged visitors to use this feature, similar to download functionality.

**Comment by ashin-czi** [comment]
@ainfeld Do you have the analytic event name and payload for when the user selects a dimension for compare?

**Comment by ainfeld** [comment]
@signechambers1 is there an analytics ticket out for this yet, @karenliang0 is the design finalized?

**Comment by tihuan** [comment]
Assigned myself to the analytics ticket 👍 Thanks @ashin-czi !
