### ISSUE TITLE
Backend API changes

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4115]
We're going to make a slight change in the backend to support the compare feature. Calling the BE that many times might cause performance issues since we'd be querying for each cell type n number of times depending on how many filters are in the dimension.

The BE would detect if it's a compare request and then return both the aggregated gene expressions and the gene expressions for each filter in the selected dimension.

OLD:
We're going to try querying individual group option in each API call instead of updating the backend API for now, unless we hit API performance bottleneck.

For example, if group by sex, we'll make three calls, male, female, and unknown to get the breakdown info to construct the groupBy in heatmap~

**Comment by metakuni** [comment]
Is this a test issue, or details still TBD? 😄

**Comment by tihuan** [comment]
details added 😆 Thanks, Kuni!

**Comment by tihuan** [comment]
I'll investigate if adding extra API calls doesn't impact performance and UX before committing to it, otherwise we'll need to make backend API changes

**Comment by ashin-czi** [comment]
Will be working off this branch `ashin-czi/4115-compare-backend-api-call` which is branched off of `ashin-czi/4112-compare-dropdown`

**Comment by atarashansky** [comment]
Implemented as part of #4198
