### ISSUE TITLE
Miscellaneous Integration

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4117]
- [ ] The updated dot plot with Selected Dimension will load interactively, or show a loading indicator. Eng, prod and design will iterate on this requirement if data takes more than a few seconds to load.
    - [ ] When a user shares a URL for a dot plot, compare functionality should be incorporated so a shared URL will reflect the selected dimension.

**Comment by atarashansky** [comment]
Implemented as part of #4198
