### ISSUE TITLE
Reenable cell ontology sort for parent child roll up work

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4141]
Based on warroom findings, when you only have the hierarchical sort and are adding genes / marker genes, it is hard to keep track of your cell type(s) of interest. We'd like to reenable the cell ontology sort as the default, but remove the tabs (since they do not reflect how the parent nodes are calculated).

Also remove plus sign and make the "K" lower case for cell count.

**Comment by seve** [comment]
@signechambers1 Would we add this functionality back if we implement cell type pinning?

**Comment by signechambers1** [comment]
@seve what functionality are you referring to? The two sort options (cell ontology and hierarchical) will remain. I don't think we would add the tabs back in to the cell ontology sort even with pinning since the underlying relationship is still too complex to show with indents. We may add a dendrogram to the cell type names for the cell ontology sort to help users understand the relationships between cell types.
