### ISSUE TITLE
Analytics (new): Compare functionality

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4146]
### Overview

**Tool**: Gene Expression

- Feature (Optional): Adding Group by drop down in the left side bar of Gene Expression

**Description**: We'd like to see how often people use this feature and which dimensions they select.

### New events to add

`WMG_OPTION_SELECT_GROUP_BY`: `{group_by_option: <dropdown selection>}`
- to fire if the user selects a category to group by

#### People to cc

**PM**: @signechambers1 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

NOTES:
1. This ticket will be implemented as part of #4116

**Comment by tihuan** [comment]
Hey @ainfeld ! The `<dropdown selection>` values are currently "None", "Disease", "Ethnicity", and "Sex"

For example, `{group_by_option: 'Disease'}` does that look good?

Thank you!

**Comment by ainfeld** [comment]
yep exactly @tihuan!! Thank you!

**Comment by tihuan** [comment]
Perfectt thanks, Amanda 🎉 !
