### ISSUE TITLE
Optimize DB Session Manager for Reads

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4150]
The DB Session Manager in the single-cell-data-portal persistence layer is not optimized for Read operations–namely, each session goes through overhead processes on close (like session commits, rollback logic, etc.) that are only necessary for successful Writes. 

Rework the Session Manager to optimize for Reads as well.

**Comment by metakuni** [comment]
Closing this for now. Will reopen when/if performance tuning is prioritized.
