### ISSUE TITLE
Revisions that were in progress pre-migration have published_at erroneously set

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#4154]
We assumed that, in the old database, a collection with `published_at` was indeed published. It turns out that this wasn't the case for in-progress revisions (i.e. `published_at` was set and - incidentally - coincided with the `created_at`), so those were migrated as published (but not _active_ - so they wouldn't show up in the main page).

To fix this issue, we will unset `published_at` for those collection versions.

**Comment by brianraymor** [comment]
In progress revisions should have a `published_at` timestamp because a revision reflects a change to a published collection.

**Comment by brianraymor** [comment]
We should use different internal and external names to reduce confusion ;-)

**Comment by brianraymor** [comment]
Per @ebezzi - _we did a database migration_. Closing.
