### ISSUE TITLE
Delete completed submissions

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#4157]
## Motivation

The [cellxgene-dataset-submissions bucket](https://s3.console.aws.amazon.com/s3/buckets/cellxgene-dataset-submissions?region=us-west-2) is never emptied of completed dataset submissions. When a dataset is uploaded to the dataset submission bucket, the submissions pipelines starts. As part of the pipeline, the original file as well as the generated files are copied to [corpora-data-prod](https://s3.console.aws.amazon.com/s3/buckets/corpora-data-prod?region=us-west-2&tab=objects). This leaves a duplicate of the original dataset submitted in the cellxgene-dataset-submissions bucket. 

## Definition of Done

Completed dataset submissions are automatically deleted from the cellxgene-dataset-submissions bucket after the submissions pipeline is completed successfully.

Optional: Failed dataset submissions are automatically deleted after a week of no progress.

## Tasks

- [ ] setup a s3 data lifecycle policy to clear out old files automatically from the cellxgene-dataset-submissions bucket.
- [ ] delete the original submissions data from the cellxgene-dataset-submissions bucket after the submission pipeline completes successfully.

**Comment by metakuni** [comment]
@Bento007 can this be closed?

**Comment by Bento007** [comment]
@danieljhegeman can this be closed?

**Comment by danieljhegeman** [comment]
Ready for staging. Prod tomorrow.

**Comment by danieljhegeman** [comment]
@Bento007 we have a retention/deletion policy set up for the bucket, right? So yes, can be closed if so
