### ISSUE TITLE
Create per-endpoint load testing script using Locust for Discover API for READs

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4172]
https://locust.io/

Break down into CuratorUser, SuperCuratorUser, and ReadUser load test classes

**Comment by nayib-jose-gloria** [comment]
Moving out of performance tuning epic and into ongoing tech debt work

**Comment by metakuni** [comment]
Closing this for now. Will reopen when/if performance tuning is prioritized.
