### ISSUE TITLE
bug(filter):  range selectors are displaying a black background around tooltips

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#4177]
## Describe the bug

Range selectors (gene count and cel count) display a black background around the min and max tooltips.

## To Reproduce

1. Go to datasets
2. Click on cell count
3. See the black background around the min and max tooltips.

## Expected behavior

There should be no black background around the min and max tooltips.

## Environment

**Desktop**

- OS: macOS Monterey
- Browser: chrome
- Version: 109.0.5414.119

**Comment by brianraymor** [comment]
Closing. Prefer to address in [Redesign UX for count filters](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/2639). CC: @hthomas-czi.
