### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4183]
Google doc:

https://docs.google.com/document/d/10AfvnrpuOr4C3sCGLhVlti-7k-C-oFHY151wxjEUjuQ/edit#

SDS side project tracker:

https://github.com/orgs/chanzuckerberg/projects/33/views/5

DoD:

1. SC replaces its existing heatmap components with SDS Heatmap components and retain feature parity through implementing all 3 phases (epics)

Costs:
1. Phase 1: 1 full time SDS eng, 1 full time SCB eng, and 1 part time SCB eng for 4 weeks
1. Phase 2:1 full time SDS eng, 1 full time SCB eng for 8 weeks 
1. Phase 3: 1 full time SDS eng, 1 full time SCB eng -- scope undetermined, depending on the gap of feature parity after phase 1 and 2 are done

1. Currently the Heatmap team is focusing on getting Phase 1 done

**Comment by dsadgat** [comment]
closing as this is the sds related work that is not prioritized

replacing with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4666
