### ISSUE TITLE
Reactify echarts with enough API for SC

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4184]
As a developer, I want to be able to initialize the heatmap using a well-documented API that includes options for callbacks, data ingestion, and formatting. ([API Design bookmark](https://docs.google.com/document/d/10AfvnrpuOr4C3sCGLhVlti-7k-C-oFHY151wxjEUjuQ/edit#bookmark=id.d3gjrnst5qw5))

- [ ] Start the SDS Heatmap in Single Cell repo first to buy us time to figure out if we actually need to bundle heatmap in a separate package ( @masoudmanson is leading the research there)

**Comment by tihuan** [comment]
Sidney said it's worth checking out visx' API!

https://airbnb.io/visx/docs/heatmap

**Comment by dsadgat** [comment]
replacing with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4666
