### ISSUE TITLE
Heatmap interaction

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4185]
As a user, I want to be able to see more information about the underlying data by hovering over the heatmap visualization

Goals:
1. Heatmap component should expose dot hover callback function that provides metadata to allow positioning tooltip

**Comment by dsadgat** [comment]
closing as this is the sds related work that is not prioritized

replacing with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4666
