### ISSUE TITLE
Data update optimization

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4186]
​​As a user, I want to be able to make changes to the data in the heatmap visualization without having to reload the entire chart.
Enable prepending, appending, unshifting, without requiring entire chart re-render

**Comment by dsadgat** [comment]
closing as this is the sds related work that is not prioritized

replacing with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4666
