### ISSUE TITLE
Single Cell Biology Feature Parity

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4187]
As a user, I shouldn’t be able to identify any regressions between new and old heatmap.

Goals:
1. Heatmap should have same feature set and functionality as original heatmap

**Comment by signechambers1** [comment]
@atarashansky is there a product question here? Not sure why I am assigned to this ticket.

**Comment by atarashansky** [comment]
I figured there would be some QA required. can unassign

**Comment by dsadgat** [comment]
closing as this is the sds related work that is not prioritized

replacing with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4666
