### ISSUE TITLE
NPM Package Setup

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4199]
1. Give our new npm package a ✨ shiny new name ✨
1. Bundle package (separate npm package in the same repo?)
1. Dependency management (SDS, echarts, etc. as peer deps)
1. Typescript export tools (similar to czifui setup)
2. Likely use Lerna? https://www.amarjanica.com/switch-to-monorepo-with-lerna-and-rollup

**Comment by dsadgat** [comment]
@masoudmanson Have you started work on this?

**Comment by tihuan** [comment]
This is the npm packaging work that Masoud has just completed!

SDS status is tracked in SDS GitHub Projects :ok: 

https://github.com/orgs/chanzuckerberg/projects/33
