### ISSUE TITLE
[SPIKE] echarts camera scroll + React Axis Component Sync

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4200]
1. As a user, I want to be able to smoothly scroll through the heatmap visualization without any performance issue

1. As a user, I want to see the row and column labels in the heatmap remain aligned with the data points as I scroll through the visualization.

1. Potentially contribute to echarts by taking over [this PR ](https://github.com/apache/echarts/pull/17288)to add mousepad panning, which I assume we need

1. Share the spike result with Single Cell and the heatmap group in Slack #sci-heatmap

**Comment by dsadgat** [comment]
@masoudmanson have you started work on this?

**Comment by masoudmanson** [comment]
@dsadgat Yes, I'll start on this ticket this week during the sprint.

**Comment by cathystoli** [comment]
3 story point for the remaining work that is completing the demo that uses that includes the single cell react axis 

cc @tihuan and @dsadgat

**Comment by masoudmanson** [comment]
Demo and Feature Implementation

- [ ] Synchronizing a custom x-axis component with Apache ECharts.
- [ ] Implementing highlight feature for user interaction.
- [ ] Enabling highlighting of single items, rows, columns, or combinations.
- [ ] Providing live demo at https://apache-echarts-camera-scroll.vercel.app/

The task involves synchronizing a custom x-axis component with Apache ECharts and implementing a highlight feature. Users will be able to highlight individual items, entire rows, entire columns, or combinations of rows and columns. A live demo showcasing these features is available at the provided link.

**Comment by tihuan** [comment]
Wow this is incredible 🤩 👏 !! Thanks so much for the amazing demo, Masoud!

Looks like camera effect is a go 🚀

**Comment by tihuan** [comment]
@masoudmanson could you help document your findings on learnings and limitations of this approach, and what areas we might need to spend more time on optimizing please?

For example, the 1500x1500 example is still interactive for scrolling and highlighting, but not as smooth as 1000x1000 or lower. Do you have any ideas on what could be causing the slow down in performance, so we can look out for those?

Originally our assumption was that since camera effect renders a fixed size of items in the window, the interactive performance should be constant regardless of the actual matrix size, but that doesn't seem to be exactly the case. Just wondering if you discovered areas we need to investigate more later 😄 

Thanks again!
