### ISSUE TITLE
Help & Documentation button in navigation bar should match style of other buttons (GitHub issue)

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4214]
Buttons/options should match between explorer and data portal (ALONG WITH STYLE).

**Comment by signechambers1** [comment]
Is this related to [#4191](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4191)? Can that be closed as a duplicate?

**Comment by dsadgat** [comment]
Closing in favor of #4191
