### ISSUE TITLE
Cell types should not be clickable

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4215]

**Comment by ashin-czi** [comment]
@signechambers1 rdev can be tested here! https://cell-type-no-click-frontend.rdev.single-cell.czi.technology/gene-expression

**Comment by signechambers1** [comment]
@ashin-czi that link isn't working for me, I'm getting "NOT FOUND" after I log in using Github. Is it still working for you?

**Comment by ashin-czi** [comment]
@signechambers1 hmmm yeah it still works for me, but I sign in with Google. Maybe that would work for you?

**Comment by signechambers1** [comment]
Ha that worked. Looks great!!!
