### ISSUE TITLE
chore(wmg): rdev should be populated with enough datasets to enable testing wmg pipeline

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4224]
Currently, rdev is populated with a small number of test datasets (~4) which makes it difficult to test changes to the WMG pipeline in rdev. The WMG pipeline typically processes ~300 datasets and properly testing the pipeline in rdev requires a similar number of datasets. This is to ensure that the tested pipeline encounters and properly processes the diversity of datasets, cell types, tissues, and all other associated metadata that would be present in production.

In my opinion, the most convenient solution is for the rdev database to be initialized with that of the dev or staging database.

**Comment by metakuni** [comment]
@atarashansky : Could you add more details in the description? Thanks!

**Comment by dsadgat** [comment]
@atarashansky could you add more details here please? Thanks!

**Comment by atarashansky** [comment]
Oh, totally forgot about this ticket - thank you for reminding me.

**Comment by dsadgat** [comment]
@atolopko-czi and @ebezzi cc @metakuni could you all give your thoughts and input here as well? Perhaps DP considerations?

**Comment by ebezzi** [comment]
I think rdev should be a self-serve environment. Developers should be able to mirror data from dev/prod (using a script) but I don't see a compelling reason for making this part of the rdev creation process.

**Comment by atolopko-czi** [comment]
Agreed with @ebezzi.  RDev creation should be fast and minimal, with ability to customize (via a script) what data and how much data it is initialized with.

**Comment by dsadgat** [comment]
Sounds like we can modify this to just create a script for folks to populate rdev with datasets mirroring an env, what do you think @atarashansky ?

**Comment by atarashansky** [comment]
SGTM

**Comment by atolopko-czi** [comment]
Addressed by #5274
