### ISSUE TITLE
Hide marker genes with marker score <0.5

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4228]
We have determined that marker genes with scores <0.5 are not very useful to users. To provide more valuable genes, we'd like to implement a cut off where no marker genes with scores <0.5 are surfaced in the marker score panel.

This ticket covers the following work:
- [ ] Implement cutoff
- [ ] If a cell type does not have any marker genes with scores >= 0.5 [Figma here](https://www.figma.com/file/blyEMZDsi7EMopyyIX4XAg/Q1-2023-Gene-Expression-Improvements?node-id=376%3A437490)
- [ ] Add a line to the documentation explaining this cutoff

**Comment by ashin-czi** [comment]
old ticket:
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4240

**Comment by ashin-czi** [comment]
Waiting on analytics: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4259

**Comment by ashin-czi** [comment]
rdev can be viewed here: https://hide-marker-genes-frontend.rdev.single-cell.czi.technology/gene-expression

**Comment by signechambers1** [comment]
@ashin-czi i'm not seeing the "Low: <1" in the marker genes panel: ![Screenshot 2023-02-28 at 9.29.09 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/21f6adf3-e1b6-4f87-a866-fe7d19fe6ce1)

**Comment by ashin-czi** [comment]
@signechambers1 this is fixed now in rdev!
