### ISSUE TITLE
Analytics (new): Track if user finds a cell type with no marker genes

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4259]
### Overview

**Tool**: Gene Expression
- Feature (Optional): Find Marker Genes

**Description**: We are not showing marker genes with marker scores below 0.5. Some cell types may not have any marker genes with scores >0.5, so a user could find no marker genes. We'd like to track how often this happens and for what cell types.

### New events to add

`WMG_FMG_NO_MARKER_GENES`: `{combination: "<CL_ID>, <UBERON_ID>"}`
- to fire when a visitor clicks to open the FMG panel for a tissue/cell-type combination and finds no associated marker genes with scores >0.5

#### People to cc

**PM**: @signechambers1 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by ainfeld** [comment]
@ashin-czi thanks so much for catching this!

Per our conversation on slack and the weekly meeting I've updated with the issue.
