### ISSUE TITLE
Add Discover API 'datasets/<id>/versions' endpoint to fetch all versions of a particular dataset

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4263]
Endpoint should return an array of dataset version metadata. 

Only allow fetching using a canonical ID.

Update OpenAPI spec accordingly.

**Comment by brianraymor** [comment]
@nayib-jose-gloria @danieljhegeman - closing as duplicate of [Implement: `/dataset_versions/{dataset_version_id}`](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4326).
