### ISSUE TITLE
Add 'version_id' as a field to all Discover API responses returning Collections and/or Datasets

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4264]
Simplify or remove logic around setting 'correct' ID in reshape_for_curation_api utility functions

Update curation-api OpenAPI accordingly. Clearly define use-case distinctions for version_id and id. 

Deprecate 'original_id' in the process

This change represents all endpoints that return collection and dataset responses returning 'dataset_id' or 'collection_id' in place of 'id'. It also adds 'dataset_version_id' and 'collection_version_id' to all endpoints with 'dataset_id' or 'collection_id' returned.

**Comment by danieljhegeman** [comment]
This should be done after all other p0 endpoint implementations.
