### ISSUE TITLE
Update single-cell-curation Notebooks to accomodate distinction between version_id and id

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4265]
Remove usage of 'original_id'

TBD: will endpoints calling revisions use 'version_id' or stick to using (canonical) 'id'? Pending discussion with team -- _see first comment_

**Comment by danieljhegeman** [comment]
The endpoints that reference revisions should use the `id` or `collection_id` terminology.

From the curator side, `version` should only be seen as part of a variable name in conjunction with using a `/.._versions/` endpoint.
