### ISSUE TITLE
Add Discover API endpoint to fetch all previously published versions of a particular Collection

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4270]
../collections/{collection[_version]_id}/versions
OR
../collections/{collection[_version]_id}?versions=true 

Update curation API OpenAPI spec accordingly.

**Comment by brianraymor** [comment]
@nayib-jose-gloria @danieljhegeman - closing as duplicate of [Implement: `/collections/{collection_id}/versions`](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4328).
