### ISSUE TITLE
chore(wmg): add back the secondary filter tests commented out in #4272 after refining dynamic test snapshot generation

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4287]
Due to the new way of calculating valid secondary filters given a set of query criteria in #4272, some tests needed to be temporarily commented out (specifically the secondary filter tests in test_query.py). It is not possible to calculate the filter relationships graph given the tight memory constraints in GHA due to the unnecessarily large size of the dynamically generated virtual snapshots. Because we are still unit testing the valid secondary filter calculation using a couple of newly added tests in the aforementioned PR, it is safe to comment these failing tests out for now. 

After updating the virtual test snapshot to be more wieldy (#3958), these tests can be added back.

**Comment by dsadgat** [comment]
@atarashansky given the closed linked ticket, what is needed for this ticket?

**Comment by atarashansky** [comment]
It's actually completed - thank you!
