### ISSUE TITLE
bug(wmg): secondary filters are not cross-filtering into each other

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4288]
To reproduce:
1. https://cellxgene.cziscience.com/gene-expression
2. select lung tissue
3. select MALAT1 gene
4. select pulmonary emphysema disease (secondary filter)
5. observe that datasets were not crossfiltered.
6. select dataset secondary filter (this specific dataset, screenshot before)
<img width="716" alt="image" src="https://user-images.githubusercontent.com/16548075/222553039-fdc6e221-eb50-4a8e-a550-9cc9f82e490f.png">
7. observe that there is no data and thus this combination of filters is invalid.

**Comment by ashin-czi** [comment]
Just some initial observations from the frontend...
<img width="751" alt="image" src="https://user-images.githubusercontent.com/109984998/222558702-662a92ec-0859-4b66-88cf-5fb096906fe8.png">
<img width="514" alt="image" src="https://user-images.githubusercontent.com/109984998/222558915-df2334e1-d91f-47cc-904d-9c9475099d02.png">

**Comment by metakuni** [comment]
Added the `P0` label based on @niknak33 's request to hot fix.

**Comment by atarashansky** [comment]
@ashin-czi The response looks good. The FE is not updating from the response when the query is triggered by secondary filter interface.
