### ISSUE TITLE
feat(wmg): online updating of snapshot 

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4289]
Credit to @nayib-jose-gloria for the idea

Instead of building the snapshot from scratch every time, could we look at the data diff and update only the portion of the snapshot that needs to be updated? This would dramatically shrink the runtime of the snapshot generation from hours to minutes.

**Comment by atolopko-czi** [comment]
The proposal should justify why the build time needs to be improved. It's probably not worth the effort to optimize snapshot building.  

The design would also need to address the case of replacing datasets that have been re-curated and then (very rare) case of a tombstone dataset needing to be removed entirely.
