### ISSUE TITLE
chore(wmg): implement wmg processing pipeline unit and e2e tests 

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4303]
We have low unit test and e2e test (full pipeline run) coverage of the WMG processing pipeline. These need to be implemented.

**Lay of the land**
 - [Not implemented](https://github.com/chanzuckerberg/single-cell-data-portal/blob/48858f4cde550d5adcf17beaf852fe40e21d69fa/tests/unit/wmg_processing/test_cube_pipeline.py#L41) 
 - [This](https://github.com/chanzuckerberg/single-cell-data-portal/blob/48858f4cde550d5adcf17beaf852fe40e21d69fa/tests/unit/wmg_processing/test_load_corpus.py#L117) starts from anndata fixtures but only tests `obs` `X` and `var`. Not any other snapshot artifacts. Adding tests for `expression_summary`, `cell_counts`, and so on would make it e2e. 
 - [A few tests not implemented](https://github.com/chanzuckerberg/single-cell-data-portal/blob/48858f4cde550d5adcf17beaf852fe40e21d69fa/tests/unit/wmg_processing/test_load_corpus.py#L103)
 - [Empty tests](https://github.com/chanzuckerberg/single-cell-data-portal/blob/48858f4cde550d5adcf17beaf852fe40e21d69fa/tests/unit/wmg_processing/test_transform.py#L1) 
 - I think [these stubs](https://github.com/chanzuckerberg/single-cell-data-portal/blob/48858f4cde550d5adcf17beaf852fe40e21d69fa/tests/unit/wmg_processing/test_update_cube.py#L1) can be removed.
 - Missing unit tests for virtually all functions in `backend.wmg.pipeline.summary_cubes`.

TBD: The actual tests that should be added and their prioritizations remain to be scoped out.

**Comment by dsadgat** [comment]
@atarashansky is this still needed, given the epic that was created, or can we close this out? Thanks!
