### ISSUE TITLE
Two (more) Collections with empty string for curator_name field

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4308]
https://cellxgene.cziscience.com/collections/1b014f39-f202-45ae-bb7d-9286bddd8d8b
https://cellxgene.cziscience.com/collections/661a402a-2a5a-4c71-9b05-b346c57bc451

These two collections have `CollectionVersion.curator_name = ''`.

The `owner` for both is, once again, `google-oauth2|106687116196602342983`, aka `Batuhan Cakir`.

**Comment by danieljhegeman** [comment]
I defer to @brianraymor for priority level on this ticket.

**Comment by brianraymor** [comment]
Thanks for reporting @danieljhegeman.

Have we determined the source of the problem? We know that Batu's name used to be set in the past. I'm curious if there's any action that we can ask Batu to perform. 

Otherwise, is there a reusable script that can be used by the on-call to set the curator name correctly?

**Comment by danieljhegeman** [comment]
>Otherwise, is there a reusable script that can be used by the on-call to set the curator name correctly?

No. Going forward this will not happen anymore. The fix is a very easy sql insert statement.

**Comment by brianraymor** [comment]
> The fix is a very easy sql insert statement.

Then could you do that now?

**Comment by danieljhegeman** [comment]
> > The fix is a very easy sql insert statement.
> 
> Then could you do that now?

I'm on it!

**Comment by danieljhegeman** [comment]
This has been done ✅ 

```update "CollectionVersion" set curator_name = 'Batuhan Cakir' where collection_id in ('1b014f39-f202-45ae-bb7d-9286bddd8d8b','661a402a-2a5a-4c71-9b05-b346c57bc451');```
