### ISSUE TITLE
Gene Expression long cell type names are not readable

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4315]
Long ell type names are truncated and there is no way to read the full name. Ideally on hover you can read the whole name.

Addtl ask from Pablo that cell type names are findable using Ctrl-F.

rdev: https://cell-type-names-tooltip-frontend.rdev.single-cell.czi.technology/gene-expression

**Comment by atarashansky** [comment]
Breadcrumbs from @seve, look how truncation is done in explorer.

**Comment by ashin-czi** [comment]
@signechambers1 Here's what I came up with so far

https://user-images.githubusercontent.com/109984998/228116414-aea0e13c-ab54-4bf0-b75e-9e618101aa16.mov

Only for truncated cell type labels, a tooltip will appear when hovered revealing the full name to the left of the label

Also the full names should be findable using the browser's Ctrl+F/Cmd+F hotkey

This can be played with in rdev here: https://cell-type-names-tooltip-frontend.rdev.single-cell.czi.technology/gene-expression

**Comment by signechambers1** [comment]
Thank you @ashin-czi ! The functionality looks great, I'm excited about this. A few questions:

1. when CTRL+F the string im searching for becomes visible in the cell type but cuts off another word. Is there a way to add a "..." after the search term?![Screenshot 2023-03-28 at 9.48.08 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/76f4f72d-957c-4bc3-a39d-f7db7686c887) 

2. The hover over looks like there is too much padding on the left and right for the centered text. Can we left align the text and reduce the left right padding? cc @karenliang0 if there is another small tweak you'd suggest instead.![Screenshot 2023-03-28 at 9.51.36 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/0ee971b5-bd33-44e2-8459-1fa096651587)

**Comment by ashin-czi** [comment]
@signechambers1 

1. Unfortunately the highlighting is browser dependent so I can't change the behavior of the highlighting. @tihuan Any ideas off the top of your head for a workaround?
2. I fixed the padding issue

**Comment by signechambers1** [comment]
Thanks! @ashin-czi don't worry about #1, let's go ahead and merge in. Thanks for the info!

**Comment by ashin-czi** [comment]
One drawback with this approach is that since the full name is "hidden" only until you do a search, you will sometimes see something like this:

![image](https://user-images.githubusercontent.com/109984998/228361547-50f225dd-2ec8-443a-acde-24b4ff4b087e.png)

But I think the ability to be able to jump to a position from ctrl+f search outweighs it. Would like to see what others think about the approach. But I think for now this would be ok, and can revisit in another polish item?

**Comment by tihuan** [comment]
Yeah I can't think of a better solution than what Andrew has now too, so LGTM 👍 Thanks for the clever solution!

**Comment by signechambers1** [comment]
Agree, the benefits outweigh the issues. I agree let's go with this! Thank you Andrew!
