### ISSUE TITLE
Implement: `/datasets` index endpoint

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4324]
See Swagger API description for this endpoint in [this feature branch](https://github.com/chanzuckerberg/single-cell-data-portal/blob/dan/rdev-4277/backend/curation/api/curation-api.yml).

**Comment by danieljhegeman** [comment]
Getting rid of `filename` and `original_id` as part of this work since they are subsets of the affected `dataset` component schema.

**Comment by brianraymor** [comment]
>  List all public Datasets with full metadata and **additional Cell Census attributes**.

1. The description references the "cell census". I've requested multiple times that the cell census never appear in the documentation. 
2. The documentation is silent on the ordering of datasets in the response. There are no specific product requirements beyond documenting the order (which may be random) to set expectations (you need to sort by) for the data consumer. @atolopko-czi - does the cell census builder have any preference?

**Comment by atolopko-czi** [comment]
> 2\. does the cell census builder have any preference?

there is no ordering requirement the census

**Comment by atolopko-czi** [comment]
A possible idea/requirement has surfaced that we may want to consider further for this endpoint: being able to filter return datasets compliant up to a given maximum Dataset Schema version.  Some initial discussion [here](https://czi-sci.slack.com/archives/C0247APK621/p1678491096239889?thread_ts=1678478848.628269&cid=C0247APK621).

**Comment by brianraymor** [comment]
The endpoint documentation does not explain the rationale for `dataset_id` and `dataset_version_id`. There are some definitions in [Surfacing Versions](https://docs.google.com/document/d/1wkbV67CI-jWgwjzDAtlpZ4qE3evZdHEaETaK0Y7RnSo/edit#heading=h.8yxeqpft8mig) that could be reused here?


```
dataset_id
A unique identifier of a Dataset.

dataset_version_id	
A unique identifier of a Dataset version.
```

Could be simple like:

```
dataset_id

The unique identifier that always references the latest published version of this dataset.

dataset_version_id	

The unique identifier that always identifies a specific published version of this dataset, 
even after subsequent versions of this dataset have been published via revisions.
```

I might include an example of dataset_revision_id (perhaps using uuid(s) to be more realistic and not suggest an incremental set of numbers.)

dataset_id is 1.
dataset_version_id is 2.

The dataset is updated and republished.
dataset_id is 1.
dataset_version id is 3.

The dataset is updated again and republished.
dataset_id is 1.
dataset_version_id is 4.

It's still possible to access and download earlier versions such as dataset_version_id 3.

**Comment by brianraymor** [comment]
The order of the datasets in the response should be documented.

**Comment by atolopko-czi** [comment]
> @atolopko-czi - I would prefer to move this idea into a separate issue . If we decide to address, it could be part of the 3.x schema (ontology bump) work. Thoughts?

Sounds good!

**Comment by danieljhegeman** [comment]
>The order of the datasets in the response should be documented per the earlier comment.

Good catch, @brianraymor . Shall we go with reverse chron for `published_at`? Or should it be by `revised_at`?

**Comment by brianraymor** [comment]
For consistency, we could reuse the algorithm for the [Datasets view](https://cellxgene.cziscience.com/datasets) asdefined in [Data consumers can filter by metadata to find datasets in the data portal](https://github.com/chanzuckerberg/single-cell/issues/218):

#### Sorting views

Both _All Datasets_ and _All Collections_ must be implicitly sorted in descending order based on the value of the publication date for datasets or collections.

#### publication date

The `publication date` is calculated as follows:

1. If the collection includes a published DOI, then the journal publication date is the `publication date` for both the collection and its datasets.
2. Otherwise, the `publication date`, in order of priority, is the `revised_at` or `published_at` timestamp for the collection or the dataset.

**Comment by danieljhegeman** [comment]
@brianraymor I am not opposed but I just want to note for clarity that this conflicts with comments from [the Tech Spec](https://docs.google.com/document/d/1wkbV67CI-jWgwjzDAtlpZ4qE3evZdHEaETaK0Y7RnSo/edit?disco=AAAAq0Ob9zk).

Do you want us to change the datasets index end (and collections index endpoint) to abide by the `Sorting views` logic you've laid out in the previous comment?

**Comment by brianraymor** [comment]
Let's continue with reverse chronological order based on these timestamps:

> Otherwise, the publication date, in order of priority, is the revised_at or published_at timestamp for the collection or the dataset.

and NOT include the DOI in the mix.

**Comment by danieljhegeman** [comment]
@brianraymor we've been fooling ourselves with our terminology.

>>...would suggest reverse chronological order - [0] is latest and [N] is earliest. Time Machine style...

**Comment by danieljhegeman** [comment]
Moving back to `In Progress` since I'll need to incorporate updates to the sorting according to the above ☝️

**Comment by danieljhegeman** [comment]
Somehow we'd managed to sneak in a dataset index response object shape that only has `revised_at` and not `published_at`. Obviously rectifying that as part of this ticket.

**Comment by danieljhegeman** [comment]
> Otherwise, the publication date, in order of priority, is the revised_at or published_at timestamp for the collection or the dataset.

@brianraymor Just to make sure:

- Dataset 'A' is originally published 1 May as part of first publication.
- Collection is revised 2 May but Dataset 'A' is not altered/updated.
- The `published_at` attribute on the response is 1 May and is used as the key for sorting amongst all datasets in the response, while `revised_at` is `None`.


- Dataset 'B' is published 1 May as part of first publication.
- Collection is revised 2 May and Dataset 'B' is updated.
- The `published_at` attribute is 1 May on the response; the `revised_at` attribute is 2 May and is used as the key for sorting in the response.

**Comment by brianraymor** [comment]
@danieljhegeman - That is correct. And then the documentation is updated to reflect the default sorting of datasets .

**Comment by brianraymor** [comment]
It appears that there's a regression in DOI value.  The datasets index notebook incorrectly returns:

`  'collection_doi': 'https://doi.org/10.1016/j.celrep.2018.09.006',`

Compare with the correct value from the the collection itself:

`'doi': '10.1016/j.celrep.2018.09.006'`

**Comment by brianraymor** [comment]
`dataset.published_at` must be included in the datasets index. Currently, only `dataset.revised_at` is returned. 

For GET Collections, I believe that we agreed that only the collection `published_at` was required since all the datasets in a collection are published at the same time as the collection itself.

**Comment by danieljhegeman** [comment]
>For GET Collections, I believe that we agreed that only the collection published_at was required since all the datasets in a collection are published at the same time as the collection itself.

Which endpoint precisely are you talking about?

**Comment by brianraymor** [comment]
> Which endpoint precisely are you talking about? 
I was thinking about [this endpoint](https://refinement-backend.rdev.single-cell.czi.technology/curation/ui/#/collection/backend.curation.api.v1.curation.collections.collection_id.actions.get). The collection has both published_at and revised_at, but the dataset only has revised_at.

I recall having a conversation about the rationale for that omission in the past. I would need to find it.

But you're absolutely right about:

> This is not necessarily true. What about new datasets that are published in a revision?

I think we should be consistent about including both published_at and revised_at for collections and datasets.

**Comment by brianraymor** [comment]
Is there a plan on the books to quickly validate this endpoint with census builder?

**Comment by atolopko-czi** [comment]
> Is there a plan on the books to quickly validate this endpoint with census builder?

No an explicit plan yet, but I've added a note to the next Cell Census team meeting so we can figure out who/when.

**Comment by danieljhegeman** [comment]
@atolopko-czi this endpoint is now in dev

**Comment by atolopko-czi** [comment]
> @atolopko-czi this endpoint is now in dev

Now tracking in https://github.com/chanzuckerberg/cellxgene-census/issues/332
