### ISSUE TITLE
Implement: `/dataset_versions/{dataset_version_id}`

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4326]
This endpoint should accept only a _Dataset version id_ and should return that version of the Dataset according to [the API spec](https://github.com/chanzuckerberg/single-cell-data-portal/pull/4282/files#diff-d808b5972f311fbcd931698c57088028785292368fca7b9b8499a9da60578c9b)

**Comment by danieljhegeman** [comment]
@Bento007 Please review the swagger spec and make sure you agree with it.

**Comment by brianraymor** [comment]
RE [swagger](https://refinement-2-backend.rdev.single-cell.czi.technology/curation/ui/#/dataset_version/backend.curation.api.v1.curation.dataset_versions.dataset_id.actions.get) - why would this return an array? 

```
[
  {
    "assay": [],
    "batch_condition": [
      "patient",
      "seqBatch"
    ],
    "cell_count": 0,
    "cell_type": [],
    "collection_id": "fedcba98-7654-3210-fedc-ba9876543210",
    "collection_version_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "dataset_id": "01234567-89ab-cdef-0123-456789abcdef",
    "dataset_version_id": "456789ab-cdef-0123-4567-89abcdef0123",
    "development_stage": [],
    "disease": [],
    "donor_id": [
      "string"
    ],
    "explorer_url": "string",
    "is_primary_data": [
      true
    ],
    "mean_genes_per_cell": 0,
    "organism": [],
    "processing_status": "PENDING",
    "processing_status_detail": "string",
    "revised_at": "string",
    "schema_version": "string",
    "self_reported_ethnicity": [],
    "sex": [],
    "suspension_type": [
      "cell"
    ],
    "tissue": [],
    "title": "string",
    "x_approximate_distribution": "COUNT"
  }
]
```

instead of being symmetrical with

**Comment by nayib-jose-gloria** [comment]
@brianraymor I believe the swagger is incorrect; my PR with this change does not return an array (see [API spec in PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/4374/files#diff-d808b5972f311fbcd931698c57088028785292368fca7b9b8499a9da60578c9bR626-R632))

**Comment by danieljhegeman** [comment]
@brianraymor I am fixing the error.
