### ISSUE TITLE
Computational consumers can access a Census landing page directly from the portal

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#4335]
A landing page for the Census (temporary feature name) should exist at cellxgene.cziscience.com. 

See discussion in [**single-cell-discover-ux**](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1677519918276539).

The current proposal is that this page should be accessible directly from the the navbar, i.e. next to "Gene Expression"

## Stories

- I am a computational biologist using data from CELLxGENE Discover, I would like to understand what the Census API is and how I can use it to access data from the portal.
- I am a computational biologist browsing the cellxgene.cziscience.com and want to download data from the portal in a programatic fashion. 

## Product requirements

- The site serves as the one-stop site to get users started on using the Census
- The site must contain a minimal set of onboarding information, for full details see this [document](https://docs.google.com/document/d/1FTwWN3AvTFDBD7zVb0IVbSUlYEhk28ZgP0wA1cBOvJU/edit#heading=h.6x8vnvqoodlv) under header "Landing Splash page" . Currently a draft of this page exists as the [readme](https://github.com/chanzuckerberg/cell-census/blob/main/README.md) of the repo. Shortly the page should include:  
   - Description of the Census at its value props.
   - Getting started info: system reqs, installation, minimal usage examples, documentation links.
   - Support information (issues, questions, etc)
   - Current projects utilizing the Census
- The site must record what links are being clicked from users for product to understand if users are being properly directed.

### At cellxgene.cziscience.com

- A button in the navbar, which upon clicking redirects you to readthedocs in the current tab with the cave entrance information.
   - **Link to readthedocs https://cellxgene-census.readthedocs.io/en/latest/**
   - The button must be instrumented for product analytics under the event `DATASETS_CLICK_NAV` See analytics tracking issue: [Analytics (new): Instrument Census button in data portal top navbar](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4624)

### At readthedocs

- A readthedocs site that has the cave entrance, and comprehensive information to all other relevant documentation as described in this Epic.
- nice-to-have: provide content (likely visual) that make it clear this is part of CELLxGENE Discover.

### At gihub
- Gihub pages: An R doc-site that has R’s reference docs and tutorials
- Repo readme: A minimal 1-paragraph github page with link to readthedocs.

## Success of page (hosted in readthedocs) 

- Users clearly understand what the Census and have enough information to start using it.
- Users clicking on the doc-site links.
- Users installing the Census data. 
- Users accessing the Census data through API.

## Potential resources needed

~~- Design work to make the page easily browsable, produce visual assets (schematic for census schema, and census general workflow).~~
- Front-end engineering, to implement navbar button with link to readthedocs site.

---

## UX Design
Deprecated [~Figma~](https://www.figma.com/file/DMoBg0zsvktKrOZ3akAnFc/Cell-Census?node-id=144-20144&t=0fQxOmtr5Cc5zfMB-0)

**Comment by pablo-gar** [comment]
@ambrosejcarr comments:

> Great thoughts. I am supportive of communicating our value propositions within the top bar. In the case of the census, which requires installation, perhaps something like the pytorch landing page could really quickly get users up and running... "Copy and run this command."
https://pytorch.org/
I know that ux is more complex than ours, but we could have selectors for language (r, python).
Or just a simple readme, if  folks think this is overkill. (

**Comment by brianraymor** [comment]
Per my earlier comments in the **discover-ux** thread (link added to the top-level summary comment) for @hthomas-czi's consideration:

> The “Collections” “Datasets” and “Gene Expression” tab set lead the user to visual/interactive UX. This new tab leads to a README which is inconsistent.
I'm also wondering whether there are opportunities (perhaps longer term) to direct the user towards the appropriate "journey" - one path leads to visual experiences and the other path leads to our API(s) and notebooks.

**Comment by pablo-gar** [comment]
Completed
