### ISSUE TITLE
chore(wmg): disentangle wmg processing pipeline from database business logic

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4347]
In #4337, we updated the pipeline requirements to be primary dependencies only. However, we did not account for code leakage between the WMG pipeline and the database business logic. The pipeline calls into the business logic to fetch the dataset S3 URIs. Consequently, WMG pipeline also requires business logic primary dependencies.

[Slack discussion](https://czi-sci.slack.com/archives/C023Q1APASK/p1678884251153219)

The best way to move forward is to have the WMG processing pipeline fetch the dataset URIs from the Discover API instead of the business logic. Something similar was done for the `fetch_dataset_metadata` function in the WMG API implemented here: #4133.

**Comment by atolopko-czi** [comment]
@atarashansky can close this issue now?

**Comment by atarashansky** [comment]
It was referenced by the PR but not implemented yet. Silly github overcommunication!

**Comment by atarashansky** [comment]
Blocked until discover API changes for retrieving dataset metadata are online.

**Comment by brianraymor** [comment]
@atarashansky - `datasets/index` is in dev if you want to test. CC: @danieljhegeman 

It would be good to get your feedback. Cell Census is also testing in their current sprint.

**Comment by atarashansky** [comment]
@brianraymor Maybe I tested it a little too early today, but I noticed that `s3_uri` is not available in `dataset_assets`, like it is in the dataportal `datasets/index` endpoint. This is something I would need for the processing pipeline to be able to download the h5ad's to the EC2 instance. Do you know if adding that to `dataset_assets` is planned?

**Comment by brianraymor** [comment]
We're not planning to expose that to data consumers. Why wouldn't the WMG builder use precisely the same code as the cell census builder for downloading the H5AD(s)?

**Comment by atarashansky** [comment]
Disclaimer: I haven't looked too closely at how the cell census builder works (e.g. how it's getting s3 uris, retreiving metadata for filtering datasets, etc). What I can say is that WMG will eventually consume the integrated census array directly for building the summary cubes, so refactoring our pipeline and porting over the cell census builder logic now isn't worth it. In the short term, to complete the separation of WMG pipeline logic from database business logic, I will continue to parse the `/dp/v1/datasets/index` endpoint (which does contain s3_uris).

**Comment by atarashansky** [comment]
Ok, looks like I can get the url to the h5ad directly, for example:
`https://datasets.cellxgene.dev.single-cell.czi.technology/f512b8b6-369d-4a85-a695-116e0806857f.h5ad`!

This could work!

**Comment by danieljhegeman** [comment]
@atarashansky the h5ad url is accessible off of `datasets.assets[].url` for any (full) `dataset` object returned by the api*

*in dev and staging

**Comment by atarashansky** [comment]
Yes, this actually will work great! It'll be much cleaner than the current solution.

**Comment by brianraymor** [comment]
Cool. it's also a **permanent** link to that version of the dataset asset. We're going to be added citations in schema 4 which this will help to support.

**Comment by dsadgat** [comment]
@atarashansky what is the status of this ticket? It looks like its in progress, but not in a sprint?

**Comment by atarashansky** [comment]
It's merged today.
