### ISSUE TITLE
Gene Expression bug when one tissue has no data due to filter selection

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4349]
Dot plot is not rendering correctly when filters exclude data from a tissue.

Steps to reproduce:

1. Prod
2. Add spleen, then blood as tissue
3. Add JCHAIN as gene
4. Filter to self-reported ethnicity = Asian
5. Dot plot updates, no spleen info but dot plot is not rendered correctly for blood, CD4+ alpha memory t-cell is showing the dot for plasmablast

Dots should align with cell types correctly. Thanks @BAevermann for finding!
![Screenshot 2023-03-15 at 12.39.31 PM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/4afcce5c-96d8-4710-9507-2fcd5dcf61e6)

**Comment by BAevermann** [comment]
No problem! 
Note that this same behavior is reproduced if choosing "Liver" or "Pancreas" first as well (These also lack asian donor representation). Furthermore, If one chooses blood first, then there is no error. Cheers.

**Comment by atarashansky** [comment]
Already fixed as part of some other feature work...
