### ISSUE TITLE
bug(WMG Cube): fails on database error

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#4380]
## Describe the bug

When running WMG cube generate: 
```
aws batch submit-job --job-name wmg-staging --job-queue wmg-staging --job-definition wmg-staging-stagestack-wmg-processing --profile single-cell-dev
```
the job fails with the following error:
```
{
    "levelname": "ERROR",
    "asctime": "2023-03-21T22:50:44.021Z",
    "name": "backend.layers.persistence.persistence",
    "message": "No row was found when one was required",
    "lineno": 87,
    "pathname": "/backend/layers/persistence/persistence.py",
    "exc_info": "Traceback (most recent call last):\n  File \"/backend/layers/persistence/persistence.py\", line 81, in _manage_session\n    yield session\n  File \"/backend/layers/persistence/persistence.py\", line 612, in update_dataset_processing_status\n    dataset_version = session.query(DatasetVersionTable).filter_by(id=version_id.id).one()\n  File \"/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py\", line 2870, in one\n    return self._iter().one()\n  File \"/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/result.py\", line 1522, in one\n    return self._only_one_row(\n  File \"/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/result.py\", line 562, in _only_one_row\n    raise exc.NoResultFound(\nsqlalchemy.exc.NoResultFound: No row was found when one was required"
}
```
[cloudwatch logs](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fstaging$252Fstagestack$252Fupload/log-events/dp-staging-stagestack-upload$252Fdefault$252Ffa032dea4cfc48bf8e925da58e252bf8)

## To Reproduce
branch https://github.com/chanzuckerberg/single-cell-data-portal/commit/af5f09654aa905346368febf39d0ad40ed26f4a7

1. Start WMG cube generation
2. Look at the batch logs.

## Expected behavior

The WMG cube should succeed in being build.

**Smartphone (please complete the following information):**

**Comment by atarashansky** [comment]
Looks like the job ended up working!
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fstaging$252Fstagestack$252Fwmg-processing/log-events/wmg-staging-stagestack-wmg-processing$252Fdefault$252Fdfcb997e03944ea699c6f66be1dd2094

**Comment by atarashansky** [comment]
These are the wrong logs @Bento007 
[/dp/staging/stagestack/upload](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fstaging$252Fstagestack$252Fupload)

**Comment by atarashansky** [comment]
I'm going to close this issue as the wrong logs were looked at (phew)
