### ISSUE TITLE
bug(version): The currently deployed version is not displayed

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#4383]
## Describe the bug

The deployed version is not showing up in the API.

## To Reproduce

Go to -> https://api.cellxgene.dev.single-cell.czi.technology/dp/v1/deployed_version 
```
{
  "Data Portal": "f7a898a"
}
``` 
## Expected behavior

The github hash should appear:
```
{
  "Data Portal": "f7a898a"
}
``` 

## Environment

branch: [f7a898a](https://github.com/chanzuckerberg/single-cell-data-portal/commit/f7a898a3f9d64b2ad2c3f94117bb738c5a8c513c)
**Smartphone (please complete the following information):**

**Comment by atolopko-czi** [comment]
dup of #4311, which is now scheduled for a sprint.
