### ISSUE TITLE
fix(codecov): add local-integration-test-backend

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#4384]
## Motivation

Run code coverage on 

https://github.com/chanzuckerberg/single-cell-data-portal/blob/b158b69185aac9d15039896c15c9f7ceffec85fb/Makefile#L162-L163

This will increase our codecoverage.

## Definition of Done

The persistence code is covered by code converage

## Tasks

- Run coverage in [this make recipe](https://github.com/chanzuckerberg/single-cell-data-portal/blob/b158b69185aac9d15039896c15c9f7ceffec85fb/Makefile#L162-L163).
- Update [backend-integration-test](https://github.com/chanzuckerberg/single-cell-data-portal/blob/b158b69185aac9d15039896c15c9f7ceffec85fb/.github/workflows/push-tests.yml#L319) to generate a covereage report and cache it.
- Add [backend-integration-test](https://github.com/chanzuckerberg/single-cell-data-portal/blob/b158b69185aac9d15039896c15c9f7ceffec85fb/.github/workflows/push-tests.yml#L319) as a depedency to [submit-codecoverage](https://github.com/chanzuckerberg/single-cell-data-portal/blob/b158b69185aac9d15039896c15c9f7ceffec85fb/.github/workflows/push-tests.yml#L370-L375)

**Comment by metakuni** [comment]
@Bento007 , can this be closed?
