### ISSUE TITLE
revised_at and published_at for DatasetVersions

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4413]
_Preamble / Discussion_

@brianraymor [has expressed interest](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4324#issuecomment-1478323621) in a sort of "full information" approach to populating the `published_at` and `revised_at` fields on Dataset and Collection objects: put both fields on both types of objects in all scenarios. I am fine with this strictly for _Datasets_ and _Collections_. But **I think `revised_at` does not belong on _Dataset versions_ or _Collection versions_: immutable entities by definition are never "revised"**. And even if we were to bend our rules there a bit, it's unclear whether `revised_at` would refer to 1) the publication date of the subsequent version of that entity, or 2) the publication date of the most recent version for its canonical entity. For clarity:

Let D0 -> D1 -> D2 represent 3 versions of a canonical Dataset, where D0 is the earliest and D2 is the latest. Would the `revised_at` field on the object returned from `GET /dataset_versions/D0` be populated with the publication date of D1? Or the publication date of D2? This confusion dovetails with the argument that _versions_ objects should not include attributes such as `revised_at` that indicate the entity is mutable. Only a canonical entity is mutable.

_Facilitating the determination of `published_at` by API handler functions_

With regard to determining `published_at`: in order to determine `published_at` for a Dataset version, we currently have to gather all associated Collection versions and iterate over them until we find the earliest version that contains the Dataset version in its datasets[]. This is cumbersome in terms of code and it increases the time complexity of Dataset-related operations from `<# of datasets>` to `<# of datasets> * <# of versions>`. We plan to add `DatasetVersion.published_at` as a field.

Given that we plan to add to the `DatasetVersion` postgres entity, it probably makes sense to remove it from the `Dataset` postgres entity. Thoughts @nayib-jose-gloria ?

## **EDIT/UPDATE**
We will postpone any database migrations until later down the road when we have time to address tech debt, if we even deem it necessary. The code changes for calculating these values on the fly were, in the end, not terribly intensive, and the computational costs are minimal considering the scale of data. The migration also will/would require `DatasetVersion.collection_version_id` in addition to `DatasetVersion.published_at`.

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman For the non-version endpoints, I believe we still want to keep track + return the original publish time of a canonical dataset (i.e. first published dataset_version timestamp) as its 'published_at' (hence the need for revised_at to track the latest update publish time as well). While there are other ways to determine it, it would add complexity to non-version fetching logic so we may as well just keep it on the Dataset entity since its already there and not a difficult field to populate logic-wise.

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria can you remind me - `Dataset.published_at` is the _original_ publication date, similar to `Collection.originally_published_at`? If so, why isn't it also called `originally_published_at`?

Although now I have this feeling that I noticed this a couple weeks ago and mentioned that I thought we should change the name from `published_at` to `originally_published_at` for this reason...

**Comment by brianraymor** [comment]
Per @danieljhegeman private summary to me:

> for canonical Dataset objects returned by the Discover API:
published_at is the original date of publish for the first public instantiation of the dataset
revised_at is the date of its most recent revision being published

Yes.

> for Dataset version objects returned by the Discover API:
published_at is the date of the publishing of the version
no revised_at field

That sounds like a good plan to me. "This is when **this version** was published."
