### ISSUE TITLE
Phase 3 - SCB feature parity

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4423]
scope undetermined, depending on the gap of feature parity after phase 1 and 2 are done

**Comment by dsadgat** [comment]
closing as this is the sds related work that is not prioritized

replacing with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4666
