### ISSUE TITLE
Rest of SDS Heatmap Components

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4436]
DoD:

Deliver the following components and use in SCB:
1. `<Heatmap />`
2. `<XAxis />`
3. `<YAxis />`
4. ... potentially other components

**Comment by dsadgat** [comment]
closing as this is the sds related work that is not prioritized

replacing with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4666
