### ISSUE TITLE
bug( ): Data Portal UI Displays Dataset Version ID as title instead of Dataset ID when an empty dataset is initialized by Curation API

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4449]
## Describe the bug

bug( ): Data Portal UI Displays Dataset Version ID as title instead of Dataset ID when an empty dataset is initialized by Curation API

## To Reproduce

1. Create Empty Dataset via Curation API in a Private Collection
2. Check Collection in Data Portal UI, and look at list of Datasets

## Expected behavior

Dataset Name Column should display Dataset ID, not Dataset Version ID when initialized and empty 

## Environment
N/A

**Comment by brianraymor** [comment]
Triaging with @metakuni - closing since this is not a significant _fit and finish_ issue with the curators. CC: @jahilton .
