### ISSUE TITLE
Newsletter Sign Up

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#4450]
***WARNING 🛑: Do NOT push into production without Trust Review Approval***

What is the problem?
We currently have no way of contacting our user base. This allows us to curate a list of users who are interested in our product, reach out to users when we are launching new features, UX studies, qualitative outreach, announcements/conferences. 

**How does this align to single cell strategy?**
Notifying users of new functionality or announcements will drive traffic and engagement to our site, hopefully allowing users to do additional analyses. This will also help with recruitment for UX research so we can continue to build tools that address users’ problems.

**How does the newsletter differ compared to the slack channel?**
The slack channel has been around for a long time and contains users who signed up because of an interest in Annotate and the newsletter will allow us to connect with users who are interested in data reuse and visualization.

**User Sub-Stories**
**Users can sign up/subscribe to the cellxgene newsletter via any GE or Explorer Pages, details below:**

1. Napari team have already launched a sign up form on their platform using HubSpot to collect email addresses. They have a similar privacy policy to cellxgene and underwent a trust review with HubSpot - [Trust Pre-read - Napari hub newsletter](https://docs.google.com/document/d/1d1MG2bkhlpFUaExSm1ZqnyuAgYRImi8ezHdCZ4jhPWs/edit#)
In basic terms this is how Napari user Hubspot to collect emails
2. Napari have a custom form on napari-hub.org to collect emails. it uses the Hubspot API to store them (so no cookies). They also trigger a plausible event on submission
Hubspot generates UTM codes for any links in outbound emails. plausible picks these up, which lets them track campaign efficacy
3. Here is the implementation ticket from Napari Hub - [https://github.com/chanzuckerberg/napari-hub/pull/661](url)
By following these rules we can avoid a cookie banner by using the HubSpot API directly in the custom banner they created

**Users can unsubscribe from the cellxgene newsletter (Hubspot managed preferences via the comms team), details below:**

The unsubscribe flow is super simple; all newsletter-type emails we send through HubSpot will have a mandatory HubSpot-hosted unsubscribe link as well as a “Manage Preferences” link in their footer. If the user selects unsubscribe, they’ll automatically be unsubscribed from receiving cellxgene emails. If they select Manage Preferences, they’ll be able to select which subscription types they would like to opt in or out of. We have a few different “business units” inside of HubSpot and we’d likely put cellxgene in the business unit that already houses our other science products (CZ ID, GEN EPI, and napari) so if the user selected “Manage Preferences” instead of “Unsubscribe” they would be given the option to opt in and out of each of our four science product subscriptions.

**Legal Summary:** Cellxgene wants to create a newsletter so that users can stay connected. They also want to provide a mobile redirect to the desktop version of Cellxgene so that users can have a better experience.

**Legal requirements:**
For Newsletter: (1) Be transparent (that is, make sure users know they are signing up for a newsletter), (2) only use the email for purposes of serving the newsletter, (3) provide an easy opt out/unsubscribe mechanism for users, & (4) don’t use cookies, unless we update our cookie policy.

Since we use Hubspot for several products, these requirements should not be a problem BUT we will need to update our privacy policy to include data collection for the purposes of serving a newsletter Nikhil Patel

**Legal rationale:** When we process personal data, we need to be transparent (which is why we need to update our privacy policy), we need to collect it for lawful reasons (consent for the newsletter), and we should only be storing personal data for as long as needed for the purposes of collection.

**Security requirements are as follows:**

**[Mandatory]** Use a HubSpot tenant separate from tenants currently used by other product teams
Note: Please reach out to Leonora Rappa to ensure your team completes a tech consultation/gets an updated contract if needed to add a new tenant to HubSpot. This may require the creation of a new Trust Review ticket to allow the Vendor teams to be pulled in!
**[Mandatory]** Ensure email collection (data in transit) and email storage (data at rest) are encrypted
**[Mandatory]** Present “success” messages only when users enter email addresses
We want to avoid the ability for bad actors to identify valid email addresses via the newsletter sign up form. For this purpose, please only provide “success” messages, such as “thank you for signing up” even if the user has signed up for newsletter in the past.
**[Mandatory]** Ensure input validation on the HubSpot API to ensure no information can be taken from or input into our system
**[Mandatory]** Complete an implementation demo with Security Engineering prior to launch
We believe product teams should be able to make app-driven decisions for how things are implemented. To provide the most flexibility, while still ensuring security is taken into account, please reach out to Jae Lee when your team has completed implementation in a non-prod environment to review the code/implementation prior to launch into prod.

**Comment by tihuan** [comment]
I just moved the warning to not push to prod to the top of the description for visibility!
