### ISSUE TITLE
Scoping Newsletter work

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/single-cell-data-portal#4453]
Ticket to scope the work for the newsletter sign up. This includes but is not limited to:

1) Breaking out functionality and epic into a multitude of tickets that can be picked up and completed
2) Understanding the scope of work, and the workflow, and making that clear in the tickets descriptions
3) Incorporating design feedback
4) Adding and fully testing this feature
5) Adding analytics

By the end of this scoping work, it should be clear what is needed to accomplish this work, and how long it will take. Please update the epic with specific dates, and update the tickets with estimates.

**Comment by tihuan** [comment]
5 tickets to complete in 3 days seems pretty tight to me. But I don't have all the context 😆

**Comment by tihuan** [comment]
Any ticket we can start working on now? Thank you!
