### ISSUE TITLE
Testing filter section (left panel) on gene-expression

### ISSUE THREAD

**Issue by victorikeokoro6** [chanzuckerberg/single-cell-data-portal#4457]
Write test to verify the filter functionality for  Dataset, Disease, Self-Reported Ethnicity and Sex.

Test details:
https://docs.google.com/spreadsheets/d/1Ckv8741Ygxj-mcmDN1NosfmYvZWD3T1e6p1Y0CY--tA/edit#gid=0

User can remove selections by clicking the x on the button with the Dataset Filter, Ethinicity Filter, Sex Filter and Development Filter

**Comment by tihuan** [comment]
Thanks for the headsup, Alec!

I just added test details link to the description, I think Victor will likely just add more test steps in our existing tests to match what products do, so they don't have to manually test anymore!
