### ISSUE TITLE
Update test Ids

### ISSUE THREAD

**Issue by charles-testco** [chanzuckerberg/single-cell-data-portal#4458]
Currently we use the format data-test-id="menu" for test Ids.

We want to change this to:
data-testid="menu"

For several reasons:
1. It is Playwright default format
2. Will allow us to Playwright command out of the box: getByTestId without writing our own wrapper
3. Will fit with some Ids from external libraries

**Comment by tihuan** [comment]
Done in https://github.com/chanzuckerberg/single-cell-data-portal/pull/4432
