### ISSUE TITLE
Make gene info button show on hover

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4462]
Have the info as a hover over next to the trash can instead of always showing the info button. 

Ensure the increase in space for the genes is still there so that the trash can & info does not cover the gene name. min width = 8/9 characters. 

[Figma](https://www.figma.com/file/Mfo9nQ1m3jQzdPbwoEZvOP/Gene-Expression-v2?type=design&node-id=5948%3A237672&t=FHZN2x6Fb5NDvLwE-1)

**Comment by seve** [comment]
> to account for the space the gene info button takes up so users can read the full gene name?

@signechambers1 @niknak33 is there a % of gene names that we want to surface untruncated?

**Comment by signechambers1** [comment]
@seve is this still in progress? I'd like to add the number of pixels the info icon takes away from gene name back to gene name. This was not an issue prior to adding gene info to gene expression.

**Comment by seve** [comment]
oops I'm sorry I haven't been actively working on this, I thought I had moved this out of in progress when I began #4478, must have been a zenhub glitch

**Comment by karenliang0** [comment]
I love that idea! It would be awesome to get the x-axis height dynamic. I think we should set a max height anyway because we have some really long gene names that would be best truncated to prevent the icons from being too far away from the end of shorter gene names (which makes it hard for users to click)

@hthomas-czi

**Comment by karenliang0** [comment]
@ashin-czi 

It looks great!!! You're awesome - thanks for adding in the dynamic x-axis height 👏 

For the truncated names, it would be great if we had a hover over tooltip like what we have for cell types that are truncated! It would make it easier for folks to reference what the full name is. That most likely is not in scope for this ticket but an improvement we can add in when there's bandwidth!

**Comment by ambrosejcarr** [comment]
LGTM. Thanks Andrew.
