### ISSUE TITLE
Update Dependencies (All Repos)

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4467]
Update the package/library dependencies of all repos, to get the team caught up. After this, it should be simple for on-call engineer to address small numbers of upgrades, as needed for security, etc.

Instructions here: https://github.com/chanzuckerberg/single-cell/blob/main/how-we-work/how-to-upgrade-dependencies.md

**Comment by metakuni** [comment]
Closing since we're now using [this](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/.github/dependabot.yml).
