### ISSUE TITLE
Data Portal - update FE dependencies

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4468]
- [ ] Update and pin FE dependencies
- [ ] Deploy and sanity check that nothing is broken
- [ ] Update [how-to-upgrade-dependencies.md](https://github.com/chanzuckerberg/single-cell/blob/main/how-we-work/how-to-upgrade-dependencies.md)

**Comment by metakuni** [comment]
Labeled as `dp` and `data-viz` since the FE code is still tightly coupled. Handle with care!

**Comment by metakuni** [comment]
^ Removed the `dp` label since FE dependencies for both Gene Expression and Portal are one in the same and Data Viz has already scheduled this work in an upcoming sprint. 🙇
