### ISSUE TITLE
Produce summary of API changes for interested parties

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4477]
Once we have finalized API changes, we should produce a summary of the changes that have occurred:
- new endpoints
- modified endpoints
    - response shape
    - parameter changes
    - (etc)
- terminological changes
and anything else that comes to mind.

Already we caused disruptions for [Bruce](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1679936695365069) and [Amanda](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1679924714670309) when we changed a response attribute from `id` to `collection_id`. Both Bruce and Amanda were able to rectify their own pipelines fairly quickly, but we should still make sure we flag all changes for all API consumers/users.

**Comment by brianraymor** [comment]
Not required.
