### ISSUE TITLE
Create technical design for compare user stories

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/single-cell-data-portal#4478]
Create a technical design document discussing how we plan on making the changes necessary for this epic.

Template [here](https://docs.google.com/document/d/1KGqZk8TaPLRXBJSGtSo67h-Ve2CSIRzQSjSfW0y2xZU/edit) - please put this in the Q2 folder.

**Comment by seve** [comment]
Chatted with Harley today about the user stories and the 4 phases of the feature set.  Currently investigating the open rabbit holes and various pivot points should technical restraints/limitations arise.
