### ISSUE TITLE
Decide on naming format/convention for asset files in s3

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4482]

**Comment by brianraymor** [comment]
> I seem to recall discussions about local being unsightly

To be candid, it was a bit of a _punt_ from the early days based on convenience. See [Dataset downloads need consistent naming](https://github.com/chanzuckerberg/single-cell/issues/128). It's standard, but non-informative. It's also easy to set your browser to prompt for a real name for a download. 

> Of course we may wish to eventually support multiple .h5ad versions

Can you clarify what you mean by "multiple .h5ad versions"? I want to ensure that I respond correctly.

> `/{dataset_version_id}.{file_ext}`

This is preferable to me. 

In service of a [data reuse policy](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/355), I'm working on a schema definition for a [citation](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/412) in datasets that will include a reference to the permanent link of the dataset. 

The expectation is that a _slice_ returned by the Discover Census API(s) will also include a reference to mutiple dataset citations.

A sample draft citation:


_Tabula Sapiens : Tabula Sapiens - All Cells, doi:10.1126/science.abl4896, [CZ Biohub, CZI Single-Cell Biology], curated and distributed by CZ CELLxGENE Discover at `<url for dataset version>`_

**Comment by danieljhegeman** [comment]
>Can you clarify what you mean by "multiple .h5ad versions"? I want to ensure that I respond correctly.
Yes, my apologies, this would've been confused with "different versions of same Dataset". What I meant to say was, different versions _of the same Dataset version_, i.e. the regular .h5ad file vs the "raw" .h5ad file.

**Comment by danieljhegeman** [comment]
So yes I think we can standardize on `https://<cloudfront + bucket url>/<version uuid>.h5ad`

**Comment by brianraymor** [comment]
> But since that is really only of interest for a select group of curators if I recall correctly, I don't think we need to worry about that;

Unlabeled (in the sense of ontology and gene names) datasets are of interest to curators and for internal automation as @nayib-jose-gloria has mentioned in the past.
