### ISSUE TITLE
E2E Test - Add scrolling test to ensure pages are all scrollable

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4492]
This is to address the latest hotfix as documented here:

https://docs.google.com/document/d/1Yo1AeYzsk7D3qg4vlNj9jGrVYTqdTskH__lr099_2KY/edit#heading=h.ka8ytu8024rr

Definition of Done:

1. Pages with long content should be scrollable. This includes `/`, `/collections`, `/datasets`, `/tos`, `/privacy`, `/gene-expression` (would require generating a heatmap and scroll), `/docs`, and `/sitemap`

**Comment by tihuan** [comment]
CC: @dsadgat not sure if we should add this for TestCo to work on or we should pull this into our next sprint? 

Thank you!

**Comment by dsadgat** [comment]
@tihuan I think we can add this to testco work since it should be a minimal add.

**Comment by tihuan** [comment]
Awesome thank you! Just added this ticket under [their epic](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4398) 👍

**Comment by tihuan** [comment]
@charles-testco we had a hotfix last week causing all pages not scrollable, so we would love your help to add some tests to make sure it won't happen again 🙏 

I'll add more details in the description now!
