### ISSUE TITLE
Document useful Cloudwatch log queries

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4498]
## Motivation

Our backend server Cloudwatch log entries are json-structured. Cloudwatch allows you to query on particular json fields, but the syntax is a moderately arcane. Engineers need some basic query examples to help usability of Cloudwatch.

## Definition of Done

* Example queries are documented in a new section [here](https://docs.google.com/document/d/1n5cngEIz-Lqk9737zz3makXGTMrEKT5kN4lsofXPRso/edit#heading=h.dujy4xt9xsik). Both Portal and Explorer backends should have examples if their log structures differ.
* Engineers are made aware of the new section and test out the queries.

## Tasks

Same as DoD

**Comment by Bento007** [comment]
Updated the doc

https://docs.google.com/document/d/1n5cngEIz-Lqk9737zz3makXGTMrEKT5kN4lsofXPRso/edit#bookmark=id.dou47sbodfv7

**Comment by Bento007** [comment]
Will close after sharing with team during staff meeting
