### ISSUE TITLE
Newsletter Analytics

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4505]
### Overview

**Tool**: Data Portal

- Feature: Newsletter Signup

**Description**: The newsletter signup is a new feature that will need analytics to show if users are subscribing or opening the signup modal. Note, the landing page does not open up a signup modal, users can directly input their email in the footer.
**Expectations**: We should know if users are showing interest in subscribing to the newsletter

### New events to add
----

`NEWSLETTER_EMAIL_SUBMITTED`
- A user has clicked the submit button
- `NEWSLETTER_SIGNUP_SUCCESS`
    -  To fire when a user clicks to submit their email and it's successful and they see the "Thanks for subscribing!" text
- `NEWSLETTER_SIGNUP_FAILURE `
    - To fire when a user clicks to submit their email but did not submit a valid email address and they see the "Please provide a valid email address" text

----

`NEWSLETTER_OPEN_MODAL_CLICKED `
- Newsletter signup modal was opened

----

`NEWSLETTER_NO_SUBMIT_CLOSE_BUTTON_CLICKED` (TBD)
- Used when the newsletter signup modal was closed without any email submission

----

`NEWSLETTER_SUBMIT_CLOSE_BUTTON_CLICKED` (TBD)
- Used when the newsletter signup modal was closed after an email submission

----

`NEWSLETTER_DIRECT_LINK_NAVIGATED `
- Used when a user is directly navigating to the signup modal

----

`NEWSLETTER_SUBSCRIBE_BUTTON_AVAILABLE`
- To fire when someone has entered text and therefore the “subscribe” button becomes active

----

Checklist
- [ ] Add events to the custom goals section of both the staging and prod Plausible spaces
- [ ] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible 

#### People to cc

**PM**: @niknak33 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by tihuan** [comment]
should we work with Amanda on deciding the event names?

**Comment by ainfeld** [comment]
thanks @tihuan!! :) one slight change, for something like this where it requires new analytics events the best template to use is the `new analytics events` one.

I would suggest we wait till the designs have been finalized to think through how to best instrument the work flow since it could change quite a bit depending on the designs and I don't want us to do unnecessary work, but @signechambers1 what do you think?

**Comment by tihuan** [comment]
Ooh even better! I didn't know the `new analytics events` template existed 😆 Thanks for sharing!

We need to scroll down a little to see it in the dropdown!

<img width="488" alt="Screenshot 2023-04-14 at 2 16 46 PM" src="https://user-images.githubusercontent.com/6309723/232156562-ce636582-da09-4dbd-a08e-c6d3df44207e.png">
