### ISSUE TITLE
Clean up and prevent orphaned, unreachable entities

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4508]
[Some recent discussion](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit?disco=AAAAuWWp4rw)

At present, the Data Portal does not delete entity rows in tables except for CollectionVersions when they are abandoned in the course of deleting a never-before-published Collection or a revision of a published Collection. When this happens, the `Collection` and any `Dataset` / `DatasetVersion` rows remain. The general motivation of this ticket is to manage database entities so that the database reflects only:

1) (previously) published entities, and
2) entities which are currently not _but may yet be_ published

This will be in keeping with an append-only approach to storing the data from the perspective of published versions of Collections and their constituent Datasets.

**Comment by metakuni** [comment]
@danieljhegeman should we add this to #4693?

**Comment by Bento007** [comment]
This should be performed after a collection is published. Here is a code snippet I was working on to find orphaned datasets associated with a canonical collection id. ```python 
    def get_orphaned_dataset_versions(self, collection_id: CollectionId) -> List[DatasetVersion]:
        """
        collection_id: CollectionId
        Returns a list of dataset versions that are not associated with a publishefd collection version.
        """
        with self._manage_session() as session:
            # Must be a published collection
            if (session.query(CollectionTable).filter(id=collection_id.id)
                    .filter(CollectionTable.originally_published_at != None).one_or_none()) is None:
                raise CollectionIsNotPublishedException(f"Collection {collection_id} not found")

            # Get all dataset versions associated with a collection
            all_dataset_version_ids = set( session.query(DatasetVersionTable.id)
                                             .filter(DatasetVersionTable.collection_id == collection_id.id)
            )

            # Get all dataset versions that have been published in a collection version
            published_dataset_version_ids = (
                session.query(CollectionVersionTable.datasets)
                .filter(CollectionVersionTable.datasets != None)
                .filter(CollectionVersionTable.published_at != None ).all()
            )
            published_dataset_version_ids = set(itertools.chain.from_iterable(published_dataset_version_ids))

            # find orphaned dataset versions
            orphaned_dataset_version_ids = all_dataset_version_ids - published_dataset_version_ids

            return [self.get_dataset_version(DatasetVersionId(dv_id[0])) for dv_id in orphaned_dataset_version_ids]
```

Be sure to test the case where a dataset has been updated multiple times in a private colleciton, or revision before publishing.
