### ISSUE TITLE
Update WMG_HEATMAP_LOADED event logic

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4533]
Context:

https://docs.google.com/document/d/1C8dcoqQNeApWZBgv3hawPcA5LWqEBbmAZ5QH7YIbOp4/edit#bookmark=id.2f71691lv96s

DoD:

Simplify the `WMG_HEATMAP_LOADED` event logic to be just:

>If no heatmap is loading, and now at least one heatmap is loading (each tissue is a heatmap), send an event. BUT while at least one heatmap is loading, don't send more events

Example A:
1. No heatmap loaded
2. User adds a tissue
3. Users adds geneA, geneB, geneC rapidly --- one event
4. Heatmap is done loading
5. User adds geneD --- another event

Example B:
1. No heatmap loaded
2. User adds a gene
3. User adds tissueA, tissueB, and tissueC rapidly --- one event
4. Heatmap is done loading
5. User adds tissueD --- another event

Example C:
1. No heatmap loaded
2. User adds a gene
3. Users adds a tissue --- one event
4. While the heatmap is loading, user selects compare Disease --- no event, since the heatmap is still loading
5. Heatmap is now done loading
6. User changes compare to Ethnicity, which gets heatmap in loading again --- another event

cc: @ainfeld 

Checklist

- [ ] Add events to the custom goals section of both the staging and prod Plausible spaces
- [ ] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible

**Comment by signechambers1** [comment]
Closing in favor of: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4922
