### ISSUE TITLE
Collections are being tombstoned without ever being published

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4539]
`select count(id) from "Collection" where tombstone = TRUE;`  # 62 such Collections
`select count(id) from "Collection" where tombstone = TRUE and originally_published_at is not null;`  # 1 such Collection

We should only have **one** tombstoned Collection in prod. This is consistent with @brianraymor 's assessment from a few months ago when we were dealing with cleaning up the 'exponential growth of tombstoned Collections' problem that I believe was resulting from post-deploy functional tests.

A brief glance at `CollectionVersion.created_at` shows that some of the CollectionVersions associated with these tombstoned-but-never-published Collections were created _before_ the redesign (e.g., 2021), and some were created _after_ the redesign (e.g., within the last week).

It is likely that we coded the redesign without the intent of deleting `Collection` rows for never-published Collections, so this will probably be easy to fix.

**Comment by danieljhegeman** [comment]
It looks like [we're treating all canonical id's as published Collections](https://github.com/chanzuckerberg/single-cell-data-portal/blob/eefb7d71bb50fe81f434d652c51a09ec4bc344dd/backend/portal/api/portal_api.py#L456-L457), which they are not.

**Comment by dsadgat** [comment]
What does the end state look like? @danieljhegeman

**Comment by metakuni** [comment]
@danieljhegeman should we add this to #4693?

**Comment by brianraymor** [comment]
@danieljhegeman - has this been addressed?

**Comment by danieljhegeman** [comment]
@brianraymor @dsadgat @metakuni at the moment this isn't a huge deal because nobody is actively querying for withdrawn Collections. When we have a moment, we can resolve the (minor) bug that is causing never-published Collections to be marked as 'tombstoned' when they are deleted. But if we need to figure out what has been published and subsequently withdrawn, we can easily do that with a query that looks for Collections that are marked as tombstoned but also with have a non-null `originally_published_at` value.

**Comment by danieljhegeman** [comment]
But it is something we should clean up. I think we include this in the redesign-of-the-redesign work.

**Comment by danieljhegeman** [comment]
Oh, silly me. I'd already put it there.
