### ISSUE TITLE
get_dataset_versions returns the original published_at timestamp for all versions of a dataset

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#4581]
1. Create collection
1. Add dataset
1. Publish collection
1. Revise collection
1. Add dataset
1. Publish revision

The dataset timestamps returned in GET /collection are:

```

 'published_at': '2023-04-14T22:22:55.524100+00:00',
 'revised_at': '2023-04-14T22:43:05.154712+00:00',
```

Per [revised_at and published_at for DatasetVersions](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4413#issuecomment-1485798718), the expectation is that GET /dataset/versions will return the publication timestamp for each version in `published_at` and `revised_at` will not be set.

But `GET /datasets/revision` returns the original `published_at` for both the original and updated version:

```

'2023-04-14T22:22:55.524100+00:00'
'2023-04-14T22:22:55.524100+00:00'

```

**Comment by nayib-jose-gloria** [comment]
Issue is as_canonical flag is not being passed as False in the versions endpoint function. 

I think we should take the opportunity to attempt to consolidate as_canonical vs. use_canonical_url args, as I suspect there is overlap. And if there is a clear distinction in which we do need both args, we should rename them to reflect the distinction more

**Comment by danieljhegeman** [comment]
Unassigning only because I have not had time to acquaint myself with the bug at all yet. Will re-assign once I've done so.

@nayib-jose-gloria if you do happen to have bandwidth to pick this up, that would be excellent
