### ISSUE TITLE
Merge Playwright tes reports when run in shard

### ISSUE THREAD

**Issue by charles-testco** [chanzuckerberg/single-cell-data-portal#4587]
We have implemented sharding so tests run faster in CI. This however has short comings because Playwright at the moment does not merge the various reports from the shards.
The means the step to upload artifacts with fail and we ultimately don't have logs to investigate potential failures in CI.
We need to implement an action that will merge these reports into one after tests have completed.

https://www.workwithloop.com/blog/merging-playwright-reports-in-github-actions-workflows-after-sharding

**Comment by tihuan** [comment]
already done!
