### ISSUE TITLE
Add easy citation to Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4608]
Users would like to easily cite our tool instead of digging around in our documentation for citation information. This would also increase citations we get and be a great measure of our impact. To enable citation, we'd like to add an easy way for users to copy a citation.

cc @hthomas-czi for design, @signechambers1 for product

[Analytics ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5757) which should also be completed with this

**UX Design**
[Figma](https://www.figma.com/file/Mfo9nQ1m3jQzdPbwoEZvOP/Gene-Expression-v2?type=design&node-id=5983-196566&mode=dev)

[ZeroHeight Notification Documentation](https://zeroheight.com/009eaf17b/v/latest/p/56981d-notifications/b/065f46)

**Comment by dsadgat** [comment]
@ainfeld for instrumentation

**Comment by ainfeld** [comment]
@signechambers1 to create the instrumentation ticket

**Comment by signechambers1** [comment]
@niknak33 should the citation link in gene expression also link to the preprint? For context, #5594

**Comment by signechambers1** [comment]
Confirmed with @niknak33 we will move forward with this citation and update to the preprint citation when that is available.

**Comment by kaloster** [comment]
development is pretty much done with the exception of adding the citation svg to sds - currently figuring out how to get that done @tihuan
