### ISSUE TITLE
get_collection_version should return its publication timestamp in published_at

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#4619]
Currently, both `published_at` and `revised_at` are set and returned:

 'published_at': '2023-04-14T22:22:55.524100+00:00',
 'revised_at': '2023-04-14T22:43:05.154712+00:00',

**Comment by danieljhegeman** [comment]
@brianraymor I'll be confirming this soon but I'm a bit confused by the title + description for this issue. Do you mean to only point out that `revised_at` should not be returned? Or are you also saying that the _value_ for `published_at` is incorrect? I'm assuming the former.

**Comment by brianraymor** [comment]
There's been a inter-related set of issues.

Per [revised_at and published_at for DatasetVersions](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4413#issuecomment-1485798718), the expectation is that GET /collections/version will return the publication timestamp for each version in `published_at` and `revised_at` will not be set.

**Comment by danieljhegeman** [comment]
Great, that is what I had thought. Fix is coming (for all related issues)...
