### ISSUE TITLE
Analytics (new): Instrument Census button in data portal top navbar 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#4624]
### Overview

**Tool**:  Census and Data Portal

- Feature: Data Portal navbar -- Census button
- Feature Epic: [Computational consumers can access a Cell Census landing page directly from the portal](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4335)

**Description**: To understand what volume of our user base is interested on and clicks on the Census button. It will let us understand the utility of that button and its contribution to bringing traffic to Census.
**Expectations**: Users will land in the Census page upon clicking, users will use the Census.

### New events to add

`CENSUS_CLICK_NAV `

- Fires upon click on Census button clicking in Census button of navbar

Checklist

- [x] Add events to the custom goals section of both the staging and prod Plausible spaces
- [x] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [x] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @brianraymor @pablo-gar 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by frano-m** [comment]
Hi @ainfeld I have an rdev environment for you to test the analytics for Census: https://cc-cell-census-frontend.rdev.single-cell.czi.technology/ - would you mind taking a look and confirming everthing works as expected?

**Comment by metakuni** [comment]
Hi @ainfeld , was just reviewing the checklist above in the description. Has the 1st task been completed?

```Add events to the custom goals section of both the staging and prod Plausible spaces```

Is this something that you would do?

**Comment by ainfeld** [comment]
Hi @metakuni, normally that would be something for an engineer to do. However, I don't think CC has that level of access to plausible to do it, so I'm happy to add it myself. Thanks for checking!!

**Comment by frano-m** [comment]
Hi @ainfeld, just letting you know that new Census link is on staging.
