### ISSUE TITLE
Improvements to Slack notifications for failed Datasets

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4626]
[see discussion](https://czi-sci.slack.com/archives/C0244PQK934/p1681836092350959?thread_ts=1681832314.264669&cid=C0244PQK934)

Two things: 

1. The Slack notification is currently including a link to the _published_ Collection whenever a Dataset upload to an ongoing _revision_ for that Collection fails. Instead, the Collection link included in the Slack notification should be a link to that revision Collection.

2. The Batch Job ID link in the notification is dead / None / not being included. This needs to be remedied. [See bottom of notification](https://czi-sci.slack.com/archives/C0244PQK934/p1681832314264669).

**Comment by metakuni** [comment]
Assigning to @Bento007 since he's on-call this week.
