### ISSUE TITLE
Create mini SDS Chart component (aka SCB Chart component)

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4667]
Goals:

1. Identify and separate business logic from chart rendering logic
1. Create a Chart component that handles chart rendering logic with simple heatmap API from [API design](https://docs.google.com/document/d/1GuO-vUFylQpU7D-IB1HPuInvVk6Z0iJ0ZXchFDyxZLY/edit)
1. Write tests that ensure dots are rendered (likely screenshots)

**Comment by dsadgat** [comment]
would this be an SDS component? Or SCB component?

**Comment by tihuan** [comment]
SCB component!
