### ISSUE TITLE
Implement a maintenance page

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4688]
For times when Data Portal servers require production downtime for upgrades (infra, database migrations, etc.) or unforeseen outages (e.g. an AWS service outage), the app and API landing pages should be redirectable to a maintenance page.

**Comment by metakuni** [comment]
We've needed this for a while, but this was spawned from a [discussion at this week's engineering meeting](https://docs.google.com/document/d/1USpxVJ_ZyObxMXWlYOOMAEHcvqeVuZCPYuQSPf55qsA/edit#bookmark=id.6cuv774p7cyt).

**Comment by Bento007** [comment]
This will also need a written process on how to enable and disable the maintenance page

**Comment by metakuni** [comment]
Closing this for now. Will reopen when/if the need is prioritized.
