### ISSUE TITLE
Change Dataset.published_at to Dataset.originally_published_at

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4694]
To match the analogous database column names, which are inherently descriptions, used for Collections:

- The column `Dataset.published_at` should be changed to be `Dataset.originally_published_at` 
- A `DatasetVersion.published_at` column should be added

These are database column changes only, and do not impinge on the API.

**Comment by brianraymor** [comment]
@danieljhegeman 

@metakuni and I are triaging H2 candidates. Please ensure that there are descriptions in all issues. Why is this breaking change being proposed? I searched slack and found [**#single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1677287387344969). 

I recommended that this be closed.

**Comment by metakuni** [comment]
Removing from the epic in the meantime since this isn't a high priority item and we likely won't have time in Q3 to do this.

**Comment by danieljhegeman** [comment]
@brianraymor @metakuni I've added a description. These are database column changes, not API changes.

**Comment by danieljhegeman** [comment]
I recommend that we re-add this to the epic it was just removed from
