### ISSUE TITLE
Add published_at and collection_version_id to DatasetVersion

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4695]
In order to reduce extraction code complexity, it would be useful to keep `DatasetVersion.published_at` and `DatasetVersion.collection_version_id` columns on the DatasetVersion table. This would obviate the need for some fairly arduous calculations made at query time.

**Comment by brianraymor** [comment]
@danieljhegeman 

@metakuni and I are triaging H2 candidates. Please ensure that there are descriptions in all issues. I reviewed the swagger and see that both `published_at` and `collection_version_id` are defined? 

```

collection_version_id	string($uuid)
The Collection Version in which this Dataset Version was first published.

published_at	dataset_version_published_atstring
A timestamp of when this Dataset Version was published.

```

Can you advise?

**Comment by danieljhegeman** [comment]
@brianraymor these are database columns, not response fields. I've added a short description to clarify. Apologies for the ambiguity.

**Comment by brianraymor** [comment]
@metakuni - I defer closure or prioritization to you.

**Comment by metakuni** [comment]
Since these are non-user facing improvements, removing from the epic and we can consider implementing this when we do [Split persistence layer #4237](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4237)
