### ISSUE TITLE
Perform a spike to determine which of the proposed data sources are viable for CellCards.

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4713]
The proposed data sources for descriptions are:
 - The [OLS4 API](https://www.ebi.ac.uk/ols/ontologies/cl)
 - [Wikidata query curated by the CL team](https://query.wikidata.org/index.html#SELECT%20%3Fitem%20%20%3Fsitelink1%20%3Fsitelinks%20%3Fclid%0AWHERE%20%0A%7B%0A%20%20%20%20%3Fitem%20wdt%3AP279*%20wd%3AQ7868%20.%20%20%0A%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%3Fitem%20wdt%3AP279*%20wd%3AQ729463%20.%7D%20%23%20Excluding%20sensory%20receptors%2C%20as%20Wikidata%20mixes%20cells%20and%20other%20non-uniquely-cell%20receptors.%0A%20%20%0A%20%7B%20%3Fsitelink1%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%3B%0A%20%20%20%20%20schema%3Aabout%20%3Fitem%3B%7D%0A%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%7B%3Fitem%20wdt%3AP7963%20%3Fclid%20%7D%0A%0A%20%20%3Fitem%20rdfs%3Alabel%20%3Flabel%0A%20%20FILTER%20(lang(%3Flabel)%20%3D%20'en')%0A%20%20%20%20%20%20%20%20%0A%20%3Fitem%20wikibase%3Asitelinks%20%3Fsitelinks%20.%20%0A%20%20%20%20%20%20%20%20%0A%7D%0AORDER%20BY%20DESC(%3Fsitelinks))
 - ChatGPT :)

The proposed data source for canonical marker genes are:
 - [ASCT+B tables from HUBMAP](https://hubmapconsortium.github.io/ccf/pages/ccf-anatomical-structures.html)

Assessment of viability will depend on data quality, data comprehensiveness, and automation.

**Desired outcome**: The [Cell Cards tech spec](https://docs.google.com/document/d/1RDqK-oGq9ahH_bBoRTJC781qCkCsbk8krHlslMZ8hCI/edit) should be updated with the data pipeline design.

**Comment by dsadgat** [comment]
@atarashansky 
Is there space in this spike (or another ticket) to then create an addendum / additional tech spec with the technical aspects of the data pipeline?

**Comment by atarashansky** [comment]
I added that as a desired outcome to this ticket.
