### ISSUE TITLE
Source data is unclear for users coming to Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4728]
We've gotten two pieces of feedback that source data is unclear for users who are coming to Gene Expression. 40% of users come straight to Gene Expression, 60% come through the home page or elsewhere on the site. Our hypothesis is that for users who come straight to Gene Expression, they may not understand that the data portal powers Gene Expression.

We would like to prioritize an onboarding user research study to comprehensively understand what questions users have when they come to our site. In the short term, we'd like to be more explicit about the data used to power Gene Expression, potentially in the Source Data panel.

[**Figma**](https://www.figma.com/file/nUbwlxcSPAGoRGWyYaIkyv/Q2-2023-Gene-Expression-Improvements?type=design&node-id=278-73227&t=Pl0ZJPLxSepWNa6y-0)

**Added language:** Gene Expression is powered by primary data submitted to CZ CELLxGENE Discover. See exceptions and processing notes [here](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_3__Gene%20Expression%20Data%20Processing).

[Link to feedback in feedback tracker.](https://airtable.com/app8fNSQ8ieIiHLOv/tblqoYEr9Ee7rYrut/viwFPtZPfH7r2hIzk/recKPf96GX3WqIisS?blocks=hide)

cc @signechambers1 @karenliang0

**Comment by signechambers1** [comment]
@ashin-czi looks great! thank you!

**Comment by karenliang0** [comment]
Looks awesome, Andrew! Thank you so much!
