### ISSUE TITLE
Documentation outline does not show up when you click in from Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4729]
The documentation outline does not show up when you click in from Gene Expression. This inhibits users from knowing there are additional pages that show the methodology and data processing. I would like the outline to expand to show where the user is on the page by default.

[Link to documentation](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_1__Get%20Started)

**Current view:**
![Screenshot 2023-05-02 at 11.01.48 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/991c97ea-46dd-462d-866a-918b0402898e)

**Desired view:**
![Screenshot 2023-05-02 at 11.01.57 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/336f5ecc-590b-4714-bfed-2b66f4cc3c33)

**Comment by joyceyan** [comment]
should be fixed in this PR https://github.com/chanzuckerberg/single-cell-data-portal/pull/4888

not entirely sure when it will deploy to prod
