### ISSUE TITLE
fix github actions AWS permissions

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4737]
Staging post-deploy [func tests failed](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/4866096281/jobs/8690654327) due to GHA not having correct AWS perms:
 ```
Error: Failed to list store contents: AccessDeniedException: User: arn:aws:sts::***:assumed-role/cellxgene-github-actions-dev/GitHubActions is not authorized to perform: secretsmanager:GetSecretValue on resource: corpora/backend/staging/auth0-secret because no identity-based policy allows the secretsmanager:GetSecretValue action
```

Likely introduced by https://github.com/chanzuckerberg/single-cell-data-portal/pull/4702/files

An earlier perms fix was made [here](https://github.com/chanzuckerberg/single-cell-infra/pull/782)

**Comment by atolopko-czi** [comment]
It looks like the perms _should_ exist:

https://github.com/chanzuckerberg/single-cell-infra/blob/main/terraform/modules/hosted-cellxgene/iam.tf#L248

**Comment by metakuni** [comment]
Lower priority than fixing staging/prod deployment issues, but FYI, I just noticed that our happy stack reaper GHA is also failing with `AccessDeniedException`s. e.g.:
- https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/4873370595/jobs/8692864143

```
[FATAL]: unable to write a workspace param: could not write parameter to /happy/data-portal/rdev/stacklist: operation error SSM: PutParameter, https response error StatusCode: 400, RequestID: 668eb4ba-9677-4199-bc37-ce7b6c7a97e4, api error AccessDeniedException: User: arn:aws:sts::***:assumed-role/cellxgene-github-actions-dev/HappyCleanupSingleCellDPRdevStacks is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:us-west-2:***:parameter/happy/data-portal/rdev/stacklist because no identity-based policy allows the ssm:PutParameter action
```

**Comment by atolopko-czi** [comment]
> Lower priority than fixing staging/prod deployment issues, but FYI, I just noticed that our happy stack reaper GHA is also failing with `AccessDeniedException`s. e.g.:

Thanks! Moved into a new issue, so that I can close this one and feel like I'm making progress in my life. 😄
