### ISSUE TITLE
Corpus Migration Job

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4749]
Script and Infra work can be parallelized

**Comment by Bento007** [comment]
Statemachine Diagram
1 Start revision from collection ID
2 Fan out and migrate each dataset. Upload the migrated datasets to the main bucket. Return the s3 path to the migrated dataset.
  A. Start the dataset submission work flow using the s3 path
3 Once all have completed publish the collection.

**Comment by Bento007** [comment]
What do we do if some of the datasets error out.

**Comment by nayib-jose-gloria** [comment]
At minimum, we should report it in the ops channel. Given that its a bulk migration, we should aggregate an 'error report' before posting vs. posting every failure. If its a few point failures, I think its fine if the ask is that curators manually inspect and reupload / republish. If its widespread, its probably an issue with the migrate script or our system, in which case its a sign to fix something + kick off a new migration.

**Comment by nayib-jose-gloria** [comment]
I think its fine imo to have mixed minor versions in a case where some are migrated successfully and some are not (since the only difference is in the reference files). But, if desired, we can wait to bulk publish once all datasets have been uploaded successfully soo that its an atomic switch and an error would just effectively cancel a migration (though we can keep revisions open in that case for any successful cases)

**Comment by Bento007** [comment]
## State machine diagram
![Screenshot 2023-06-15 at 10.39.58 AM.png](https://images.zenhubusercontent.com/5a4d3418a016c5b034bbeac9/025f83f7-190a-4803-a2a8-05d5e4f20b9b)
## [Mermaid Source Code](https://mermaid.live/edit#pako:eNqVVLtuhDAQ_BXLZXQ0KSlSJWWqlCFCG7PkLBnb8iNSdOLfYzDE5nGIuAJmZh-Dd2-UqQZpSa0Dh88cvgx0xfdjJUk47w8fpCieiGVX7KDueEAdV7LmkjsOThkSiQeEQc-U0d4m-JSoBS68wZKgMcpEyTpQrE6DrJkSAtnwzR5Q92KOnW-CkFtEcxsSvG4lJtyiqb4GHFh0NvGzvDOYJ80TT_he1uFs4IVIG8XQ2v9IljaRfekUlxwoTwhDi4nVZ-4sfFm5r_2n4PZ6wvsMuFfaNu4Z5VTqYZn7N3gNjyqDWhmHW1Je0kwqifUs_dP7cea32Wl6oR2aDngTJn68axV1YQixomV4bLAFL1xFK9kHqtehMXxpeJhIWrYgLF4oeKfefiSjpTMeZ9K0OP5YOIpe42oZN0z_C-7de5I)
```mermaid
stateDiagram-v2
    [*] --> schema_migration_initiator 
    schema_migration_initiator --> corpus_migration
    schema_migration_initiator --> failure: error
    corpus_migration --> span_collections
    corpus_migration --> failure: error
    state span_collections {
        [*] --> collection_migration
        collection_migration --> span_datasets
        state span_datasets {
            [*] --> dataset_migration
            dataset_migration --> dataset_process
            dataset_migration --> dataset_failure: error 
            dataset_process  --> dataset_failure: error
            dataset_process  --> [*]
        }
        span_datasets --> collection_publish
        collection_migration --> collection_failure: error
        collection_publish --> collection_failure: error
    }
    span_datasets --> collection_failure: error
    collection_failure --> reporter
    collection_publish --> reporter: success
    failure --> reporter
    reporter --> [*]
```
