### ISSUE TITLE
feat(wmgv2): Refactor `/query` endpoint to be capable of querying without having tissues specified in its request body

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#4761]
Here are the execution steps in order:

1. Inject dimensions as arguments (Dependency Injection) into the `WMGQuery` public methods like [`expression_summary`](https://github.com/chanzuckerberg/single-cell-data-portal/blob/aa092f81fdb944ad13f9007bbb65c917fa626f80/backend/wmg/data/query.py#L63). This would effectively set the stage to use the [`query`](https://github.com/chanzuckerberg/single-cell-data-portal/blob/aa092f81fdb944ad13f9007bbb65c917fa626f80/backend/wmg/data/query.py#L59) module to query without tissues
2. `tissue_ontology_term_ids` ([here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/aa092f81fdb944ad13f9007bbb65c917fa626f80/backend/wmg/data/query.py#L14)) should be updated to allow no items (`min_items=0`) 

At the end of these 2 steps, `\query` in `v1.py` is technically capable of querying without specifying tissues in its request body.

**Comment by seve** [comment]
I think I just tackled this in my branch

**Comment by seve** [comment]
Never mind, I only handled the second point

**Comment by prathapsridharan** [comment]
This ticket is not relevant anymore and is superseded by https://app.zenhub.com/workspaces/single-cell-data-viz-backlog-641e2e32789cc20f6c3128e2/issues/gh/chanzuckerberg/single-cell-data-portal/4863

**Comment by prathapsridharan** [comment]
@seve - Please take note that this ticket is closed because it is superseded by https://app.zenhub.com/workspaces/single-cell-data-viz-backlog-641e2e32789cc20f6c3128e2/issues/gh/chanzuckerberg/single-cell-data-portal/4863
