### ISSUE TITLE
feat(wmgv2): Refactor wmg cubes to remove tissue index

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#4762]
`expression_summary` and `expression_summary_default` cubes will be refactored to update `tissue_ontology_term_id` to be an attribute instead of a dimension. 
* Specifically, dimensions will be `[gene_ontology_term_id, organism_ontology_term_id]` for both cubes.
* Attributes will be the same as they are for both cubes, with the addition of `tissue_ontology_term_id`.
----
Note: The existing schemas should be copied to new modules, and the backend should be updated to import from the copied modules. This will prevent regressions as the pipeline updates the data artifact. Later work will delete these copies and update the backend to read from the updated modules once the feature is ready to deploy.

**Comment by prathapsridharan** [comment]
The performance benchmark for wmg/v1 and wmg/v2 as documented in [#4976](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4976) indicates their performance is similar. Therefore this work is currently not needed.
