### ISSUE TITLE
feat(wmgv2): Make adding genes more intuitive

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#4766]
**⚠️⚠️⚠️⚠️ MUST BE IN PROD BEFORE 9/5 ⚠️⚠️⚠️⚠️**

Adding genes to the dot plot should be a more intuitive experience that matches the UX of the cell type search.

- [ ] Remove add gene button and replace with [Autocomplete](https://mui.com/material-ui/react-autocomplete/), similar to cell type search
- [ ] Update e2e tests
- [ ] Ping @MegUrisko @karenliang0 @niknak33 for testing

**UX Design**
[Figma](https://www.figma.com/file/Mfo9nQ1m3jQzdPbwoEZvOP/Gene-Expression-v2?type=design&node-id=5686-171103&mode=dev)

**⚠️⚠️⚠️⚠️ MUST BE IN PROD BEFORE 9/5 ⚠️⚠️⚠️⚠️**

**Comment by tihuan** [comment]
Should we wait for SDS to build the Autocomplete component for us? Around Aug 18 ![Screenshot 2023-07-27 at 11.17.41 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/aaa2ccb5-ee44-4c40-af15-98c4adc43841)

https://docs.google.com/spreadsheets/d/151dzBKp5tB0AvgEr6E-A2Bi2dt7PaeCl9YeVNGmY4Q0/edit#gid=733175099

**Comment by tihuan** [comment]
@seve thanks for helping to get this done and be ready before 9/5 user studies! 🙏 🙏 🙏 

CC: @niknak33
