### ISSUE TITLE
Investigate Publish Test Results Failing

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4769]
## Motivation

Currently the Publish Test Results stage in GHA is failing which shows failures in PRs

![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/03015bd4-80f4-481a-993e-5c7aa60ed45d)
![image.png](https://images.zenhubusercontent.com/62dee801e47e5625ea12d27f/cb27a10f-126a-446e-a294-848da1307c27)

## Definition of Done

Publish test results should work as before and generate a report successfully 

## Tasks

- [ ] Investigate publish test results failure

**Comment by tihuan** [comment]
This is fixed yesterday! #4771
