### ISSUE TITLE
Integrate with Slack to upload 'dry-run' curator report

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4782]

**Comment by Bento007** [comment]
I found this https://gist.github.com/lakshmantgld/42b32a38af2a64b5b683bbc92aae8d8e to be useful

**Comment by Bento007** [comment]
Do we went to upload to slack as a file.txt or as a message?

**Comment by Bento007** [comment]
[Here](https://api.slack.com/methods/files.upload) is how we can upload via curl command
