### ISSUE TITLE
Update cellxgene-schema validate command to validate against latest minor schema version

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4786]
As part of release workflow, update cellxgene to validate against whatever the newest schema version is

May want to set as a global config, pull that where schema is validated in the cli, and then automate updating that file before a merge/release to PyPI

**Comment by Bento007** [comment]
> Update schema versions create a template for schema.md minor update cellxgene_schema_cli versions when ontologies change

This is not needed. All we needed to do was update the validator to always validated against the latest  minor version.
