### ISSUE TITLE
Move ontology mappings that inform Frontend filters to S3 bucket

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4795]
new, or leverage existing if we already have one that’s appropriate

Cell Type Ontology [Mapping](https://github.com/chanzuckerberg/single-cell-data-portal/blob/827ca730da15affb64b221d7af630851b2d24cf9/backend/corpora/common/utils/cell_type_ontology_mapping.py#L4-L3)
Cell Type [Descendants](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/components/common/Filter/common/constants.ts#L443) 
Tissue Ontology [Mapping](https://github.com/chanzuckerberg/single-cell-data-portal/blob/827ca730da15affb64b221d7af630851b2d24cf9/backend/corpora/common/utils/tissue_ontology_mapping.py)
Tissue [Descendants](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/components/common/Filter/common/constants.ts#L2024)
Development Stage Ontology [Mapping](https://github.com/chanzuckerberg/single-cell-data-portal/blob/f79c5da26babe85c09066708128338cdfc536833/backend/corpora/common/utils/development_stage_ontology_mapping.py#L3)

**Comment by atolopko-czi** [comment]
@nayib-jose-gloria Can you also update the Tech Overview doc to make mention of this new bucket? Ty!
