### ISSUE TITLE
Turn on intelligent tiering in dataset-assets and corpora-data S3 buckets

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4798]

**Comment by Bento007** [comment]
Do we have more details on how we want to do this configure the intelligent tiering?

**Comment by nayib-jose-gloria** [comment]
@Bento007 https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-intelligent-tiering.html, but we DON'T want to enable S3 Intelligent-Tiering Archive Access and Deep Archive Access tiers

**Comment by nayib-jose-gloria** [comment]
Cost saving measure about how we store artifacts in the backend. It can happen async to migration because it is agnostic as to how/when those files get there. We will implement it either in parallel, as a follow-up, or in 4.0 if necessary.

**Comment by danieljhegeman** [comment]
This issue requires a 1, possibly 2-day spike before an accurate estimate of total time can be made, though for now I suspect the worst-case scenario is one week.

**Comment by danieljhegeman** [comment]
Confirmed application of Intelligent Tiering via lifecycle [will be retroactive](https://aws.amazon.com/s3/faqs/#:~:text=S3%20Lifecycle%20policies%20apply%20to%20both%20existing%20and%20new%20S3%20objects) (for pre-existing objects)
