### ISSUE TITLE
Create Lambda that fetches collection IDs + submits to batch job

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4799]
fetches collection IDs for every published and private collection in the corpus

Edge case: don’t fetch collection ID for public collections with open revisions, but do fetch the revision ID

Output collection ID list such that an AWS Batch Array Job can use it to trigger Jobs

**Comment by Bento007** [comment]
We can use business logic to make this happen.
