### ISSUE TITLE
Create ‘Rollback' Job

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4811]
- Run manually, only can be triggered by powerusers
- Points canonical Datasets / Collections in database to previous Dataset Version or Collection Version
- Delete database rows related to erroneous dataset versions that may be created by accident
- Necessary to block them from appearing in versions endpoints
- Can accept no input (will rollback the latest schema minor version for every collection where applicable), or list of collection IDs to only rollback specific collections

A lambda should be doable, but may need to do batch job if long-running. Or cxg admin script in repo

**Comment by danieljhegeman** [comment]
@Bento007 @nayib-jose-gloria does the rollback feature for schema migration require the ability to rollback to a previous _unpublished_ Dataset version? Or only to the previous _published_ version?
