### ISSUE TITLE
Add `visibility` query parameter to dataset index to fetch private datasets

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4841]
# Context 

_added by @brianraymor_

See [**#single-cell-discover-api**](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1690228380491379?thread_ts=1690212233.937829&cid=C03PXFMM7ST) and [**#single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1690219077787599)

@jahilton wrote:

> I would enjoy seeing that capability.
> I specifically want to test migration updates, which rely on dataset title for private datasets (so we don’t expose uuids publicly) and that property are not returned in collection[‘datasets’]

---

Mini tech spec:
* https://docs.google.com/document/d/1-qP4vIN_RlNH-MASUSHI8vWKKbd0LfAIBwB682Dyb3I/edit#heading=h.tt98dulq6wn6

**Comment by brianraymor** [comment]
I would like to review the swagger when available. And this API is limited to authorized consumers similar to other "curator" API(s).

**Comment by metakuni** [comment]
@nayib-jose-gloria , I can't recall the context for this issue... Do we still need/want this? And is it still a P2?

**Comment by nayib-jose-gloria** [comment]
@metakuni the curation API doesn't have an endpoint to query for a list of all private datasets. At best, you need to query for private collections then make a follow-up call per dataset to get its metadata. We ran into this extra overhead when working on the ontology dry run reporter, and I believe (though I can't find the message) that Lattice suggested they would find this endpoint useful as well. 

It's not a requirement since the ontology report works fine with the extra calls, so maybe its a p3. But it would be nice to have

**Comment by brianraymor** [comment]
> Lattice suggested they would find this endpoint useful as well.

@nayib-jose-gloria -are these the conversations ? 

* https://czi-sci.slack.com/archives/C03PXFMM7ST/p1690228380491379?thread_ts=1690212233.937829&cid=C03PXFMM7ST
* https://czi-sci.slack.com/archives/C02UGUV5R3J/p1690219077787599

If so, I'll add them to the top-level summary comment for context.

**Comment by metakuni** [comment]
Downgrading to P3 for now then.

**Comment by Bento007** [comment]
The dataset index input is intended to return all of the datasets and let the user filter locally. I think we should keep with the that paradigm otherwise we open the flood gates to add more complex filtering similar to the portal. 

I propose we include an flag in the response to indicate the dataset is private and let the curators continue to filter locally.

This change will also require adding authentication to the dataset index endpoint.

**Comment by brianraymor** [comment]
> I propose we include an flag in the response to indicate the dataset is private and let the curators continue to filter locally.

@jahilton - comments?

**Comment by jahilton** [comment]
That would be fine with me

**Comment by MillenniumFalconMechanic** [comment]
Hi @brianraymor, it looks like the Discover API datasets index currently only returns public datasets. To confirm, the changes required for this ticket are:

1. Modify the Discover API datasets index to return all public and private datasets.
2. Update the Discover API datasets index response shape to include a flag indicating if a dataset is private.

Note, these updates would allow discovery of all private datasets by calling the non-authenticated Discover API datasets index endpoint. Is this the intended behavior?  Our understanding is that private datasets are currently only available to users who know the private collection version URL.

**Comment by brianraymor** [comment]
> Note, these updates would allow discovery of all private datasets by calling the non-authenticated Discover API datasets index endpoint. Is this the intended behavior? 

This is a feature requested by curators, it would require the API key similar to other curator operations in the Discover API. A curator would only see the private collections they're authorized to see. A regular curator only sees their private collections. Super curator (Lattice) can see all private collections. Please compare against Discover API endpoints that are intended only for curators and not consumers.
