### ISSUE TITLE
Create Cloudfront route for Swagger link

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#4843]
The Swagger doc index was historically located at https://public-backend.production.single-cell.czi.technology/, and has now moved to https://backend.production.single-cell.czi.technology/ due to a LB rename within happy. Since those URLs are effectively owned by happy, they shouldn't be used externally. We should instead create a Cloudfront route that is stable and uses the right domain (e.g. https://cellxgene.czisciene.com/swagger)

**Comment by brianraymor** [comment]
> they shouldn't be used externally. We should instead create a Cloudfront route that is stable and uses the right domain (e.g. https://cellxgene.czisciene.com/swagger)

With the exception of the curation endpoint, none of these swagger are intended for external use.

**Comment by brianraymor** [comment]
We should close this and rely on https://api.cellxgene.cziscience.com/curation/ui/#/ when we broadly announce the Discover API. We don't want external data consumers to use any of the other API(s) such as DP.

**Comment by ebezzi** [comment]
I wasn't aware of that link. Definitely no need to do anything else then. Closing!
