### ISSUE TITLE
Update README to include instructions on running auth-related tests locally

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#4878]
#### Approach
* See @tihuan's original instructions on [Slack](https://clevercanary.slack.com/archives/C023Q1APASK/p1684527025846779?thread_ts=1683244820.549759&cid=C023Q1APASK).
* For frontend changes against a deployed backend:
    1. Connect your local FE app to deployed dev API, so your local app fetches data from dev API
    1. Follow changes in this draft PR: https://github.com/chanzuckerberg/single-cell-data-portal/pull/4868
    1. Run `HEADFUL=true SKIP_LOGIN=true npm run e2e -- -- /Users/thuang/Code/single-cell-data-portal/frontend/tests/features/collection/revision.test.ts`

COMMENTS:
Reference PR example: https://github.com/chanzuckerberg/single-cell-data-portal/pull/4868

**Comment by MillenniumFalconMechanic** [comment]
Hi @tihuan, I was unable to set the `cxguser` cookie in `frontend/playwright.config.ts` but had success setting it using the `page` object within tests, like:

```
await page.context().addCookies([
  ...
]);
```

Let's discuss when you have a moment!

**Comment by brianraymor** [comment]
@MillenniumFalconMechanic @metakuni - who's the owner for this issue?

**Comment by tihuan** [comment]
Thanks Brian 👍  I should be the owner!
