### ISSUE TITLE
Update tiledb python library to latest version

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#4893]
As of this writing, the latest `tiledb` python library is `0.21.4` : https://pypi.org/project/tiledb/#history

This needs to be fixed because the `requirements.txt` [has pinned `tiledb` at 0.16.5](https://github.com/chanzuckerberg/single-cell-data-portal/blob/4b4fb4384f414e271c828255c05ca8b4b2b55895/requirements.txt#LL25C12-L25C12) which is starting to really lag the latest release and given that we depend on this database, we shouldn't wait too long to upgrade as that will exact a lot of pain when we are forced to upgrade.

Moreover, **cannot be installed on M1 Macs**. Only newer versions of tiledb can be `pip install` on M1 Macs. This means that docker containers (which runs version `0.16.5`) is different from `0.21.*` that one can install in their M1 Mac python virtual environment.

This means running _unit tests locally without docker_ fails due to backward incompatibility in the `tiledb` python API between `0.16.5` and `0.21.*`.

One example in API incompatibility is this:

#### 0.16.5

Calling `query` method is done this done by passing in `QueryCondition` object

`query_result_df = cube.query(attr_cond=attr_cond, use_arrow=True).df[tiledb_dims_query]` (https://github.com/chanzuckerberg/single-cell-data-portal/blob/4b4fb4384f414e271c828255c05ca8b4b2b55895/backend/wmg/data/query.py#L157)

#### 0.21.3

Here the `QueryCondition` object has been discarded and a string version of the query expression is passed in if the string is non-empty or `None` is passed in if the string is empty.

```
query_result_df = cube.query(cond=(query_cond_str if query_cond_str else None), use_arrow=True).df[tiledb_dims_query]
```

Best to upgrade when the API changes needed on the call sites are not too difficult to do.

**Comment by atarashansky** [comment]
Thanks for raising this @prathapsridharan  - to my knowledge, you've highlighted the only location in the code that would need to be updated to complete the upgrade.
