### ISSUE TITLE
Bug(curation) Obsolete session storage filters can result in getting stuck in "no results" collections and datasets

### ISSUE THREAD

**Issue by NoopDog** [chanzuckerberg/single-cell-data-portal#4906]
#### Description

In the updated curator experience, a curator can filter down to where a single row exists in the collections list, and then modify that single row so it no longer matches the filter. Once the update is processed the filter will show "no results" and the user will have to either clear the cellxgene session storage (which forces logout) or open the collections/datasets page in a new tab.

#### To reproduce

1. Login, with curator=true (as curator, not super curator)
2. Navigate to the collections page, 
3. Publish or cancel all your "Revision" collections except one (or create a revision collection if you don't have one)
4. Set the Status filter to "Revision" to filter out all collections except your one revision.
5. Publish or cancel your remaining revision

The status filter of "Revision" will be applied making the collection list show "No Results" but the filter will be missing from the filter selections on the left-hand filters ( the blue chip with "Revision") so you can't clear the "Revision" filter to get back to the full result set.

**Comment by NoopDog** [comment]
Regarding UX for this feture...


Our initial idea on the functionality for this was to show the empty list but also show the user the obsolete filter and let them dismiss it. Trying to develop this, we realized this requires, for ontology filters, for us to save the ontology term description along with the selected value in local storage when we save the filters. 

One simplifying idea is to clear the obsolete filters for the users automatically. Doing so would free us from having to save the term name and value and simplify the implementation. Usually, we don’t “do things for the user,” but I wanted to check if this was an acceptable UX for this “obsolete filters” corner case. 

To clarify, the user experience would be:
- Create a new collection. Add the Alzheimers dataset to the collection.
- Filter by Tissue: organ is brain and then tissue is entorhinal cortex.
- Create a revision of the new collection. Update the dataset to “All cells…“.
- Publish the revision.
- Go to the collections page.
- Instead of seeing “No Results” and no filters selected, we would detect that an obsolete filter was applied and silently. 

The UX approach above was discussed and thought "ok" on our Aug 14, 2023, call with Harley, Brian, and Kuni.

**Comment by NoopDog** [comment]
Ont the  Aug 14, 2023 call it was also determined that this fix will be deprioritized as the problem is not currently being complained about by curators. We will move this ticket back to "Disorder", and reprioritize if we hear curator feedback that this is a problem. 
@brianraymor @frano-m @metakuni

**Comment by brianraymor** [comment]
There have been no complaints from curators. @jahilton - may we close this issue as "nice to have"?

**Comment by jahilton** [comment]
Sounds good. (I have been entirely unaware of this. If others have seen it, it wasn't disruptive enough to warrant them mentioning it)
