### ISSUE TITLE
Integrate schema gated dataset fetch with Census Builder

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4927]

**Comment by brianraymor** [comment]
Until census builder is automated and merged into DP, this should be in the [`cellxgene-census` repo](https://github.com/chanzuckerberg/cellxgene-census)?

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/cellxgene-census #518](https://github.com/chanzuckerberg/cellxgene-census/issues/518) via [**Zenhub**](https://www.zenhub.com/)
