### ISSUE TITLE
Feedback Mechanism for Cell Guide

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#4931]
During our external feedback sessions, we heard multiple users mention they would like to edit/contribute/upload changes to the descriptions we had generated for the CellGuide product.

**Why** - By having a feedback mechanism in place, cell biologists can easily share their observations, suggestions, and concerns regarding the accuracy, completeness, or usability of cell type descriptions. This feedback not only helps refine the existing classification systems but also aids in the development of new methods that better capture the complexities of cell types. Ultimately, a feedback mechanism empowers cell biologists to actively contribute to the advancement of cell type characterization, leading to more accurate and comprehensive insights into cellular heterogeneity.

User Stories:

- As a user, feedback mechanism should be accessible from within the CellGuide interface, ensuring a smooth transition to provide feedback
- As a user, the feedback mechanism should have a user-friendly interface that is intuitive and easy to navigate.
- As a user, the feedback mechanism should have dedicated fields or sections to capture comments, suggestions, or issues related to cell type page.
- As a user, I want to provide feedback based on the cell type description I am currently viewing
- As a user, I want to see confirmation that the feedback I inputted was successfully delivered
- As a user, I want the option to submit feedback anonymously, respecting my privacy preferences 

Nice to have:
- Implement a system to send follow-up notifications or updates to users regarding the progress or resolution of their feedback, whenever applicable.

@hthomas-czi to provide latest designs.

- We can instrument the feedback into an Airtable, I will reach out to the trust team on how we handle emails in Airtable before we go live, this might be a sticky point based on the fact we are now collecting emails.

**Comment by atarashansky** [comment]
AirTable link: https://airtable.com/shrEReYLtRTAAsNiE
Figma link: https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellMap?type=design&node-id=1324-195937&t=vz2aMABJGnYnVrn4-0

![image.png](https://images.zenhubusercontent.com/62a0d9c6d187050d7413df9d/0e0b0f70-f802-49bf-9b3f-4302d5cf5876)
