### ISSUE TITLE
 Add help tooltip for Expression Score and % of Cells

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#4932]
Based on feedback from our first round of testing of CellGuide, we were asked to include a help tooltip for the definition of Expressions Score and % of Cells to help users understand that these columns of data represent.

Why - Expression scores and cell percentages can be complex metrics that require additional explanation to understand their meaning and significance. By incorporating tooltips, cell biologists can hover over or click on these metrics to access explanatory pop-up windows that provide detailed definitions, guidelines, or examples. 

Tooltips also promote consistency and avoid confusion by providing standardized explanations, ensuring that researchers have a clear understanding of how to interpret and utilize these metrics in their studies.

User Stories:

- As a user, I want the tooltip to provide clear definitions of expression scores and the percentage of cells, using language that is easily understandable to cell biologists of varying expertise levels.
- As a user, I want the tooltip to offer guidance on how to interpret different ranges or values of expression scores and percentages. This includes explaining what high or low values may indicate, as well as any specific thresholds or benchmarks that users should be aware of.
- As a user, the tooltip should be visually distinct and easily distinguishable from other elements in the user interface. They should have a consistent and recognizable appearance with the rest of the cellxgene product suite.

**UX Design**
Notes:

- We use three SDS [Tooltip](https://czi.zeroheight.com/styleguide/s/66099/p/74af45-tooltips/b/065f46/t/65e1c5) variants: Dark, Condensed, and Table.
- The dark-style [Tooltip](https://czi.zeroheight.com/styleguide/s/66099/p/74af45-tooltips/b/065f46/t/07fde2) should be used for communicating information about the interface or system to the user. For example, Help tooltips like this issue. 
- [TooltipCondensed](https://czi.zeroheight.com/styleguide/s/66099/p/74af45-tooltips/b/065f46/t/65e14f) and [TooltipTable](https://czi.zeroheight.com/styleguide/s/66099/p/74af45-tooltips/b/065f46/t/957d7f) should be used for communication additional information about the data that are being displayed, depending on the amount/complexity of the information. For example, the overflow Tag in the Data table or the citation links, or hovering over the dot plot in Gene Expression

**Comment by atarashansky** [comment]
**Text for expression score:**
The expression score is the average [rankit-normalized gene expression](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_3__Gene%20Expression%20Data%20Processing) among cells in the cell type that have non-zero values.

**Text for % of Cells:**
Percentage of cells expressing a gene in the cell type. These numbers are calculated after cells with [low coverage and low expression values](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_3__Gene%20Expression%20Data%20Processing) have been filtered out.

Requires @niknak33 's approval :D

**Comment by niknak33** [comment]
Approved - thank you Team.
