### ISSUE TITLE
Geneinfo Panel

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#4937]
Based on internal (product consistency) and external feedback on Geneinfo sources, we would like to present the user with NCBI as the source of Geneinfo data and an option for the user to also access Genecards information in a separate tab. We would like to present this in the form on a panel instead of tooltip, this is consistent with the offering we have in GE.

Why - A gene info panel provides a dedicated space where users can access a wealth of information about a gene without the need for repeated hovering or clicking. Unlike tooltips that provide brief, contextual snippets of information, a gene info panel can display a wide range of data such as gene annotations, expression patterns, and links to external databases. 

User Stories:

- As a user, I want to view a gene info panel that remains visible and accessible while viewing cells in the cell typing product. The panel should be displayed alongside or within the cell data, allowing users to refer to gene information continuously without obstructing the main view.
- As a user, I want the same consistent experience of accessing a gene panel as I experience in Gene Expression, with the source of description coming from NCBI Gene.
- As a user, I want to see links or integrations with external databases, such as NCBI Gene, and GeneCards, to provide users with additional gene information from trusted sources. This allows provides me with access more extensive and specialized details about the gene directly from the gene info panel.

[Figma](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellMap?type=design&node-id=1324%3A194120&t=TbPrZ4iR9h4lzPKy-1)

🎙️ COMMENTS:
- [ ] Make sure to instrument analytics
- [ ] GeneInfo behaviors - in large viewport - side panel is not dismissable and the geneInfo panel will be at the bottom
- [ ] GeneInfo behaviors - in small viewport - side panel will take up whole viewport and is dismissable. And the geneInfo panel will be at the top

**Comment by atarashansky** [comment]
Open in gene cards link will have the pattern:
``https://www.genecards.org/cgi-bin/carddisp.pl?gene=${symbol}``

**Comment by tihuan** [comment]
In prod now!

https://cellxgene.cziscience.com/cell-guide/CL_0002306
