### ISSUE TITLE
Analytics (new): Publication Filter

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4953]
### Overview

**Tool**: Gene Expression

- Feature: Publication Filter
**Description**: We have a new filter, publication, that users will be able to filter results by.
**Expectations**: We would like to know how often this filter is used and what values users filter on.

### New events to add

`FILTER_SELECT_PUBLICATION`: `{collection_name: 'name of collection user filtered on'}`

- `to fire whenever a user uses the publication filter (if a user filters on one collection and then adds another collection to the filter it should fire each time)`

Checklist

- [x] Add events to the custom goals section of both the staging and prod Plausible spaces
- [ ] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @signechambers1 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by ainfeld** [comment]
@carolinechoi can this issue be closed now?
