### ISSUE TITLE
Change DP API dataset schema (id, version id)

### ISSUE THREAD

**Issue by czepham** [chanzuckerberg/single-cell-data-portal#4972]
Current state of the data portal API dataset schema:
- 'id' field contains dataset version id
- no stable dataset id

Proposed changes:
- Update 'id' field to contain stable dataset id
- Add new 'version_id' field to contain dataset version id

Reasoning:
- Currently the front-end filtering system returns collections that do not contain stable dataset ids
- The new publication filter being built relies on the comparison of dataset ids belonging to selected publications with dataset ids belonging to selected datasets (from the respective secondary filters)
- The curation API can be called to get stable dataset ids from the version dataset ids that live in the returned collections data, but this is not ideal as some publications contain 25+ datasets & calling the curation API for each dataset may take an non optimal amount of time

**Comment by brianraymor** [comment]
**?** - change dataset schema may mean something different to me.

**Comment by czepham** [comment]
sorry about that, updated now! Will give you a tech spec soon as well

**Comment by brianraymor** [comment]
Can this be closed now?
