### ISSUE TITLE
feat(wmgv2): Do performance benchmark comparing `wmg/v1/query` and `wmg/v2/query`

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#4976]
Do the following 5 tests between `wmg/v1/query` and `wmg/v2/query` and report results. Ensure the queries are exactly the same between v1 and v2

1. query with filter criteria: all tissues
2. query with filter criteria: single gene and all tissues
3. query with filter criteria: all tissues and multiple genes **(~25)** by clicking `add to dot plot` for 1 cell
4. query with filter criteria: all tissues and multiple genes **(~50)** by clicking `add to dot plot` for 2 cell
5. query with filter criteria: all tissues and multiple genes **(~80)** by clicking `add to dot plot` for 4 cell
6. query with filter criteria: all tissues and multiple genes **(~170)** by clicking `add to dot plot` for 8 cell

**Comment by prathapsridharan** [comment]
### Get All Tissues

|version|total response time|waiting for server response|
|-------|-------------------|---------------------------| 
|   v1.    |        1.72s                |.        1.66s                            |
|   v2.    |        1.74s                |.        1.68s                            |

**Comment by prathapsridharan** [comment]
Per the benchmark done above, `wmg/v1` and `wmg/v2` have similar performance for the `\query` endpoint. @signechambers1, do you agree that at this point performance need not be prioritized?

**Comment by signechambers1** [comment]
@prathapsridharan agreed! we do not need to prioritize performance of the endpoints now. Thank you for this analysis.
