### ISSUE TITLE
CXG(s) for deleted datasets are not deleted

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#5000]
### Context

See [**data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1686604455914939). 

This is another regression. 

1. If a collection is deleted by a submitter, then each CXG for the datasets in the collections must be deleted.
2. If a dataset is deleted by a submitter, then its CXG must be deleted.

**Comment by danieljhegeman** [comment]
@brianraymor reading the Slack thread, Jenny has asked if we can redirect users to the homepage when a user visits a deleted cxg url `../e/<deleted_dataset_id>.cxg/`

Should that ask be included as a requirement for this ticket?

**Comment by brianraymor** [comment]
> Edit: [redirect regression](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5004) describes this, so it will be handled as part of that ticket within this epic.

Correct. The original toast and redirect was regressed.

**Comment by danieljhegeman** [comment]
@brianraymor I think I mentioned this in Slack already, but public-access Dataset versions were also not being deleted _in cases where the Dataset versions were never published._ I have included logic to this.

**Comment by danieljhegeman** [comment]
Tested scenario where a subset of the expected assets are not actually in s3 through some sort of glitch; the deletes do not choke in this case 👍
