### ISSUE TITLE
Redirect and toasts for withdrawn collections and datasets (CXG) were regressed

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#5004]
### Context

See the original design:

* [Curators may delete a published collection](https://github.com/chanzuckerberg/single-cell/issues/132)
* [feat(withdraw): Add withdrawn collection toasts](https://github.com/chanzuckerberg/single-cell-data-portal/issues/1283)
* [feat(withdraw): Add withdrawn dataset toast](https://github.com/chanzuckerberg/single-cell-data-portal/issues/1237)

### Refinements 

A withdrawn collection should now redirect the consumer to the collections tab. The related [message](https://github.com/chanzuckerberg/single-cell-data-portal/blob/7c156bc829468184bba555f49f10c1223d978b01/frontend/src/components/Collections/common/utils.ts#L25):

          "This collection was withdrawn. You’ve been redirected to the cellxgene Data Portal homepage.",

needs to be updated:

          "This collection was withdrawn. You’ve been redirected to Collections.",

**Comment by MillenniumFalconMechanic** [comment]
See [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1692734823407699).

_What I did:_
- Deleted a collection
- Viewed the deleted collection in the DP

_What happened:_
- I was redirected to the DP home page

_What I expected:_
- Redirected to the collections tab
- Toast popped with the updated text (as per ticket)
