### ISSUE TITLE
Use independent requirements.txt files for each image

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5024]
We currently have a schema whereby Docker images install requirements from two requirements.txt files, a "base" file and an image-specific file:

```
ADD requirements.txt requirements-base.txt
ADD backend/api_server/requirements.txt requirements-api.txt
RUN python3 -m pip install -r requirements-base.txt -r requirements-api.txt
```

The makes it more difficult to infer exactly which python package versions are installed since you must 1) first know that this is being done in the Dockerfile, 2) examine both files (which may even specify redundant packages but at different versions).

Also, defining common dependencies across images is not necessarily a good thing, since:
* Different teams may "own" different images, but a single change to the base requirements impacts all images
* We can end up with a base requirement that isn't actually needed by an image, causing image bloat (this is currently happening).
* We sometimes need different versions for the same package in different images. One known case is the TileDB reader-stays-ahead-of-writer case, between the WMG FE/BE image and the WMG pipeline image.

To address these concerns, the team agreed at the 2023-06-14 staff meeting that each Docker image will maintain its own, independent requirements.txt file that lists _all_ of it requirements in one place. Related, we agreed that dev-time-only requirements (testing packages, linters, etc.) should be placed a requirements-dev.txt file, to differentiate between prod run-time requirements and dev requirements.

**Comment by metakuni** [comment]
Removing the `dp` label since Prathap said that he'd be addressing all requirements.txt files. 🙇
