### ISSUE TITLE
Canonical Markers from ASCT+B Sorted based on Refs

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5033]
From our second round of user testing, we found that users were confused when they navigated the canonical markers that certain markers were shown without references on the first page. 

User Stories:

As a user, I want to see canonical markers with actual references to be sorted as the highest priority/ranked (at top) in alphabetical order.
As a user, I want to see canonical markers with no references to be sorted as the lowest priority/ranked in alphabetical order.

**Comment by atarashansky** [comment]
@ashin-czi When you change the cell card, the pagination state for the table should be reset to 0. Please add this to the PR :) <3
