### ISSUE TITLE
Cell Type Descendants on Tissue Page

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5037]
Based on our second round of external user feedback, users noticed that cell type descendants not in a tissue are able to be viewed on the tissue page.

User Story:

As a user, when I view a selected tissue page, I should not be able to view cell type descendants that are not present in the tissue.

Notes from (alec) Add a new property to tissue cell ontology tree state fixture indicating cell types that are able to be displayed. Cell types not in this list should have a different visual indicator.

**Comment by dsadgat** [comment]
@hthomas-czi need input here
