### ISSUE TITLE
Analytics (new): Cell Guide Instrumentation 

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5049]
### Overview

**Tool**: `Cell Guide/Maps`

- Feature: `Users reaching Landing page, User searches for cell type/tissue and enter search, interactions on cell card page that qualifies them as engaged (Copy description OR scroll OR click on a section OR click on the page), MODIFIED - scroll/current section changes, Somehow (click ontology or search within cell) go to a different cell, search within CellGuide, search within ontology, (implicit)) copy url (no action)`

**Description**: `New Product Feature Launch`
**Expectations**: `We expect a wide range of users to engage with CellGuide via a number of aspects on the cell type page, depending on the user type, they spend an longer duration than most and browse other cell types`

### Cell Guide top line metrics
`Awareness`: # visitors view the landing page OR any of the individual cell type/tissue pages 
`Interaction`: # visitors view any of the individual cell type/tissue pages (even if they enter on these pages) 
`Engagement`: # visitors that search, interact with the ontology tree, copy cell type descriptions, or view any other sections in the individual cell type/tissue pages

### New events to add
`CG_SEARCH_CT_TISSUE`: `{tissue: "tissue name", cell_type: "cell type"}`
- to fire if a user searches and selects a cell type or tissue using the search bar on the landing page or any of the cell type/tissue pages 
- depending on whether a tissue is searched for or a cell type, that's the payload field that will be populated with the value that was selected 

`CG_TREE_NODE_CLICKED`: `{cell_type: ["cell type name" OR "multiple cell types"]}`
- to fire if a user clicks on one of the nodes in the ontology tree 
- if the node clicked is for a specific cell type, record that cell type name in the payload 
- if the node clicked is for multiple cell types, record the value "multiple cell types" in the payload

`CG_TREE_CELL_TYPE_CLICKED`: `{cell_type: "cell type"}`
- to fire if a user clicks on one of the cell type labels in the ontology tree

`CG_VIEW_SECTION`: `{section: "section label"}`
- to fire if the section highlighted in the navigation bar on the right changes, this can be from clicking on one of the sections directly or just scrolling to that section 

`CG_COPY_CELL_TYPE_DESCRIPTION`
- to fire if a user copies any portion of the cell type description 

`CG_CHAT_GPT_HOVER`
- to fire when the user hovers over the ChatGPT link by source in the cell type description section 
- to understand if visitors are curious about this use 

`CELL_GUIDE_CLICK_NAV`
- to fire when the user clicks the cell guide tab in the navigation bar 
- make sure it doesn't fire if clicked when already on the cell guide page

`SUGGEST_CHANGE_CLICKED`
- to fire when a user clicks the `Suggest Change` button on any of the individual cell type pages

`CELL_GUIDE_CANONCIAL_TAB_CLICKED`
- to fire when a user clicks the `Canonical (HuBMAP)` button in the `Marker Genes` section of any of the individual cell type pages 

`CELL_GUIDE_COMPUTATIONAL_TAB_CLICKED` 
- to fire when a user clicks the `Computational (CZI)` button in the `Marker Genes` section of any of the individual cell type pages

Checklist
- [ ] Add events to the custom goals section of both the staging and prod Plausible spaces
- [ ] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @niknak33 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by ainfeld** [comment]
@ashin-czi wanted to flag I updated this issue slightly this morning
