### ISSUE TITLE
Entry/Exit Points for CellGuide V2

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5079]
As a user, I want to view the cell-type descriptions in Gene Expression when I select a cell type from the heatmap

As a user, I want to explore further about the cell type I have chosen within Gene Expression (entry into CellGuide)

As a user, I want to explore further the gene expression of a particular cell type (entry into GE - Open in Gene Expression link)

Figma Link - https://www.figma.com/file/Mfo9nQ1m3jQzdPbwoEZvOP/Gene-Expression-v2?type=design&node-id=6314-209402&mode=design&t=mx5STeGmjIFMUaRR-0

**Comment by atarashansky** [comment]
We need to patch CellGuide to form the share link URL to filter the cell types

**Comment by carolinechoi** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/4876
https://github.com/chanzuckerberg/single-cell-data-portal/pull/5382
https://github.com/chanzuckerberg/single-cell-data-portal/pull/5340
