### ISSUE TITLE
SEO for Cell Guide

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5080]
Epic: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5206

**Background:**
SEO Recommendations from Central Team
Implement unique meta titles and descriptions using a template format. We recommend using a template to programmatically generate unique meta titles and descriptions for each URL. Target the following keywords, whose average number of searches per month in the US are: 
Cell types - 2,400
Cell tissue - 1,000

**User Stories:**
1. As a user, I want to be able to find cell types or tissues via Google Search. AND As a user, I want to view a short description of the cell type I searched on Google.
    - This implies we implement meta tags that include the cell type/tissue name for each cell type (Wildcard SEO method)
    - This implies we implement a cell-type description in the meta description of cell type page for SEO and Google search results, ensuring they are concise, compelling, and accurately represent the content of our page, aiming for a length of around 150-160 characters to avoid truncation in search results.
    - Solution: We'll use GPT4 to generate ~150 chars of description

1. As a user, I want to search Google via synonyms and find CellGuide/Maps pages.
    - This implies we implement meta tags that include synonyms for each cell type (Wildcard SEO method)

1. As a user, I want to be able to view the sitemap index/html sitemap and find cell pages I am interested in
    - We can assign the central team to perform this task; we did this previously with our site in Q4 2022
 
Guidance from the SEO team on how to construct our meta titles and meta descriptions - https://docs.google.com/document/d/1R8ocUllm8EV3SPd5XBkY1rIC8sZgYVV1A93dsA7QujQ/edit#heading=h.kh7oxyc39a8c

**Comment by tihuan** [comment]
@atarashansky to support story `As a user, I want to search Google via synonyms and find CellGuide/Maps pages.` - does BE store synonyms for each cell type already?

If not, it sounds like we need to do some research to figure out how to find the synonyms 💡

**Comment by tihuan** [comment]
@atarashansky to support story `As a user, I want to search Google via synonyms and find CellGuide/Maps pages.` - does BE store synonyms for each cell type already?

If not, it sounds like we need to do some research to figure out how to find the synonyms 💡

**Comment by tihuan** [comment]
Still 3 questions need to be resolved in the gDoc:

https://docs.google.com/document/d/1R8ocUllm8EV3SPd5XBkY1rIC8sZgYVV1A93dsA7QujQ/edit#heading=h.kh7oxyc39a8c

CC: @niknak33 

Thank you!

**Comment by tihuan** [comment]
@niknak33 for User Story 1, currently it says to only have ~150 char description for cell types, what about cell tissues? Thank you!

**Comment by niknak33** [comment]
@tihuan I am assuming we can use synonyms from CL? @atarashansky is that feasible?

**Comment by niknak33** [comment]
@tihuan Now that @atarashansky has a PR ready for tissue descriptions, we can complete 150 char descriptions for them as well.

**Comment by tihuan** [comment]
> @tihuan I am assuming we can use synonyms from CL? @atarashansky is that feasible?

@atarashansky PTAL thank you 🙏

**Comment by dsadgat** [comment]
@tihuan can you update this ticket pls? TY

**Comment by tihuan** [comment]
Oh @dsadgat I created a new epic for more granular tracking here:

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5206

PTAL thank you!

**Comment by dsadgat** [comment]
@tihuan In the future could you just update the epic that already exists? thank you!

**Comment by tihuan** [comment]
Hey @dsadgat ! Happy Friday! I created https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5206 because https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5080 is an issue and I couldn't convert it to an epic. Unless there's an epic I'm not aware of?

Thank you!

**Comment by dsadgat** [comment]
@tihuan yea zenhub might make that hard to do. I found a programmatic way, but realistically what I care about is 2 things -
 
1. Zenhub cleanliness - If you do end up creating a separate 'duplicate' ticket, close the original one and copy paste all the context missing into the new one. 
2. Tracking - make sure to have them linked and comment a reason for closing.

TY!
