### ISSUE TITLE
Explorer Link to UMAP Instance for Cell Guide V2

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5081]
**Feature: Linking to a Unified UMAP of a Particular Cell Type in the Explorer Visualization Tool**

**Objective**:
Enhance user experience and scientific exploration in the CellxGene Explorer by enabling direct linking to a unified UMAP (Uniform Manifold Approximation and Projection) visualization of specific cell types.

**Background:**
UMAP visualizations are pivotal in single-cell RNA sequencing data exploration, offering a 2D representation that helps researchers discern patterns, clusters, or variations in the data. A unified UMAP that amalgamates data from various studies into a single visualization can provide a comprehensive view and facilitate comparative analysis across different datasets.

- As a user, I want to preview a UMAP instance per cell type in Cell Guide and further investigate in Explorer. 

- As a user, the UMAP should display all the different datasets that pertain to the cell type (new capability in Explorer - Develop functionality to amalgamate UMAPs from different studies/datasets into a unified visualization).

- As a user, I want to be able to share the UMAP instance via a URL share link. Enable generation of URLs that direct users to specific UMAP visualizations of chosen cell types.

**Comment by niknak33** [comment]
When works starts on this - please ping Tiffany, as this work will require marketing resources

**Comment by dsadgat** [comment]
Blocked on census LTS containing embeddings - then we can proceed here.
