### ISSUE TITLE
CellGuide Survey Banner

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5101]
Add the survey and subscription banner to CellGuide pages

User Stories:

As a user, I want to sign up to the CxG newsletter or take a survey on the CellGuide Landing Page.
As a user, I want to sign up to the CxG newsletter or take a survey on any cell type I select.
As a user, I want to see the CellGuide Roadmap when I click on the banner.

Figma Link - https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1597-74351&mode=design&t=TJFrmcMINuu8f66V-0

**Comment by dsadgat** [comment]
@atarashansky closing as well as complete
