### ISSUE TITLE
[DP] /collections/index and /datasets/index are NOT gzipped

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5110]
Problem:
`/collections/index` and `/datasets/index` endpoints are NOT gzipped

Solution:
gzip them at Cloudfront or in BE?

see thread:
https://czi-sci.slack.com/archives/C023Q1APASK/p1687449592226519

![Screenshot 2023-06-27 at 12.21.24 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/73f1f4c5-8329-4154-a094-e7b2cb61bf42)

**Comment by metakuni** [comment]
Assigning to @Bento007 for implementation during next on-call rotation. 🙏
