### ISSUE TITLE
Update high level tissue mapping for GE

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5115]
@pablo-gar reviewed our current list of supported tissues in Gene Expression. We'd like to add the following tissues to the tissue mapping code:

**1. abdomen (UBERON:0000916)**, which rolls up : abdomen, abdominal wall, ascitic fluid, peritoneum, parietal peritoneum, and omentum
**2. mucosa (UBERON:0000344)**, which rolls up : mucosa, lamina propria

Secondly, please update the [documentation page](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_4__Available%20Tissues) to reflect the list of currently supported tissues, listed [here](https://docs.google.com/spreadsheets/d/1ZeRKlD-4ukPbVQakVqfq8-R_R3QRmVUoD4ryPRSCQqg/edit#gid=0).

cc @signechambers1 for any questions.

**Comment by signechambers1** [comment]
FYI @brianraymor we will be making an update to the high level tissue mapping for GE.

**Comment by atarashansky** [comment]
Mucosa is already a high-level tissue term. Only adding abdomen.
