### ISSUE TITLE
Determine why int32 is required for categorical variables in CXG

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5117]
We ran into a CXG conversion failure due to the issue that a dataset had an int64 type categorical variable, and we only allow categorical variables that are int32.

We need dev to determine why we require int32 type for categorical variables to determine if this is a schema requirement for 4.0.

[Relevant slack thread](https://czi-sci.slack.com/archives/C024HCSH9PT/p1687483718696969).

**Comment by brianraymor** [comment]
@signechambers1 I suggest we use the original single-cell-curation issue for the investigation and close this issue.
