### ISSUE TITLE
Duplicate asset artifacts being stored in DatasetArtifact table

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#5136]
See [**#single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1688595007007299). 

[Originally reported by Bruce with census error](https://github.com/chanzuckerberg/cellxgene-census/issues/606)

The `DatasetArtifact` table has a few uris that are duplicated:

`select count(uri), uri from "DatasetArtifact" group by uri having count(uri) > 1 order by count(uri) desc;`

The corresponding `DatasetVersion.artifacts` array contains all of the duplicates.

A simple fix for now would be de-duping when formulating the API response. Likely arising from insufficient cleanup of artifacts during a failed processing attempt, but not known for sure.

**Comment by atolopko-czi** [comment]
Might be worth considering adding relevant scheme constraints to database tables.

**Comment by danieljhegeman** [comment]
@atolopko-czi yeah that's a better fix, along with handling any such errors that would then come out of the processing pipeline. Quick fix for now.

**Comment by brianraymor** [comment]
> Might be worth considering adding relevant schema constraints to database tables.

@atolopko-czi @danieljhegeman 

Should there be a separate tracking issue after this band-aid is applied?

**Comment by danieljhegeman** [comment]
@brianraymor ☝️
