### ISSUE TITLE
Duplicate asset rows created in DatasetArtifact table

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#5147]
It would be nice for a cleaner, longterm fix to be applied that prevents the mucking up of the intended DatasetVersion-DatasetArtifact relationship.

Quick fix at API-filtering level will be applied in #5136

A reasonable solution likely exists in
1) enabling table-level constraints for uri uniqueness, and handling errors appropriately in the processing pipeline logic, or
2) checking before insertion

**Comment by danieljhegeman** [comment]
Since we're not using foreign keys in the `DatasetArtifact` table, I can't do a composite key of `type` + (nonexistent) `dataset_version_id`. So I'll just go with enforcing a unique constraint on `uri`.

**Comment by metakuni** [comment]
Temporarily removing priority label until this work is scheduled.
