### ISSUE TITLE
The timestamp format for `published_at` and `revised_at` must be documented

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#5202]
# Context

See [**#single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1689130614869979).

For the `published_at` (and `revised_at`) the swagger only documents "timestamp" such as:

> A timestamp of when the Collection was first published.

There are no format descriptions or examples in the swagger, which then forces the consumer to inspect a few `published_at `return values to figure out the format.

**Comment by metakuni** [comment]
Consider implementing this with #5203.
