### ISSUE TITLE
[Epic] Cell Guide SEO

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5206]
Source:

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/new?issueType=epic

Background:
SEO Recommendations from Central Team
Implement unique meta titles and descriptions using a template format. We recommend using a template to programmatically generate unique meta titles and descriptions for each URL. Target the following keywords, whose average number of searches per month in the US are:
Cell types - 2,400
Cell tissue - 1,000

User Stories:

As a user, I want to be able to find cell types or tissues via Google Search. AND As a user, I want to view a short description of the cell type I searched on Google.

This implies we implement meta tags that include the cell type/tissue name for each cell type (Wildcard SEO method)
This implies we implement a cell-type description in the meta description of cell type page for SEO and Google search results, ensuring they are concise, compelling, and accurately represent the content of our page, aiming for a length of around 150-160 characters to avoid truncation in search results.
Solution: We'll use GPT4 to generate ~150 chars of description
As a user, I want to search Google via synonyms and find CellGuide/Maps pages.

This implies we implement meta tags that include synonyms for each cell type (Wildcard SEO method)
As a user, I want to be able to view the sitemap index/html sitemap and find cell pages I am interested in

We can assign the central team to perform this task; we did this previously with our site in Q4 2022
Guidance from the SEO team on how to construct our meta titles and meta descriptions - https://docs.google.com/document/d/1R8ocUllm8EV3SPd5XBkY1rIC8sZgYVV1A93dsA7QujQ/edit#heading=h.kh7oxyc39a8c

**Comment by tihuan** [comment]
due date TBD, still waiting to add more tickets

**Comment by dsadgat** [comment]
@niknak33 can you validate this and close it with the prod release thursday/friday? Thanks!
