### ISSUE TITLE
Sitemap XML + HTML

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5209]
Add the new cell type and tissue URLs to the xml and html sitemaps

Ensure both website visitors and search engine crawlers can easily find these new URLs by incorporating them into the existing CELLxGENE [xml sitemap](https://cellxgene.cziscience.com/sitemap.xml) and the [html sitemap](https://cellxgene.cziscience.com/sitemap). 

gDoc: https://docs.google.com/document/d/1R8ocUllm8EV3SPd5XBkY1rIC8sZgYVV1A93dsA7QujQ/edit#bookmark=id.ixa8g0bz2p9l

**Comment by tihuan** [comment]
Waiting for Seth to implement for us!

**Comment by tihuan** [comment]
Seth plans to start implementation the week of 8/28

[thread](https://czi-sci.slack.com/archives/C04CP2N7XC5/p1691083126049809?thread_ts=1690491046.459759&cid=C04CP2N7XC5)
>Thanks for the gentle ping, 
@thuang
. We have this task on the KNI schedule.
We will be working on design for the HTML sitemap next week (adding 700 URLs with good UX in mind). I'll send a Figma for approval when it's ready.
We plan to start dev on both HTML and XML sitemaps the week of 8/28. Seth has some OOO this month but he'll probably reach out to you to coordinate details.

**Comment by dsadgat** [comment]
re this - https://czi-sci.slack.com/archives/C04CP2N7XC5/p1694564799966049 these changes will be live this thursday
