### ISSUE TITLE
Add Experimental Description as Header for ChatGTP

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5253]
Based on feedback from Ambrose and in an effort to align more with feedback from stakeholders such as Brand/Comms, we should add a header at the top of all chatgtp descriptions that reads "Experimental Description". This should lower our risk profile when we launch from a product positioning and communications standpoint.

[Figma](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1573-69487&mode=dev)

![image.png](https://images.zenhubusercontent.com/6306898cc3fd3cfeeb1b7727/f8a8f705-dda7-46e1-bb7f-5d4d812d62a2)

**Comment by dsadgat** [comment]
@atarashansky closing as complete
