### ISSUE TITLE
CI/CD GHA Updates

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5267]
GHA and Terraform Infrastructure work required to enable CI/CD per this [plan](https://docs.google.com/document/d/1UyJS8wxkLvtACUM6mVUBUotwqEiX2iVOd_RGyzUN9NI/edit#bookmark=id.41icelecev3a). Goal is to have main deployed to staging env, with all tests run there, and then provide single-command invocation of a prod deploy, replacing all of the manual [deployment steps](https://docs.google.com/document/d/1G2NTjXTJJeHyhqvnyzYmcO0Um24Ph0dCLUyMIWZvLfg/edit#heading=h.s3hd6u84yvyd) that engineers currently follow.  (Note that dev environment will be maintained, but only used for Terraform testing, and not part of the CI/CD pipeline.)

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5267?planning-poker) with Zenhub @atolopko-czi @Bento007 @danieljhegeman @ebezzi

**Comment by Bento007** [comment]
shouldn't we split into issue first?

**Comment by tihuan** [comment]
Yeah that would definitely help. I think it's more than 10 points total lol

Do you have time to take a stab at splitting the issues, or do you want me to give it a shot? I took a look earlier today and felt like I didn't have enough context to group/split the issues 😆

**Comment by Bento007** [comment]
I'll take a crack at it.

**Comment by tihuan** [comment]
Amazing thanks so much, Trent!

**Comment by atolopko-czi** [comment]
All issues now addressed or moved to follow-up epics. Closing
