### ISSUE TITLE
RDev prod data mirroring

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5274]
Goal:
Allow engineers to initialize an RDev stack with selected production data, as needed for a particular dev/testing effort.

Provide a script that can mirror any combination of the following data types:
- [ ] Portal database (RDS db) sync
- [ ] S3 Portal datasets: .h5ad, .rds. Specify by list of datasets and or collection identifiers.
- [ ] S3 Explorer datasets: CXGs.  Specify by list of datasets and or collection identifiers.
- [ ] S3 WMG snapshot(s)

**Comment by Bento007** [comment]
closing in favor of #5437
