### ISSUE TITLE
Newsletter banner should not cover up Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5277]
Ensure users can scroll to the bottom of gene expression without the dot plot being covered by the banner

![Screenshot 2023-07-19 at 8.36.05 AM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/9b2b29fb-6af2-45aa-80ea-7e0b7a601dfe)

**Comment by niknak33** [comment]
Closed - won't do.
