### ISSUE TITLE
Add Gene drop down is unresponsive

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5278]
The Add Gene drop down is unresponsive. 

Steps to reproduce:
1. Prod
2. Click into add genes
3. Scroll to click on additional genes, nothing happens
Desired behavior
Drop down immediately shows gene as selected

See below video:
https://images.zenhubusercontent.com/228681195/1641f4cc-edb9-4171-af8f-baf77ac67e2f/screen_recording_2023_07_19_at_8_44_45_am.mov

NOTES:
1. ~Use SDS Dropdown `buttons` prop: [demo](https://chanzuckerberg.github.io/sci-components/?path=/story/dropdowns-dropdown--default&args=buttons:!true)~: Actually we're still using SDS `MenuSelect`, so we need to implement the buttons ourselves. But doesn't seem too bad! [Code](https://github.com/chanzuckerberg/sci-components/blob/d872f0fc998e22c079e3042b6ad72aee36cdfe1d/packages/components/src/core/Dropdown/index.tsx#L152)

**Comment by tihuan** [comment]
It'd take a lot longer to fix the heatmap freezing issue, since it involves performance profiling, finding top bottlenecks, and derive potential solutions from there

**Comment by atarashansky** [comment]
Update the dropdown to not render heatmap until dropdown is closed. If the lag is fixed, then we confirm that the heatmap rendering is causing the dropdown to lag.

**Comment by atarashansky** [comment]
@signechambers1 @hthomas-czi Need some design/product work to figure out a good solution assuming that the Apply/Cancel pattern is required

**Comment by atarashansky** [comment]
@tihuan Please link to SDS ticket here

**Comment by tihuan** [comment]
I asked SDS if they could add Cancel/Apply buttons for us in the ticket above 👍

**Comment by tihuan** [comment]
I asked SDS if they could add Cancel/Apply buttons for us in the ticket above 👍

**Comment by signechambers1** [comment]
Closing, no longer an issue.
