### ISSUE TITLE
bug(functional tests): Update tests functional tests for deleting a dataset

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#5284]
## Describe the bug

Functional tests fail when deleting published datasets. the commit https://github.com/chanzuckerberg/single-cell-data-portal/commit/d5783db7bb6e89e8f8fd7cf419075de1321181d8 was recently added and blocks the deletion of publish datasets. [Here](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/5593170965/jobs/10226622699#step:7:208) is a run on staging demonstrating the failing functional test.

## To Reproduce

1. run the functional test `test_revision_flow` against the staging environment 

## Expected behavior

- The 405 is the expected behavior when trying to delete a publish datasets. The tests should be updated to reflect this. 
- The datasets should also be cleaned up after the test runs. 
- Additional tests are required to test deleting an unpublished dataset

**Comment by danieljhegeman** [comment]
Temporarily moving back to 'In Progrsess' because I merged the solution without actually making the necessary point edits to the functional tests... will do a follow-up PR...
