### ISSUE TITLE
Validated Cell Type Descriptions

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5301]
This story captures the user stories for when cell type chatgtp descriptions are validated via our biocurator team.

User Stories:

As a user, I want to see validation info (icon and disclaimer) for the cell type description I am viewing.
As a user, I want to references that are attributed to the validated cell type description.
As a user, I want to see a link to Cell Ontology to view their cell type definition.
As a user, I want to see a logo of the Cell Ontology next to their link - https://user-images.githubusercontent.com/112839/107354015-9375bb00-6ac5-11eb-9394-7318df343ec2.png
As a user, I want to see only 1 type of description when a cell type description is validated.
As a user, I want do not want to see the chatgtp source for any validated cell types.
As a user, I want do not want to see the Header - Experimental Description for any validated cell types.

**UX Design**
[Figma Explorations](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1615%3A75091&mode=design&t=RYc6H0cOEZgH5ODQ-1)

Update - After we receive the first set of descriptions (around 120), we will move the descriptions spreadsheet to Github and train the biocurator on how to use Github for updating descriptions (allows us to see/track changes and easier to automate new descriptions from Github to CellGuide)

**Comment by hthomas-czi** [comment]
> As a user, I want to see a logo of the Cell Ontology next to their link

Do users really want that?

**Comment by niknak33** [comment]
It's a request from David on the CL side, I'm thinking it might be a small
favicon store logo

**Comment by hthomas-czi** [comment]
Sure. Just want to be clear about whether requirements are actually user needs.

I'm not sure that having a small logo next to the link will work though. Their logo doesn't work well at small sizes. 

We could consider having an "Acknowledgments" section that has a list of contributors with their logos. That would be a good incentive for attracting partners.

<img width="1440" alt="CL Logo" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/72052788/a33b21b9-182f-4ead-b911-699a8c9bccdd">

<img width="1440" alt="Acknowledgments" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/72052788/9f1ffa4d-e67b-430c-95ac-a20572c4f524">

**Comment by niknak33** [comment]
Thanks, Harley - that works, an acknowledgments section would be great.
Probably a secondary ticket?

**Comment by atarashansky** [comment]
Update 8/31: 90 descriptions ready so far. Time to get them onto CellGuide.
