### ISSUE TITLE
WMG Performance Improvements

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5307]
We have consistently heard feedback that WMG feels very slow and clunky, even from Biohub leader Joe Derisi. 

We have a lot of room for improvement in the performance of WMG. This epic contains all the ongoing and completed work to address performance issues in WMG.

An important outcome (and perhaps prerequisite) for this work is to have clearly defined baseline performance measures to be able to assess improvements when implementing these tickets. See #5134 for the load testing story.

**Comment by tihuan** [comment]
do we have baseline performance data collected already, so we can measure the perf improvement from implementing these tickets?

Thank you!

**Comment by atarashansky** [comment]
I will add the load testing ticket to this epic. Thanks for highlighting this.
