### ISSUE TITLE
bug(cellguide): clicking a cell type label when ontology tree is in full screen does not reset full screen

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5325]
Take a look at this video for an example of how it looks:

https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/d9b1c614-9128-49f3-921a-dbe6b9d5f73a

@niknak33 Can you assign a priority level for fixing? If not P0, then it will be fixed by next deployment.

**Comment by niknak33** [comment]
Done @atarashansky added as P1
