### ISSUE TITLE
[WMGv2] Share Link Tissue Id vs. Tissue Name? Breaking change or bug?

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5358]
Context:
1. V2 share link uses tissue name in params, however, currently WMGv2 expects tissue in share link param to be IDs

E.g., 

Doesn't work: https://localhost:3000/gene-expression?compare=disease&sexes=PATO%3A0000383&tissues=blood%2Clung&genes=DPM1%2CTNMD%2CTSPAN6&ver=2

Does work:
https://localhost:3000/gene-expression?compare=disease&sexes=PATO%3A0000383&tissues=UBERON%3A0000178%2CUBERON%3A0002048&genes=DPM1%2CTNMD%2CTSPAN6&ver=2

Figure out:
1. Is share link tissue param now expects ID or still name
2. If it now expects ID, we need to bump the share link version to v3 and keep v2 link backward compatible

**Comment by tihuan** [comment]
CC: @signechambers1 @dsadgat this one needs Signe's input 

Thank you!

**Comment by signechambers1** [comment]
@tihuan im confused, the share link functionality works properly for me on prod right now. are you saying old share links will not work? (ie share 
links that were generated pre-v2)?

**Comment by tihuan** [comment]
Sorry for the confusion! 

Currently we have two types of v2 link:

1. Old v2 link has tissue names in the share link
2. New v2 link has tissue ids in the share link

Right now old v2 links don't work, since the latest WMG expects tissue ids instead

If this share link breaking change is expected (tissue names to tissue ids), we should bump the new v2 link to v3, and in the code support v2 links, so the old v2 links continue to work

However, if this change was unintentional, we'll just fix this bug lol

**Comment by signechambers1** [comment]
Thanks @tihuan! I'm not sure if this was intentional but is it possible this change was made due to the new tissue filter? checking with @seve although he is OOO. 

Either way I'd like the v2 links to work and the code to support the new tissue filter, so whatever you think the best way of doing that would be is fine with me from the product perspective.

cc @niknak33 since I am OOO next week. Thank you!!

**Comment by tihuan** [comment]
Got it 👌 Thanks, Signe!

In that case, I think we can just modify the code to support tissue share link to expect either id or name and keep the version as v2. This way we'll continue to support both types of v2 share links!

I'll update the description on Monday!

One last thing is assigning priority, so I'll wait for @niknak33 to let us know on Monday

Enjoy your time off, Signe!!

**Comment by niknak33** [comment]
Assigned as P1 @tihuan @signechambers1

**Comment by tihuan** [comment]
Awesome thanks, @niknak33 !

**Comment by tihuan** [comment]
CC @dsadgat for a sprint later 🙏 Thank you!
