### ISSUE TITLE
Discovery work required by Data Viz to enable spatial visualizations based off visium and slide-seq datasets 

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5364]
### Product discovery proposed for Q4 (Sep - Nov)

In no particular order:

- User Research: Conduct interviews and surveys with data submitters and consumers to understand their needs, pain points, and expectations when it comes to visualizing Visium and Slide-seq data.
- Competitive Analysis: Review other tools or platforms that support Visium and Slide-seq data visualization to identify their strengths, weaknesses, and unique features. (Completed a high level review - [Spatial Competitive Analysis](https://www.figma.com/file/99wd6MIA2fbEJXdNzB0T1n/Spatial-Competitive-Analysis?type=whiteboard&node-id=0-1&t=eUDjimERjly52Vby-0)
- Technical Feasibility: Assess the technical requirements and feasibility of supporting visualization of these data types. Aligns with DP Discovery work points 1 and 2
- UI/Usability: How can CELLxGENE ensure a user-friendly experience for data submitters and consumers when they are working with these new data types? What UI/UX principles would need to be applied?
- Wireframe Development: Create initial wireframes of the new visualization features based on the early findings from user research and technical feasibility studies. **(Most likely begin in Q1 2024 - based on planning later this year)**

From early reading and in no particular order, Data Viz would need to prioritize and complete some form of discovery work on the possible features required for spatial visualizations:

1. Spatial Visualization Tools: Integration of spatial coordinates to display gene expression data overlaid on tissue images. Users should be able to zoom into regions of interest and select individual cells or cell clusters to view detailed gene expression profiles (demo from current user does highlight some of this already - https://github.com/chanzuckerberg/cellxgene/issues/2056#issuecomment-1667568140). Based on the comments from the thread, we could use some of the code from VIP to expand on our prototype).

2. Integrated Histological Data: Allow users to toggle between gene expression heatmaps and traditional histology or immunohistochemistry images.

3. Spatial Clustering: Algorithms designed specifically for spatial data that can identify clusters or regions of interest based on spatial gene expression patterns. **_This would require some comp bio resourcing_**

4. 3D Visualization: If 3D spatial transcriptomics data become more common, tools to visualize gene expression in a 3D context would be invaluable.

5. Spatial Differential Expression: Tools to identify genes that are differentially expressed in specific spatial regions or between different tissue types.

6.  Advanced Image Processing: Tools that help clean up and enhance tissue images, adjust for artifacts, or even integrate with other imaging modalities.

7. Integration with Non-spatial Data: Tools to integrate spatial data with traditional single-cell RNA sequencing data, enabling users to correlate spatial and non-spatial findings.

### [Visium Datasets Analysis](https://docs.google.com/spreadsheets/d/1z-H_9hhenqsvtopJQTNuuCjOXCqPeuL3851yjSZEoh0/edit#gid=0)

- Analysis shows some decent interest in spatial data, especially that around 25% of visitors who filter by assay are looking for spatial data.
- Regarding engagement with spatial datasets in Explorer, for some actions, it seems higher for spatial datasets, and some actions are lower for spatial datasets, so it's hard to know how sufficient users find Explorer for spatial data.
- Original [Zenhub Issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-analytics/176)

### [Spatial (Visium Only) Discovery Work Doc](https://docs.google.com/document/d/1mtTOmUslIV5pbHmoTnY3YzMlVEWRyodpO1aZ6zyWSGI/edit#heading=h.58l4i5w5kmu8)
- Contains Project timeline
- Introduction and context of spatial transcriptomics 
- Potential Metadata Fields
- Potential Features

### [Scientific Specs](https://docs.google.com/document/d/10aNbIWczWHa3h-xme1Ghge8dq4RJLq2tv34JK8_nNpk/edit#heading=h.9qec0r15m6xg)

**Comment by brianraymor** [comment]
Also see [Spatial Talking Points](https://docs.google.com/document/d/1bl5EHBnUG2qJZ4mRxHPKBdClOWj_7LMs3BrfGIAakPs/edit) related to the earlier prototype.
