### ISSUE TITLE
Mobile Experience Improvements for CellGuide

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5370]
Currently our CellGuide experience on any mobile platform is insufficient with areas of the feature not loading correctly and making it unusable. 

We plan to make the following changes:

- [x] #5590 General Fixes
- Remove `min-width` on Description
- Improve Zoom on mobile

- [x] #5591 Tables
- Update Canonical Marker Gene table responsive behavior – [Figma](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1756-222247&mode=dev)
- Update Computational Marker Gene table responsive behavior – [Figma](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1756-222248&mode=dev)
- Update Data Table responsive behavior – [Figma](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1756-222243&mode=dev)

- [x] #5592 Navigation
- Update In-Page Navigation – [Figma](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1742-101528&mode=dev)
- Update Site Navigation – [Figma](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1742-101528&mode=dev)

**UX Design**
[Figma – Overview](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1071-48272&mode=dev)

**Comment by dsadgat** [comment]
@niknak33 were these all completed?
