### ISSUE TITLE
bug(cellguide+wmg): opening marker genes for a cell type in cellguide in GE crashes if cell type isn't available in GE

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5398]
[Bug report by Garabet](https://czi-sci.slack.com/archives/C0247APK621/p1691149878892099).

Clicking "Open in Gene Expression" in CellGuide for a cell type that doesn't exist in WMG will load a failed instance of WMG.

Proposed solution is to update WMG to display cell types with no labels in the corpus but have descendants with labels in the corpus.

**Comment by atarashansky** [comment]
The above proposed solution was intractable to implement given limited bandwidth. It also worsened performance and made the gene expression plots more difficult to read.

As an alternative course of action, there are two stories that need to be addressed related to this bug:

1. The share URL feature in Gene Expression must (a) remove invalid filters when parsing the URL instead of crashing and (b) signify to the user that certain invalid filters were removed as they did not exist in the application (this applies to genes, tissues, and cell types)
2. The Open in Gene Expression feature in CellGuide must be grayed out with a tooltip if the corresponding cell type has `n_cells=0` (even if `n_cells_rollup>0`).

**Comment by seve** [comment]
I can take this on during the bug bash if needed

**Comment by signechambers1** [comment]
@seve the dot plot looks good when i tested this in rdev but is there a way to notify users we removed the cell type filter that was not applicable? A toast or something? FYI @karenliang0 (i tested with absorptive cell)

**Comment by karenliang0** [comment]
@signechambers1 @hthomas-czi Signe and I chatted and thought it would be the most clear and simple to disable the 'View in Gene Expression' button with a tooltip on hover that states that we do not have data on this cell type within gene expression. Let us know if there's any other ideas that might work better!

**Comment by hthomas-czi** [comment]
@karenliang0 That makes sense to me!
