### ISSUE TITLE
Fix WMG Datadog synthetic tests for v2

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5413]
The [Datadog synthetic tests are failing for WMG](https://app.datadoghq.com/synthetics/tests?query=wmg&from_ts=1691429016267&to_ts=1691432616267&live=true) API v1, but we're now at v2, so the tests should be updated so that they are valid again.

Interestingly, dev and prod tests are failing, while staging still reports OK. Not sure if this is related to WMG data availability  in respective environments.

**Comment by prathapsridharan** [comment]
`staging` is point to `v2` but `prod` is pointing to `v1` - that explains `prod` failure.

**Comment by atolopko-czi** [comment]
Ah, indeed! Note the dev is also failing, but clearly for another reason. Will fix prod now.

**Comment by atolopko-czi** [comment]
Prod fix and recovered. 

Dev still failing, but looks like it's dev resource-limited and performance is dithering around the 6s SLO, causing intermittent failures. I don't think it's valid to have this test on dev, but for now I'm going to increase to 10s.

**Comment by atolopko-czi** [comment]
All green now.
