### ISSUE TITLE
Gene Expression consistency quick fixes

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5416]
- [ ] Tissues shouldn't be in bold - This is when you come to the GE landing page, you notice all the tissues are listed in bold. Only tissues that have their accordions in an open state should be bold. (Please consider picking up the padding fix between tissues if easy to do in #5837)
- [ ] For consistency, Cell Type tags from the Autocomplete should match the style of Filter Tags.

**Comment by tihuan** [comment]
@niknak33 please help adding a priority tag thank you!

**Comment by signechambers1** [comment]
@niknak33 added P1 since this is gene expression related. let me know if you disagree!

**Comment by niknak33** [comment]
Totally agree - P1. Thanks Signe.

**Comment by signechambers1** [comment]
@dsadgat @niknak33 updated this ticket so removing nik as the assignee
