### ISSUE TITLE
bug(Gene Expression - Cell type persists even after removing from search filter):

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5423]
## To Reproduce

1. Go to Gene Expression
2. Click on Search Cell Type
3. Scroll down to any cell type of your choice, select a cell type
4. After the cell type has been loaded, click x on the cell type below the search bar
5. Cell type icon is removed but the cell types still remain in the heatmap

## Expected behavior

If only 1 cell type is present, it should be removed across the heatmap, and original state should be restored.
If multiple cell types are present, the cell type you have chosen to remove, should be removed and the heatmap recalibrated with the other remaining cell types being present. 

## Environment - Production.

@karenliang0

**Comment by signechambers1** [comment]
this is now fixed.
