### ISSUE TITLE
RDev improvements for CI/CD

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5435]
The RDev (Remote Dev) environment must be made capable of fully supporting both ad hoc and automated testing on feature branches prior to being merged to main. This epic involves the necessary work.

**Comment by metakuni** [comment]
@Bento007 / @atolopko-czi : Please make sure to consult #team-happy on any rdev-related changes and push down any work that makes sense for them to do! 🙏
