### ISSUE TITLE
Data mirroring for RDev stacks [CI/CD]

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5437]
For both ad hoc test and automated E2E and functional tests, RDev envs will need to be initialized with prod-representative data. We already data mirroring scripts to move data from prod to dev and staging, which can be adapted to also mirror to RDev. Both engineers and automated testing workflows should be able to invoke this script.

Implementation notes:
* For ad hoc testing needs, should support user-selectable data types to be mirrored: Portal DB (RDS), H5ADs (S3), CXGs (S3), WMG snapshot (S3) and possibly by collections/datasets (subsets of corpus).
* It may be sufficient for E2E tests to only test on subsets of corpus data, so the user-selectable data types feature may also be useful for automated tests.
* Any S3-related code that is not currently capable of finding its data using S3 paths that include the "stack prefix" will need to be updated (WMG only?)
* It is worth considering having this script run as a Batch job (or some other hosted compute), rather than in the localhost process, but that is a stretch goal.

Goal:
Allow engineers to initialize an RDev stack with selected production data, as needed for a particular dev/testing effort.

Provide a script that can mirror any combination of the following data types:
- [X] Portal database (RDS db) sync
- [X] S3 Portal datasets: .h5ad, .rds. Specify by list of datasets and or collection identifiers.
- [X] S3 Explorer datasets: CXGs.  Specify by list of datasets and or collection identifiers.
- [X] S3 WMG snapshot(s)
- [X] S3 CellGuide data (to s3://cellguide-data-public-dev/env-rdev-cellguide/{stack-name}/)

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5437?planning-poker) with Zenhub @atolopko-czi @Bento007 @danieljhegeman @ebezzi

**Comment by Bento007** [comment]
duplicate https://github.com/chanzuckerberg/single-cell-data-portal/issues/5274?

**Comment by tihuan** [comment]
Hmm yeah feels like duplicate to me, maybe worth combining the descriptions since they're slightly different? Will defer to BE engs to decide what to do 😆

**Comment by atolopko-czi** [comment]
We pointed the dup issue at 3 pts, so I pointed this issue the same.

**Comment by danieljhegeman** [comment]
> S3 Portal datasets: .h5ad, .rds. Specify by list of datasets and or collection identifiers.
 S3 Explorer datasets: CXGs. Specify by list of datasets and or collection identifiers.

I'm not going to handle Portal datasets and Explorer assets separately. Instead, the user can pass dataset ids or collection ids; all related assets will be copied over.

**Comment by atolopko-czi** [comment]
@danieljhegeman There's another requirement for this script: CellGuide S3 data. See https://docs.google.com/document/d/1nynGcBS_TA55qlQo9WjINGkcMnE_xIBz7-inmop2bqo/edit?disco=AAAA4WHy6wE

**Comment by atolopko-czi** [comment]
@danieljhegeman Ready to be closed?

**Comment by danieljhegeman** [comment]
> @danieljhegeman There's another requirement for this script: CellGuide S3 data. See https://docs.google.com/document/d/1nynGcBS_TA55qlQo9WjINGkcMnE_xIBz7-inmop2bqo/edit?disco=AAAA4WHy6wE

I'll add this!

**Comment by atolopko-czi** [comment]
Done!
