### ISSUE TITLE
Support high-resource testing on RDev [CI/CD]

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5439]
For RDev to more fully support all modes of testing (ad hoc, automated, QA testing), it must be provide compute resources that are capable of working with prod-equivalent data and with performance that is closer to our deployment environments. Currently, API calls and selected data can causes OOM errors or cause systems to operate too slowly, making RDev insufficient for some testing scenarios.

* ECS backend instances need to be up-scaled appropriately. 
* Batch instances need to be up-scaled appropriately

Implementation notes:
* Determine the appropriate levels of scaling needed
* Assess cost of upscaling to the desired levels. **Once we have estimates, let's get approval from Arathi before increasing AWS costs.**
* As needed, investigate the use of ECS soft and hard memory limits to prevent over-provisioning of RDev compute resources.
* As needed, work with the Happy Team to understand if RDev auto-scaling is possible.
* Document how RDev cost can be monitored so cost impact can be effectively managed by engineering team.

Tasks:
1. Once all the tests are in place, run the tests in current RDEV config to see if tests pass
2. If not, figure out how much to scale up given estimated parallel runs (includes ad-hocs and CI/CD provisioned stacks), and assess costs and get Arathi's approval budget

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5439?planning-poker) with Zenhub @atolopko-czi @Bento007 @danieljhegeman @ebezzi

**Comment by tihuan** [comment]
team agreed with 3

**Comment by Bento007** [comment]
Here is the current configuration for rdev
https://github.com/chanzuckerberg/single-cell-infra/blob/d5783679da0611e020eef727e1fa7730a737c783/terraform/envs/dev/dp-rdev/main.tf#L71-L73

It uses a larger machine than dev 
https://github.com/chanzuckerberg/single-cell-infra/blob/d5783679da0611e020eef727e1fa7730a737c783/terraform/envs/dev/dp-dev/main.tf#L53-L55

**Comment by Bento007** [comment]
Increasing the size of the ECS cluster will not significantly increase the cost of development. We could double it and it would only be an additional $200 a month. We are also configured to use 1-2 servers for happy and are only using 1. We have plenty of room to grow. There is no need to change the current configuration for running the data portal server.

**Comment by Bento007** [comment]
No changes need to be made at the moment to support more rdev environments.
