### ISSUE TITLE
Increase parallelization of E2E tests

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5440]
## Motivation

To reduce the (wall clock) time it takes to run our E2E tests. Context: For CI/CD, we intend to run (most) E2E tests prior to every push to `main` branch (running on a RDev stack). Since this will be more frequent than running only on deploy GHA jobs, the test test run time needs to be improved.

## Definition of Done

E2E tests run on RDev instances in < 10min (wall clock time).

## Tasks

- [ ] Finish https://github.com/chanzuckerberg/single-cell-data-portal/pull/4926
- [ ] Implement similarly on Explorer repo.

**Comment by tihuan** [comment]
Closing this in favor of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5449, so everything is in CI/CD epic
