### ISSUE TITLE
Improve localhost testing processes for CI/CD

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5441]
Goal is to improve the ease of debugging code and running tests locally by adding necessary documentation. There is a good deal of tribal knowledge surrounding how tests are run locally for various components of the CxG Platform. BE engineers often find it difficult to setup environment to run FE tests or FE servers, and vice-versa. There are also caveats with certain components or tests being run on Intel vs M1/2 Mac laptops.

Address issues, including, but not limited to:

* {DP,Viz} engineer can run {FE,BE} tests locally Individual test
* BE engineers can run FE local servers to manually test backend changes
* All engineers can run the full test suite locally.
* All tests and servers can be run on either Intel and M1/2 Macs

Implementation notes:
* This should be taken on by both a FE and BE engineer, which should each act as a guinea pigs (aka tester) for the other's documentation.
* All testing processes should be organized and compiled into a single location, in the repo
* Any scripts, Makefile commands, etc, that are found confusing should be improved (time-permitting, documentation is more important)
* While improving documentation, we may identify pain points that should result in follow-up issues being created for test environment improvements or running localhost server. This may involve addressing, e.g. Docker container resource requirements (memory usage), test fixtures, etc.

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5441?planning-poker) with Zenhub @Bento007 @danieljhegeman @ebezzi @atolopko-czi

**Comment by atolopko-czi** [comment]
Folded the issues from this epic into https://github.com/chanzuckerberg/single-cell-data-portal/issues/5245. Closing this now empty epic.
