### ISSUE TITLE
Shard tests further to keep tests under 10 mins

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5450]

**Comment by Bento007** [comment]
duplicate of #5453?

**Comment by tihuan** [comment]
Oh sorry, this one is for Data Portal and #5453 is for Explorer! 

I propose Explorer sharding test as optional work, since its e2e test infra is quite outdated, it'd take quite a bit of effort to get it done

**Comment by tihuan** [comment]
This will be completed as part of #5449
