### ISSUE TITLE
Shard tests and merge report

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5453]

**Comment by Bento007** [comment]
You can look at how it is done in the backend as an example 

## shard
https://github.com/chanzuckerberg/single-cell-data-portal/blob/ed223a802a708fcf1ac6801428545473a5f6c4c5/.github/workflows/push-tests.yml#L152-L164

## merge
https://github.com/chanzuckerberg/single-cell-data-portal/blob/ed223a802a708fcf1ac6801428545473a5f6c4c5/.github/workflows/push-tests.yml#L543-L578

**Comment by tihuan** [comment]
Ooh nice! Thanks for sharing the config, Trent 🎉 !!

**Comment by tihuan** [comment]
Removing 3 points to avoid polluting the final epic points at the root epic

**Comment by atolopko-czi** [comment]
I think we decided the explorer e2e tests did _not_ need to be sharded at this time (they run fast enough). OK to close? Note that this issue is in a _closed_ epic.

**Comment by tihuan** [comment]
Yeah closing SGTM! Thanks, Andrew!
