### ISSUE TITLE
RDev "testing" stack init (data seeding), test run, and destroy

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5455]
#5574 will provision an RDev stack, as needed, when PR push occurs
#5603 and #5604 will provide necessary scripts to add seeding data for E2E tests

The GHA "push" workflow will need to:
- [x] Invoke the seeding data scripts (and should re-seed, since the seeding scripts may have changed on latest commit)
- [x] Invoke the E2E tests in `rdev-update-for-pr.yml`
- [x] Remove the "local" E2E tests from `push-tests.yml` (this will only need to run unit tests for pre-PR pushes to feature branch)
- [x] Fix failing tests as needed, by a) adding seeding data that is required or b) moving the tests to post-deploy run mode only; e.g. tests where 1) Explorer hits Portal API, 2) Portal UI links navigate Explorer.  The set of RDev-incompatible tests should become apparent during test run attempts while working on this issue.

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5455?planning-poker) with Zenhub @atolopko-czi @Bento007 @danieljhegeman @ebezzi

**Comment by Bento007** [comment]
Is the rdev, and the mirroring updated with every push to the branch?

**Comment by tihuan** [comment]
good question 🤔 Sounds excessive if it's done on every push. @ebezzi any suggestions? Thanks!

**Comment by ebezzi** [comment]
Two issues:
1. The mirroring needs to happen for the database only (mirroring S3 data will take ages) and needs to point to non-prod assets (dev likely?). Consider mirror the dev/staging database instead, otherwise the state will be inconsistent
2. This won't work if the branch has schema changes - the mirroring will fail.

IMHO, consider working with pre-seeded data. This data could live in the repo and can be modified in the branch if there are schema changes.

**Comment by tihuan** [comment]
Ooh pre-seeded data sounds like a great approach 💡 ! What do others think?

**Comment by Bento007** [comment]
preseed for sure.

**Comment by metakuni** [comment]
Add dependency on #5574

**Comment by danieljhegeman** [comment]
@tihuan I am a bit confused as to why this is labeled as "blocking" [5437](Data mirroring for RDev stacks [CI/CD])

**Comment by tihuan** [comment]
I think @Bento007 set it as a blocker  19 days ago!

**Comment by atolopko-czi** [comment]
> @tihuan I am a bit confused as to why this is labeled as "blocking" 5437

Should have been "blocked by"; now fixed.  Though, since we agreed to use data seeding instead of mirroring, this may not even be a blocker. It's an implementation decision as to which strategy to take, though seeding was the consensus.

**Comment by atolopko-czi** [comment]
@danieljhegeman Note that I added a task, `Perform a happy update on the RDev stack`. As this involves building and uploading Docker images for the RDev update, do you think this will be a performance concern? If so, we may need a strategy whereby the E2E and Functional tests are only run under certain conditions. E.g. do not run them if PR is a draft, and  assume that a PR that is "ready for review" will not experience many pushes; we could rely on engs to put PRs back into "draft" mode if post-CR follow-up dev work is necessary.

**Comment by Bento007** [comment]
We could also only gate update on if the unit-tests and local e2e tests pass.

**Comment by atolopko-czi** [comment]
Also, this issue should replace the "local" E2E run tests, invoked via the npm `e2e-pr` script, with the`e2e-rdev` script. The latter is the more faithful test.  (@seve @tihuan please confirm!)

**Comment by tihuan** [comment]
this is in main now!
