### ISSUE TITLE
Automate Moving Zenhub issues to next status after deploy

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#5481]
This would be one of the final step after a staging or prod deploy occurs:
- For staging, move issues included in the staging deploy to "Ready for Prod".
- For prod, move issue marked as "Ready for Prod" to "Closed"

Implementation notes:
* The Zenhub API can be used for this https://help.zenhub.com/support/solutions/articles/43000010351-api-endpoints-and-use-cases
* This staging-deployed issue(s) will need to be handled in the `trigger-release-candidate-build-and-deploy.yml` GHA, where the automation logic "finds" the issue via the merged PR.
* The prod-deployed issues(s) should be able to (more simply) find the "Ready for Prod" issues via the Zenhub API.

Follow-up task(s):
- [ ] Remove "Ready for Staging" Zenhub pipeline (it is no longer relevant)
- [ ] Update deployment checklist in on-call log.

**Comment by Bento007** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5481?planning-poker) with Zenhub @ebezzi @tihuan

**Comment by Bento007** [comment]
Deployment consists of a successful explorer and portal deployment. How would we know if both succeed to know when to trigger moving Zenhub issues.

**Comment by metakuni** [comment]
@Bento007 , I'd love to have autoclosing of issues on successful prod deployments 😄, but is this more like a nice-to-have wrt MVP? Could we add a priority label to this issue? Maybe `P2` to be addressed after MVP? 🙏

**Comment by atolopko-czi** [comment]
Moving to P1, since this is an important part of CI/CD automation. (CI/CD MVP issues are at P0)

**Comment by metakuni** [comment]
Time-box initial assessment of Zenhub API to 1 day

**Comment by danieljhegeman** [comment]
Detail: should not progress the status of a ticket unless _all_ PRs that have that issue attached have been merged; many times we have a ticket that is attached to multiple PRs.

**Comment by Bento007** [comment]
python example: https://community.zenhub.com/t/zenhubs-new-public-api/832/4

## Zenhub GraphQL Explorer
https://developers.zenhub.com/explorer/index.html

### Get info about the zenhub workspace:
```graphql
query {
  viewer {
    id
    searchWorkspaces(query: "single-cell") {
      nodes {
        id
        name
        repositoriesConnection {
          nodes {
            id
            name
          }
        }
        pipelinesConnection{
          nodes{
            id
            name
          }
        }
      }
    }
  }
}
```


### Get info about issues in a pipeline for the single-cell-data-portal repo:
```graphql
query {
searchIssuesByPipeline(
  	# "Ready for Prod" in "single-cell" workspace 
    pipelineId: "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI5NzY2ODc",
    filters: {
      # "single-cell-data-portal" repo
      repositoryIds: "Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvNTM5NzQwOTg"
    }
) {
  nodes {
      id
      number
      title
    	blockingIssues{
        nodes{
          id
          number
          title
        	pullRequest
          state
        }
      }
    	connectedPrs{
          nodes{
          id
          number
          title
          pullRequest
          state
        }
      }
    
  }
}
}
```

**Comment by danieljhegeman** [comment]
@Bento007 just out of curiosity, does the Github API offer the same functionality (to move issues in pipeline) as the Zenhub API?
