### ISSUE TITLE
Re-instate merge queues

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#5483]
This is expected to become more useful as commit rate to main increases. Possibly wait to see how much conflict we have on parallel PRs/commits to main.

**Comment by Bento007** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5483?planning-poker) with Zenhub @ebezzi @tihuan

**Comment by atolopko-czi** [comment]
The issue is now more fully covered by https://github.com/chanzuckerberg/single-cell-data-portal/issues/6047. Closing.
