### ISSUE TITLE
Create Github Release for each deployment to prod

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#5487]
After a successful deployment to **prod**, generate a new release in github with a change log (e.g. Github "Releases"). The change long will consist of the commits since last prod deployment. This should be an automated process.

Update deployment checklist in on-call log.

**Comment by Bento007** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5487?planning-poker) with Zenhub @ebezzi @tihuan

**Comment by tihuan** [comment]
P1 sounds good to me!
