### ISSUE TITLE
Cell type filter selections do not clear

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5491]
When a user selects a cell type (B cell for example), a blue tag shows up under the cell type search bar. However when you click the x to clear the filter, the tag disappears but the results do not refresh and B cell continues to be shown.

Desired behavior is that the application shows all cell types when a cell type filter is removed. Or, if there are multiple cell types, the cell type the user clears should no longer show in the application.

**Comment by seve** [comment]
cell types clear if we reduce the cell type filter to something > 0.

This is stinky https://github.com/chanzuckerberg/single-cell-data-portal/pull/5357/files#r1279803002

cc: @tihuan

**Comment by seve** [comment]
cell types clear if we reduce the cell type filter to something > 0.

This is stinky https://github.com/chanzuckerberg/single-cell-data-portal/pull/5357/files#r1279803002

cc: @tihuan

**Comment by tihuan** [comment]
Ooh yeah my bad! I thought that condition was just for resetting the state when organism changes 🤦 

Adding these back seems to work, but probably further testing is needed and adding tests too

```ts
if (filteredCellTypes.length === 0) {
  setDisplayedCellTypes(initialDisplayedCellTypeIds);
  setExpandedTissues(new Set<string>());
  return;
}
```

Thank you!

**Comment by seve** [comment]
> Adding these back seems to work, but probably further testing is needed and adding tests too

Since this is main functionality and not an edge case, this functionality will be covered by testing described in #5447

**Comment by tihuan** [comment]
> > Adding these back seems to work, but probably further testing is needed and adding tests too
> 
> Since this is main functionality and not an edge case, this functionality will be covered by testing described in #5447

Sounds good! I added this as a task item in #5447 👍 !
