### ISSUE TITLE
***rdev*** - datafiles uploaded to submissions s3 bucket are not being processed

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#5496]
The s3-upload-to-submissions-bucket-dataset-processing pipeline is not functioning properly for rdev. Uploads to `s3://<rdev-dataset-submissions-bucket>/<stack>/<user>/<collection_id>/<dataset_id>` are not being picked up.

**Comment by danieljhegeman** [comment]
It appears this isn't working on dev either...

```
Unable to import module 'app': No module named 'tenacity'
```

**Comment by ebezzi** [comment]
@danieljhegeman I submitted a [fix](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5443) for this the other day. Where are you seeing the errors?

**Comment by Bento007** [comment]
It looks like requirements-submissions.txt is still missing tenacity which is the lambda that would be failing if s3 submissions are failing
https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/requirements-submissions.txt

**Comment by ebezzi** [comment]
> It looks like [requirements-submissions.txt](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/requirements-submissions.txt) is still missing tenacity which is the lambda that would be failing if s3 submissions are failing

Ahh, thanks for the catch. Let me add it now and tag you for a review.
