### ISSUE TITLE
Instantiate functional test for upload-to-s3 dataset submission

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#5514]
## Motivation

Moving to CI/CD requires excellent automated testing; at present, the local-file-upload-to-s3 method of dataset submission is not being automatically tested, and we recently introduced a [small bug that broke the dataset submission lambda](https://github.com/chanzuckerberg/single-cell-data-portal/issues/5496).

## The exact approach to completing this ticket has not been decided on

At the very least, we need to develop a functional test that will test the dataset submission pipeline starting with uploading a file to s3 and (perhaps) ending with the beginning of the dataset processing step function / its attempted invocation. Really this could be considered an e2e test.

- [ ] Needs to work on RDEV
- [ ] Needs to work on regular envs
- [ ] Will exercise the whole flow and check the artifact is created at the end
- [ ] DO NOT RUN ON PROD

Considerations: we could also use this as a test of the temporary credential-based local file upload curator flow as well; we'd use the super curator api key in our Auth0 secret to generate an access token via the Discover API and then call for temporary upload credentials via the s3 upload credentials endpoint (also Discover API).

**Comment by tihuan** [comment]
Team agreed with 3

**Comment by metakuni** [comment]
Removed P2 label since that priority assignment was wrt the CI/CD MVP work.

This will be queued as DP work.
