### ISSUE TITLE
CxG Front Page - Newsletter Sticky

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5526]
Currently, this is a bug - when a user closes the newsletter banner, the frontpage footer with the newsletter is removed and shows a large empty block. Please see image below:

Solution - is to have the newsletter banner be a sticky format so it's more visibly apparent for users and resolve the bug above. @hthomas-czi 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUlOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c01ffa2293fbcc23d64d341604384ec814c0aa94/image.png)

Update - We will use the same sticky banner that is present on other pages i.e. CellGuide and GE, remove the survey links from the banner and roadmap links.

**Comment by tihuan** [comment]
@hthomas-czi 
Hmm the visible gap seems to be part of the margin for the timeline section, so if we use the Gene Expression / Cell Guide banner, the gap will still be there. What is the ideal end state we want to have?  Is it just less margin bottom for the timeline?

20px margin bottom with banner:
<img width="1383" alt="Screenshot 2023-08-31 at 11 55 16 AM" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/6309723/3f552bb6-ea92-460f-8e7a-9fc60a9c6430">

20px margin bottom with banner:
<img width="865" alt="Screenshot 2023-08-31 at 11 57 22 AM" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/6309723/4a2a197c-9e3d-43e5-b1fc-95ec8a6b366f">

Current timeline section margin in orange:
<img width="1722" alt="Screenshot 2023-08-31 at 11 53 32 AM" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/6309723/9a0adef1-e8bf-49ec-84b2-d0db833cc352">

Current with banner:
<img width="1728" alt="Screenshot 2023-08-31 at 11 49 23 AM" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/6309723/58ef42c0-a86b-4f5d-bafe-6214d776182d">

Current without banner:
<img width="1728" alt="Screenshot 2023-08-31 at 11 49 30 AM" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/6309723/d519b368-56df-439d-9656-9aa767f01087">

**Comment by tihuan** [comment]
@niknak33 @hthomas-czi this should be in prod now thank you!

**Comment by tihuan** [comment]
Amazing! Thanks for checking already @niknak33 🙏
