### ISSUE TITLE
Update codecov to avoid false PR status report

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5529]
Problem:
This PR doesn't update Python code, yet the codecov failed

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUFTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58a82019bc0b5e8b9a2c4c8409a41422927165dd/Screenshot%202023-08-17%20at%207.17.11%20AM.png)

DoD:
PRs that don't touch Python code shouldn't fail codecov

**Comment by Bento007** [comment]
@ebezzi is this fixed by https://github.com/chanzuckerberg/single-cell-data-portal/pull/5544

**Comment by ebezzi** [comment]
> @ebezzi is this fixed by #5544

Yes, I'll close this ticket.

**Comment by tihuan** [comment]
Woohoo go @ebezzi !! ✨✨✨✨✨
