### ISSUE TITLE
[Gene Expression] Heatmap Tooltip CellType Shows Tissue Id instead of CellType Name

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5559]
Bug:
In prod - Heatmap Tooltip CellType Shows Tissue Id instead of CellType Name

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXdiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55b22751b03b0f4da4ce9ba0c5749287eaf013a3/Screenshot%202023-08-18%20at%209.33.04%20AM.png)

DoD:
1. Fix this bug
2. Add a test to catch this bug

**Comment by tihuan** [comment]
@niknak33 @signechambers1  please help add a priority tag thank you!

**Comment by niknak33** [comment]
I put it down as a P0, mainly because it is a data quality issue. There is no workaround to the cell type, as the data in the field corresponds to a tissue ID. @signechambers1 let me know if you feel different.

**Comment by tihuan** [comment]
Awesome thanks, Nik! @seve I know you have adding WMGv2 new tests this week, but are you able to send out a fix for this today 🙏 ? Thanks so much!

**Comment by seve** [comment]
Should the tooltip still say `Cell Type` for organisms? I'm going to fix the bug and push for merging this because of the priority, but we may want to open a seperate ticket to address.

**Comment by tihuan** [comment]
> Should the tooltip still say `Cell Type` for organisms? I'm going to fix the bug and push for merging this because of the priority, but we may want to open a seperate ticket to address.
> 
> CC: @hthomas-czi @niknak33

@seve Just to double check: you meant the tooltip should say "Tissue" instead of "Cell Type" for tissue rows, right?
