### ISSUE TITLE
Docker based testing and debugging technique

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5571]

**Comment by Bento007** [comment]
here is the slack conversation it was discussed https://czi-sci.slack.com/archives/C023Q1APASK/p1683754124880179

**Comment by atolopko-czi** [comment]
@Bento007 Noting that we have this CI/CD guide section related to [Portal Docker-based testing](https://docs.google.com/document/d/1YRzbhq7E7OtkZ3zIDHnuQCLcj837gRDKrlJw13wKQ3w/edit#heading=h.lctdad3j0zsg), is there anything more you feel we could document? Or does this address issue the sufficiently?

**Comment by atolopko-czi** [comment]
@Bento007 See comment above. I think we have addressed this, but re-open if you think otherwise.
