### ISSUE TITLE
Centralize a doc as starting point to find all testing related topics

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5573]

**Comment by tihuan** [comment]
@atolopko-czi I'll remove myself from this ticket for now, since it's not p0 anymore!

**Comment by atolopko-czi** [comment]
> @atolopko-czi I'll remove myself from this ticket for now, since it's not p0 anymore!

Sounds good. I'm actually working on this as part of #5602.

**Comment by tihuan** [comment]
perfect! Thanks so much for taking this on 🙏

**Comment by atolopko-czi** [comment]
https://docs.google.com/document/d/1YRzbhq7E7OtkZ3zIDHnuQCLcj837gRDKrlJw13wKQ3w/edit#heading=h.ngsi3ohh56ov
