### ISSUE TITLE
RDEV testing stack provisioning strategy

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5574]
Figure out a smart way to provision resources if needed:

Objectives:
1. @atolopko-czi whether we can create a new stack on demand (based on if an rdev has already been created based on rdev naming convention to find its corresponding stack) per PR and delete the rdev once PR/branch is deleted

**Comment by metakuni** [comment]
Can this be considered a partial dup of #5439 ?

**Comment by atolopko-czi** [comment]
> Can this be considered a partial dup of https://github.com/chanzuckerberg/single-cell-data-portal/issues/5439 ?

These are separate issues. #5439 is about creating/reusing a stack for running tests on rdev, while this issue #5574 is about scaling up the infra that runs _all_ of the stacks.

**Comment by Bento007** [comment]
Over the past week I've been working on fixing issues in the rdev lifecycle that cause it to fail setup or teardown. 

What we want to do is spin up an rdev for e2e and functional tests then tear down afterwards. We will take the branch name and replace any characters that cannot be in a domain such at "./" and create an rdev with that name. Once the PR is merged, the environment will be torn down.

**Comment by atolopko-czi** [comment]
@Bento007 ok to close this issue now?
