### ISSUE TITLE
Updating Citation Documentation Page of CxG - Preprint Requirement

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5594]
Based on requirements from the Program Team - A preprint will be going live - likely mid-September. 

The lift should be extremely light and will just be adding switching out the current citation to be for the new preprint, or to make a Discover & Annotate section and have the corresponding preprints under each section. 

Nik to add more details based on actual citation from Bailey

**Comment by dsadgat** [comment]
@niknak33 could you update this ticket please?

**Comment by niknak33** [comment]
I went and pinged Bailey on the latest news for the pre-print, will update here with confirmed dates.

**Comment by signechambers1** [comment]
Preprint link expected 10/27

**Comment by signechambers1** [comment]
Please also update the citation link in GE. When a user clicks on the Citation button, hte preprint link should show up in the notification and be copied to the user's clipboard. Thank you!

**Comment by signechambers1** [comment]
[Citation link](https://www.biorxiv.org/content/10.1101/2023.10.30.563174v1)
