### ISSUE TITLE
Ensure WMG E2E & functional tests run in RDev

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5603]
- Add test fixtures, as needed, to seed data required for these tests. These can be dynamically-generated or statical fixtures, as appropriate. Ideally, test fixtures should be made available for usable in RDev stacks for ad hoc testing, via scripts/commands that can seed the stack.
- Add configuration, as needed, for FE to identify the BE endpoint for a specifc RDev stack

This issue does *not* cover invocation of these scripts in GHA, which will be handled by #5455.

NOTES:
1. We need the WMG fixture to be accurate enough for e2e share link tests to pass!

**Comment by atolopko-czi** [comment]
@tihuan Please review estimate. We pointed higher since we're not sure what will be needed to create valid WMG test data for E2E tests.

**Comment by tihuan** [comment]
@atarashansky I think you're uniquely positioned to work on this ticket 😆 Please help with pointing and implementing this. Thanks so much!

**Comment by atarashansky** [comment]
I'd estimate this with as 0.5 points.

**Comment by atolopko-czi** [comment]
> I'd estimate this as 0.5 points. All we'd need to do is clone the latest snapshot from `dev` into the the rdev bucket.

Nit; We will no longer rely on dev, so the snapshot cloning would have to be from `staging`.

Do we need to be concerned about the time snapshot copying will add to the E2E tests? Wondering if it's worth having a shared rdev-specific location for test fixtures that get updated at less frequent intervals than every push to a PR branch; e.g. a nightly test fixture setup job.

**Comment by dsadgat** [comment]
@atarashansky please pick this up when you get back, thank you! (assuming it is just a half days worth effort)

**Comment by tihuan** [comment]
I'm back! Please let me know how I can help, @atarashansky ! But I assume the WMG e2e tests hopefully should just work after adding rdev test fixtures 😆 🤞
