### ISSUE TITLE
Gene Expression: Clarify why marker genes are unavailable

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5608]
We've gotten user feedback that our users are confused or would like more information on why marker genes are unavailable for certain cell types. This ticket covers the work to clarify why marker genes are unavailable by:

- [ ] Adding a cell type info icon to every cell type
- [ ] Updating the marker genes modal to explain why marker genes are not available

[Figma](https://www.figma.com/file/nUbwlxcSPAGoRGWyYaIkyv/Q2-2023-Gene-Expression-Improvements?type=design&node-id=318-77808&mode=design&t=2Ck6l5LvsqeNhEZp-0)

cc @karenliang0 and @signechambers1 for any questions

Notes for eng estimate:
- Would have to alter `YAxisChart/index.tsx` to show the three different types of empty state instead of not showing the icon
- Looks like some tests would have to be altered, such as in `geneUtils`
- Alter or add new e2e test that would capture the empty state

**Comment by joyceyan** [comment]
@signechambers1 In addition to not showing the info icon when the marker gene count is under 25, we also explicitly exclude all tissues that are within the "blood" tissue. Do you know why this was the case? The null state message here should probably be different.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3luQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df15ce9616313d6958b6d980a22afa188b302856/image.png)

**Comment by signechambers1** [comment]
@joyceyan yes, we do not compute marker genes for blood becuase the cell types are too closely related to generate high value markers, which is not unique to us. @karenliang0 has some language in the figma file but I'm thinking we might want to add more clarity there. Suggested language (feedback welcome):

"Cell types within Blood are closely related, so we are unable to generate high value marker genes at this time."

**Comment by karenliang0** [comment]
Updated the designs with the language you suggested @signechambers1!
