### ISSUE TITLE
Update [Explorer] e2e tests config to work with rdev

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5623]
## DoD
E2E tests will run against rdev in PRs and on demand locally

## Tasks
- [ ] Accept rdev link through env var or something
- [ ] Fix anything else that comes up

**Comment by tihuan** [comment]
Hopefully the learnings from doing the DP one will make Explorer one easier!

**Comment by atolopko-czi** [comment]
Closing this, since CI/CD support for Explorer is not prioritized currently. If we decide to support CI/CD for Explorer there is likely additional work that needs to be considered and that can be done as an epic.
