### ISSUE TITLE
Delete label h5ads if download-validate fails

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#5648]
During a submission if the datasets fails after download-validate, retaining the labeled and raw h5ad for debugging. These files would be cleaned up when the datasets is deleted, or resubmitted.

**Comment by danieljhegeman** [comment]
@Bento007 this appears to have been wallowing in Code Review for a while. I'm assuming that was a mistake. Moved to Ready for Staging.
