### ISSUE TITLE
bug(wmg): download svg spacing is abnormally large compared to png

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5656]
SVG:
<img width="577" alt="image" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/fb5bda50-ebcd-4c30-9a1e-456e1e69ca7a">

PNG:
<img width="640" alt="image" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/c22cf9d9-7f06-4aed-9a45-157b9e058e2a">

Likely introduced with WMGv2.

**Comment by niknak33** [comment]
I listed this as a P1, as there is would be extremely annoying to fix post downloading and might deter further use of the product.

**Comment by dsadgat** [comment]
Will assign this to Ronen

**Comment by kaloster** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmFPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6f1c5317ad5b76ce911fe2a6a078d97c0c6c919f/Screenshot%202023-09-12%20at%209.57.50%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmVPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--044c9069ce3401a113c89ff6c8016a2e4e13610f/Screenshot%202023-09-12%20at%209.57.39%20AM.png)

**Comment by kaloster** [comment]
fixed spacing, added bold styling and some indentation for expanded cell types
