### ISSUE TITLE
RDS and CXG conversions should be independent operations

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#5660]
# Context

See [**single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1693261728537429).

Recently, RDS conversions have been especially _brittle_. Currently, a RDS conversion failure will result in the cancellation of a **pending** CXG conversion although there should be no correlation between potential RDS and CXG failures. As a result, curators and submitters are unable to view the Explorer visualization until the RDS conversion is addressed. This is currently blocking a submitter review.

I do not remember if there was a rationale for this design such as _fast failing_. 

CC: @Bento007 since this issue is based on a personal slack conversation. @atolopko-czi

**Comment by atolopko-czi** [comment]
> I do not remember if there was a rationale for this design such as fast failing.

I'm not aware of any technical reason why fast failing behavior is required here. But we may have to consider the processing status logic to ensure that _partial_ failures (e.g. just RDS) can be retried appropriately.

We actually want to eventually have the [CXG generation be moved into a separate pipeline](https://docs.google.com/document/d/1oeNXVrNn8PyBjkY_v4kiNobmE97bEMx-nGBq-Vm-X7s/edit#bookmark=id.oo23v4xea6z5), so it can be owned by the Viz team.  It would only be loosely coupled to the dataset submission pipeline via an event notification when a "labeled" h5ad is ready, and not an RDS. This might be worth considering when we take on this issue.

**Comment by brianraymor** [comment]
@nayib-jose-gloria - added to schema 4 epic for visibility. Please consider.

**Comment by Bento007** [comment]
https://dev.to/aws-builders/parallel-task-error-handling-in-step-functions-4f1c

**Comment by danieljhegeman** [comment]
>As a result, curators and submitters are unable to view the Explorer visualization until the RDS conversion is addressed.

Noting that, currently, it also blocks _publishing_.

@brianraymor I am unclear on whether you would want to start allowing publishing in cases where seurat conversion failed.

**Comment by metakuni** [comment]
On a side note, I think I recall from a long time ago that despite being defined as parallel steps in the step function that the Seurat and CXG conversions actually run sequentially.

@ebezzi , is this still the case?

**Comment by danieljhegeman** [comment]
If the reported `TaskStarted` times are to be believed in the step function logs, then the cxg and seurat steps/tasks are indeed being launched in parallel rather than in sequence.

**Comment by ebezzi** [comment]
They indeed run in parallel. My recommendation here is to change the Seurat job to return a success code instead of a failure, so that won't block the step function execution. The failure will still be handled by the processing status management we have in the database.

**Comment by brianraymor** [comment]
> @brianraymor Can you please advise on whether we should start allowing publishing in cases where seurat conversion failed?

It depends. If the seurat conversion failed due to the known R sparse matrix limitation, then publication is allowed. Otherwise, publication is not allowed.

**Comment by danieljhegeman** [comment]
I will test by forcing seurat failure _for a specific test Collection in prod only_ once we deploy to prod on Thursday 11/2
