### ISSUE TITLE
Seed Published Collections for E2E Test Account

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5666]
Problem:
Recently we created a new Auth0 account for BE functional tests to use, in order to avoid Auth0 rate limiting. However, the [data seeding script](https://github.com/chanzuckerberg/single-cell-data-portal/blob/cd5566c56cfcfa960de01930a95d0112dc7b0add/scripts/smoke_tests/setup.py#L37) is now creating published test collections that belong to the functional test accounts instead of the E2E test account, which results in E2E tests not being able to run certain tests, like revisions

Solution:
1. Use smoke test account to create seeded published collections for smoke test account
2. Please notify Timmy when this is done, so I can re-enable collection revision tests!

**Comment by metakuni** [comment]
Scheduling for Oct 2 on-call rotation

**Comment by danieljhegeman** [comment]
>Use smoke test account to create seeded published collections for smoke test account

Originally only made private collections. Adding published Collections...

**Comment by tihuan** [comment]
@danieljhegeman feels like this ticket is done now? Thank you!
