### ISSUE TITLE
Change "All Tissues" to "Tissue Agnostic" in the global tissue filter dropdown

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#5671]

**Comment by prathapsridharan** [comment]
## NOTE:
This is only a change to the name shown in the dropdown. "Tissue Agnostic" should not be sent as the name to the cell ontology view component. When a user picks "Tissue Agnostic" in the dropdown, "All Tissue" should be the string sent to the cell ontology view component

**Comment by joyceyan** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/5707
