### ISSUE TITLE
Private Collections are tombstoned when `delete_published=true` and user is cxg_admin

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#5683]
## Motivation

[Sample private Collection](https://api.cellxgene.staging.single-cell.czi.technology/dp/v1/collections/88383e47-bf0a-4a4e-ba43-acd87dbb8d5d) that was (likely) successfully tombstoned by a cxg_admin with query param `delete_published=true`.

Only published Collections should be capable of being tombstoned.

## Definition of Done

If a cxg_admin user passes the `delete_published=true` query param to remove a Collection, but the Collection is private, then the Collection should simply be deleted rather than tombstoned.

**Comment by metakuni** [comment]
Assigning to @danieljhegeman for his next on-call rotation starting Oct 2. 🙏
