### ISSUE TITLE
Portal API is yielding 403 for a nonexistent Collection

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#5684]
https://api.cellxgene.dev.single-cell.czi.technology/dp/v1/collections/94d7a586-5839-4335-82b6-4352d78f089e

The Portal API appears to be yielding 403 instead of 404 for nonexistent Collection uuids. This should be fixed.

It should be confirmed that this is not happening for Portal Dataset endpoints as well.

**Comment by danieljhegeman** [comment]
Actually, it's not totally clear to me that we need to change 403->404 in this case. What really matters is that tombstoned Collections, [and _only_ tombstoned Collections](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5683), return 410.

**Comment by metakuni** [comment]
Assigning to @danieljhegeman for on-call rotation starting Oct 2. 🙏

**Comment by metakuni** [comment]
@danieljhegeman in light of your last comment, could you either rewrite the title and description or close this issue? 🙏

**Comment by danieljhegeman** [comment]
Closing in favor of #5683
