### ISSUE TITLE
Revision is viewable after publish

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#5694]
#### What I Did
1. Created a revision
2. Published revision
3. Viewed published revision (from copied URL, that is, using the collection version ID)

#### What Happened
1. Published revision was displayed
2. The "This is a private revision of a published collection" banner is not displayed
3. The "Start Revision" button is displayed

#### What I Expected
I would not have expected to be able to access a published revision.

---
See [this revision in dev](https://cellxgene.dev.single-cell.czi.technology/collections/88f94d6d-5a05-4da3-a562-7f4e654d9aa7): it has been published ([here is the corresponding published collection](https://cellxgene.dev.single-cell.czi.technology/collections/05c936eb-7dbe-4cef-a2f7-2cd9f466decf)) and I would not expect to be able to access the revision anymore.

**Comment by brianraymor** [comment]
I don't understand this bug @MillenniumFalconMechanic...

**Comment by MillenniumFalconMechanic** [comment]
Working as expected (see [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1693937866238669)).
