### ISSUE TITLE
GE genes are not visually removed when you scroll genes

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/single-cell-data-portal#5703]
How to repro:

Go to cell guide, type neuron, click the 'open in gene expression link' (wait for load) and scroll to the right.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFowIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa48f9ccdfe738c421d21c495311e1f3086bda47/Screenshot%202023-09-06%20at%204.47.05%20PM.png)

**Comment by signechambers1** [comment]
Closing, this is now fixed.
