### ISSUE TITLE
[Discovery] Data Platform API(s) must be rationalized

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#5712]
# Context

The Data Platform API(s) include the legacy Data Portal API and the Discover API which address the following use cases:

| **API**         |  **Access** | **Serves** |
|-----------------|:---------:|------------|
| Discover  | Protected | Only **authorized** curators creating and revising private collections |
| Discover  |   Public  |    curators, internal _experiences_ such as the gene expression and cell census builders, and external computational consumers   |
| Data Portal |  Private  | Curation and Discover UX   |
||||

Problems:

A curator can use the Curation UX ( based on the Data Portal API) or the Discover API for their curation workflow. For the mid-term, we plan on supporting both approaches.  This complicated development of new curation features because interactions between the API(s)  and the UX needed to be tested. For example, the curator uses the API to create a collection and upload a dataset and then switches to the UX to make further updates prior to publication. 

As the schema and data platform evolve, we must constantly assess whether to _backport_ new features to the legacy Data Portal API such as dataset versions or `primary_cell_count`.

# Objective

To minimize the maintenance and testing of two _almost but entirely unlike_ API(s), a technical assessment is required to understand opportunities to align the API(s). @atolopko-czi shared some thoughts:

> If there are entirely unused methods in the DP API, we certainly should prune them. For functionally-equivalent, but duplicate methods between DP and Discover APIs, I would have us consider keeping the _logical_ DP endpoints, and have them be proxies to the equivalent Discover API backend code. This reduces the maintenance burden (less code), but maintains the explicit dependency between the DP FE and the BE, so it's clear what specific endpoints are needed by the FE.

but we're open to other approaches.

# Design

@MillenniumFalconMechanic shared:

[Data Platform APIs Review](https://docs.google.com/document/d/1t3XN1XdmZmXXtxyEMR-LamtnEVab18WdnFJnIEG2wVQ/edit#heading=h.tdhqwdrg25ez).

@atolopko-czi noted:

I referenced this issue and the new doc from our related, standing Tech Proposal, [Data Portal & Curation APIs Improvements](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.8zw7lxm55zxv)

# Food for Thought

[Embracing the Differences : Inside the Netflix API Redesign](https://netflixtechblog.com/embracing-the-differences-inside-the-netflix-api-redesign-15fd8b3dc49d)

**Comment by brianraymor** [comment]
@MillenniumFalconMechanic and @atolopko-czi - I'm going to move your information to the top-level summary comment for at-a-glance comprehension and then delete this comment thread.

**Comment by metakuni** [comment]
See also #3810

**Comment by metakuni** [comment]
Also consider #4841

**Comment by metakuni** [comment]
Closing this discovery issue since we have:
* agreement on the approach
* estimates for implementation
(see https://docs.google.com/document/d/1t3XN1XdmZmXXtxyEMR-LamtnEVab18WdnFJnIEG2wVQ/edit#heading=h.3ti8jlk73zbc)
