### ISSUE TITLE
Marker genes cannot be added to the dot plot unless the marker gene panel is closed

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5719]
From Karen during usability study: 

He selected podocyte as a cell type and tried to add all the marker genes to the dot plot via marker gene panel and none of the dots would load on the dot plot.
The dots on the dot plot will load but only if you close the marker gene panel

[Slack thread](https://czi-sci.slack.com/archives/C0247APK621/p1694191617560819)

**Comment by tihuan** [comment]
1. If no genes, bulk add marker genes will render heatmap as expected
2. If there are existing genes, bulk add marker genes won't trigger a render
3. Open/close marker gene panel will force re-render the heatmap
