### ISSUE TITLE
Group by functionality should only show options with data when cell type filter is being used

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5720]
Steps to reproduce:

1. Prod
2. Select tissue = kidney
3. Cell type = podocyte
4. Group by = publication
Rows show up empty with misaligned dots

Desired result: only publications with data are shown, dots are aligned. 

Please ensure this is fixed for ALL group by options.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1dCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3fa6eaa26ba1870366050288b045b1cc07faff52/image%20%281%29.png)

**Comment by atarashansky** [comment]
This is the same bug as #5719. Will only close if this test case passes.
