### ISSUE TITLE
bug(wmg): cell type search bar includes all UBERON tissue terms

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5747]
To reproduce:
 - Go here: https://cellxgene.cziscience.com/gene-expression
 - Search UBERON: in the cell type search bar.
 - See all the UBERON: terms (e.g. UBERON:0002048 is lung).

**Comment by signechambers1** [comment]
Looks good on rdev! Thanks seve!
