### ISSUE TITLE
Analytics (new): Citation button in Gene Expression

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5757]
### Overview

**Tool**: Gene Expression

- Feature: Citation button

**Description**: We are adding a new citation button to Gene Expression to make it easier for users to cite our tool.
**Expectations**: I expect ~5% of engaged users to use the citation. This feature is mostly to help promote citation of our tool, so low usage might be acceptable but if we see <1% using it we may want to follow up with UXR.

### New events to add

`WMG_CITATION_CLICKED`
- to fire when a user clicks the citation button

Checklist

- [ ] Add events to the custom goals section of both the staging and prod Plausible spaces
- [ ] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: `<tag PM for the tool/feature>`
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by kaloster** [comment]
@signechambers1 - missing information on "information that should be stored in the payload" - once I have that I can complete this ticket as well and the citation feature should be dev-complete

**Comment by signechambers1** [comment]
@ainfeld would you mind helping fill in the info that should be in the payload? Thanks!

**Comment by ainfeld** [comment]
Thanks @kaloster! Was at a conference all week so I'm just getting to this now. 

@signechambers1 would the citation just be a general gene expression citation? If so, do you think it's important to try and capture the current state of the heatmap when the user clicked the citation button? I would actually lean towards not, because if it's just a general gene expression citation a user may click that at any time even with a blank heatmap if they used it and then only when they were ready to submit a publication came back to get the citation. What do you think though?

**Comment by signechambers1** [comment]
@ainfeld yes this would be the general gene citation. I agree, we don't need to capture the state of the heatmap when the user clicks the citation button. The analytics for this button are more to capture use of the button, we have other features and analytics tracking which heatmaps are useful to users (download, share). Thank you!

**Comment by ainfeld** [comment]
Thanks @signechambers1!! 

@kaloster I've updated the ticket with the event name. No need to track any additional information in the payload. Thanks!!
