### ISSUE TITLE
Generating shared URL and opening it up in a separate tab/window results in a page crash

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell-data-portal#5775]
For example, I generated this URL: https://cellxgene.cziscience.com/gene-expression?compare=publication&sexes=PATO%3A0000384[…]1L1%2CWNT16&ver=2&cellTypes=B+cell%2CBergmann+glial+cell

And when I opened the link in a new tab, the new tab crashed.

**Comment by seve** [comment]
The app is failing to find the filtered cell type

**Comment by seve** [comment]
Cell type was a red herring, looks like the genes are being stripped, and a query is attempted to be made leading to a crash. (genes are required on a query)

**Comment by seve** [comment]
zenhub or slack broke this URL, there's an encoded `[...]` in the middle of it

**Comment by joyceyan** [comment]
Okay yeah I think this isn't a real issue - if you click the link directly in slack it seems fine, it's just when you copy and paste the shortened version with `[...]` in it it doesn't work

**Comment by seve** [comment]
there might still be a bug in this, we shouldn't crash on malformed share links. We should just ignore the link

**Comment by seve** [comment]
P2 though?
