### ISSUE TITLE
[QUESTION] Downloading raw datasets

### ISSUE THREAD

**Issue by reetm09** [chanzuckerberg/single-cell-data-portal#5786]
Is there a way I can download the raw datasets (FastQ files) based on certain filters (either through collections or datasets), as well as the metadata associated with it? Additionally what are all the options for us to download the metadata? Are AnnData & Seurat the only options for accessing metadata? Or can it be a text file etc.?

**Comment by brianraymor** [comment]
> Is there a way I can download the raw datasets (FastQ files) based on certain filters (either through collections or datasets), as well as the metadata associated with it? 

CELLxGENE Discover does not accept or store **raw** datasets. Submitters may use the `Raw Data` link type in Collections to reference raw data.  

> Additionally what are all the options for us to download the metadata? Are AnnData & Seurat the only options for accessing metadata? Or can it be a text file etc.?

AnnData and Seurat are the only formats available for downloads.

CELLxGENE required metadata is defined in the [schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.1.0/schema.md).

**Comment by maximilianh** [comment]
Does this relate to specific data sets? Or any dataset?

**Comment by brianraymor** [comment]
_"this"_ is ambiguous. Can you clarify?

**Comment by maximilianh** [comment]
The user probably is referring to a particular dataset. “This” means “the
dataset that you’re referring to"

**Comment by jahilton** [comment]
@reetm09 Could you help us understand your use case a little more?
For example, once you filter down to the Collections/Datasets of interest, would it be helpful to more readily get the `Raw Data` links associated with each? Or are those easy enough to gather, it's just the challenge of downloading FASTQs from multiple resources/records and associating those files with metadata in CELLxGENE?

**Comment by reetm09** [comment]
Hi everyone,

Thanks so much for your quick response!

@jahilton Yes, a little bit of both! It would be easier if after I filter Collections/Datasets of interest, instead of only having AnnData/Seurat as the options, it would be useful if there was a `raw data` option as well.  Also after filtering, the dashboard has metadata such as tissue, organism, cells etc. it would be very helpful if there was a way I could easily download that information into an excel spreadsheet or something like that so I can associate each raw data link to it's metadata information. Right now, I have to manually copy over the information.

I think downloading FASTQs from multiple resources is also a challenge so I was wondering if there was a standard repository those are mostly stored on (i.e GEO accession number). If there is no raw data link, at least displaying that information on the dashboard directly would be super helpful so I can pull a list of multiple datasets.

Let me know if that helps or if I should clarify my use case more!

**Comment by jahilton** [comment]
Very helpful @reetm09 , thank you!

As Brian noted, CELLxGENE is not a repository for raw sequence data so a direct download option won't be feasible. However, we are interested in understanding how we can more directly connect users to the raw sequence data in other repositories. Your use case will help us as we think about opportunities to improve there.

As for the fastq repositories - GEO/SRA seems to be the most common that researchers submit single cell raw sequence data to, but you'll also find fastqs in ArrayExpress, ENA, EGA, dbGaP, NeMO, DUOS, HCA Portal...

**Comment by reetm09** [comment]
Hi @jahilton,

Awesome, thanks so much! Do you also have advice or resources by any chance of how to download raw data from these different portals?

**Comment by jahilton** [comment]
We've only recently started to look into how to do more high-throughput (less manual) fastq downloads. This is as far as we've gotten...

For GEO/SRA, I think the [SRA Toolkit](https://github.com/ncbi/sra-tools/wiki) will be the best bet. If it's helpful, we just put together a quick notebook to extract sample and run metadata from GEO, including fastq S3 URIS - [query_GEO](https://github.com/Lattice-Data/lattice-tools/blob/main/scripts/query_GEO.ipynb)

For ArrayExpress, we've found their API & FTP site to be very user-friendly (haven't tried Aspera yet) - https://www.ebi.ac.uk/biostudies/arrayexpress/help#programmatic
