### ISSUE TITLE
Open in Gene Expression button in CellGuide doesn't appear to work

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell-data-portal#5815]
Steps to reproduce:
1. Navigate to any cell type
2. Click on "Open in Gene Expression"
3. Application crashes

A few cell types I was able to reproduce this on:
- https://cellxgene.cziscience.com/cellguide/CL_0001061
- https://cellxgene.cziscience.com/cellguide/CL_0000896
- https://cellxgene.cziscience.com/cellguide/CL_4030026

Tagging this as both CellGuide and Gene Expression cause I'm not sure if the fix will involve changing the generated URL on CellGuide or changing how we parse URL params in Gene Expression.

**Comment by atarashansky** [comment]
This is a gene expression bug with the share link feature.

**Comment by signechambers1** [comment]
Tested on 12/18. I think this is no longer an issue, please reopen if still an issue.
