### ISSUE TITLE
Gene Expression spacing, padding and alignment issues for GE

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5837]
Spacing, padding and alignment issues for GE

**P1**
- [ ] Space between Tissue label and disclosure arrow for tissue accordion should be `gap: spacing.s`
- [ ] “View Options” dropdown labels should all be `fontBodyXXS[500]`
- [ ] Cell count values should all be right aligned to the cell count label.
- [ ] Padding between gene trash icon and add genes search bar should be `gap: spacing.m`.
- [ ] Divider line on the main interface of GE should be on the right side of cell count. (Currently is on the left side of cell count). Should be `gap: spacing.m` on either side of divider line.
- [ ] Padding between Tissues should be `spacing.xxs`  instead of `8px`

cc @signechambers1 @karenliang0 for questions

Eng estimate note: budgeting 3 days of the 10/31 - 11/13 sprint for this, and 2 days of the 11/14 - 11/27 sprint

**Comment by joyceyan** [comment]
@signechambers1 @karenliang0 I'll be the engineer picking up this ticket! I had a few clarifying questions:

1. The Tissue filter appears to have the same spacing as the other filters, so just for my own understanding, is there a reason we would want to update only the tissue filter?
2. What/where is the gene trash icon?

**Comment by joyceyan** [comment]
Another question: moving the divider line to the right of the cell count column without doing anything else results in this. Would it make more sense to make the divider shorter, or shift the gene search bar? If it's the latter, what should the spacing be between the divider and the search bar?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXFoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccfbb5f9ef281dd92623ca93ac7c59a4fbc35592/image.png)

**Comment by karenliang0** [comment]
@joyceyan @signechambers1 

hey joyce!! thanks for picking up these items for us.

1. Sorry this was a bit unclear! We were referring to the tissue accordions on the dot plot. We wanted to increase the spacing between the accordion arrow and the tissue label to `gap: spacing.m`. Let me know if that clears things up for you!

2. When a user adds a gene to the dot plot and hovers over that gene label, they get a trash icon. Added an image below for clarity as to what I'm referring to! 
![image](https://github.com/chanzuckerberg/single-cell-data-portal/assets/87047537/b7d2de45-707e-4347-88fe-d8f20ad0ad2a)

For the third and fourth item you mentioned, I'll send a screenshot later today outlining what it should look like!

**Comment by joyceyan** [comment]
Thanks @karenliang0! It would also be good to see what the desired padding looks like between tissues. It looks like the padding between the tissue accordions on the dot plot is more than 8px right now, so I'm probably misunderstanding what this item is referring to.

**Comment by karenliang0** [comment]
I redlined all the relevant items in this ticket. Let me know if you need additional clarity or something is missing! Thanks @joyceyan!!!

![image](https://github.com/chanzuckerberg/single-cell-data-portal/assets/87047537/bda34806-f8b3-43cd-bae8-35108dcb9e05)

**Comment by joyceyan** [comment]
@karenliang0  Thank you! To clarify, it seems we also want to shift the alignment of the cell type search bar and the gene type search bar. Should that be encapsulated in this ticket or is there a separate ticket that would describe that work?

**Comment by karenliang0** [comment]
@joyceyan good catch! I would say we can put that in a separate ticket, so no need to worry about that now :)
