### ISSUE TITLE
Implement Metadata-Update Batch Job

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#5881]
Full [context](https://docs.google.com/document/d/1wXP4BVD6Js-Lj9T8nwzkBA931lutUbTLu56pNpSatwc/edit) proposal

add as branching step in process file in single-cell-data-portal, same as the other steps for single dataset processing (i.e. downloadvalidate)

Inputs: dataset_version_id, metadata_key, new_value

1. Fetch current DatasetVersion from DB using dataset_version_id
2. Fetch h5ad + rds artifact s3 URIs from DB for current DatasetVersion
3. Create new DatasetVersion for canonical Dataset that is a duplicate of the current DatasetVersion
4. Set DatasetVersion processing status to PENDING and upload status to UPLOADING
5. For this CollectionVersion, replace its mapping to the current DatasetVersion with this new DatasetVersion.
6. Update metadata_key to new_value in 'uns' metadata dict for h5ads and rds files (load in 'backed' mode if possible for minimal memory usage)
           - TODO: Look into Python libraries to easily handle calls to R to handle rds update (from Emanuele: look into rpy2)
7. Store updated artifacts in S3 under s3://corpora-data-<env>/<new_dataset_version_id>/ (same pattern for regular dataset artifact processing)
8. Create new entries in DatasetArtifact DB table for updated artifacts
9. In the new DatasetVersion DB object, update:
         - dataset_metadata JSON field to also map metadata_key to new_value
         - artifacts field to list of UUIDs mapping to the new entries in DatasetArtifact DB
10. status back to processing status SUCCESS and upload status to UPLOADED

**Comment by nayib-jose-gloria** [comment]
Note: Reach out to R expert on TileDB team (Dirk)

**Comment by Bento007** [comment]
For ease of review I would break it into 4 PRs:
- h5ad updates.
- cxg updates.
- seurat updates.
- batch job.
