### ISSUE TITLE
GE Understanding underlying data

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5904]
In our most recent user research sessions for Gene Expression we found that the “Source data” was easily missed, people relied on dataset filter which is uninterpretable. This finding is corroborated by analytics and previous user feedback.

Analytics tell us that the dataset filter is used by about ~11% of all users (daily avg) and source data is clicked on by ~7% of all users (daily avg). We've received feedback through our survey that people do not understand where the underlying data is from.

This work aims to inform our users of the underlying data and reduce confusion. We'd expect to see ~10% of users click on Source Data as a result (depending on underlying design).

**UX Design**
[Figma](https://www.figma.com/file/Mfo9nQ1m3jQzdPbwoEZvOP/Gene-Expression?type=design&node-id=7019-364503&mode=dev)

Changes:
- [x] Remove dataset filter
- [x] Move source data button and add badge
- [x] Update Source data panel to link to collections and show number of datasets
- [x] Add tool tip to Gene Expression color legend

cc @hthomas-czi for design, @ainfeld for analytics, @signechambers1 for product questions

**Comment by signechambers1** [comment]
@hthomas-czi we need to update the copy of the tool tip on Gene Expression to reflect the new normalization method. I suggest this copy for the tool tip:

"After filtering cells with low coverage (less than 500 genes expressed), gene counts are normalized independently for each cell using ln(TTPM+1). The algorithm is summarized in detail in our documentation <<link to documentation>>."

cc @sidneymbell would you mind reviewing this copy? Any suggestions are welcome.

**Comment by kaloster** [comment]
@signechambers1 - for "Update Source data panel to link to collections and show number of datasets" 
Could you please elaborate on how this would work? Would this be dynamic data that is loaded based on the filters applied or static?

What does the red bubble counter represents? total datasets powering GE or specific to the users displayed data?

**Comment by signechambers1** [comment]
@kaloster the source data panel would be (and is currently) dynamic, showing only the datasets based on the filters applied. This change would should the collection name and number of associated datasets instead of the datasets listed under the collection name.

The red bubble counter would reflect the number of datasets based on the filters applied as well, so it will decrease when the user selects a subset of the data.

fyi @hthomas-czi

**Comment by kaloster** [comment]
ok gotcha! thanks for clarifying @signechambers1

**Comment by kaloster** [comment]
@signechambers1 one more Q: 

Could you please also explain the meaning of the '1 of X' column on the Data Source list? [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77b7af4d03d19c19fa6f688c32b50e028635baf8/Screenshot%202023-11-13%20at%2011.31.38%E2%80%AFAM.png)

**Comment by signechambers1** [comment]
@kaloster yes, it should be X of Y where X is the number of datasets that support the current view and Y is the total number of datasets in that collection. does that make sense? fyi @hthomas-czi

**Comment by kaloster** [comment]
please note that for the X of Y functionality the data currently does not exist in GE and the `/filters` end point does not provide the total number of datasets - this will need to be extended to a separate ticket to either extend `/filters` or create an additional endpoint. @signechambers1

**Comment by signechambers1** [comment]
ah thanks @kaloster. A couple questions: What do you recommend in the mean time? Could we just show the number of datasets in the collection (so just X)? FYI @hthomas-czi

**Comment by kaloster** [comment]
1. Yes in the meantime we could just show the X value
2. I'd point it at 3/4 mostly to allow time to research, allow backend and frontend dev changes and extend/ fix any breaking tests
3. Done

@signechambers1

**Comment by kaloster** [comment]
as per Harley - also add a tool tip as outlined [here: ](https://www.figma.com/file/Mfo9nQ1m3jQzdPbwoEZvOP/Gene-Expression?type=design&node-id=7019%3A408665&mode=dev)

**Comment by kaloster** [comment]
Also adding a couple of e2e tests to this

**Comment by kaloster** [comment]
@signechambers1 - WRT X of Y - after further discussion with Timmy, Alec and Harley - it was decided that the value of Y is:

- Not available to the FE and that is intentional - the value of X represents the primary dataset
- The value of Y is not that critical and could potentially be more confusing to the users
- The value of X (total datasets available as datasource in GE) is accurately calculated and returned fromthe BE

Based on the above - the "of Y" portion has been omitted for now - please see [slack discussion](https://czi-sci.slack.com/archives/C0247APK621/p1699984318384739) for further context

cc: @hthomas-czi
