### ISSUE TITLE
GE Make load state more obvious

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5905]
In our most recent user research sessions for Gene Expression we found that the loading indicator was easily missed, people were not sure if the application was responding to their feedback or just broken.

This work ticket captures the work to improve the loading state to make it more obvious when results are loading.

cc @hthomas-czi for design, @ainfeld for analytics, @signechambers1 for product questions

**UX Design**
[Figma](https://www.figma.com/file/Mfo9nQ1m3jQzdPbwoEZvOP/Gene-Expression?type=design&node-id=7019-413187&mode=dev)
[Skeleton Loader Animation Example (MUI)](https://mui.com/material-ui/react-skeleton/)

**Comment by dsadgat** [comment]
Figure out what is feasible technical wise, and scope prior to taking on ticket! Thanks!
