### ISSUE TITLE
Fix missing get_tombstoned parameter in persistence_mock.get_collection_version_with_datasets 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#5916]
#### Need
The `get_tombstoned` parameter in `persistence_mock.get_collection_version_with_datasets` is not passed through to `self._update_version_with_canonical`. See [code](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/layers/persistence/persistence_mock.py#L270) and [suggested fix](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5824/files#diff-766d914dd42c86f642d416c3e803a78eab7c8c8a14ec64f2b5f31d1358f4be70R270).

CC @danieljhegeman.

**Comment by danieljhegeman** [comment]
This is a bug that should be fixed before any further development is done on DP service code! Thanks Mim!

**Comment by danieljhegeman** [comment]
@MillenniumFalconMechanic any chance this can be tackled this week?
