### ISSUE TITLE
Tissues should be expanded when share link (or Open in Gene Expression) is utilized

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5936]
Selected tissues should be autoexpanded when a user clicks a share link or clicks Open in Gene Expression from cell guide. We are also seeing intermittent loading errors.

From @dsadgat: Look at neuron in cell guide. Go to marker gene section, computational genes, click link to open in gene expression. See that neuron is not shown within the tissues (default collapsed it looks like). Sometimes, the loading state never goes away. Not quite sure whats happening, but the loading state issue is not always reproducible.

**Comment by tihuan** [comment]
This fix is in prod now!

https://cellxgene.cziscience.com/gene-expression?tissues=UBERON%3A0000916%2CUBERON%3A0001013%2CUBERON%3A0002369&genes=TSPAN6%2CTNMD&ver=2

**Comment by tihuan** [comment]
Actually this scenario is part of share link cellType filter fix that Seve has in [this PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5938)

**Comment by tihuan** [comment]
Actually somehow Seve's fix doesn't fix this one:

https://localhost:3000/gene-expression?genes=NRXN1&cellTypes=neuron&ver=2

Will look into it after Make-a-thon!

**Comment by tihuan** [comment]
@seve can you help add your discovery so far regarding this ticket please? IIRC at one point the bug was fixed in your bug fix PR above by adding cell types to the dispatch payload or something 🤔 Thank you!
