### ISSUE TITLE
E2E tests should only run if unit tests pass

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5939]
Context: 
In RDev, unit tests will run upon the "push" action, and E2E tests run on "pull request" actions, and these run in parallel. If the unit tests fail, the E2E tests still will be run even though it's probably not worth doing so.

Goal:
The E2E tests should only run if the unit tests have passed

This may require restructuring the workflows so that unit tests are _not_ run on push, but are instead run as part of the `rdev-update-for-pr` workflow, adding a dependency between the unit and e2e tests.

**Comment by danieljhegeman** [comment]
I'm going to expand the scope of this ticket a tad to move all tests out from under the rdev creation/update workflow; e2e test dependency on rdev update will be maintained via [workflow run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run:~:text=In%20this%20example,types%3A%0A%20%20%20%20%20%20%2D%20completed) syntax.

**Comment by danieljhegeman** [comment]
1. unit tests (depends on: none)
2. rdev creation/update (depends on: none)
3. e2e tests (depends on: 1, 2; PR must be 'ready for review')

**Comment by danieljhegeman** [comment]
Cannot use `workflow_run` trigger to launch rdev creation +  e2e test script because we want rdev creation to run even if the unit tests fail.

This requires nontrivial reorganization: merging the 'push tests' and 'rdev update' workflow files.

**Comment by atolopko-czi** [comment]
As we now have a number of issues related to our CI/CD GHA workflow, we are better off considering all of these issues' goals/requirements together to ensure we end up with a clean solution. To that end, we now have an [epic](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6169) that subsumes them all, including this issue.  This issue is now referenced by the epic to ensure it is considered during design. Closing this issue.
