### ISSUE TITLE
Prevent DDoS from FE

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5940]
Context
1. Recently we discovered that there's an infinite loop in FE that would send infinite API calls to DDoS BE

Solution:
1. FE now adds a network guard to detect excessive API calls within a 5 second sliding window and shut down API calls
2. Add a global assertion to catch DDoS in every e2e test

**Comment by dsadgat** [comment]
@tihuan can you move this to the appropriate swim lane pls? TY

**Comment by tihuan** [comment]
Done! Sorry was hoping this would get merged on Monday. Added to the current  sprint!

I'll ask Ronen to help get this reviewed and merged!
