### ISSUE TITLE
bug(wmg): filtered tissues spacing is too large from the top

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5946]
To reproduce:
 - Go here: https://cellxgene.cziscience.com/gene-expression?datasets=137ca42b-33b3-48fa-ae80-02a0747027cb&genes=MALAT1&ver=2
 - Observe the weird spacing
<img width="1259" alt="image" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/ae0562eb-cb4b-42ae-8dae-09628c7f221e">

Another example:
<img width="1256" alt="image" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/0a96584d-b2d0-4bf6-842d-c4ee7414ae44">

**Comment by signechambers1** [comment]
looks good on rdev!
