### ISSUE TITLE
Edit collection is broken

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#5950]
See [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1696960323125529).

**Comment by danieljhegeman** [comment]
Do we have a sense of what might be causing this?

**Comment by danieljhegeman** [comment]
The Collection Details modal is failing only on Collection edit, not on Collection creation.

**Comment by MillenniumFalconMechanic** [comment]
From @frano-m 's [comments in the related PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5957#issue-1937034677):

> Currently, editing a collection is unavailable due to a bug that causes the page to freeze or return an error: "Application error: a client-side exception has occurred (see the browser console for more information)".

> The bug was introduced with an upgrade of `czi-sds` package version; specifically the package upgrade introduced a defect in the consortia dropdown functionality in the [create / edit collection](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fe226f5f20ef7ff5690ddf47e3add9bae082a040/frontend/src/components/CreateCollectionModal/components/Content/index.tsx#L217) component.

> Between versions `15.4.2` and `18.1.0`, a modification was made where a hook's dependency array was updated to include the prop `onChange` (`v15.4.2`: [L112-114](https://github.com/chanzuckerberg/sci-components/blob/bf8c991055bf4715ded0ebee4d325ac0276650f6/packages/components/src/core/Dropdown/index.tsx#L112), `v18.10`: [L112-114](https://github.com/chanzuckerberg/sci-components/blob/%40czi-sds/components%4018.1.0/packages/components/src/core/Dropdown/index.tsx#L112)).

> Thanks to a recent `czi-sds` [commit](https://github.com/chanzuckerberg/sci-components/commit/8d9ffda2992a112f1e489dabcf10315f0561f167) by @tihuan 🎉 , this hook has been removed, and the update functionality now resides in the `setValueAndCallOnChange` function [here](https://github.com/chanzuckerberg/sci-components/blob/main/packages/components/src/core/Dropdown/index.tsx#L315). The purpose of this commit was to address infinite loop issues.

> Until the `czi-sds` library publishes this update, we can memoize the dropdown function `handleConsortiaChange` to prevent an infinite loop when editing a collection.

> See https://pr-5957-frontend.rdev.single-cell.czi.technology/collections.

**Comment by tihuan** [comment]
Thanks so much for providing the context, @MillenniumFalconMechanic ☺️ I believe SDS will release today!

CC: @masoudmanson
