### ISSUE TITLE
Upgrade SDS to resolve drop down issues

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#5959]
Follow on for [Edit collection is broken](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5950).

#### To Do
@MillenniumFalconMechanic and @frano-m - determine if [intermediate fix](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5957) is still required after upgrade.

**Comment by metakuni** [comment]
@MillenniumFalconMechanic , any updates on the To Do?

**Comment by MillenniumFalconMechanic** [comment]
Resolved in https://github.com/chanzuckerberg/single-cell-data-portal/pull/5957.
