### ISSUE TITLE
Removing cell type filter in mus musculus causes weird spacing

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5963]
Steps to reproduce:
1. Prod
2. Search for neuron in cell type filter
3. Switch organism to Mus Musculus
4. Clear cell type filter
5. Weird spacing shows up and does not reset on adding genes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0l1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15739f9f4c37a692e2bb2b8238060f065dbf7c9d/Screenshot%202023-10-12%20at%2010.24.00%20AM.png)

Desired result:
1. When user clears cell type, spacing goes back to normal.

**Comment by dsadgat** [comment]
@seve do you have a fix for this?

**Comment by seve** [comment]
Cell type filtering state will be reset upon changing of organism once #5938 is merged, can I close as not planned? @signechambers1

**Comment by signechambers1** [comment]
@seve yes! you can close. the reset you have in the rdev link looks good and fixes this issue
