### ISSUE TITLE
Cleanup rdev buckets during teardown

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#5967]
When an rdev is created, [data is seeded](https://github.com/chanzuckerberg/single-cell-data-portal/tree/main/backend/scripts) into the rdevs buckets to make setting up easier. After the rdev is no longer need all of the data associated with the rdev needs to be cleaned up. It should run as part of the existing `happy delete <stack-name>` [process](https://github.com/chanzuckerberg/single-cell-data-portal/blob/df7ed176d338ec6f1e0174eca78c558e08516d74/.happy/config.json#L82).

**Comment by atolopko-czi** [comment]
@Bento007 Isn't this a happy bug? I'll keep our issue to track the problem, but isn't something we should have to fix ourselves, correct?

**Comment by metakuni** [comment]
@Bento007 should we lean on happy for this?
