### ISSUE TITLE
chore(wmg): Update expression summary builder to use tiledbsoma solution when X_sparse_iter is deprecated

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5973]
[Context](https://czi-sci.slack.com/archives/C048BN7K6U8/p1697228924382769?thread_ts=1697228699.326509&cid=C048BN7K6U8)

**Comment by bkmartinjr** [comment]
@atarashansky - please fix this ASAP, as I'm about to remove the X_sparse_iter (it has been deprecated for several months).
