### ISSUE TITLE
FE bug preventing strategy

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#6008]
1. Find systemic ways to prevent future FE bugs

**Comment by dsadgat** [comment]
@tihuan was this completed?

**Comment by tihuan** [comment]
Will keep it for this week, so I can research a little more if there are more things we can proactively do to prevent FE bugs

But so far the two big action items are done, which are:

1. Use PR rdev for e2e tests
2. Update PR template to require FE changes to include e2e tests

**Comment by tihuan** [comment]
I can't think of anything else we can do proactively as a whole to improve the process. But I'll just keep an eye on this as we go!
