### ISSUE TITLE
Restructure workflows to limit race conditions

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#6047]

**Comment by prathapsridharan** [comment]
## The Problem
In the current scheme for continuous deploy from `main` to `staging` environment, we `git merge main` into `staging` branch. That is, HEAD commit in `main` will always be deployed. However, the continous deploy (`trigger-release-candidate-build-and-deploy.yml`) only if `push-tests.yml` workflow initiated by a push to `main` branch passes.

Our current workflow DAG looks like this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--459b3beb5e08acea2872d698e8cbb4aa3f091157/Screenshot%202023-10-18%20at%204.32.00%20PM.png)


_This is problematic because if we have commits in `main` in the following order `C1, C2, C3`, C1 could pass `push-tests.yml` and deploy the HEAD of `main` which is C3 in this case (remember, the deployment starts with `git merge main` into `staging`). However, C3 could fail `push-tests.yml` and should not have been deployed but the passing `push-tests.yml` initiated the first step of the deploy which is `git merge main` into `staging` which brought in C3 into `staging` branch!_

It is not sufficient to `git cherry-pick` single commits from `main` to `staging` because if `push-tests.yml` is the gate that triggers the continuous deploy which starts with `git cherry-pick <commit-initiating-push-tests>` into `staging`, then _due to the lack of order guarantees_ in GHA, you could have an order of `git cherry-pick`, say `C2, C1, C3`, such that there is a merge conflict in `staging` branch.

_What we want is that if we have commits in `main` branch in the order C1, C2, C3, then we want the deployments to `staging` (or any other environment) to happen is to either run the deployment workflow (including pre-requisite workflows like `push-tests.yml`) on C3 alone or run them in the exact order: C1, then C2, then C3._

## Potential Solution 1 - Use a merge queue

Put a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) for merging into `main` and leave our worflow DAG as is. 

When commits are coming in high velocity, it will group commits into a `merge group` and [_only commit them if they pass the target branch's protection rules_](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues):

```
A merge queue will wait for required checks to be reported before it can proceed with merging. You must update your CI configuration to trigger and report on merge group events when requiring a merge queue.
```

**Note that this reduces but does not eliminate ordering related race conditions entirely**. In our example, if we are lucky, `C1, C2, C3` all get put into one merge group. However, if they are split up into 2 groups: `[C1, C2]` and `C3`, then there is possibility of race conditions between groups if the _post-merge workflows_ of the 2 groups proceed at different rates. This _seems_ like a significantly better situation because our branch protection rules run slowly enough that make race conditions between merge groups less likely (famous last words)

We could try this solution as it is easy (famous last words again). We will need to analyze for gotchas.

## Potential Solution 2 - Rearrange Workflow DAG

There is possibility of race conditions moving from one workflow to another in the DAG and therefore you still have the possibility that the HEAD commit is not deployed. However, with a `merge_queue` at the beginning and a unidirectional workflow graph for each branch, race conditions seem unlikely. _This is more work than solution 1 but not too bad and the DAG structure is significantly better_:


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a381166480baa51eae17336ffc38ecd26761b3d3/Screenshot%202023-10-19%20at%204.40.21%20PM.png)



## Potential Solution 3 - Single Workflow File

**This is a lot of work! **:

- It should be able to be triggered _on push event to `main` branch_
- It should be able to be _triggered manually by single click_ (`workflow_dispatch`) by accepting input vars: `deploy_env` and `commit_to_deploy`
- Has a merge queue

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHhXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--507601625120861b11b51ea41af5470d7efcbb4e/Screenshot%202023-10-19%20at%204.40.46%20PM.png)

**Comment by atolopko-czi** [comment]
A couple more thoughts about solution 3 (single workflow file):
- If it is used in combination with both merge queues and concurrency=1, it might provide guaranteed ordering. After a merge_group is committed to main, the concurrency queue only has a single workflow to run to achieve the full deployment. So I don't see how another workflow invocation could jump in front of it.
- The workflow DAG is easier to understand and reason about, because the full DAG is represented in a single view. All of the various triggering logic tricks currently in use (deployment, repository_dispatch events) are no longer needed. Dependencies are easy to understand and view. Future maintenance for an uninitiated engineer will be much easier.

**Comment by atolopko-czi** [comment]
Noting here for future reference that this [GHA doc page](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#how-merge-queues-work) provides the most detail about how merge queues and groups work

**Comment by prathapsridharan** [comment]
I might also add that if we are going to use `merge queue` _we may not need to run `push-tests.yml` or any unit tests post-merge on `main` branch if the branch protection rules on `main` require that unit tests (`push-tests.yml`) pass_.

**Comment by prathapsridharan** [comment]
> * If it is used in combination with both merge queues and concurrency=1, it might provide guaranteed ordering. After a merge_group is committed to main, the concurrency queue only has a single workflow to run to achieve the full deployment. So I don't see how another workflow invocation could jump in front of it.

_This is in regards to Solution 3 (but equally applies to all other solutions):_

If the merge queue groups `C1, C2, C3` into a merge group and runs all branch protection tests before committing them, _will that register as a single push event on `main` or 3 different push events (C1, C2, C3) on `main`_?

1. If it is a single push event and the workflow gets triggered on the HEAD of `main`, then `concurrency` is not needed at all since commit C3 will be the only commit to trigger our single workflow run.
2. If each commit in the merge group registers a push event and triggers 3 workflow runs (one for each of C1, C2, and C3), then a concurrency group would not ensure that C3 (presumably the HEAD commit in `main`) would be deployed because [ordering is not guaranteed for jobs or runs using concurrency groups, they are handled in the order that they are processed](https://docs.github.com/en/actions/using-jobs/using-concurrency#overview)

Moreover, even if the merge queue merges each merge group one at a time (I would expect this is how it would operate), say merge group [C1, C2, C3] is merged then merge group [C4, C5] is merged after rebasing on on [C1, C2, C3], you would still have a race condition between merge groups even if push events operate by condition (1) above.

It seems to me that concurrency group is useful as _deduplication mechanism for idempotent operations_ but not a race condition resolving mechanism. This is why I thought we could add step right before deployment to check what commit is deployed before proceeding with the current deployment:

_We could further mitigate the possibility of an older commit deployed over the latest commit by checking the currently deployed commit sha, x, against the candidate commit sha to be deployed, y. If x already includes y, then abandon the deploy! We would make this check in the deployment step of the workflow_

We will need to study merge queues to better understand where race conditions might emerge

**Comment by atolopko-czi** [comment]
I am assuming that merge queues enforce the strict ordering, and if so, a concurrency=1 setting eliminates the possibility of a race condition since only one (monolithic) workflow can be running at a time, so there's never a race in workflow completion order.  Unless the concurrency queue somehow (!) gets the main merges submitted to it out-of-order from the merge queue order, I think we're safe.

**Comment by prathapsridharan** [comment]
Let me see if I understand with a concrete example here. If the merge queue finally submits a commits in the following order to `main` branch: `C1, C2, C3` where `C3` is the latest/HEAD commit, then:

_are you assuming that the workflows will be queued as as `[C1, C2, C3]` where `C1` is the head of the queue (that is, `C1`, is the first commit triggered workflow to run)?_

If that is in fact the case, I agree that setting a concurrency group into which these 3 commits fall into will guarantee that `C3` will win out and be deployed.

But it is not clear to me how the [workflows associated with commits are queued given an ordering of the commits](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) in `main`.

We could try the merge queue with concurrency group approach and if we do run into a race condition we will know.

**Comment by atolopko-czi** [comment]
As we now have a number of issues related to our CI/CD GHA workflow, we are better off considering all of these issues' goals/requirements together to ensure we end up with a clean solution. To that end, we now have an [epic](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6169) that subsumes them all, including this issue.  This issue is now referenced by the epic to ensure it is considered during design. Closing this issue.
