### ISSUE TITLE
refactor WMG2 Main

### ISSUE THREAD

**Issue by kaloster** [chanzuckerberg/single-cell-data-portal#6054]

**Comment by dsadgat** [comment]
@kaloster  Should this be closed? Not sure why Timmy is asking if it should be closed if its merged?

**Comment by kaloster** [comment]
There was another ticket for removing wmgv1 that used the same branch that's why the confusion. The Main component definitely still needs to be refactored

**Comment by tihuan** [comment]
Given that populating global tissue filter ticket is around 5 points without analytics changes, I think I might not be able to get to this one this week (and I'm out next week)! Sorry 😞

CC: @dsadgat
