### ISSUE TITLE
Add notification to GE that normalization method has changed

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#6089]
Please add a notification to GE to notify our users that our underlying data has changed and that Census.

Improvements to our data: Gene Expression now includes more data from [CELLxGene Census](https://chanzuckerberg.github.io/cellxgene-census/).
We now normalize this underlying data using ln(CPM+1) instead of quantile normalization. Learn more about the data and normalization in the [documentation](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_1__Get%20Started).

cc @karenliang0 for design, fyi @sidneymbell 

[Figma Design](https://www.figma.com/file/z6CczUpCBQUuIHGq826hzN/2023-H2-Gene-Expression-Improvements?type=design&node-id=213%3A16229&mode=design&t=FqJD3OCWwGiVgaax-1)

**Comment by tihuan** [comment]
Quick question - if a user navigates to a different page and comes back to GE page, do we want to show the notif again?

Currently we will show the notif again, but not sure if that's what we wanted 😄 

Thank you!

**Comment by signechambers1** [comment]
@tihuan i think that's fine! i dont have a strong opinion fyi @karenliang0
