### ISSUE TITLE
Cell types showing up not in the correct tissue

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#6110]
Steps to reproduce:
1. [Go here](https://cellxgene.cziscience.com/gene-expression?genes=CFAP54%2CRMST%2CSTK33%2CDNAH7%2CAR[…]CGLIS3%2CLRRIQ1%2CRFX3%2CSPATA17%2CTRMT9B%2CCFAP70&ver=2)
2. Expand "Brain"
3. Sort cell types -> hierarchical
4. See screenshot, notice half of cell types are above the Brain header

Expected result: All cell types are under the Brain header.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN04zQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9f04af4252c62ad3fb5985707f3470f229498fb/Screenshot%202023-10-26%20at%2011.40.35%20AM.png)

**Comment by seve** [comment]
@signechambers1 I think ZenHub broke your share link, it shortened in and injected a `[...]`
