### ISSUE TITLE
Investigate initial page load performance issues and possible solutions

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/single-cell-data-portal#6117]
Initial Page load of gene expression takes over 3 seconds currently. Please investigate where this time is coming from, and what options we have to cut this down (from FE & BE perspective). 

Are we loading too much? Pulling too much? What operations/endpoints are taking the bulk of this time?

Please do the investigation and come up with a write up, thanks!

Performance doc linked to the epic.

**Comment by kaloster** [comment]
Writeup for above can be found here: https://docs.google.com/document/d/1I6I0kzs4hpqtDKy-vHMR-kSktLvSUsR59sQeJlOfGoo/edit?usp=sharing

**Comment by kaloster** [comment]
instrumentation (datadog) added to the frontend
