### ISSUE TITLE
Investigate performance issues with adding 1 gene to all tissues

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/single-cell-data-portal#6118]
Adding one gene to all tissues currently in prod testing takes over 6 seconds. Please investigate and add datadog trace metrics if they do not exist to see where the performance lag is coming from. 

Scope this effort to 1-2 days max, and please have a write up of possible solutions.

Be aware of overlap potential with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6117

**Comment by atarashansky** [comment]
I just checked - adding a single gene (MALAT1) takes ~3s now. This might be due to the fact that we are presenting fewer cell types (so less data) after excluding redundant ancestor nodes.

If this no longer counts as a performance issue, we can close out this ticket.

**Comment by dsadgat** [comment]
The ask is to get it to lower than 3 https://docs.google.com/document/d/1w-XUG8AmioSYKekWrA1cSjyoGsAPKzE5c6V4C5gCm_U/edit - if this is the case (consistently) then feel free to kick up to product and please create and review a ticket about the slowness of group by. Thanks!

**Comment by joyceyan** [comment]
Yeah it's taking about 3 seconds or so for me.

@signechambers1 Are we good to close out this ticket?

**Comment by prathapsridharan** [comment]
Thanks @atarashansky! I can also independently confirm that picking 1 gene at a time has a roundtrip time of ~3s. I think this is reasonable and therefore this ticket can be closed. What do you think @dsadgat

**Comment by atarashansky** [comment]
> The ask is to get it to lower than 3 https://docs.google.com/document/d/1w-XUG8AmioSYKekWrA1cSjyoGsAPKzE5c6V4C5gCm_U/edit - if this is the case (consistently) then feel free to kick up to product and please create and review a ticket about the slowness of group by. Thanks!

@dsadgat I added another column with the current timings as of today.

**Comment by signechambers1** [comment]
I concur, this takes about 3 seconds for me now too. We can close, thanks everyone!
