### ISSUE TITLE
investigate sharelink test failure and re-enable cellTypes test

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#6131]
```
// TODO: investigate test failures and re-enable cellTypes test
```

https://github.com/chanzuckerberg/single-cell-data-portal/blob/4ab9b46ded0d064f0c201cc34a9baba71a3c433a/frontend/tests/features/wheresMyGene/shareLink.test.ts#L75

**Comment by tihuan** [comment]
@seve can you add more context as to what failure you're seeing and any leads for fixing this?

Since this creates a test gap, I'll add a P0 tag to fix this ASAP!

Thank you!

**Comment by tihuan** [comment]
@dsadgat I should take a look at this this week, since it's a test gap we're missing!
