### ISSUE TITLE
Updates to marker gene panel

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#6132]
We'd like to update the columns and tooltips available for the marker genes panel. Changes below:

- [ ] Rename Marker Score to Effect Size
- [ ] Remove Low Medium High cutoffs from panel (we're adding to tool tip below)
- [ ] Add tool tip to Effect Size, copy:
Effect size indicates how much higher the average gene expression is in this cell type relative to other cell types in the same tissue.
Low: <1    Medium: 1-2    High: >2
[Learn more about how this is calculated.](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_5__Find%20Marker%20Genes)
- [ ] Add a Specificity column
- [ ] Add Specificity tooltip, copy:
"Specificity indicates the percentage of cell types in {tissue} tissue with a lower Effect Size for this gene. Higher Specificity values indicate markers which are more specific for this cell type."
[Learn more about how this is calculated.](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_5__Find%20Marker%20Genes)

----

Cell Guide updates:
- [ ] Rename Marker Score to Effect Size
- [ ] Update effect size tooltip to the same as above
- [ ] Rename Expression Score to Mean Expression
- [ ] Update expression score tooltip, copy:
Average [ln(CPTT+1)-normalized](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_3__Gene%20Expression%20Data%20Processing) gene expression among cells in the cell type.
- [ ] Add Specificity column with same tooltip copy as GE

---

[Figma Designs
](https://www.figma.com/file/z6CczUpCBQUuIHGq826hzN/2023-H2-Gene-Expression-Improvements?type=design&node-id=282%3A12977&mode=design&t=lYlQgSLE8jyMYXHA-1)

---

cc @karenliang0 @sidneymbell 

Notes for eng estimate:
- Copy changes to update "Marker Score" to "Effect Size" should be quick
- Adding the specificity column will require using `MarkerGene.specificity`. It looks like we're already pulling this down from WMG, but passing it all the way through to to the `MarkerGenesTable` will be a bit tricky
- Add/update e2e test to verify the Specificity column exists

**Comment by joyceyan** [comment]
@signechambers1 @sidneymbell Just a suggestion, but do you think that we should update the column names and tooltip copy in CellGuide as well? We currently show "Marker Score" and "% of Cells".

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE8rQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a408c9670edc3416340d5d514cca5c83ba7d29fb/image.png)

Also, if there are any guidelines on where the Specificity column should appear and what the spacing/justification should be, let me know. cc @karenliang0

**Comment by signechambers1** [comment]
cc i think it would make sense to update marker score in cell guide as well, but defer to @sidneymbell. cc @niknak33 for cell guide.

**Comment by karenliang0** [comment]
Correct me if I'm wrong, but are we holding off on implementing specificity @signechambers1? Maybe I heard incorrectly!

**Comment by signechambers1** [comment]
No, we are adding in specificity. Thank you!

**Comment by karenliang0** [comment]
Nevermind, we are doing specificity! Will add them to the design right now.

**Comment by joyceyan** [comment]
Thanks @karenliang0 and @signechambers1 !

**Comment by karenliang0** [comment]
Updated in Figma! :) @joyceyan

**Comment by sidneymbell** [comment]
Yes, we can rename "marker score" to "effect size" in cell guide as well. Thanks!
