### ISSUE TITLE
Add cell type description to Marker genes panel

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#6133]
We can add the Cell Ontology short cell type descriptions from Cell Guide to the marker genes panel to provide our GE users more information and promote cross product interoperability.

---

[Figma Designs](https://www.figma.com/file/z6CczUpCBQUuIHGq826hzN/2023-H2-Gene-Expression-Improvements?type=design&node-id=282%3A12977&mode=design&t=lYlQgSLE8jyMYXHA-1)

---

cc @karenliang0 for design, @signechambers1 for product

**Comment by dsadgat** [comment]
@karenliang0 to add design by EOD
