### ISSUE TITLE
Remove the "Improvements to our data" notification

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#6134]
The "Improvements to our data" notification was temporary to notify users to changes in the underlying data. With the last release of the year we'd like to remove this notification. It will have been up for 6 weeks which is enough to notify most returning users.

**Comment by dsadgat** [comment]
@seve can you pick this up pls? ty

**Comment by kaloster** [comment]
taking over this one as I am doing some other work [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6109) already
