### ISSUE TITLE
Add Human Cell Atlas (HCA) to the consortia list

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6138]
@jonahcool has requested that `Human Cell Atlas (HCA)` be added to the list of valid consortia.

Please verify, but I believe that the following will need to be updated:

1. [backend/layers/common/validation.py](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fd5778d347da7609f5d5362970da84a1bc18face/backend/layers/common/validation.py#L12C1-L12C1)
2. [frontend/src/components/CreateCollectionModal/components/Content/common/constants.ts](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fd5778d347da7609f5d5362970da84a1bc18face/frontend/src/components/CreateCollectionModal/components/Content/common/constants.ts#L1)
3. [backend/portal/api/portal-api.yml](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fd5778d347da7609f5d5362970da84a1bc18face/backend/portal/api/portal-api.yml#L1066)
4. [backend/curation/api/curation-api.yml](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fd5778d347da7609f5d5362970da84a1bc18face/backend/curation/api/curation-api.yml#L787)

**Comment by metakuni** [comment]
We'll need this deployed to production next Thu (9th) so that it's available to Lattice before the upcoming Single Cell Annual Meeting.
