### ISSUE TITLE
bug(gene expression): Citation button is deactivated until a gene is selected

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/single-cell-data-portal#6158]
## Describe the bug

The "cite" button should be active / clickable even if the user has not input a gene. 

## To Reproduce

[Screen shot](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c142b5191ed24dc7a68112a2222af1c11a99b9c/image.png)

**Comment by kaloster** [comment]
taking over this ticket since I am already doing some other work here
