### ISSUE TITLE
Cleanup crossref code

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#6166]
## Motivation

Code hygiene makes for healthy engineering. By DRY. Delete dead code.

## Definition of Done

- All CrossRef code is in encapsulated in a single service

## Tasks

- [ ] Refactor this [code](https://github.com/chanzuckerberg/single-cell-data-portal/blob/bc584a92c7585b511e70dc8822a7836b9a54a0b0/backend/cellguide/pipeline/canonical_marker_genes/utils.py#L39), moving it [here](backend/layers/thirdparty/crossref_provider.py)
- [x] Delete this dead code implementation of [CrossrefProvider](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/layers/thirdparty/crossref_provider.py) and its tests.

**Comment by seve** [comment]
We'll soon be making crossref calls from the frontend, too. If this is a service with an API, that'd be fantastic

**Comment by atolopko-czi** [comment]
Currently, it's just a library-level API (in the "business layer") that is used privately by the backend code, so it's not exposed via an HTTP API. But do add a new issue for that if needed! (maybe as part of upcoming epic that requires it)

**Comment by brianraymor** [comment]
CC: @metakuni ^^^

**Comment by danieljhegeman** [comment]
Handling the second task in #6414

**Comment by danieljhegeman** [comment]
Moved back to Disorder after completing subtask named above. Refactor for Cellguide (first item) still remains to be completed.

**Comment by brianraymor** [comment]
I'm adding to a larger crossref epic so this doesn't get lost.
