### ISSUE TITLE
Analytics (new/update): cellxgene homepage revamp

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-data-portal#6168]
### Overview

**Section**: `homepage`

**Description**: 
Given how many changes have been made to cellxgene since the homepage was launched the team decided to update it to 1) ensure we’re using the most current version of our messaging to describe the platform and 2) articulate the full breadth of CELLxGENE's tools and features with our core audiences. 

With these changes comes new/updated analytics instrumentation needed to track user interaction with the homepage. We want to know if users who visit the homepage visit other pages in cellxgene and how they get to those other pages from the homepage.

~ Given the update-nov 6 [figma version](https://www.figma.com/file/V8VgVuNptyacVmRkOTITUP/rd-1?type=design&node-id=2283-729&mode=design&t=TW4NEuQPAMilhvcG-0)

### New events to add
**Secondary navigation bar**
`HOMEPAGE_SEC_NAV_CENSUS`:
- To fire when a user clicks _Census_ in the secondary navigation bar

`HOMEPAGE_SEC_NAV_CELL_GUIDE`:
- To fire when a user clicks _Cell Guide_ in the secondary navigation bar 

`HOMEPAGE_SEC_NAV_COLLECTIONS_DATASETS`:
- To fire when a user clicks _Collections & Datasets_ in the secondary navigation bar 

`HOMEPAGE_SEC_NAV_WMG`:
- To fire when a user clicks _Gene Expression_ in the secondary navigation bar 

`HOMEPAGE_SEC_NAV_EXPLORER`:
- To fire when a user clicks _Explorer_ in the secondary navigation bar 

`HOMEPAGE_SEC_ANNOTATE`:
- To fire when a user clicks _Annotate_ in the secondary navigation bar 

**Additional buttons**
`CENSUS_DOCUMENTATION_CLICKED`
- To fire when a user clicks the _See quick start tutorial_ button within the _Census_ section

`CELL_GUIDE_CLICKED`
- To fire when a user clicks the _Search for a cell type or tissue_ button within the _Cell Guide_ section

For the **Collections & Datasets** section
- If the _Browse data collections_ button takes users to the collections list -> keep as is 
- If the _Browse data collections_ button takes users to the datasets list -> adjust to fire `BROWS_DATASETS_CLICKED`

**Events to depreciate**
- HOMEPAGE_LEARN_FIND_SINGLE_CELL_DATA_CLICKED
- HOMEPAGE_LEARN_EXPLORE_GENE_EXPRESSION_CLICKED
- HOMEPAGE_LEARN_ANALYZE_DATASETS_CLICKED
- HOMEPAGE_LEARN_DOWNLOAD_DATA_CLICKED
- HOMEPAGE_LEARN_EXPEDITE_COLLABORATION_CLICKED

Checklist

- [ ] Add events to the custom goals section of both the staging and prod Plausible spaces
- [ ] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @niknak33 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by dsadgat** [comment]
Hold on pickup until KNI completed homepage work.

**Comment by kaloster** [comment]
putting a pause on this until the recent changes from KNI are merged: https://czi-sci.slack.com/archives/C039X645880/p1700150590777309

**Comment by kaloster** [comment]
closing this ticket! above was already completed by KNI.
