### ISSUE TITLE
Analytics (new): FILTER_SELECT_TISSUE_TYPE

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#6185]
### Overview

**Tool**: Discover UX

- Feature: Feature: Collection and Datasets Tissue Type filter

**Description**: See [Add Tissue Type filter to Collections and Dataset](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5877)
**Expectations**: `<usage of this feature or functionality>`

### New events to add

`FILTER_SELECT_TISSUE_TYPE `: `{tissue_type: <name of tissue type>}`

- A data consumer selects one or more tissue type in the filter.

Checklist

- [ ] Add events to the custom goals section of both the staging and prod Plausible spaces
- [ ] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @brianraymor
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by brianraymor** [comment]
Closing per the comment in its epic - **December 2023: This feature is pended based on changes in priorities for 2024. The mitigation is that the consumer may still continue to search for "organoids" or "cell culture" in the absence of a special filter.**
