### ISSUE TITLE
Data Submission Policy was regressed and is returning incorrect version

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6202]
# Context

The `data_submission_policy_version` was previously stored for each collection to support:
1. Tracking which collections have been updated to a new policy when approval by existing submitters or others is required
2. Allowing CELLxGENE Discover to support multiple submission policies when existing submitters do not agree to an updated policy 

The value is also returned by DP API. The current version is 2.0, but the implementation was regressed (eliminated?) and 1.0 is being returned as a hard coded value. See the [code](
https://github.com/chanzuckerberg/single-cell-data-portal/blob/655f391d81c89b403422ea81e0d5d69cf3427aa5/backend/portal/api/portal_api.py#L270):

` "data_submission_policy_version": "1.0",  # TODO`

#### Tech Spec
[Tech Spec: The Data Submission Policy was regressed and is returning an incorrect version](https://docs.google.com/document/d/1kTsaW-Paf5yHxzR3kK5RfGBd1gjY8hpm__tgojmv9ZU/edit#heading=h.jcf27gbiblyg)

**Comment by metakuni** [comment]
Fix notes:
1. For each collection, find the most recent `data_submission_policy_version` that predates the hardcoded 1.0 value. (from before the Portal redesign)
2. Set that value in the current collection version via `cxg_admin.py`.
3. Fix the [API](https://github.com/chanzuckerberg/single-cell-data-portal/blob/655f391d81c89b403422ea81e0d5d69cf3427aa5/backend/portal/api/portal_api.py#L270) to return `collection.data_submission_policy_version`.

**Comment by MillenniumFalconMechanic** [comment]
4. Save current data submission policy version on publish.
