### ISSUE TITLE
feat(census-spotlight): Add metadata fields required for maintained projects

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#6205]
We're predicting we're going to need additional metadata fields to support maintained projects on the spotlight page. We'll need to add those fields to the type defined for the static projects' JSON, as well as add code to handle the display of this additional metadata.

figma [link](https://www.figma.com/file/DMoBg0zsvktKrOZ3akAnFc/Census?node-id=774%3A21604&mode=dev) - @hthomas-czi

**Comment by dsadgat** [comment]
@seve can you get started on this?
