### ISSUE TITLE
feat(SFN Errors): Mark ingest sfn with errors as failed

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#6234]
## Need

When an ingest step function runs, if an error occurs and everything is handled using error handler, the step functions is marked as successful in the AWS Console. This can make it difficult to go to find a dataset that failed during a seurat, cxg, or validation step.

 <img width="518" alt="Screenshot 2023-11-15 at 3 45 54 PM" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/1429913/5f10277d-0426-47cc-820c-de5391bdc011">

If an error is detected that results in a CXG, seurat, or validation failure, the SFN should handle the error and mark it's self as failed.
<img width="1011" alt="Screenshot 2023-11-15 at 3 49 38 PM" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/1429913/2749879d-d3b3-49ad-8dcd-8b07ba5f4336">

This will mark the SFN as failed and will be clear when looking at the AWS SFN Console

## Approach

- Add a step to check if there are errors in the output and set SFN to failed if any were found. This is require modifying the outputs of some steps to pass along the error message.

## Definition of Done
- An ingest SFN that fails any of the previous step will be marked as failed.

**Comment by brianraymor** [comment]
Says "flowchart!" in Minion's voice.
