### ISSUE TITLE
bug(CellGuide): Tissue Description Errors

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6249]
## Describe the bug

Certain Tissue descriptions end with a [GO] or [WP] at the end. 

## To Reproduce

1. Go to https://cellxgene.cziscience.com/cellguide/tissues/UBERON_0002107 and https://cellxgene.cziscience.com/cellguide/tissues/UBERON_0000955
2. See error
3. Both descriptions you will see either GO or WP at the end.

## Expected behavior

Tissue type descriptions should not have [GO] or [WP] at the end of their descriptions.

## Environment

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 119.0.6045.160

**Smartphone (please complete the following information):**

**Comment by signechambers1** [comment]
Nik to decide.

**Comment by niknak33** [comment]
Closed after investigation that the bug is on the Uberon side and not on CellXGene
