### ISSUE TITLE
Update WMG pipeline’s Census schema version to include schema 4 migration

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/single-cell-data-portal#6254]
This is blocked by the [census upgrade work](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-census/750). 

Make sure this work is done after this [ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6019).

**Comment by signechambers1** [comment]
Closing since schma 4.0 is a minor upgrade
