### ISSUE TITLE
Add "consortia" to Contribute and Publish docs

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-data-portal#6258]
Our [Collection requirements](https://github.com/chanzuckerberg/single-cell-data-portal/blob/98f4bb5ba9863bd69ac1b6bed6aa775d6ee1189f/frontend/doc-site/032__Contribute%20and%20Publish%20Data.mdx#L30) can add a bullet point for Consortia as optional information to provide. Should point to a list of options (if it exists)

**Comment by brianraymor** [comment]
> Should point to a list of options (if it exists)

It is [hardcoded](https://github.com/chanzuckerberg/single-cell-data-portal/blob/7851ae1fba2b21bedb951e3487fce08f7a805d49/backend/layers/common/validation.py#L12)
