### ISSUE TITLE
Test schema 4 downstream + fix bugs

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/single-cell-data-portal#6263]
Please test all changes made downstream of Schema 4 - on GE and Explorer. Feel free to organize as you wish.

We'll have to run the WMG pipeline in dev, and then verify that each individual ticket we worked on is completed.

**Comment by joyceyan** [comment]
WMG filters out system-level tissues from GE in dev now! https://cellxgene.dev.single-cell.czi.technology/gene-expression
