### ISSUE TITLE
Remove tissue type-related Schema 4.0.0 feature flag

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#6266]
#### Approach
* Remove references and logic branches in FE, BE and tests.

**Comment by metakuni** [comment]
@MillenniumFalconMechanic , can this be closed?

**Comment by brianraymor** [comment]
Closing - we decided not to expose tissue type per the comment in its epic:

**December 2023: This feature is pended based on changes in priorities for 2024. The mitigation is that the consumer may still continue to search for "organoids" or "cell culture" in the absence of a special filter.**
