### ISSUE TITLE
bug(wmg): respiratory system is empty when filtering by melanocyte

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#6275]
1. Go here: cellxgene.cziscience.com/gene-expression
2. Filter by melanocyte using the cell type filter
3. Observe respiratory system being empty:
<img width="699" alt="image" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/ea7a4f7d-e840-4433-a5ba-29f3e7b033d8">

**Comment by joyceyan** [comment]
Now that we filter out system-level tissues, this bug doesn't seem to exist anymore. Closing this out unless we see this being a problem for other tissue types.
