### ISSUE TITLE
Batch Job Id and Step Function ARN 

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#6282]
[Reporting for failed dataset](https://czi-sci.slack.com/archives/C024HCSH9PT/p1701190353714849) has some problems.

- (higher priority) `Batch Job Id` is `None`

- (lower priority) `Step Function ARN`, while appearing to be printed out correctly in the Slack output, is _linking to_ a url that is prefaced by `https://none...`. This is likely resulting from slack expecting a more standard protocol (e.g. `http` or `https`) when a link-like piece of text is submitted. It may be necessary to figure out how to specify that it is not a link.

**Comment by metakuni** [comment]
Actually, comparing [today's Slack notification with broken links](https://czi-sci.slack.com/archives/C024HCSH9PT/p1701190353714849) to the [last one that had good links](https://czi-sci.slack.com/archives/C024HCSH9PT/p1700177532756139):

**Batch Job ID:** (region and UUID missing)
https://**none**.console.aws.amazon.com/batch/v2/home?region=**None**#jobs/detail/**None**
vs
https://**us-west-2**.console.aws.amazon.com/batch/v2/home?region=**us-west-2**#jobs/detail/**efe48d73-9fdb-4f2a-abeb-804592ee03f6**

**Step Function ARN:** (region missing)
https://**none**.console.aws.amazon.com/states/home?region=**None**#/v2/executions/details/arn:aws:states:us-west-2:231426846575:execution:dp-prod-prodstack-sfn:d63f9eca-d40a-403b-b0d6-a76d96356400_1701190342
vs
https://**us-west-2**.console.aws.amazon.com/states/home?region=**us-west-2**#/v2/executions/details/arn:aws:states:us-west-2:231426846575:execution:dp-prod-prodstack-sfn:9d70e3f6-77ba-4f75-96a5-58d800622b12_1700176280

**Comment by danieljhegeman** [comment]
**SOLVED**:

This was the full input to the `HandleErrors` step that reports to Slack:

```
{
  "execution_id": "arn:aws:states:us-west-2:231426846575:execution:dp-prod-prodstack-sfn:d63f9eca-d40a-403b-b0d6-a76d96356400_1701190342",
  "dataset_version_id": "d63f9eca-d40a-403b-b0d6-a76d96356400",
  "error": {
    "Error": "Batch.ClientException",
    "Cause": "JobQueue arn:aws:batch:us-west-2:231426846575:job-queue/dp-prod not found. (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: 4cb56747-53d3-4753-8945-d7bf417cbbce; Proxy: null)"
  },
  "collection_version_id": "106fb408-0c6b-487a-af94-6323fdcef219"
}
```

As stated by the error, the job queue was (mysteriously) gone. This was noticed this morning and a rerun of terraform fixed the problem, reinstantiating the queue. As this error occurs outside of the context of an actual sfn _task_, the error structure in the report differed from what is expected from a task, and our parsing failed. This is an error unrelated to the Dataset/datafile, and as such may not be worth putting effort into reporting in the wrangling channel.

At present no reason to expect this sort of irregularity to occur when the error arises from _within_ a task.
