### ISSUE TITLE
Update doc & UX references from Seurat v4 to Seurat v5

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#6283]
Once all datasets have been migrated to schema 4, the following UX references to Seurat v4 will need to be updated to Seurat v5:
- https://github.com/search?q=repo%3Achanzuckerberg%2Fsingle-cell-data-portal%20%22seurat%20v4%22&type=code

**Comment by danieljhegeman** [comment]
[Referenced in the original issue](https://github.com/chanzuckerberg/single-cell-data-portal/issues/5532#issuecomment-1797902469)
