### ISSUE TITLE
Investigate GE frontend performance problem rendering heatmap AFTER getting the query-by-genes result back from the backend

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#6295]
### Reproduction Steps
1. Go to https://cellxgene.cziscience.com/gene-expression - _a backend query is sent to fetch data but this is quite fast_
2. Expand "Brain" Tissue and _info icon_ on "stem cell" - _a backend query is sent to fetch rolled up data - this takes about 6 seconds - not fast but is a known performance issue that is currently being investigated_
3. Add the 25 marker genes on "stem cell" to dot plot - **Notice it takes very long to render the heatmap even though there is no query to the backend - It feels like it takes longer to render the heatmap than the RTT for the backend API call!!!**
4. Expand any other tissues ("large intestine", "small intestine" ,etc) - **Notice it takes very long to render the heatmap even though there is no query to the backend - It feels like it takes longer to render the heatmap than the RTT for the backend API call!!!**

See attached video to get a feel for this:

https://github.com/chanzuckerberg/single-cell-data-portal/assets/5581819/f3dae993-dd59-4e3b-88c1-8b813ff2ba8c

**Comment by kaloster** [comment]
findings posted here: https://czi-sci.slack.com/archives/C0247APK621/p1702582794788949

closing this and will create a new ticket with action items once direction decided on by product
