### ISSUE TITLE
Automatically update DOIs during migration runs

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#6313]
(inspired by [this issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/575))

Sometimes data submitters do not diligently update the DOIs for their Datasets which are associated with preprints. When the _published_ DOI is eventually released, we want to associate the published DOI with the Dataset instead of the preprint DOI. 

Requirement: check for, and incorporate, published DOIs for all Datasets on a regular cadence: during each migration run.

**Comment by metakuni** [comment]
Closing this in favor of updating DOIs when revisions are published:
* https://github.com/chanzuckerberg/single-cell-data-portal/issues/6924
