### ISSUE TITLE
[Discovery] Curators and Data Submitters do not want to cancel and restore long-term in-progress revisions during a schema migration

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6317]
# Context

See [**#single-cell-four**](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1701804138556999).

If a public collection has a long-term revision in progress during a schema migration, the curators are forced to:
*  Cancel the revision
*  Wait for migration to complete
*  Create a new revision
*  Restore changes such as uploading revised datasets
*  Share new revision links with the submitter

This also impacts the Data Submitter - _Data Submitters with long-term Revisions want a stable private URL to share with collaborators and reviewers._

# Design

The actors:
**A**: Current Published Collection
**B**: Long-Term Private Revision of **A**
**C**: Second Private Revision of **A** for schema migration (not currently supported)

The desired behavior during migration:
1. Create **C**. Migrate. Re-publish as **A**. 
2. Migrate **B**. Do not republish.
3. Ensure that the collection/dataset versions reflect that **C** is the version before **B** (when/if **B** is published)

**Comment by metakuni** [comment]
Needs discovery first

**Comment by danieljhegeman** [comment]
> Ensure that the collection/dataset versions reflect that C is the version before B (when/if B is published)

This made me realized I don't recall the following topic ever being addressed: a migration incurs an additional Collection/Dataset version for each entity. To someone reviewing version history, a migration is indistinguishable from a (curator-prosecuted) revision. Is this a problem?

And given that that is the current implementation behavior for migrations, why does the quoted text ask that C be the version before B, as `C->B`. Because it appears to me that the actual version history should be `C->A->B` per the ordered steps in the example at the end of the description.

**Comment by brianraymor** [comment]
> Is this a problem?

No. Migration is simply automating an earlier manual curation process that required revisions.

> Because it appears to me that the actual version history should be C->A->B 

No. It would be (earliest to latest):

A->C->B IF B is published. 

Consider the current case:
1. A is published.
2. B is the private revision. Curators have to cancel that revision for migration.
3. C is the migrated revision of A, so A->C
4. Curators recreate B revision and publish, so A->C->B.

**Comment by danieljhegeman** [comment]
Sorry I misunderstood this initially

>Create C. Migrate. Re-publish as A

both the separation of "create c" from "migrate" and then "re-publish _as A_". But I get it now. Thanks!

**Comment by nayib-jose-gloria** [comment]
- Estimate: 1-2 weeks x 1 engineer + 1 reviewer
	- Call Crossref API and check “deposited” against most recent “revised_at” / “published_at” (if never revised) date when either CREATING or PUBLISHING a collection version. If deposited is more recent, update collection metadata pulled from crossref (i.e. get published DOI if preprint and its been published, get updated author info). Can reuse existing functions for extracting collection metadata from Crossref.
		- advantage of doing it upon CREATE: allows curator to review changes before publishing. To accommodate this for publish, would probably require additional frontend work to 		warn curators of new collection metadata extracted after hitting publish + asking them to confirm. Though perhaps this can be baked into the initial confirmation modal. 
		- advantage of doing it upon PUBLISH: pick up new metadata if deposited during curation, particularly helpful for long-lasting revisions. Also allows 
		- FE: either way, helpful to have some sort of modal show up in UI letting curator know that collection metadata has been updated when new changes are pulled.

**Comment by nayib-jose-gloria** [comment]
-Estimate: 4-5 weeks x 2 engineers + testing for regression 

- Add “is_migration_revision” flag to CollectionVersionTable
- During migration, make “is_migration_revision” True for all revisions opened by the schema_migrate.py script
-  If a collection has an open revision during a migration—Update schema_migration.py to both migrate the revision AND open a new revision with “is_migration_revision” is True, and migrate that as well 
- Update create_collection_version in business.py to allow creating second revision, ONLY IF coming from migrate script (pass flag?)
- Update publish_revisions to only publish revisions with “is_migration_revision” == True
- IF a collection index / fetch endpoint looks up collection revisions and there is >1 revision, filter out “is_migration_revision” revision and return the other
    - i.e. the frontend should display the pre-existing collection if two are available due to a migration

**Comment by metakuni** [comment]
Link to impl ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6930
