### ISSUE TITLE
Bug: data snapshots provided in docs are out of date and don't match the interface

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/single-cell-data-portal#6318]
A user recently emailed because they were not able to reproduce the results shown in the interface with the current data downloads. 

Upon investigation with Alec, this is because these data snapshots have not been updated. 

I will submit a PR today to remove these download links to avoid further confusion. We should update these data snapshots as soon as possible.

**Comment by dsadgat** [comment]
This is not a bug @niknak33
