### ISSUE TITLE
Postgres json is not queryable, possibly double-encoding?

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#6348]
I'm unable to query our json-type columns for individual json attributes, such as `"name"` on `CollectionVersion.collection_metadata`.

I've tried:

`select collection_metadata->>'name' as name from "CollectionVersion";`
`select collection_metadata->'name' as name from "CollectionVersion";`
`select collection_metadata::json->'name' as name from "CollectionVersion";`

Additionally, I find it a bit suspicious that the output for `select collection_metadata from "CollectionVersion" limit 1;` gives
```"{\"name\":...\"links\": []}"``` 
where there are explicit `"` quotes terminating the output; running `select owner from "CollectionVersion" limit 1;` gives 
```<owner>``` with _no_ terminating `"` characters.

I think we might be double-encoding our json, such that psql sees every one of our values as json _strings_ rather than json _objects_. This makes querying attributes impossible, and it also makes for a much less enjoyable psql console experience.

**Comment by nayib-jose-gloria** [comment]
completed
