### ISSUE TITLE
GE Download not working

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#6372]
Steps to reproduce:

1. Go to prod: https://cellxgene.cziscience.com/gene-expression
2. Add first four genes in drop down
3. Click download PNG (or PNG and CSV)
4. Loading state starts but nothing ever downloads

Desired Result:
1. Selected outputs download successfully

This has been broken since 12/10 at least according to user feedback survey.

**Comment by tihuan** [comment]
Postmortem scheduled for 1/10 11am

**Comment by tihuan** [comment]
Confirmed to work in prod now!

https://czi-sci.slack.com/archives/C0244PQK934/p1703098386154199?thread_ts=1703095426.462079&cid=C0244PQK934
