### ISSUE TITLE
Create a performance profiling script to be run before and after performance improvements

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#6401]
Rough outline of the performance profiling script:
 - The script will submit POSTs to the WMG API of a deployed environment, requiring the user to specify the backend API URL as an argument.
 - The script will iterate through a number of different queries (e.g. gene sets of increasing sizes, compare on/off, etc)
 - The script will parse the response header for the server timings and output the results.
 - The script will have the capacity to execute requests serially or in parallel (controlled by an optional input flag)

Here are the following test cases:

For "Group By" in [None, Disease, Publication]:
 - 1 gene
 - 5 genes
 - 10 genes
 - 25 genes
 - 50 genes
 - 100 genes
 - 200 genes

The genes should be sliced from a hardcoded list of 200 random genes to ensure reproducibility.

The parallel input flag accepts an integer N, default 1. If N>1, each test case is triggered N times concurrently.

**Comment by prathapsridharan** [comment]
@atarashansky - A couple of clarifications here:

1. I read the description as the script will run through all test cases (7 x 2 = 14). If we notice something odd about a particular test case and want to isolate that (ex: 25 genes with group-by disease), we won't be able to do that. Maybe that is ok but just want to call that out.
2. Clarification on parallelism here. Do you mean that if N = 5, 

**2A)** it will run 5 concurrent requests of "1 gene" and after that is complete, it will trigger 5 concurrent requests of "5 genes" and after that is complete, it will trigger 5 concurrent requests of "10 genes", etc? OR
**2B)** it will trigger all 14 tests concurrently and run 5 trials of 14 concurrent requests?

I think you mean **2A** but want to clarify here.
