### ISSUE TITLE
Review impact of HsapDv and MMusDV updates to development stage filter 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#6539]
* [Curation](https://github.com/chanzuckerberg/single-cell-curation/issues/401) issue.
* [Currently used terms that will be deprecated](https://clevercanary.slack.com/archives/C06AVGFV222/p1705514733452099):

  - HsapDv:0000004 [Cleavage]
  - HsapDv:0000080 [Immature]
  - HsapDv:0000082 [Newborn]
  - HsapDv:0000083 [Infant]
  - HsapDv:0000081 [Child]
  - HsapDv:0000204 [Mature]
  - HsapDv:0000086 [Adolescent]
  - HsapDv:0000087 [Adult]
  - HsapDv:0000088 [Early adulthood]
  - HsapDv:0000091 [Late adulthood]
  - MmusDv:0000061 [Early adulthood]
  - MmusDv:0000097 [Late adulthood]
* As per @jahilton [(see Slack)](https://clevercanary.slack.com/archives/C06AVGFV222/p1705516985673359?thread_ts=1705514733.452099&cid=C06AVGFV222), possible filters after the update:

  **Human**
  * prenatal stage [HsapDv:0000045]
    * embryonic stage [HsapDv:0000002]
    * fetal stage [HsapDv:0000037]
  * postnatal stage [HsapDv:0010000]
    * pediatric stage (0-15y) [HsapDv:0000264]
      * newborn stage (0-28d) [HsapDv:0000262]
      * infant stage (28d-1y) [HsapDv:0000261]
      * child stage (1-5y) [HsapDv:0000265]
      * juvenile stage (5-15y) [HsapDv:0000271]
  * adult stage (15y+) [HsapDv:0000258]
    * young adult stage (15-40y) [HsapDv:0000266]
    * middle aged stage (40-60y) [HsapDv:0000267]
    * late adult stage (60y+) [HsapDv:0000227]

  **Mouse**
  * prenatal [MmusDv:0000042]
    * embryonic [MmusDv:0000002]
    * fetal [MmusDv:0000031]
  * postnatal stage [MmusDv:0000092]
    * immature (0-6w) [MmusDv:0000043]
    * mature (6w+) [MmusDv:0000110]
      * prime adult (6w-18m) [MmusDv:0000136]
         * young adult (6w-10m) [MmusDv:0000153]
         * middle aged (10-18m) [MmusDv:0000135]
      * late adult (18m+) [MmusDv:0000134]

**Comment by MillenniumFalconMechanic** [comment]
#### Deprecated Terms
<img width="1222" alt="development-stage-deprecate-terms" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/2446424/9a0f25f9-0286-40d8-85f8-de94ade51d41">

#### Counts Deprecated Terms
| Deprecated Term | Collections | Datasets |
| --- | --- | --- |
|`HsapDv:0000004 [Cleavage]`|0|0|
|`HsapDv:0000080 [Immature]`|31|54|
|`HsapDv:0000082 [Newborn]`|12|16|
|`HsapDv:0000083 [Infant]`|16|32|
|`HsapDv:0000081 [Child]`|21|41|
|`HsapDv:0000204 [Mature]`|133|742|
|`HsapDv:0000086 [Adolescent]`|16|31|
|`HsapDv:0000087 [Adult]`|130|717|
|`HsapDv:0000088 [Early adulthood]`|89|427|
|`HsapDv:0000091 [Late adulthood]`|112|635|
|`MmusDv:0000061 [Early adulthood]`|26|191|
|`MmusDv:0000097 [Late adulthood]`|6|53|

#### Impact
After the migration, without updating the frontend:
* Deprecated filter terms in UI will have a count (and result set) of 0.
* Collections/datasets with new terms, new ancestors, or new top-level terms won't be findable via the filter.
* No frontend errors/exceptions are expected ([frontend protects against undefined `x_ancestor` arrays](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/common/queries/filter.ts#L1089)).

**Comment by brianraymor** [comment]
@metakuni @MillenniumFalconMechanic - can this be closed? Is it referenced in [Curation](https://github.com/chanzuckerberg/single-cell-curation/issues/401) issue so the information will not be lost in the interim.
