### ISSUE TITLE
Address schema migration SFN reaching max amount of execution event history (25000)

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#6541]
During schema 4.0.0 migration, the step function auto-cancelled before finishing due to reaching the max amount of execution event history (25000). This was temporarily resolved by triggering a re-run, which works functionally but messed with proper error reporting (errors from the first run were subsequently ignored in run 2 and not captured in our post-migration report--albeit, recoverable in AWS)

Look into solutions proposed by AWS [here](https://docs.aws.amazon.com/step-functions/latest/dg/bp-history-limit.html)

Note From Trent:

> The link suggest using map state or calling a separate step function.
> 
> Calling a separate step function would keep collection and datasets executions more contained but it would be spread over several step functions which would making debugging more difficult.
> 
> We are already using map state, but not in distributed mode. Switching to distributed mode requires some configuration, but appears trivial. Verifying the output and error cases will be the most important part of the work. We are mapping both collections and datasets. Mapping at either level will fix the problem. However, the number of datasets grows fast than the number of collections. Therefore distributing over the datasets would be more robust. We could implement distributed over both collections and datasets. If there is no significant downside going that route should prevent this issue from happening in the future.

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria was there exploration into simply deleting/clearing this event history? Is that not possible?

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman have not investigated if that is an option, look into it if feasible

**Comment by danieljhegeman** [comment]
We'll look to enable distributed mode.

**Comment by joyceyan** [comment]
**Changes made for dev**

I updated the IAM permissions of `dp-schema-migration-dev-policy` to include
```
,
		{
			"Effect": "Allow",
			"Action": [
				"states:DescribeExecution",
				"states:StopExecution"
			],
			"Resource": "arn:aws:states:us-west-2:699936264352:execution:stateMachineName:dp-dev-*"
		}
```

In the AWS UI, I edited the `dp-dev-devstack-schema-migration-sfn` state machine. I updated the Processing mode of `SpanCollections` and `SpanDatasets` to Distributed.
