### ISSUE TITLE
Discover should deduplicate authors within a collection

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#6558]
## Motivation
Data imported from Crossref can include duplicate authors for a paper. This is confusing to our data consumers, so duplicate authors should be removed from our collections.

Reported by @jahilton:

> [jahilton 5 hours ago](https://czi-sci.slack.com/archives/C06AVGFV222/p1705596748525349)
Martin Morgan surfaced [an issue where Discover API](https://mtmorgan.github.io/cellxgenedp/articles/b_case_studies.html#duplicate-collection-author-combinations) is reporting the same author multiple times for a Collection. This is rooted in crossref - [Tabula Sapiens Collection](https://cellxgene.cziscience.com/collections/e5f58829-1a66-40b5-a624-9046778e74f5), [crossref query](https://api.crossref.org/works/10.1126/science.abl4896), Angela Pisco is listed 4 times. 221 authors are returned, but down to 166 if you unique them.
Think the Discover API may want to filter out duplicate authors

## Definition of Done
No existing or new collections should have duplicate authors, even if Crossref's API response contains duplicate authors for a paper linked to a collection.

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

- [ ]
- [ ]

**Comment by brianraymor** [comment]
@metakuni:

1. Are there additional cases in Discover with duplicate authors? I can also send a support request to crossref to ask the journal to correct this submission. 
2. I would expect the de-duplication to occur when CELLxGENE DIscover is processing the response to the crossref query?

**Comment by metakuni** [comment]
> 1. Are there additional cases in Discover with duplicate authors? I can also send a support request to crossref to ask the journal to correct this submission.

@danieljhegeman / @joyceyan : Before you start working on this, could you find how many and which other collections have duplicate authors?

> 2. I would expect the de-duplication to occur when CELLxGENE DIscover is processing the response to the crossref query?

Definitely, I'll update the title.

**Comment by danieljhegeman** [comment]
>@danieljhegeman / @joyceyan : Before you start working on this, could you find how many and which other collections have duplicate authors?

Absolutely, will do.

Separately, I see this is currently a `P1`. Is there an interest in completing this before beginning on Schema 4.1 work?

**Comment by metakuni** [comment]
> Separately, I see this is currently a P1. Is there an interest in completing this before beginning on Schema 4.1 work?

Nope, not necessarily, unless @brianraymor or @jahilton think so.

**Comment by jahilton** [comment]
No urgency on this from my viewpoint

**Comment by brianraymor** [comment]
It's a P2 from my perspective since the mitigation is that the consumer can de-duplicate as needed in the interim.

**Comment by danieljhegeman** [comment]
Ack 👍 

Wrt prevalence:
```
51544e44-293b-4c2b-8c26-560678423380 Multiomics single-cell analysis of human pancreatic islets reveals novel cellular states in health and type 1 diabetes
e5f58829-1a66-40b5-a624-9046778e74f5 Tabula Sapiens
```

and then also one private Collection.

**Comment by MillenniumFalconMechanic** [comment]
Hi @brianraymor, can you confirm the de-dupe algorithm is on _exact_ matches on `given` and `family` values returned from Crossref? (See [provider](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fran/6483-mim-test/backend/layers/thirdparty/crossref_provider.py#L127).)

**Comment by brianraymor** [comment]
> can you confirm the de-dupe algorithm is on exact matches 

Yes. When I was assessing the overall state of authors in crossref in 2023, I did note that the code failed to "normalize" names (like removing diacriticals or unicode characters), but that's outside the scope for this issue which is a band-aid.
