### ISSUE TITLE
Investigate spatial data on DP why not coordinates don't align with image

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#6578]
1. @ebezzi pointed out that quite a few spatial data coordinates are not aligned with their corresponding images. So we might need to find an image registration process to align the dots with the image, and propose a revision for the uploader to review. Otherwise the dots won't be aligned when we use the original dataset
2. @ebezzi said that we should be able to write a script to check which datasets don't have aligned dots
3. @niknak33 to scope the project properly, perhaps we could premark datasets that have misaligned dots and disable image feature for them?

NOTES:
1. Inform Lattice and @brianraymor on progress and solution to save Lattice team time ⏰ 👏

**Comment by brianraymor** [comment]
@jahilton and @jychien - this is the issue that I referenced on our call today. @tihuan - Lattice has a lot of experience with this problem and it can require serious manual QA effort on their part. They'd love to see this automated. 

Also, something I shared earlier with @sidneymbell on #cell-science-modalities:

> You might take this with a grain of salt because I'm only browsing (and it's R), but https://themilolab.github.io/SPATA2/articles/spata-v2-image-handling.html#applying-transformation-of-images sounds promising?

**Comment by tihuan** [comment]
Thanks @brianraymor ! Perfect 😄 Glad to know that if we can solve this problem it will save us a lot more manual time for the Lattice team 🔥 Will keep everyone posted!

Thanks for the research there too, will look into it 🤩 !

**Comment by jychien** [comment]
Thank you! Yes, there are a number of datasets with lots of images which required manually plotting and checking visually that they lined up. Would be wonderful if there could be a way to automate checking that the spot align with tissue.

Was curious, @ebezzi, do you have an example of Visium dataset not lining up in the portal? Since the Visium schema was in flux at the time, we ended up wrangling adata.uns['image'] to match adata.obsm['X_spatial']. Most of them should also have scaling factors in adata.uns, as well. And in case these are the datasets that you are looking into: https://github.com/chanzuckerberg/single-cell-curation/issues/676. (One collection has X/Y mixed up and the other could not determine how they scaled the X/Y coordinates).

**Comment by tihuan** [comment]
In the kickoff meeting it sounds like we have spatial data in DP, but they're not conformed with schema 4.2 yet, so @sidneymbell and @niknak33 will provide us datasets that conform schema 4.2 for the eng team to develop the feature!

**Comment by ebezzi** [comment]
> Thank you! Yes, there are a number of datasets with lots of images which required manually plotting and checking visually that they lined up. Would be wonderful if there could be a way to automate checking that the spot align with tissue.
> 
> Was curious, @ebezzi, do you have an example of Visium dataset not lining up in the portal? Since the Visium schema was in flux at the time, we ended up wrangling adata.uns['image'] to match adata.obsm['X_spatial']. Most of them should also have scaling factors in adata.uns, as well. And in case these are the datasets that you are looking into: [chanzuckerberg/single-cell-curation#676](https://github.com/chanzuckerberg/single-cell-curation/issues/676). (One collection has X/Y mixed up and the other could not determine how they scaled the X/Y coordinates).

Those were datasets that were available ~2.5 years ago. I can't remember if they were part of the DP or not. Anyway my recommendation is to run some analysis from scratch as my assumptions could now be outdated.

**Comment by brianraymor** [comment]
See [Add requirements for Visium Spatial Gene Expression assay](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/674) for details on the proposed dataset schema. The primary difference with the existing +100 visium datasets in CELLxGENE is that the spatial embedding will not be scaled so one embedding can be associated with multiple overlay images (full, high, low) and their corresponding scalefactors.

**Comment by kaloster** [comment]
After discussing with the team @jychien @ebezzi @tihuan - it was decided to attach the script that validates the spatial dots overlapping with the image and close this for now.

The script attached will traverse through an array of dataset names, identify the background color of the image, then check if the dots overlap the rgb data. The script will then return the percentage of points overlapping the image which can be used to make an assumption if the image overlaps or not.

<img width="977" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc28b3753ce59d69b0ef7ea81915a943abfa330d/Screenshot%202024-01-31%20at%203.42.21%E2%80%AFPM.png" alt="Screenshot 2024-01-31 at 3.42.21 PM.png" />
[spatial_overlap_validation.ipynb.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b5526c8dd062111e083d8e113139557ee46194e/spatial_overlap_validation.ipynb.zip)

**Comment by tihuan** [comment]
Thanks so much for the awesome solution and investigation, Ronen! We'll pick it up in Q2 🔥
