### ISSUE TITLE
Review and update schema references (4.0.0 -> 5.0.0) 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6629]
There are many references to the schema specification or its sections that must be reviewed for potential updates. In most cases, this will be a simple change - replacing "4.0.0" with "5.0.0".

For example, [search for 4.0.0 references](https://github.com/search?q=repo%3Achanzuckerberg%2Fsingle-cell-data-portal%204.0.0&type=code).

**Comment by joyceyan** [comment]
This change is feature ready but we're going to hold off on merging this until we're ready to actually deploy the change.

**Comment by danieljhegeman** [comment]
Deployed to prod last week
