### ISSUE TITLE
Download of RDS is unsatisfying

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6631]
Reported by @NoopDog :

The [RDS dataset download](https://datasets.cellxgene.cziscience.com/d0bbb292-7b5d-4f49-b3d8-046bc32a444c.rds) for the dataset in [Human developing neocortex by area](https://cellxgene.cziscience.com/collections/c8565c6a-01a1-435b-a549-f11b452a83a8) returns:

```
ERROR
The request could not be satisfied.
```

**Comment by danieljhegeman** [comment]
This particular asset file is large, just over 50 gb. I was able to download the asset via `aws s3 cp`. Confirmed unable to download via Cloudfront permalink. Same error for the `.rds` asset for previous versions of that dataset (which are the same size, roughly).

**Comment by danieljhegeman** [comment]
[A total bummer](https://aws.amazon.com/cloudfront/faqs/#:~:text=Q%3A%20What%20is,Amazon%20CloudFront%20distributions.)

**Comment by brianraymor** [comment]
Nice research and ... **yikes**.

**Comment by danieljhegeman** [comment]
I have one possible workaround to offer: we insert Lambda@Edge. In the lambda we:
- detect requests for files that are large
- instead of attempting to fulfill that request, we construct a presigned s3 url in real time, and we then redirect the original request to the presigned s3 url

**Comment by brianraymor** [comment]
Hmm - https://datasets.cellxgene.cziscience.com/788e2ad7-dca6-415a-b0f4-54bc968ff8db.h5ad is 35.2 GB and is now downloading.

**Comment by danieljhegeman** [comment]
I'll call the CloudFront Police.

**Comment by danieljhegeman** [comment]
Possible that they merely guarantee that all files < 30 gb will be served, while those larger may or may not get served.

**Comment by metakuni** [comment]
Downgrading to a P2 for now since the blast radius is very small. We'll revisit after getting some guidance from AWS Support and/or after work on schema 5.0 has been completed.
