### ISSUE TITLE
Gene Expression Source Data lacking "total number of cells"

### ISSUE THREAD

**Issue by sunhuaiyu** [chanzuckerberg/single-cell-data-portal#6655]
In the "Gene Expression Source Data" page under "Help & Documentation", the two data sets for download (expression-summary-full, expression-summary-condensed) are both missing "total number of cells", even though the page claims that "full dataset contains the summed expression, number of cells with nonzero expression, and total number of cells for all possible combinations of metadata ... "

Here are columns in the "expression-summary-full" table: 
    pyarrow.Table
    : int64
    gene_ontology_term_id: string
    tissue_ontology_term_id: string
    organism_ontology_term_id: string
    cell_type_ontology_term_id: string
    tissue_original_ontology_term_id: string
    dataset_id: string
    assay_ontology_term_id: string
    development_stage_ontology_term_id: string
    disease_ontology_term_id: string
    self_reported_ethnicity_ontology_term_id: string
    sex_ontology_term_id: string
    publication_citation: string
    nnz: int64
    sum: double

**Comment by sunhuaiyu** [comment]
It would also be helpful if the column names are consistent with metadata column names in Census. For example, here in "expression-summary-full" we have "tissue_ontology_term_id" and "tissue_original_ontology_term_id". However in "obs" (Cell metadata) of "census_data", the tissue level ontology term id columns are "tissue_general_ontology_term_id" and "tissue_ontology_term_id". It's not clear how the two pairs of column names are matched.

**Comment by MaximilianLombardo** [comment]
Hey @sunhuaiyu regarding your first comment our engineering team has noted similar issues from other users and is working to implement a fix.

W.r.t. your second comment, the discrepancy between columns has been noted and the feedback has been forwarded to the appropriate teams, thanks for flagging.

**Comment by sunhuaiyu** [comment]
Appreciate the follow up

On Feb 15, 2024, at 8:10 AM, MaximilianLombardo ***@***.***> wrote:



Hey @sunhuaiyu<https://github.com/sunhuaiyu> regarding your first comment our engineering team has noted similar issues from other users and is working to implement a fix.

W.r.t. your second comment, the discrepancy between columns has been noted and the feedback has been forwarded to the appropriate teams, thanks for flagging.

**Comment by sunhuaiyu** [comment]
Would you please include "assay_ontology_term_id" in you current release? Or is current result already filtered for assays that allow cptt normalization? Thank you!

**Comment by atarashansky** [comment]
Assays not included in Gene Expression are already filtered out!
