### ISSUE TITLE
CELLxGENE schema update impacts Cell Guide and GE

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6657]
The cell type “Native cell” (CL:0000003) will be deprecated in the coming 4.1 schema, and **it will be replaced by “unknown” for both** `cell_type` and `cell_type_ontology_term_id`

It is theorized that this might break Cell Guide and GE depending on where the filtering for native cell takes place.

Furthermore - Based on the census call and the subsequent conversation in https://czi-sci.slack.com/archives/C0247APK621/p1707769564679499, there was agreement to treat the new "unknown" value for cell type as a breaking change. Dataset schema 4.1.0 (in development) is now 5.0.0. Census schema is being updated to 2.0.0.

**Comment by niknak33** [comment]
For Data Apps team to begin work, we are blocked on the delivery of the schema work.

**Comment by brianraymor** [comment]
Isn't Applications waiting on a **census build** that includes schema 5.0 for testing?
