### ISSUE TITLE
Cell Guide Biocurator Final Request and Questions

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6660]
After speaking to the curation team, they have some final requests to wrap up their work with descriptions:

1. Discrepancies between cell types in [CellCardDescriptions](https://docs.google.com/spreadsheets/d/1HOeyfPbv_ncJrgNP5kkYdJZYZuMUkDoqpoqPVKgQcgc/edit#gid=1294147951) and in Cell Guide

E.g. “Experimentally modified cell in vitro” in the spreadsheet is no longer listed in the Cell Guide

→ we (biocurator team) need an updated list for curation. 
→ we (CELLxGENE team) need to provide a list of remaining cell types based in the [CellCardDescriptions](https://docs.google.com/spreadsheets/d/1HOeyfPbv_ncJrgNP5kkYdJZYZuMUkDoqpoqPVKgQcgc/edit#gid=1294147951) sheet

2. For some cell types, there is a specific subtype “human”. This seems very inconsistent - not clear why these subtypes exist for some, but not other cell types
E.g. Dendritic cell, human (CL:0001056) 

→ should the “human” subtypes be curated? 

Some cell types seem redundant - e.g. abnormal cell only has one child term (neoplastic cell). Keep both? (abnormal cell could also include dysplasia, senescent cells etc. but these are not listed.
→ should the biocurator team flag all cell types that seem redundant for someone to review?
 Or just curated them anyway - with near-identical descriptions?

**Comment by niknak33** [comment]
1. Alec to work on these
2. Can use near-identical descriptions for now.
3. We can leave those terms experimental for now, we would use that as a flag to review.

**Comment by atarashansky** [comment]
@niknak33 I think I completed this with you in Slack DMs, but if not please re-open.
