### ISSUE TITLE
Analytics (update/new): <Spatial Mode FE - User Story 1> 

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6667]
### Overview

**Tool**: `<Explorer>`
Feature: `<Dropdown selection for type of embedding>`

**Description**: `<Track the number of the users that switch from UMAP to Spatial embedding view>`
- Current: `<We currently have a selection of embeddings, spatial would be new>`
- Requested change: `<Allow for tracking for Spatial embedding view, the new change is the addition of Spatial in the dropdown menu>`

### Updates needed
rename `EXPLORER_LAYOUT_CHOICE_BUTTON_CLICKED` to `EXPLORER_EMBEDDING_CLICKED`
- visitor clicked the embedding button in the top left of the explorer view window

### New events needed
`EXPLORER_EMBEDDING_SELECTED`: `{embedding: ‘embedding type selected’}`
- visitor selected an embedding from the drop down menu

### Events to remove
`EXPLORER_LAYOUT_CHOICE_CHANGE_ITEM_CLICKED`

Checklist

- [ ] Once event updates are deployed to Staging ping @ainfeld to check analytics
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once event updates are deployed to Prod ping @ainfeld
- [ ] Confirm Plausible events are still showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @niknak33 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by tihuan** [comment]
@niknak33 I linked this one to the deep zoom analytics epic already 🙌 Thank you!

**Comment by ainfeld** [comment]
@tihuan @kaloster I made a small update to the ticket to just remove the `EXPLORER_LAYOUT_CHOICE_CHANGE_ITEM_CLICKED` event

**Comment by tihuan** [comment]
Sounds good 👍 Thanks Amanda!!
