### ISSUE TITLE
Citations in RDS datasets incorrectly reference H5AD dataset versions

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6671]
# Context

I was examining RDS datasets in RStudio and noted that the citation references the H5AD dataset version and not the RDS dataset version:

cellxgene@misc[["citation"]]
[1] "Publication: https://doi.org/10.1126/sciadv.adh1914 Dataset Version: **https://datasets.cellxgene.cziscience.com/188dfb70-dd81-44ec-a8fd-648d54cb7b5e.h5ad** curated and distributed by CZ CELLxGENE Discover in Collection: https://cellxgene.cziscience.com/collections/8c4bcf0d-b4df-45c7-888c-74fb0013e9e7"

See the requirements and RDS example in [citation](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#citation).

**Comment by danieljhegeman** [comment]
Brainstorming initial solution idea, which is slightly hacky, but would get the job done: base the rds conversion off of an h5ad file that has the _rds-version citation_ in it.

**Comment by joyceyan** [comment]
Conversion to RDS is here: https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/layers/processing/make_seurat.R#L16
It uses the sceasy package: https://github.com/cellgeni/sceasy
Which will will eventually want to remove in 5.1: https://github.com/chanzuckerberg/single-cell-data-portal/issues/6672
