### ISSUE TITLE
Remove dependency on sceasy for AnnData->Seurat conversion

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#6672]
## Motivation

Also review the potential of [schard](https://github.com/cellgeni/schard) as a replacement for Seurat conversions. It is reticulate-free and builds on BIoconductor [rhdf5](https://bioconductor.org/packages/release/bioc/html/rhdf5.html). 

---

Currently, we depend on [sceasy](https://github.com/cellgeni/sceasy) for AnnData -> Seurat conversion:

https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/layers/processing/make_seurat.R#L16

Since [sceasy development appears to have been inactive for ~1.5 years](https://github.com/cellgeni/sceasy/commits/master/), the conversion code should be imported into our repository and unit tests should be added.

Seurat conversion bugs could have been avoided with basic unit tests. Examples:
* https://github.com/chanzuckerberg/single-cell-data-portal/issues/939
* https://github.com/chanzuckerberg/single-cell-data-portal/issues/6671

Upcoming dataset schema changes will also include changes that should be covered by Seurat conversion unit tests. (e.g. spatial data)

## Definition of Done
* AnnData -> Seurat conversion code lives in this repo (remove dependency on sceasy)
* Unit tests added for Seurat conversion that cover the [Seurat encoding for the current dataset schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/seurat_encoding.md)
* [Deprecated dependencies](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/Dockerfile.processing_base#L26-L32) are removed from `Dockerfile.processing_base`

**Comment by Bento007** [comment]
@metakuni since dataset with spacial will not use seurat conversion is this still a P0?

**Comment by Bento007** [comment]
suggest by @danieljhegeman 
> Are we considering allocating time to overhaul our seurat pipeline, perhaps by getting away from R and writing seurat files using something like [this](https://github.com/ofajardo/pyreadr)?

**Comment by Bento007** [comment]
another reticulate bases [R library](https://cran.r-project.org/web/packages/anndata/readme/README.html) for reading anndata

**Comment by Bento007** [comment]
schard is still early stage development and doesn't have a version out yet we can lock too. This increase the potential for it break from under us. Here is an example of how we can convert an h5ad to seurat using schard.
```
install.packages('devtools')
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("rhdf5")
devtools::install_github("cellgeni/schard")
# load h5ad as Seurat
converted = schard::h5ad2seurat('/example_valid.h5ad')
saveRDS(converted, './example_valid.rds')\
```

**Comment by Bento007** [comment]
[testthat](https://testthat.r-lib.org/) can be used for testing

**Comment by metakuni** [comment]
Deprioritizing this until further notice.
