### ISSUE TITLE
CXG conversion should enforce that the var dataframe generates columns with "name_X"

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell-data-portal#6695]
In the genecode dry run script: https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/schema_bump_dry_run_genes/gene_bump_dry_run.py#L78-L90 we assume that all gene names are stored in columns in the var dataframe with the pattern `name_X` (ex: "name_0", "name_1", etc).

However, in the CXG conversion code: https://github.com/chanzuckerberg/single-cell-data-portal/blob/9fe1a2550c5a571fdce55f708bd337e09435380b/backend/layers/processing/h5ad_data_file.py#L216-L225 we don't actually enforce this. The issue we had with dataset b2dda353-0c96-42df-8dcd-1ea7429a6feb in collection 1b014f39-f202-45ae-bb7d-9286bddd8d8b was that the var dataframe already had an index specified with name `ensg_id`, which was also a column in the var dataframe. This meant that we never entered the block of code that calls `convert_index_to_column()`.

There isn't anything technically wrong with how the CXG conversion code is behaving. The expectation of `transform_dataframe_index_into_column` is to ensure that there is an index on the var dataframe that is also a column. However, since it's a bit easier for us to assume that gene names being used are stored in var dataframe columns following the same naming convention (and there may be other downstream places that make this assumption), it seems better to just update the CXG conversion code to adhere to what we expect in the genecode dry run script, rather than alter the genecode dry run script to search through the var dataframe's index name.

Steps to verify this works as expected would be to:
1. Update CXG conversion code and deploy to dev/staging/prod
2. Create a new revision for `b2dda353-0c96-42df-8dcd-1ea7429a6feb` that goes through the new CXG conversion code
3. Re-run the gencode dry run script

**Comment by metakuni** [comment]
Closing this for now since a link to this issue has been created here:
* https://github.com/chanzuckerberg/single-cell-curation/pull/783/files
