### ISSUE TITLE
Fix disease auto expand e2e test

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell-data-portal#6706]
<img width="1497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ecfb694c446a80c1d3efefd5de806a58efd53d3/image.png" alt="image.png" />

This e2e test is failing. The current expectation is that:
1. We expand 3 tissues: axilla, blood and brain
2. We select "influenza" from the disease filter
3. After incorporating the disease filter, only blood should remain filtered since that is the only tissue type that contains influenza cells
4. Select "B cell" from the cell type filter
5. After incorporating the cell type filter, only blood should remain filtered since that is the only tissue type that contains influenza B cells
6. Remove the "B cell" cell type filter
7. After removing the cell type filter, only blood should remain filtered since that is the only tissue type that contains influenza cells

The problem is that it appears we now have influenza brain cells in our corpus. So the test should be updated with the following expectations:
1. We expand 3 tissues: axilla, blood and brain
2. We select "influenza" from the disease filter
3. After incorporating the disease filter, only blood _and brain_ should remain filtered since that is the only tissue type that contains influenza cells
4. Select "B cell" from the cell type filter
5. After incorporating the cell type filter, only blood should remain filtered since that is the only tissue type that contains influenza B cells
6. Remove the "B cell" cell type filter
7. After removing the cell type filter, only blood _and brain_ should remain filtered since that is the only tissue type that contains influenza cells

**Comment by tihuan** [comment]
Thanks so much for the well documented ticket, Joyce 🔥 You rock!!
