### ISSUE TITLE
Disable RDS conversion for Visium Spatial Gene Expression datasets

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6752]
# Context

**DRAFTING**

This decision has been reviewed with @ambrosejcarr and @pablo-gar.

See [**internal rationale**](https://czi-sci.slack.com/archives/C02SP5AV7PV/p1708719500889799?thread_ts=1708709851.860369&cid=C02SP5AV7PV).

# Design

Currently, there are ~24 datasets without RDS downloads due to limitations in the R dgCMatrix sparse matrix class. When a RDS artifact is not returned in the DP API, the Download UX disables the RDS option and sets [a tooltip](https://github.com/chanzuckerberg/single-cell-data-portal/blob/63f44bc4fcbc3398e0c3cfe50dc36f18c4852031/frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/constants.ts#L10) to  ".rds (Seurat v5) is unavailable due to limitations in the R dgCMatrix sparse matrix class."

This issue would create a second case. Depending on development costs, options could be:
1. Track the different reasons for a missing RDS download and display different tooltips.
2. Simply change the existing tooltip to ".rds (Seurat v5) is unavailable." with no explanation.

**May 8**: Confirmed option `2`.  It can be implicitly assumed that if the assay is not visium, then the missing RDS is due to the dgCMatrix issue. 

@jahilton suggested that it will be helpful to R users if there was messaging related to using census. This is definitely excellent guidance for the longer term, but currently census does not support spatial and per Trent's comment, census does not consume all datasets in the corpus.

**Comment by MillenniumFalconMechanic** [comment]
#### Estimated Efforts for Option 1

**1. FE Only**
- Calculate messaging on FE only, using assay ontology term ID and dataset assets file types.
- Effort required: one day

**2. Calculate on BE**
- Calculate messaging on BE and update /assets response shape to include messaging.
- Update FE to use returned messaging.
- Effort required: two days

**3. Store Flags in DB on Ingest**
- Add flags to DB.
- Use flags to determine messaging, and update /assets response shape to include messaging.
- Effort required: three days

**Comment by Bento007** [comment]
do any of these optional rely on https://github.com/chanzuckerberg/single-cell-data-portal/issues/6753?

**Comment by Bento007** [comment]
I like 1, because if we ever do start supporting spatial for RDS then undoing this will be really easy. I don't think there are any other scenarios where the assay ontology id would be a spatial, with no RDS file.

**Comment by nayib-jose-gloria** [comment]
@Bento007 Only Visium-assay datasets are blocked from rds conversion (Slide-Seq-v2 is spatial as well but not blocked) so we'd use an assay_ontology_term_id check rather than anything added by #6753

**Comment by nayib-jose-gloria** [comment]
Agree that option 1 seems reasonable. Looking forward, we may want to do option 2 to be flexible for new, more complicated cases of rds conversion being skipped. But we can punt on that since its a hypothetical.
