### ISSUE TITLE
Add uns['spatial'] metadata to the Discover API

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6753]
# Design

**DRAFTING**

```JSON
"spatial": {
    "is_single": boolean
    "has_fullres": boolean,
}
```

See references:
[`is_single`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/schema.md#is_single)
[`has_fullres`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/schema.md#spatiallibrary_idimagesfullres) - `true` if the optional `uns['spatial'][library_id]['images']['fullres']` is present and `false` if not. 

**[GET /collections/{collection_id}](https://api.cellxgene.cziscience.com/curation/ui/#/Collection/backend.curation.api.v1.curation.collections.collection_id.actions.get)**

MUST be added to each dataset in `datasets`

**[GET /collections/{collection_id}/datasets/{dataset_id}](https://api.cellxgene.cziscience.com/curation/ui/#/Collection/backend.curation.api.v1.curation.collections.collection_id.datasets.dataset_id.actions.get)**

MUST be added

**Comment by Bento007** [comment]
This will require updating the portal database with the new fields and updating the processing container to extract the spatial fields from the dataset.

**Comment by nayib-jose-gloria** [comment]
@brianraymor For non-spatial datasets, should this field be excluded from the response? Or should we always include, and add an 'is_spatial' flag to this set of values? i.e. 
```
"spatial": {
    "is_spatial": boolean,
    "is_single": boolean
    "has_fullres": boolean,
}
```

**Comment by atolopko-czi** [comment]
Primarily, I would stick with whatever pattern is currently in use wrt indicating optional data. 

But without that as a consideration, I would go with:
```
"spatial": {
    "is_single": boolean
    "has_fullres": boolean,
}
```
and
```
"spatial": null
```
