### ISSUE TITLE
Data Migration should not perform a RDS conversion for a published dataset without a RDS download

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6754]
# Context

**DRAFTING**

See [**cell-science-platform**](https://czi-sci.slack.com/archives/C06AVGFV222/p1709506643202369?thread_ts=1709343841.746689&cid=C06AVGFV222). 

If a published dataset does not have a RDS conversion, then data migration should not attempt to perform a RDS conversion in a brute force manner that will simply fail again - wasting time and resources. 

Also see [Disable RDS conversion for Visium Spatial Gene Expression datasets](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6752).

**Comment by Bento007** [comment]
Do we think this will require changes to the database. If so we might want to group all issues with database changes into one to avoid doing multiple migrations.

**Comment by danieljhegeman** [comment]
Right now we have less than a half dozen files that do not have RDS assets and which were not explicitly `SKIPPED` due to the R matrix size limitation (in which case RDS processing will similarly be skipped during schema migration), so deprioritizing this as being of only trivial utility for the time being

**Comment by brianraymor** [comment]
>so deprioritizing this as being of only trivial utility for the time being

I'd prefer to discuss before simply deprioritizing as "trivial". 

It depends on how we're implementing the logic for [Disable RDS conversion for Visium Spatial Gene Expression datasets](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6752). True, there are ~24 datasets today, but in 5.1.0 there will be +161 (and counting) Visium datasets without RDS downloads. I don't know why we couldn't combine the checks for Visium and maybe an API call to check for a RDS asset for other assays. It seems silly/inelegant to waste time/resources on conversions that we know will fail every time if the implementation cost is low. CC: @metakuni

**Comment by danieljhegeman** [comment]
I agree it is more desirable to have a solution here than to not, but including it as requisite work for delivering 5.1 strikes me as _pennywise_.

**Comment by brianraymor** [comment]
Again, I'm only seeking a conversation. If the cost is too high for the benefits, then I'd agree. I've seen zero costing or proposals. It doesn't seem particularly hard to make an API call to check for an existing RDS asset as an alternative to DB changes for example.

**Comment by danieljhegeman** [comment]
API call yes but it will also require some additional configurations to get the correct dataset version id to use for that API call, as it is different than the (only) dataset version id that the seurat logic has access to at the moment, i.e updates to step function definitions in tf. I would say it is still fairly simple, but, apropos of prioritization, it would probably help if you could specify the _Product_ impact that getting this done as part of 5.1 will have. 

I'm all for this optimization when we (engineers) are addressing other aspects of _Engineering_ tidiness.

**Comment by nayib-jose-gloria** [comment]
@Bento007 @brianraymor The change described [here](https://github.com/chanzuckerberg/single-cell-curation/issues/827#issuecomment-2067103789) will allow us to skip visium dataset rds conversion attempts during migrations without further code changes, as we already check for this flag before trying an rds conversion both during regular ingestion and a migration. This flag is also used to determine if we can skip rds conversion attempts (ingestion and migration) when the validator detects that the dataset matrix exceeds size limitations in the R dgCMatrix sparse matrix class.

If any other cases pop up of datasets failing seurat conversion during migration and we decide we're ok with skipping, we should write an issue to update the validator to also mark this new failure case as skippable in the CLI.

Unless there's another rds skip scenario I'm missing here, I think we can close this issue.

**Comment by nayib-jose-gloria** [comment]
Closing, please re-open if note above is not sufficiently covering intent of the issue.
