### ISSUE TITLE
Add retry on dropbox or container failures

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#685]
# Need

If a download fails, retry the download at a later time. This could be caused by the container or dropbox.

# Approach

- Use the step function logic to retry the upload with an exponential back off. Cap the number of retries to 5. The starting backoff time is 10 seconds.
- The container must return a response that the step function can interpret as a retryable event.
- The upload_status is changed to waiting if waiting for the retry
- After retires are exhausted the step function runs the cleanup handler.  
- Retryable errors
  - Cloud provider exceeded daily bandwidth limit
  - The container timed out
  - The download did not match the source hash.
  - Any transient error related to AWS infra.

# DoD
- Downloads from the cloud storage provider are retried if they fail.
- After retries are exhausted the upload_status is set to failed.

**Comment by tihuan** [comment]
Quick question! For `Cloud provider exceeded daily bandwidth limit`, should we just transition `upload_status` to `failed`?

Another question is whether this ticket has a blocker? E.g., the container is created in a different ticket, etc.

Thank you!

**Comment by brianraymor** [comment]
During November 10 Refinement, we agreed to address this issue **after** the basic functionality was in place.

**Comment by brianraymor** [comment]
Closing per January 5th refinement.

**Comment by Bento007** [comment]
We are seeing 500 errors from dropbox on occasion when downloading files. I think the best course of action is to add some retry logic where we are downloading the file from dropbox. We use requests which has `requests.adapter.HTTPAdapter` that allows us to specify a retry strategy. Example from [here](https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/)
```python
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

retry_strategy = Retry(
    total=5,
    status_forcelist=[429, 500, 502, 503, 504],
    method_whitelist=["HEAD", "GET", "OPTIONS"],
    backoff=2
)
adapter = HTTPAdapter(max_retries=retry_strategy)
http = requests.Session()
http.mount("https://", adapter)
http.mount("http://", adapter)

response = http.get("https://en.wikipedia.org/w/api.php")
```

Dropbox also has a retry-after header, but it appears this is only used for dropbox apps. More investigating is needed to see if we must follow this.

**Comment by tihuan** [comment]
@Bento007 Thanks for the investigation 🙏 !

@brianraymor @maniarathi what's the priority of this? And I suppose we should tag this issue as a `design me`? 

Thanks all!

**Comment by brianraymor** [comment]
I have an agenda item for the curator call tomorrow morning to understand more about the curation work flow. For example, are we expecting a series of *curate dataset-uploads* or one big *curate X 42 datasets-near simultaneous uploads* (Pablo's case). We also do not have a good sense for average datasets per collection. 

I suggest that the **investigation** should continue since there are open questions about `retry-after` for example. Arathi and I would need to understand more about the final costs.

Is our implementation using this dropbox API - https://www.dropbox.com/developers/documentation/http/documentation ?

**Comment by tihuan** [comment]
Sounds good!

I just checked our BE code, it seems like we're not using their `api.dropbox.com` API, just the share link directly. E.g., https://www.dropbox.com/s/jz6fd5e4rdhx68a/20mb.h5ad?dl=1

<img width="713" alt="Screen Shot 2021-03-15 at 1 00 05 PM" src="https://user-images.githubusercontent.com/6309723/111213797-661da080-858e-11eb-86b2-4a2aac8b045b.png">

**Comment by brianraymor** [comment]
Also - as @tihuan has noted in [**eng**](https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1615429137201800?thread_ts=1615418937.199400&cid=C01CPJURT0S) - another approach is to allow _multiselect_, but have the portal BE rate limit the FE. There are definitely multiple options/combinations to explore.

**Comment by metakuni** [comment]
Retries of failed downloads from Dropbox will be addressed by the new decomposed step function. It is currently configured to retry twice, but that can easily be changed if we see more frequent errors.

Closing this story and will open a new one if any issues with download retries arise.
