### ISSUE TITLE
Opacity for Spatial Images

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6867]
User Story:

As a researcher, I want the ability to adjust the opacity for spatial images so I can control the opacity and allow me to visualize certain regions of the tissue if the original image quality is poor.

**Comment by tihuan** [comment]
@niknak33 updated wording to `opacity` !

**Comment by niknak33** [comment]
Thank you @tihuan

**Comment by tihuan** [comment]
Done!
