### ISSUE TITLE
Adjustable Spot Transparency

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6868]
User Story:

As a researcher analyzing spatial images, I need the ability to adjust the transparency of spots within my visualizations so that I can fine-tune the overlay of molecular data on histological tissue images. This capability will help me to better distinguish between high-density gene expression areas and the underlying tissue regions, facilitating a more nuanced interpretation of how gene expression correlates with tissue morphology.

Designs - https://www.figma.com/design/eJ3acPxG04PKVlom6eS8ft/Spatial?node-id=887-113907&t=uXCQmDp4z62Xsmbg-1

**Comment by tihuan** [comment]
Done!
