### ISSUE TITLE
Review and update schema references (5.0.0 -> 5.1.0)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#6877]
There are many references to the schema specification and/or its sections that must be reviewed for potential updates. In most cases, this will be a simple change - replacing "5.0.0" with "5.1.0".

For example, [search for 5.0.0 references](https://github.com/search?q=repo%3Achanzuckerberg%2Fsingle-cell-data-portal%205.0.0&type=code).

Ensure that the following are updated:

1. [Discover API](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/curation/api/curation-api.yml)
2. [Contribute and Publish](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/doc-site/032__Contribute%20and%20Publish%20Data.mdx)
3. [Download UX Modal](https://github.com/chanzuckerberg/single-cell-data-portal/blob/83383dea8103b2d9c33b6d8ca4c42cde15ea8d27/frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DownloadLink/components/CopyCaption/index.tsx#L6-L8)

**Comment by Bento007** [comment]
complete
