### ISSUE TITLE
Generate a new S3 bucket for deep zooming

### ISSUE THREAD

**Issue by kaloster** [chanzuckerberg/single-cell-data-portal#6915]
1. Decide on bucket location and naming convention
2. Adjust terraform/infra to generate new bucket
3. Make sure permissions are in line with required application access

DoD:
Bucket is generated with the correct permission

**Comment by kaloster** [comment]
reference: https://github.com/chanzuckerberg/single-cell-explorer/pull/879

**Comment by tihuan** [comment]
@kaloster I think this is done? Thank you! CC: @ebezzi

**Comment by tihuan** [comment]
I think we just need to create the S3 bucket for prod now IIRC

**Comment by ebezzi** [comment]
@tihuan The bucket has been created on all 3 envs. We can close this ticket.

**Comment by tihuan** [comment]
Really appreciate your help, Emanuele 😍🙏 Closing!
