### ISSUE TITLE
Migration SFN is not robust to mid-run deployments

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#6918]
At present, a single invocation of the schema migration SFN is not robust to deployments that occur while the step function is running. One or more task definitions that the step function depends on will be expired / rendered no longer active. It might be worthwhile determining how to make sure task definitions are not immediately expired if they are updated in order to prevent the SFN run from being disrupted. This would allow us to continue to deploy as normal when schema migrations are running.

**Comment by metakuni** [comment]
@nayib-jose-gloria / @Bento007 : Moved this over to epic #544 for your consideration. Please close if not relevant.

**Comment by Bento007** [comment]
Now that we can freeze deployment and plan to move to a different migration paradigm, this work is not worth the effort.
