### ISSUE TITLE
Analytics (update): <User Story 3: Gene Expression and Diff Exp > 

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#7059]
### Overview

**Tool**: `<Explorer>`
Feature: `<Gene Expression and Differential features within Explorer>`

**Description**: `<We are launching the ability for users to view/analyze Visium datasets, users would also like to perform Gene Expression and Differential Expression on the Spatial images/datasets available. We want to track the number of users who perform GE and DE on spatial datasets.>`

### Updates needed

`<Event name>`

- Current: `<Gene Expression and Differential Expression buttons are currently available on any embedding within Explorer>`
- Requested change: `<Ensure, Gene Expression and Differential Expression buttons are tracked for analytics for spatial datasets as well>`

Checklist

- [ ] Once event updates are deployed to Staging ping @ainfeld to check analytics
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once event updates are deployed to Prod ping @ainfeld
- [ ] Confirm Plausible events are still showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @niknak33 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by ainfeld** [comment]
Closing this out as these will be wrapped into the general explorer analytics updates given the new definition of engagement
