### ISSUE TITLE
Implement edit dataset frontend component

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#7061]
#### Approach
- Implement edit dataset from edit collection page ([dialog](https://www.figma.com/design/jEv0ZWQd0Q53aFl9nNRbBy/Portal?node-id=1250-8974&t=QpSmEdPyvZfHUtVq-0), [modal](https://www.figma.com/design/jEv0ZWQd0Q53aFl9nNRbBy/Portal?node-id=1250-9546&t=QpSmEdPyvZfHUtVq-0), [error](https://www.figma.com/design/jEv0ZWQd0Q53aFl9nNRbBy/Portal?node-id=1380-1935&t=QpSmEdPyvZfHUtVq-0)).
  - Track changes in title and trigger PATCH of any updates on click on save.
  - Confirm invalidation of cache after click on save.
- Add unit tests of update functionality.
- Add E2E tests to existing revision-related tests to cover edit dataset title.

**Comment by MillenniumFalconMechanic** [comment]
This will take approximately four weeks to complete. We expect the core functionality to be completed within three weeks, with a fourth week allowing for E2E tests.
