### ISSUE TITLE
Analytics (new): <Side-by-Side Embedding>

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#7085]
### Overview

**Tool**: `<Explorer>`

- Feature: `<New Embedding view selector, and new embedding card>`

**Description**: `<We are launching a new modality, called Spatial, this new feature called Side-By-Side will allow users to visually compare different embeddings within that dataset.>`
**Expectations**: `<We expect the majority of spatial dataset users to use the side-by-side embedding, the two areas of convergence are selecting the side-by-side embedding feature, and also interacting with the new embedding card>`

### New events to add

`EXPLORER_SBS_SELECTED`: `{embedding: ‘embedding type selected’}`
- visitor clicked the "side-by-side" button

`EXPLORER_SBS_SWAPPED`: `{main_embedding: 'embedding type selected in the main window when visitor clicked to swap the embeddings', window_embedding: 'embedding type that was in the small window when visitor clicked to swap the embeddings'}`
- visitor clicked the button in the small window that swaps the embedding types 

`EXPLORER_SBS_SIDE_WINDOW_EMBEDDING_CLICKED`
- visitor clicked the embedding drop down button in the side window

`EXPLORER_SBS_SIDE_WINDOW_EMBEDDING_SELECTED`: `{embedding: 'embedding type selected in the small window'}
- visitor clicked to change the embedding type in the side window

### Events to update
`EXPLORER_DOWNLOAD_COMPLETE`: `{embedding: 'embedding type currently selected', side_by_side: [True, False]}`
- adjust to also include the new payload category "side_by_side" to denote if side by side is activated at time of download

Checklist

- [x] Add events to the custom goals section of both the staging and prod Plausible spaces
- [x] If rdev environment is created for this new feature, once it has been deployed, ping @ainfeld to check analytics
- [ ] Once feature is deployed to Staging ping @ainfeld to check analytics again
- [ ] Verify events are showing up in the Staging space in Plausible correctly
- [ ] Once feature is deployed to Prod ping @ainfeld
- [ ] Confirm Plausible event names in Prod look the same as Staging and are showing up in the Prod space in Plausible correctly

#### People to cc

**PM**: @niknak33 
**DS**: @ainfeld

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by tihuan** [comment]
https://github.com/chanzuckerberg/single-cell-explorer/pull/998

**Comment by tihuan** [comment]
Done!
