### ISSUE TITLE
Add the DOI label to GET /datasets

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#7159]
## Context

See [**cell-sci-eng**](https://czi-sci.slack.com/archives/C023Q1APASK/p1716245770988479). If Census supports the the human readable name for the DOI url anchor link in the collection UI - like "Ahern et al. (2022) Cell" for https://doi.org/10.1016/j.cell.2022.01.012, then GE can stop using the Discover API and depend on the Census API which will simplify post-migration. 

## Design

Unfortunately, the name is being [calculated on the FE](https://github.com/chanzuckerberg/single-cell-data-portal/blob/f0fa3b8054fa2bb4a185b5b50a5e5d419a9f722b/frontend/src/common/queries/filter.ts#L564) from the collection `publisher_metadata` rather than being returned  in the **DP** API, so there's no BE code to reuse.

The **Discover API** must add information to [GET /datasets](https://api.cellxgene.cziscience.com/curation/ui/#/Dataset/backend.curation.api.v1.curation.datasets.actions.get) -  either the calculated name or the `publisher_metadata` (which would force Census to re-create the name). 

There's definitely an opportunity to refactor and add the calculated name to both the **DP** and **Discover API** and remove the FE code?

**Comment by nayib-jose-gloria** [comment]
My design preference is to calculate the short_citation in the backend and return in DP & Discover API, then remove the calculated citation from the FE.

**Comment by brianraymor** [comment]
To align with the [census schema](https://github.com/chanzuckerberg/cellxgene-census/issues/1179#issuecomment-2148093202), I'd recommend using the name - `collection_doi_label`.
