### ISSUE TITLE
bug(portal): page intermittently hangs on cancel revision

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#7296]
## Describe the bug

A blank page is intermittently being displayed on cancel of a revision.

## To Reproduce

1. Create a revision.
2. Click "Cancel Revision"

## What Happened

The navbar is displayed but the body (collection detail) is missing; the browser is still displaying the  (cancelled) revision.

## Expected behavior

The navbar and the published collection detail are displayed; the browser has navigated to the published revision.

## Additional context

This defect is causing the edit dataset name E2E tests to fail (e.g. [here](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/9997047093/job/27632997085)).

**Comment by brianraymor** [comment]
Per Nayib, this is in production. Closing.
