### ISSUE TITLE
Optimize memory usage of CXG conversion

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#7310]
## Motivation

Currently resources allocated to the CXG conversion step are not well utilized. Many VCPUs are allocated to the container to meet AWS memory/VCPU requirement, but very little of the actual process uses multiple CPUs. Reducing the memory needed will allow us to reduce the number of VCPUs, and support processing more cxg in parallel. This will save on compute costs by reducing the compute size. In the future we can rewrite the code to make better use of multiple CPUS to speed up CXG conversion.  

## Definition of Done

- The size of the dataset does not have a significant(20% diff) impact on the maximum memory used by cxg_conversion.

## Tasks

- investigate lines of code with the comment `# big memory usage`. 
- Make changes to optimize memory usage of those lines.
- Rerun the memory profiler and verify memory usage has decreased.
- modifying the `tile_db_ctx` [parameters](https://docs.tiledb.com/main/how-to/configuration#configuration-parameters) could help. https://github.com/chanzuckerberg/single-cell-data-portal/blob/bd179bf7f1ee89e235083ea4c0e1899293137d04/backend/layers/processing/h5ad_data_file.py#L33

# related issue
- https://github.com/chanzuckerberg/single-cell-data-portal/pull/7300
- https://github.com/chanzuckerberg/single-cell-data-portal/issues/7308

**Comment by nayib-jose-gloria** [comment]
Estimate (incl testing): 1-1.5 weeks

@Bento007 for comment if you agree
