### ISSUE TITLE
Portal UI Polish

### ISSUE THREAD

**Issue by hthomas-czi** [chanzuckerberg/single-cell-data-portal#780]
- Update navigation bar style [Figma](https://www.figma.com/file/TpoXVKFjd6MAl4ImidZ3wn/UI-Polish?node-id=102%3A122)
- Portal should use `Inter` font instead of `Roboto Condensed`
- All buttons should use the same primary blue [Figma](https://www.figma.com/file/TpoXVKFjd6MAl4ImidZ3wn/UI-Polish?node-id=0%3A1)
- Dataset table horizontal padding should match collection table [Figma](https://www.figma.com/file/TpoXVKFjd6MAl4ImidZ3wn/UI-Polish?node-id=0%3A1)
- Update button styles to match [design system](https://www.figma.com/file/JsWBZz7BuKhNcFqzYNJZLO/Design-System?node-id=22%3A8122)
- Add Link button should be `minimal` [Figma](https://www.figma.com/file/TpoXVKFjd6MAl4ImidZ3wn/UI-Polish?node-id=0%3A1)
- Menu padding should be consistent
- Improve Collection dialog validation errors (only show on submit)
- Reduce top margin on ViewGrid
- Add commas to cell count
- Parse and format tissue to remove erroneous `(disease)` string

**Comment by brianraymor** [comment]
RE _Improve Collection dialog validation errors (only show on submit)_, for example the current behavior for DOI is to constantly scold the user while they're completing the field. The error messages cause multiple resizes of the modal:

https://images.zenhubusercontent.com/228681195/1ee961f7-fece-4f23-9ea3-edcb6b66ba6d/screen_recording_2021_06_15_at_4_38_15_pm.mov

**Comment by brianraymor** [comment]
To add to the collection UX error experience, it's also odd that the redlines only appear if the curator types and then deletes text for many fields:

https://images.zenhubusercontent.com/228681195/e74fcad4-9243-4f85-8766-6a597efcb146/screen_recording_2021_07_28_at_5_20_44_pm.mov

**Comment by atolopko-czi** [comment]
@hthomas-czi issue is old; ok to close?

**Comment by hthomas-czi** [comment]
These issues have mostly been addressed. Okay to close @atolopko-czi
