### ISSUE TITLE
bug(upload): Multiple datasets being uploaded from a single user interaction

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#884]
## Describe the bug
Sometimes the backend will receive multiple identical POST's to `/upload-links` which results in a single user interaction creating multiple datasets on their collection

## To Reproduce
¯\\_(ツ)_/¯

## Expected behavior
One user interaction with dropbox chooser should result in one dataset upload

**Comment by Bento007** [comment]
This happens when the frontend sends two requests in quick succession to upload a dataset. This results in the creation of two unique dataset with the same h5ad file.

**Comment by maniarathi** [comment]
Add integration tests to make sure that only one request is sent. Assert at the UI level and request level.

**Comment by seve** [comment]
Related: #1069

**Comment by seve** [comment]
Saw today: 05/05/21

Deployment: staging


|  job id | dataset id |
| --- | --- |
| d57450ea-293e-4197-8461-f2d57443dac0 | b1098e34-ec6c-43dc-91a6-6b330d4afede |
| 6598750d-aa83-48c1-a884-871a677c93b7 | 85c4e5e3-f494-4ca8-a36d-9f9f5e96e55b |

**Comment by brianraymor** [comment]
Closing per conversation with @seve
