### ISSUE TITLE
[FE] Geneset upload flow 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#913]
See https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=178%3A1414
![Screen Shot 2021-02-17 at 11.59.33.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/62ff6ad6-49f9-4da0-902b-1e8a013587f3)

@tihuan Please add any frontend details

**Comment by MDunitz** [comment]
Transform the csv to json
Parse as javascript object
pass to validation function
validate
upload the json (POST)
on response from POST request update page with all available gene sets for the collection

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
