### ISSUE TITLE
[FE] Validation error flow

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#917]
When the validation flow discovers errors in the gene set file we need to raise them so the user can update the file and reupload it. 
Errors should be raised preventing the upload of the gene sets for the following conditions.
- Missing Gene Set Name
- Duplicate Gene Set Name (within the file)
- Duplicate Gene Set Name (in the database)
- Missing Gene Set Description
- No Gene Symbols in Gene Set (The set is empty)
- Duplicate Gene Symbols in Gene Set
- New Gene Set Name duplicates an existing Gene Set Name in the private collection

If validation fails for any reason, then upload does not proceed. The curator can correct the file based on the validation warnings in the UX and try again.

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
