### ISSUE TITLE
Need test suite to ensure that dataset rds format conversions are valid

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#939]
@pablo-gar r[ecently discovered](https://chanzuckerbergteam.slack.com/archives/C018B64J3HN/p1613608165066800?thread_ts=1613587670.058800&cid=C018B64J3HN) a failure in the portal anndata to RDS conversion. 

@MaximilianLombardo summarized:

_I wanted to follow up on the issue of seurat objects not having raw counts when being downloaded from the data portal. The information/actions that resulted from this thread are as follows:_

_The issue was with using sceasy to convert anndata to seurat objects, and the when the resulting seurat object was downloaded, it was missing the raw counts._

_@pablo-gar  is currently working on a [PR for sceasy](https://github.com/cellgeni/sceasy/pull/25) to fix this issue and enable the inclusion of the raw counts in the converted seurat object._

---

I reviewed with @maniarathi. Her response:

_We should validate that the conversion code that we use generates usable data. I think a suite of tests to ensure that all the required schema fields of a dataset exists and are readable is in order and we can add on to the test if we run into additional issues._ 

We would require validation for:
- rds

**Comment by brianraymor** [comment]
Adding to the sprint backlog per conversation with @maniarathi. Estimated to be added before moving to _in progress_.

**Comment by Bento007** [comment]
@pablo-gar suggest we test the following
For .rds we can try the following in R:
1. check that it can be read
2. check that it’s a seurat V3 object
3. check that the following exist:
   - seurat@assays$RNA
   - seurat@assays$RNA@counts (shape is non-zero for rows and columns)
   - seurat@assays$RNA@data (shape is non-zero for rows and columns)
   - seurat@meta.data
4. Check an embedding at least 1 embedding exists

**Comment by brianraymor** [comment]
Scroll down to **Leveraging the best of Both Worlds** for some _R within Python_ ideas:
https://towardsdatascience.com/from-r-vs-python-to-r-and-python-aa25db33ce17

**Comment by tihuan** [comment]
Spike - @Bento007  is syncing with Pablo right now. And will change this to a design ticket!

**Comment by brianraymor** [comment]
The scope can be limited to RDS per [Deprecate support for the loom format](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/191).

**Comment by atolopko-czi** [comment]
@metakuni Might this be added to epic #1549 (or one of it's sub-(sub-) epics)?

**Comment by metakuni** [comment]
> @metakuni Might this be added to epic #1549 (or one of it's sub-(sub-) epics)?

Surely, if we want to keep that epic open indefinitely.

**Comment by atolopko-czi** [comment]
> > @metakuni Might this be added to epic #1549 (or one of it's sub-(sub-) epics)?
> 
> Surely, if we want to keep that epic open indefinitely.

Ah, no, don't want to encourage that. Thx.

**Comment by metakuni** [comment]
We should consider implementing comprehensive format conversion testing as part of SOMA.io instead.

**Comment by atolopko-czi** [comment]
> We should consider implementing comprehensive format conversion testing as part of SOMA.io instead.

Presumably, rds conversions have been working correctly up until now. But we do have some risk of introducing regressions with the upcoming schema 3.0 update. If we perform one-time _manual_ verification of schema 3.0 h5ads to the rds format, then I agree we can punt on this story with SOMA in the wings. That said, we might still take on this story _before_ SOMA, since the test implementation could focus "what is being verified" from "where the data is read from", and thus still have value before SOMA comes online. And tests would require minimal changes when converted to work with SOMA.

**Comment by atolopko-czi** [comment]
@brianraymor Still a concern?

**Comment by brianraymor** [comment]
It's still a concern, but low priority. Per my own principles, if it had not been addressed in two years, then it should be closed until it becomes more a problem. I would not re-prioritize higher at the moment.
