### ISSUE TITLE
Create endpoint GET /datasets/{dataset_ids}/genesets 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#958]
## Approach
- Create endpoint GET /datasets/{dataset_ids}/genesets 
- Return the s3 link pointing to where the csv of genesets for the dataset is stored

## DOD
-If collection is public return 403
- if dataset does not exist return 403
- if there are no genesets linked to the dataset return 403
- if function successful return s3 link

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
