### ISSUE TITLE
The portal references outdated curation documentation

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#964]
Recently, the curation schema documentation and (renamed) CLI  validator were moved to [single-cell-curation](https://github.com/chanzuckerberg/single-cell-curation/).

There are multiple outdated references in the [corpora-data-portal repo](https://github.com/chanzuckerberg/corpora-data-portal/search?q=schema_guide). Since the originally planned schema guide has been [deprecated](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/226), the best reference is `https://github.com/chanzuckerberg/single-cell-curation/blob/main/readme.md`.

**Comment by brianraymor** [comment]
@MaximilianLombardo - we may want to wait for your curation tutorial and reference that instead. Is there a schedule to share?

**Comment by MaximilianLombardo** [comment]
Not a completed schedule as of yet, but curation will likely be the first tutorial that I write - do you have a specific time frame for the curation tutorial to be "online"?
