### ISSUE TITLE
FE Integration Tests

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#971]
- [x] Create a collection
- [x] Delete a collection
- [x] Publish a collection
- [ ] upload a dataset
- [ ] delete a dataset
- [ ] delete a pending dataset
- [ ] upload a bad dataset
- [ ] delete a bad dataset
- [ ] cannot retrieve a tombstoned collection
- [ ] cannot retrieve a tombstoned dataset
- [x] login
- [ ] logout
- [ ] list owners collections
- [ ] only owner can delete and upload datasets to a collection

## Definition of Done
- [ ] Write an integration test that run on a deployed environment.
- [ ] Ensure that cleanup happens after the test.

**Comment by tihuan** [comment]
We should fill out the rest of the tests, since they are still relevant and will improve product stability

**Comment by tihuan** [comment]
upload dataset test ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1349

**Comment by atolopko-czi** [comment]
@maniarathi @dsadgat Kuni suggested this as possible work for TestCo when they return to Single Cell.

**Comment by metakuni** [comment]
Closing since curators now use the Discover API.
