### ISSUE TITLE
The list of tissues for Construction of a human cell landscape at single-cell level is clipped

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#972]
The UX needs to be redesigned for edge cases where the list of Tissues is long and gets clipped by the view. 

Hover over `+47` in [Construction of a human cell landscape at single-cell level](https://cellxgene.cziscience.com/collections/38833785-fac5-48fd-944a-0f62a4c23ed1)

![Screen Shot 2021-03-03 at 2.31.10 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/6691e5d7-b0d5-4554-8795-92d7033344e0)

**UX Design**
[Figma](https://www.figma.com/file/yw3j0OQADELXB3RBUIWvsX/UI-Refinement?node-id=109%3A4650)

DoD:
1. Reference UX design in Figma
2. Every 25 items should start a new column. E.g., 55 items should have 3 columns with first two 25 items each and last column 5 items

**Comment by MDunitz** [comment]
It should be possible to reuse logic for listing genesets in a dataset

**Comment by brianraymor** [comment]
@seve and @hthomas-czi :

I believe that there are some other issues when calculating layout - whether the popup appears above or below the dataset row. 

In the case below, the popup appears **below** the dataset and is clipped even though there is adequate space to display it above the dataset:

![Screen Shot 2021-05-05 at 1.21.33 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/ceac073d-541b-4207-906f-c9b338838cd3)

**Comment by tihuan** [comment]
Harley is out this week. I'm looking at the [design](https://www.figma.com/file/yw3j0OQADELXB3RBUIWvsX/UI-Refinement?node-id=109%3A4650) now, which has two columns. But do we know when to switch from one column to two columns? E.g., when item count > 30, etc.. Or what's the business logic for this ticket in general?

CC: @seve in case you remember, since it was pointed already! Thank you!

**Comment by brianraymor** [comment]
I'm meeting with Harley on Monday morning to catch him up on pending launch questions. I don't see further details in the original [ux thread](https://czi-sci.slack.com/archives/C02450L5YAX/p1614810872039800).

**Comment by tihuan** [comment]
Thanks so much, Brian!

I think Blueprint already does the layout calculation, but maybe it's just not right all the time lol

I feel the simplest solution is to split to two columns given enough item count that we determine heuristically, so we don't need to do layout calculation twice, once in our own implementation and the other in Blueprint 🤔

**Comment by hthomas-czi** [comment]
Hi @tihuan I agree with your solution. I'd expect a new column to start every 25 items. 

For example, there would be three columns if there were 55 items.

**Comment by tihuan** [comment]
Awesome! Thanks so much, @hthomas-czi ! Will add the business logic to the ticket description now 🚀 !

And hope you enjoyed your vacayyyy 🍹 !!

**Comment by tihuan** [comment]
This ticket is now ready to be worked on!

**Comment by brianraymor** [comment]
Reproduces on production.
